### ISSUE TITLE
invalid_signature | Signature does not match, it may have been tampered with.

### ISSUE THREAD

**Issue by duleorlovic** [Shopify/shopify_app#1009]
I created sample app using `rails generate shopify_app`.
You can download this commit https://github.com/trkin/shopify-sample-data-generator/commit/f1907582be984a2c0eb26e575503e2b4658b24f0

When I use brand new account it works fine (it lists products under `/admin/apps/:id`.

I have old account with two disabled organizations. 
When I update keys from that account
```
# https://partners.shopify.com/648793/apps/3898079
export SHOPIFY_API_KEY=a...
export SHOPIFY_API_SECRET_KEY=shpss_e...
export SHOP=dule-test.myshopify.com
export SCOPES=write_products,write_customers,write_draft_orders
```

after I install the app on the store it give me an error

```
OmniAuth::Strategies::OAuth2::CallbackError

invalid_signature | Signature does not match, it may have been tampered with.

Extracted source (around line #25):
    def raise_out!
      raise(env['omniauth.error'] || OmniAuth::Error.new(env['omniauth.error.type']))
    end

Rails.root: /home/orlovic/rails/shopify_sample_data_generator

Application Trace | Framework Trace | Full Trace
omniauth (1.9.1) lib/omniauth/failure_endpoint.rb:25:in `raise_out!'
```

so I assume this error is certainly because of the fact that account has some "disabled" organizations.

**Comment by tanema** [comment]
This would have nothing to do with a inactive organization. This is specifically an error raised from `omniauth-shopify-oauth2` gem when the app gets a callback from shopify with the HMAC and the secure comparison between the payload and the HMAC does not match with your secret. 

This might mean that you have entered the wrong api_secret_key into your app configuration.

**Comment by duleorlovic** [comment]
@tanema thank you for explanation. That was the reason.
But the cause of this confusion is that shopify api cli now uses SHOPIFY_API_SECRET_KEY instead of SHOPIFY_API_SECRET https://github.com/Shopify/shopify-app-cli/issues/387

I think there should be a consistency, so I created pull request https://github.com/Shopify/shopify_app/pull/1010 we can continue discussion there.
