### ISSUE TITLE
user_session does not match session on shopify mobile - redirects forever

### ISSUE THREAD

**Issue by awd** [Shopify/shopify_app#1011]
Hello old pals, I've been attempting to test an app on an iPhone, and noticed some differences between mobile safari and shopify mobile. Which prevent the app being used within shopify mobile.

With shopify mobile, the `user_session` does not match the `session` param, and it causes an infinite redirection loop via [`login_again_if_different_user_or_shop`](https://github.com/Shopify/shopify_app/blob/7e81ae8cb7f3891444bf5376435264981deebac3/lib/shopify_app/controller_concerns/login_protection.rb#L67).

The `user_session` is set in the [`CallbacksController:102`](https://github.com/Shopify/shopify_app/blob/7e81ae8cb7f3891444bf5376435264981deebac3/app/controllers/shopify_app/callback_controller.rb#L102) based on the `auth_hash`. 

On Shopify Mobile - these sessions are compared, but `user_session` never seems to match the `session` passed in the params. This is causing a redirect loop and unable to properly access the application.

I am happy to help resolve this if we can in this here repo, but it might be worth asking why shopify mobile is reporting such strange browser information (see below).

My app is using the latest (everything), iOS, mobile safari, shopify mobile, shopify_app gem, rails, etc. But I'll include some specific versions for clarity.

Application:
```
    rails (6.0.3.1)
    shopify_app (13.3.0)
      browser_sniffer (~> 1.2.2)
      jwt (~> 2.2.1)
      omniauth-shopify-oauth2 (~> 2.2.2)
      rails (> 5.2.1)
      redirect_safely (~> 1.0)
      shopify_api (~> 9.1.0)
```

Mobile Safari (from browser sniffer):
```
@user_agent="Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) 
             AppleWebKit/605.1.15 (KHTML, like Gecko) 
             Version/13.1.1 Mobile/15E148 Safari/604.1", 
```

Shopify Mobile (from browser sniffer):
```
@user_agent="Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) 
             AppleWebKit/ 604.1.21 (KHTML, like Gecko) 
             Version/ 12.0 Mobile/17A6278a Safari/602.1.26 
             MobileMiddlewareSupported 
             Shopify Mobile/iOS/8.61.0 (iPhone12,3/com.jadedpixel.shopify/13.5.1) - Build 485", 
```

Bonus: If you made it this far, on shopify mobile, tapping into my app will redirect loop until it gets kicked back to the list of apps view, tapping into it one more time does the same thing... tapping into the app for a third time, will load the app as expected, but `session[:user_id]` is nil. On desktop and on mobile safari - `session[:user_id]` is correctly set as one would expect. Weird eh?

**Comment by tanema** [comment]
Hey Doeler! I browsed through all of this and cannot see any clear reason why the user_session comparison would fail. Just to clarify `session[:user_session] != params[:session]` you are saying one of these is always nil? Which means `session[:user_session] = auth_hash&.extra&.session` always returns nil from the mobile app only?

**Comment by tanema** [comment]
This is extra weird if it is only happening in Mobile, I will reach out to that team about this.

**Comment by awd** [comment]
Thanks @tanema - let me know if I can be of any help here. Happy to test against my codebase.

**Comment by ragalie** [comment]
I'm pretty sure this is a bug in Shopify core that we have a fix for, and will hopefully go out in the next few days.

For Shopify employees, it's this one: https://github.com/Shopify/shopify/pull/245849

**Comment by awd** [comment]
Thanks Mike @ragalie !!

**Comment by awd** [comment]
Looks like this issue was fixed via this commit from @shawnfrench (thanks Shawn!). I've tested this against `shopify_app - v.13.4.1` on shopify mobile and it appears to work as expected now.

https://github.com/Shopify/shopify_app/commit/25714e0d2c3b47f7062b39428bac4dbfc40f94f9

Thanks all!
