### ISSUE TITLE
Error creating app_subscription/update webhook topic

### ISSUE THREAD

**Issue by awd** [Shopify/shopify_app#1016]
Hello!

I've found a bug when registering webhooks via `ShopifyApp.configuration.webhooks` for `app_subscriptions/update` topic. It appears this topic is not available to the REST API (which is what this gem defaults to using in `WebhooksManager`).

The error received is `ActiveResource::ResourceNotFound (Failed.  Response code = 404.  Response message = Not Found (Could not find the webhook topic app_subscriptions/update).)`

I tested this in `rails console` using my shop token.

Is this a bug, or is there a known work-around? Perhaps webhook manager needs to be migrated to the GraphQL API instead?

Rails 6 latest, ShopifyApp gem latest, Ruby 2.7

**Comment by mramsden** [comment]
As you mention it looks like the webhook manager is still based on the rest API and that new topic is not available through GraphQL. I worked around this for the time being by adding an [after authentication job](https://github.com/Shopify/shopify_app#afterauthenticate-job) which is called just after `install_webhooks` when the merchant installs your app.

I then used the job to call the graphql endpoint to do the installation of required Webhooks for my app.
