### ISSUE TITLE
Shopify App may not be compliant with the latest Google Chrome cookie behaviour.

### ISSUE THREAD

**Issue by navadiyasank** [Shopify/shopify_app#1017]
I am Ruby On Rails Developer. I have developed app with this gem. Shopify rejected the app with the reason that your app may not be compliant with the latest Google Chrome cookie behaviour.

They provide me with [https://shopify.dev/tutorials/migrate-your-app-to-support-samesite-cookies](https://shopify.dev/tutorials/migrate-your-app-to-support-samesite-cookies) to fix the issue. 

As per this link, Shopify app version should be latest and I am using the latest version 13.4.0.

Provide me with the solution How I fixed this issue?

Reference Video: [https://www.loom.com/share/43cde6e6d4334bb481ecbf37685c3837](https://www.loom.com/share/43cde6e6d4334bb481ecbf37685c3837)

**Comment by tanema** [comment]
Are you using https, id you are not then it cannot set the cookie appropriately.

**Comment by navadiyasank** [comment]
@tanema Thanks for the reply.
Yes, I am using https. I also check for many other apps that are published that have the same issue.

**Comment by tanema** [comment]
Then the session cookies that shopify_app manages should be compliant with SameSite. Do you see in your cookie inspector that the cookies do not have those attributes?

**Comment by navadiyasank** [comment]
Hey Tim,

Which Cookie do I want to see for this issue? provide me cookies name.
Here is reference video where you can see all the cookies list:
<https://www.loom.com/share/e186019b6ec441ebab015945afd89fe2?focus_title=1&muted=1>

Shopify -
<https://www.loom.com/share/e186019b6ec441ebab015945afd89fe2?focus_title=1&muted=1>Watch
Video <https://www.loom.com/share/e186019b6ec441ebab015945afd89fe2>
<https://www.loom.com/share/e186019b6ec441ebab015945afd89fe2?utm_medium=gif>

**Comment by tanema** [comment]
Why do you have koa cookies if you are running a rails app?

**Comment by ragalie** [comment]
The video looks like it's showing Shopify's cookies, not your app's cookies. You need to select the https://translatepro.mokoolapps.com entry in the cookies list to see your app's cookies.

**Comment by navadiyasank** [comment]
> The video looks like it's showing Shopify's cookies, not your app's cookies. You need to select the https://translatepro.mokoolapps.com entry in the cookies list to see your app's cookies.

Here is screenshot which contains the cookie which is of https://translatepro.mokoolapps.com https://prnt.sc/t1so6c

**Comment by navadiyasank** [comment]
> Why do you have koa cookies if you are running a rails app?

koa cookie is from Shopify store. It's don't from App side.
reference: https://prnt.sc/t1spht

**Comment by navadiyasank** [comment]
@tanema @ragalie Please provide your input to fix this issue.

**Comment by tanema** [comment]
It seems your app is compliant then. Please provide that screenshot to the app review team but you might also want to change the name of your session cookie.
