### ISSUE TITLE
Webhook verification changed?

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1019]
Looking at the logs for my App, incoming webhooks. 

Filter chain halted as :verify_request rendered or redirected

Shopify App:  shopify_app (13.3.0)

So the scenario is: webhook is generated by an App #1 installed in Shop A but the webhook is being directed to a different App, App #2, installed on Shop B. App #2 has the API key from App #1 which installed the webhook. So is there simple enough way to override the behaviour of the webhook verification to use the API key from App #1 in App #2 to allow the payload to be decoded properly and processed? 

I know it is a longshot but I am trying anyway.

**Comment by tanema** [comment]
No, reusing ApiKeys like this is not a recommended practice. I realize that you probably have a very valid reason for doing this so I would recommend you write your own. Our [payloadverification](https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/controller_concerns/payload_verification.rb) module is very simple for you to copy and use in your own code.

**Comment by resistorsoftware** [comment]
Got it. I am going to do just that. It is a really neat pattern, and breaks no security or otherwise compromises anything. I just never had a need to have Apps swap webhooks till now. I guess this means monkey patching my App so as to accomplish said goal.

Thanks!
