### ISSUE TITLE
What is the way to convert embedded App into non-embedded App?

### ISSUE THREAD

**Issue by codemicky** [Shopify/shopify_app#1021]
I have researched but couldn't find the doc to build a **non-embedded** App.
I have rich experience in building **embedded** App but I am almost new with a **non-embedded** App.
What is the way to convert **embedded** App into a **non-embedded** App?

**Comment by tanema** [comment]
You can just change the configuration, in your shopify_app configuration `embedded_app` to false. This will ultimately just change how your app authenticates and it will no longer rely on AppBridge on your front-end.

**Comment by codemicky** [comment]
Hi @tanema 
Thank you for your reply.

I have changed to 
`config.embedded_app = false`

And I have uninstalled the App and installed again but the App is still in the AppBridge.

**Comment by codemicky** [comment]
Hi @tanema, it works. Thank you. 👍

**Comment by atinder** [comment]
@codemicky @tanema Do you know any prefered means of authentication after moving to a non-embedded app.
Can we still use App bridge or something similar for easy authentication?

**Comment by manpreet396** [comment]
> You can just change the configuration, in your shopify_app configuration `embedded_app` to false. This will ultimately just change how your app authenticates and it will no longer rely on AppBridge on your front-end.

Hi tanema,
Do you have any idea how to change this variable in laravel osiset.
