### ISSUE TITLE
API Version not Set when registering webhooks on heroku

### ISSUE THREAD

**Issue by treeuri** [Shopify/shopify_app#1022]
shopify_app-13.4.0
local env works fine
when deploying to heroku and trying to register webhooks I get this error
ShopifyAPI::ApiVersion::ApiVersionNotSetError (You must set ShopifyAPI::Base.api_version before making a request.):

Are workers aware of the Shopify configuration at all? If not , what do I need to add in order for them to be aware of this configuration?

**Comment by kartikluke** [comment]
This generally occurs if you're not wrapping your calls to the Shopify API with a session. The easiest way to do it is to take `Shop` or whatever your Shop model is and call `.with_shopify_session` on it.

```
shop.with_shopify_session do
  ShopifyAPI::Order.last
end
```
