### ISSUE TITLE
Shopify App (Reviews are out of step with Reality)

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1030]
Created an App with the gem v ~> 13

The gem takes care of Chrome Issues, like the Same Site Cookie. A Partner submitted this App, and it was rejected by Shopify saying, "This App has problems with Chrome".

That is absolute BOLLOCKS as the code in this repo is coded to prevent that. I examined the cookies in Chrome and they are all perfect. The App has zero Chrome Cookie problems. 

I know this is not the fault of the Shopify App gem team. But it does SUCK that Apps get rejected for a reason that just does not compute.

**Comment by tanema** [comment]
We are reaching out to our app review team to see if there is something that is maybe a flaky test because you are certainly not the first developer to report being on the most recent update but still being denied approval.

**Comment by resistorsoftware** [comment]
Thank you. I have had many run-ins with Shopify claiming my Apps are not doing Chrome right, but when I send them screenshots of it working perfectly, they apologize, laugh it off, and apparently move on. Yet nothing has changed in the few months since this became a thing... I fixed an App in February, and they called me in April, and I was ticked off that they insisted my App still did not work in Chrome, yet it worked perfectly well in all versions and in all my local tests with Chrome.

It is like when they tell me to either use Chrome or clear my cache when Shopify Admin has failures. I am stunned that that is still advice. 

Finally, anyone can examine the Web Developer console of any typical Shopify merchant store, and see the warnings and errors piled up by Shopify code too! Often my App is clean as whistle but the console has many many red flags almost all generated by Shopify itself. Kind of frustrating for us when the pot is calling the kettle black as the old proverb goes. 

Thanks Tim!

**Comment by paulomarg** [comment]
Could you please share which App was rejected? We're looking into this rejection with the app review team, as mentioned by @tanema, to see if/where we can improve the process.

**Comment by paulomarg** [comment]
We've looked into the review, and found that there is indeed an issue where Chrome itself is triggering 'false positives' for the SameSite cookie check for a certain percentage of users during the app review process.

The issue has been forwarded to the app review team and they are investigating possible solutions for it.

Thank you for bringing this to our attention!
