### ISSUE TITLE
Why is GDPR Webhook topic not registering?

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1034]
ShopifyApp::WebhooksManager::CreationFailed: Topic Invalid topic specified: customers/redact.

Why? If I am supposed to add this endpoint to public Apps, should this not just work?

**Comment by tanema** [comment]
These webhooks are not webhooks that you create subscriptions for. They are mandatory so they are created for you and configured through the partners dashboard..

**Comment by resistorsoftware** [comment]
Thanks for clarifying that. The documentation implies we must add those ourselves. The documentation should instead say what you just said.
<img width="867" alt="Add_GDPR_webhooks_to_your_app" src="https://user-images.githubusercontent.com/123307/88335097-be9ee580-cd00-11ea-82d1-0c5f43602dca.png">
