### ISSUE TITLE
Could not find generator shopify_app:products_controller

### ISSUE THREAD

**Issue by ivorpad** [Shopify/shopify_app#1038]
I'm using Rails 6.0.3.2 and the latest version of `shopify_app` (13.5) but when I run `rails generate shopify_app:products_controller` as advised [here](https://github.com/Shopify/shopify_app#home-controller-generator), I get:

```bash
Could not find generator 'shopify_app:products_controller'. Maybe you meant "shopify_app:app_proxy_controller"?
Run `rails generate --help` for more options.
```

Any ideas?

Thanks

**Comment by tanema** [comment]
I believe the products controller generator was added in the 13.6 version
