### ISSUE TITLE
JWT and generator 

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1039]
shopify_app gem 13.5

From the docs:

> beta] with-session-token: This flag generates an unauthenticated home_controller and a protected sample products_controller. It also creates a home view that leverages a session token to fetch products from your products_controller. Use this flag if you plan to build a single-page application or to secure your app using JWT session tokens (e.g. --with-session-token or --with-session-token true).

So I run the generator 

    rails generate shopify_app:home_controller --with-session-token

And nothing special at all happens. Just the vanilla generic home controller, and view to go with it as per any normal install happens. Is there some typo in the docs about the JWT code being dished out with that flag?

I read the PR details:  https://github.com/Shopify/shopify_app/pull/1014/files/575dc96a26d7340096340b5bda0938c891e995fc

So, I am not understanding, you expect us to do what here? Confused. We have to work off a special branch? We have to ask for permission to play with this?

I looked in the 13.5 source code, and saw zip zero zilch in that generator about --with-session-token, so I guess I need to use a branch... sigh.. confusing.

**Comment by NabeelAhsen** [comment]
Hi @resistorsoftware, sorry for the inconvenience! This capability hasn't been cut as a gem release yet, and will be available in v13.6.

I will look into it this morning and get back to you on this thread.

**Comment by resistorsoftware** [comment]
S'alright. I get it. I am piecing Humpty Dumpty together! I found your App here to see it in action:

https://github.com/Shopify/next-gen-auth-app-demo

**Comment by NabeelAhsen** [comment]
Hi there, this functionality should now be available in v14.0.0

https://github.com/Shopify/shopify_app/releases/tag/v14.0.0

Turns out we had to skip an official release of v13.6.0 due to breaking changes.
