### ISSUE TITLE
Anyone ever use JWT? 

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1043]
After reading this: https://shopify.dev/tools/app-bridge/authentication

I am not sure how this is supposed to be helpful. Some questions, rapid fire style:

- installing an App is identical, in that oAuth and getting an API token all are the same.
- instead of rendering an authenticated controller in our App we render an unauthenticated controller
- we get a token from the header to now use JS to get data. 

So now what? We get back data and we no longer render in the world of server side templates, we can only play with data from calls that return data? So this is fine if you have all of your front-end rendered by something like React, but if you at all use templates like Erb or Haml you're screwed?

**Comment by NabeelAhsen** [comment]
The JWT auth does seem to highly favour the world of single-page applications made by something like React. Fortunately, there is a recommended workaround using [TurboLinks](https://github.com/turbolinks/turbolinks) to help multi-paged apps behave nicely using session tokens.

* https://shopify.dev/tools/app-bridge/authentication#use-turbolinks-to-convert-a-multi-page-app
    * A guide to using turbolinks for apps multi-paged apps that rely on erb, haml, or multiple pages
* https://github.com/Shopify/turbolinks-jwt-sample-app
    * A sample app that helps illustration the changes required to make something like this work. Specifically, see how [`shopify_app.js`](https://github.com/Shopify/turbolinks-jwt-sample-app/blob/master/app/javascript/shopify_app/shopify_app.js) handles adding this token as a header throughout the app with minimal effort.


I'd also highly recommend posting questions like this on https://community.shopify.com . There's a higher chance your questions the App Authorization team at Shopify will be able to respond quicker!

**Comment by resistorsoftware** [comment]
Well, at a glance, sure. But honestly this project is just getting more convoluted with age rather than leaner, cleaner and tighter.  Progress? 

In the first example you made, with turbolinks, all the controllers are still AuthenticatedController, meaning the old cookie pattern is in play? To be inheriting AuthenicatedController just means the same old iframe with third-party cookies or am I missing something there? 

I see glimpses of the future in the bizarre but Rubyish... 

     skip_before_action :verify_authenticity_token, if: :jwt_shopify_domain

So does that mean this controller could just be unprotected and still work?
