### ISSUE TITLE
App rejected with error: "App must install successfully"

### ISSUE THREAD

**Issue by mluders** [Shopify/shopify_app#1045]
My app is unable to pass the automated review. I'm getting the following rejection message:

```
App must install successfully.
Your app does not request installation on the shop immediately after clicking "add app". Apps must ask a shop for access when being installed on a shop for the first time, as well as when they are being reinstalled after having been removed. During install or reinstall we expected Oauth to be initiated at https://appstoretest5.myshopify.com/admin/oauth/request_grant but was redirected to https://www.mywebsite.com/.
```

I spent some time browsing the Shopify forums - apparently, other people have experienced the same issue:
1. https://community.shopify.com/c/Shopify-Discussion/App-Got-Rejected-due-Redirect/td-p/711904
2. https://community.shopify.com/c/Shopify-APIs-SDKs/Your-app-was-rejected-App-must-install-successfully/td-p/716644

One person suggested appending `/auth/login` to the the App URL in the Shopify Admin. I tried a few different variants of this, but none of them were successful.

At this point, I'm stumped. I haven't altered the OAuth flow in any way - I'm using the vanilla OAuth flow provided by the `shopify_app` gem. When I test myself, the app is able to install, reinstall, etc., with no apparent issues. I’ve even added a dummy ShopifyAPI::Shop.current in my Home controller, in order to force the OAuth flow when reinstalling.

Does anyone have any experience with this issue?

**Comment by tanema** [comment]
I suggest re-submitting. Sometimes the app approval process is glitchy. If you are using the default oauth flow there should not be a problem with the authentication.

**Comment by mluders** [comment]
I’m also wondering if it’s DNS-related, or somehow related to my domain settings on Heroku. I’m not doing anything special. But it’s the only other variable I can think of.

**Comment by mluders** [comment]
Also, I’m not using the “embedded app” approach. My app is an external site. Are those still supported by Shopify?

**Comment by ntcong** [comment]
I have the same problem but using Django. Shopify does not reject because of redirect before but suddenly complaining about it after 10/8

**Comment by resistorsoftware** [comment]
I see this too. Latest version of Shopify App (14.0 baby), and the message back from Shopify Review was pretty clear. 

So is the state of the art at Shopify Reviews? Glitchy? Or are we guilty of something in our use of Shopify App out of the box, virginal perfect install everywhere but Shopify reviews? 
<img width="1057" alt="App_Listing_Submission___Shopify_App_Store" src="https://user-images.githubusercontent.com/123307/90572057-1c4c1380-e181-11ea-9b55-ce92e59951f9.png">

**Comment by tanema** [comment]
I definitely understand it is frustrating when you have been working on a project for a while and are excited to launch. Unfortunately I cannot give you any other advice at this time than resubmitting it. We have been in contact with the app review team and they are trying to debug their app review process for all of this. I am under the impression that the automated testing is a complicated system that they are still trying to improve so things like this don't happen. 

I will forward the suggestion that it may be DNS related to see if this helps resolve the process at all.

**Comment by resistorsoftware** [comment]
Well, the way that one rolled out was a sem-disaster for many reasons. One, Shopify was unable to figure out that while the App was not a conventional Sales Channel, it was in fact a really cool Sales Channel, that broke no rules, except in the sense that it was unique and the round peg did not fit Shopify's square holes. 

Secondly, the review team installed > 20 stores in testing, of which this reject message was the only one listed? 1:20 is not bad I guess. But why so many test shops? Seemed like out of control over-kill to me. 

And third, with specific regards to this shopify_app gem, again, apologies, but since the warnings/errors are coming from the Shopify mothership, and concern this gem, it has to be posted as an issue! 

Here is hoping the App Review team gets it together. They invited these disasters upon themselves, best they dig out of their hole quickly!

**Comment by mluders** [comment]
After waiting a few weeks, and re-submitting the app multiple times, it finally passed the automated review with no errors.
