### ISSUE TITLE
How to "login" with home controller generated via option --with-session-token

### ISSUE THREAD

**Issue by colinbrogan** [Shopify/shopify_app#1063]
Hi,
I have tried generating the home controller --with-session-token, to enable App Bridge and JWT.
Most everything works great, and I prefer using this method than standard (old) oauth methods, as it feels much more seemless.

However, I have ran into a problem.  I am using a browser from which I have not "logged in" to the app (by typing the shop url in the login page), the ajax request for products will not load. I have noticed that the ajax to call products literally redirects to the login page (instead of serving product json), leaving the unauthenticated home controller page in it's "Loading" message.

In other words, if the session has already been created by manually logging in, everything works great. If not, you have to go in and manually login from that page to create an initial session. This is a horrible user experience for my clients, and I want to solve it fast. Is there some javascript, such that I can do this in the background? I'd prefer to not have to redirect. Like, is there a way to start the session from a valid shopify session, without having to physically redirect to some page the first time they use the app on a new device?

I am a bit uneducated on the technical minutia of JWT, and was hoping there would be some boilerplate JS code.

**Comment by ragalie** [comment]
I think it's _supposed_ to return a 401 in this case: https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/controller_concerns/login_protection.rb#L104-L119

Rails has a particular header value it looks for to determine if the request is an AJAX request though, so you may need to specify that if you're not using a library that includes it automatically: https://apidock.com/rails/ActionController/Request/xml_http_request%3F
