### ISSUE TITLE
JWT Authentication skips `perform_after_authenticate_job`

### ISSUE THREAD

**Issue by minichate** [Shopify/shopify_app#1073]
In the callback controller, the Post-Install job (via `after_authenticate_job`) is not getting triggered. We think we’ve got it narrowed down to[ JWT’s not triggering `perform_after_authenticate_job`](https://github.com/Shopify/shopify_app/blob/master/app/controllers/shopify_app/callback_controller.rb#L17-L19) like[ non-JWT auth does](https://github.com/Shopify/shopify_app/blob/master/app/controllers/shopify_app/callback_controller.rb#L30). 

This means that configurations that specify `after_authenticate_job`'s (eg: https://github.com/Shopify/shopify_app/blob/96cfba49a19f7cb1d81367d8b127b74568810d89/lib/generators/shopify_app/install/templates/shopify_app.rb.tt#L9) are not getting those jobs invoked during the callback phase.

**Comment by paulomarg** [comment]
I think this may have been fixed in version 14.4.3 (by https://github.com/Shopify/shopify_app/pull/1079).

**Comment by minichate** [comment]
<3
