### ISSUE TITLE
JWT: Deep linking not working

### ISSUE THREAD

**Issue by netwire88** [Shopify/shopify_app#1092]
Hi,
I've tried various ways to get deep linking working per https://github.com/Shopify/turbolinks-jwt-sample-app, but to no avail.

Assuming we are trying to go to `/help`, are these types of queries working for you (JWT enabled, third-party cookies disabled)?

- https://[host]/help - doesn't work, redirect loop
- https://[host]/help?shop=shopname.myshopify.com - doesn't work, redirect loop
- https://[host]/?return_to=/help - doesn't work, goes to `/splash_page` but `return_to` param not passed from Shopify login to `SplashPageController`
- https://[host]/?return_to=/help&shop=shopname.myshopify.com - works

**Comment by forsbergplustwo** [comment]
I was having the same redirect issues when working through the https://github.com/Shopify/turbolinks-jwt-sample-app repo and the tutorial. The current implementation stops us from using Shopify App Extensions (links to the emnedded app from inside the Shopify Admin), or deeplinks to our app pages outside of the Shopify iframe. Those always end with a redirect loop as @netwire88 outlines above.

I have come up with a solution to make this work, where if a request arrives at an AuthenticatedController, which is not a JWT request, we automatically redirect to the "splash_page" with the original request details passed along. Here's my modified controller:

```ruby
# app/controllers/authenticated_controller.rb

class AuthenticatedController < ApplicationController
  before_action :shop_origin
  before_action :redirect_to_splash_page_unless_jwt_request
  include ShopifyApp::Authenticated

  def shop_origin
    @shop_origin = current_shopify_domain
  end

  private

  def redirect_to_splash_page_unless_jwt_request
    if ShopifyApp.configuration.allow_jwt_authentication && request.env["jwt.shopify_domain"].blank?
      splash_page_load_path = root_path(return_to: request.fullpath, shop: @shop_origin)
      redirect_to(splash_page_load_path) && return
    end
  end
end
```

Note: The order of the before_actions is important, as we need to do this before ShopifyApp::Authenticated concern kicks in.

This works ok for any deeplink which is loaded *outside* of the Shopify Admin iFrame, such as `https://localhost:3000/products`.

To get this working for Shopify App Extensions (which are loaded *inside* the iFrame by default), I also had to remove the `X-Frame-Options` header in my SplashPageController actions:

```ruby
class SplashPageController < ApplicationController
  include ShopifyApp::EmbeddedApp
  include ShopifyApp::RequireKnownShop

  after_action :remove_x_frame_header

  def index
    remove_x_frame_header
    @shop_origin = current_shopify_domain
  end

  private

  def remove_x_frame_header
    response.headers.except!('X-Frame-Options')
  end
end

```

Now the embedded app works as intended, where we can access all pages directly. I'm sure there are edge cases though that are not yet known.

Is there any chance we'll see something like this supported by the Shopify App gem by default?

I do realize that using a splash page is an implementation detail, and may not be what everyone ends up doing. It is however currently the only documented way of using this gem with JWT tokens and Turbolinks.


Thanks!

**Comment by netwire88** [comment]
Thank you @forsbergplustwo , it's worth trying, but I do hope Shopify addresses this glaring issue

**Comment by tanema** [comment]
@netwire88 do not directly tag developers unless you are responding to a comment or work they have already done in this issue. Our team will respond when there is time to and tagging our developers will not expedite that. Thank you.

**Comment by netwire88** [comment]
Hi @forsbergplustwo , I finally got a chance to test your suggestions. 
When I go to a deep link without a `shop` variable, I'm redirected to Shopify login. However, after I login, the deep link (i.e. `/help`) isn't saved by Shopify and the `SplashPageController` doesn't know to redirect. 
Are you experiencing this?

**Comment by forsbergplustwo** [comment]
Hey @netwire88 Yes, the experience when not logged in beforehand doesn't work, as the return_to is lost during the login process. The changes I made help mostly when the link is being triggered from within the Shopify admin (Admin Links). Deep links from outside the platform work if already logged in only :(

**Comment by netwire88** [comment]
@forsbergplustwo , oddly, when I changed the order of to this, it seems working. Can you verify?

```
  include ShopifyApp::Authenticated
  before_action :shop_origin
  before_action :redirect_to_splash_page_unless_jwt_request
```
