### ISSUE TITLE
JWT: Subject should be a string according to the spec

### ISSUE THREAD

**Issue by cooldarkdryplace** [Shopify/shopify_app#1094]
Currently, Shopify expects that the optional "Subject" field in JWT standard claims has type `integer`.   [Specification](https://tools.ietf.org/html/rfc7519#section-4.1.2) mentions it as a string though.

> The "sub" value is a case-sensitive string containing a StringOrURI value.

Is there a chance to change the type of this value to a string? This will enable developers to use standard/existing libraries to parse JWT.
I believe that this is still in Beta, would be nice to have it corrected before the GA.
Thanks!

**Comment by ragalie** [comment]
Thanks for the report! We're looking into it!

**Comment by andyw8** [comment]
Looks like this was resolved by https://github.com/Shopify/shopify-dev/pull/4330.
