### ISSUE TITLE
Deprecation warning in RSpec tests after upgrading to Rails 6+

### ISSUE THREAD

**Issue by dansundy** [Shopify/shopify_app#1096]
I recently update my rails version to `6.0.3.4`. All seems to be working fine but every time I run RSpec I get the following warning:

```
DEPRECATION WARNING: Initialization autoloaded the constants Shopify and Shopify::AfterAuthenticateJob.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload Shopify, for example,
the expected changes won't be reflected in that stale Module object.

`config.autoloader` is set to `classic`. These autoloaded constants would have been unloaded if `config.autoloader` had been set to `:zeitwerk`.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <top (required)> at [...]/config/environment.rb:5)
```

All of the tests pass, this message just appears at the beginning. 

Line 5 of the `environment.rb` file is:

```
# Initialize the Rails application.
Rails.application.initialize
```

Should I ignore the warning or should I be changing something in the initialization process? Thanks in advance if anyone can shed light on this for me.

Ruby: `2.5.8`
Rails: `6.0.3.4`
shopify_app: `15.0.0`

**Comment by paulomarg** [comment]
Thanks for the detailed report! We will look into this and see if we can fix these warnings.

As the message says, this shouldn't break your app, but you'll need to work around this by rebooting the application when changes are made until we have a fix.

**Comment by dansundy** [comment]
Returned to focus on this error and found that it can be avoided by registering the `Shopify::AfterAuthenticateJob` with a string.

So in `config/initializers/shopify_app.rb` do this:

```
config.after_authenticate_job = { job: 'Shopify::AfterAuthenticateJob' }
```

instead of this:

```
config.after_authenticate_job = { job: Shopify::AfterAuthenticateJob }
```

**Comment by nelsonwittwer** [comment]
Closing as it seems as if there were working suggestions
