### ISSUE TITLE
Basic Explanation

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1107]
Shopify App v 15.0

I see these statements in the logs. 

    [ShopifyApp::Itp] Clearing top level oauth cookie...
    [ShopifyApp::LoginProtection] Activating session...
      Rendering ...
      Rendered ...
      Rendered ...
    [ShopifyApp::LoginProtection] Clearing session...

What do those log statements signify in terms of how things are going with the App? I notice we are still using cookies even though that is supposed to be on the way out. Just curious... this on the road to help us to move to JWT at some point?

**Comment by andyw8** [comment]
@lstp These additional logging calls were added in #1074, can they be removed now?

**Comment by lstp** [comment]
> @lstp These additional logging calls were added in #1074, can they be removed now?

Hi, yes, I originally added these debug logs for debugging auth issues we were having. It's safe to remove them if they're not useful.

**Comment by andyw8** [comment]
Resolved by #1110
