### ISSUE TITLE
How to prettify shopifyAPI request in console output

### ISSUE THREAD

**Issue by almeidaz** [Shopify/shopify_app#1108]
Windows 10
Ruby 2.4.3

Hey,

How can i prettify output in pry or (irb) when i make ShopifyAPI request in console ?

currently i got this : 

[11] pry(main)> Product.all
[#<ShopifyAPI::Product:0x0000000004e87408 @attributes={"id"=>502988177438, "title"=>"adele", "body_html"=>"", "vendor"=>"player simple", "product_type"=>"", "created_at"=>"2018-01-26T05:21:38-05:00", "handle"=>"test", "updated_at"=>"2020-04-04T08:40:48-04:00", "published_at"=>"2018-01-26T05:21:34-05:00", "template_suffix"=>nil, "status"=>"active", "published_scope"=>"web", "tags"=>"", "admin_graphql_api_id"=>"gid://shopify/Product/502988177438", "variants"=>[#<ShopifyAPI::Variant:0x0000000004e84ff0 @attributes={"id"=>7118364868638, "title"=>"Default Title", "price"=>"0.00", "sku"=>"", "position"=>1, "inventory_policy"=>"deny", "compare_at_price"=>nil, "fulfillment_service"=>"manual", "inventory_management"=>nil, "option1"=>"Default Title", "option2"=>nil, "option3"=>nil, "created_at"=>"2018-01-26T05:21:39-05:00", "updated_at"=>"2018-09-11T22:36:20-04:00", "taxable"=>true, "barcode"=>"", "grams"=>0, "image_id"=>nil, "weight"=>0.0, "weight_unit"=>"kg", "inventory_item_id"=>7125910323230, "inventory_quantity"=>1, "old_inventory_quantity"=>1, "requires_shipping"=>true, "admin_graphql_api_id"=>"gid://shopify/ProductVariant/7118364868638"}, ....

i have install awesome_print gem but looks like it's not working. Do you have an idea? How do you prettify your output?

**Comment by yourivdlans** [comment]
You could maybe transform it to a json object first and then output, like so:

```
pp Product.all.to_json
```
