### ISSUE TITLE
Issue with shopify_app assets, app proxy, and Rails fingerprinting

### ISSUE THREAD

**Issue by skillmatic-co** [Shopify/shopify_app#1109]
I'm getting this error in my Shopify App (which it seems like a lot of other's have):

`ActionView::Template::Error (The asset "shopify_app/request_storage_access.js" is not present in the asset pipeline.`

on line 66 of: `app/views/shopify_app/sessions/request_storage_access.html.erb`

It appears, with Rails asset fingerprinting, that the actual file is at:

```
app_proxy/assets/shopify_app/request_storage_access-b788d39d049a021c613dbac4f0f60c18d4eed19381c77df24fb91210a7919e4e.js
```

This is due to:

1. My app is a proxy app.
2. Rails asset fingerprinting: https://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark

How do I go about updating this path to the correct path to the file?

**Comment by skillmatic-co** [comment]
To get this to work for me I had to edit 3 files:

`app/views/shopify_app/sessions/request_storage_access.html.erb` and change line 66 to:

```
<%= javascript_include_tag("/app_proxy/assets/" + Rails.application.assets_manifest.assets["shopify_app/request_storage_access.js"], crossorigin: 'anonymous', integrity: true) %>
```

`app/views/shopify_app/shared/redirect.html.erb` and change line 8 to:

```
<%= javascript_include_tag("/app_proxy/assets/" + Rails.application.assets_manifest.assets["shopify_app/redirect.js"], crossorigin: 'anonymous', integrity: true) %>
```

`apps/views/layouts/embedded_app.html.erb` and change line 7 to: 

```
<%= stylesheet_link_tag "/app_proxy/assets/" + Rails.application.assets_manifest.assets["application.css"] %>
```

and line 9 to: 

```
<%= javascript_pack_tag "/app_proxy/assets/" + Rails.application.assets_manifest.assets["application.js"], 'data-turbolinks-track': 'reload' %>
```

and line 11 to: 

```
<%= javascript_include_tag "/app_proxy/assets/" + Rails.application.assets_manifest.assets["application.js"], "data-turbolinks-track" => true %>
```

After making these changes, my `The asset "[FILENAME]" is not present in the asset pipeline.` errors went away.

**Comment by andyw8** [comment]
@skillmatic-co thank you for sharing your solution here.

**Comment by malachaifrazier** [comment]
@skillmatic-co do you think that your solutions should go in a documentation-only PR?

**Comment by paulomarg** [comment]
@skillmatic-co great that you found a workaround! Ideally we'd like to figure out why this isn't working, so I just wanted to confirm a few settings on your app to see if we can spot the reason why this might be failing.

- Are these env vars set in your production environment?
  - `SHOPIFY_APP_DISABLE_WEBPACKER`
  - `RAILS_SERVE_STATIC_FILES`
- What is your `config.assets.compile` setting for production (in `config/environments/production.rb`?
- What is your `config.public_file_server.enabled` setting? By default it should be dictated by the `RAILS_SERVE_STATIC_FILES` var above.
- I assume as per the related issue that you've already precompiled your assets with the production environment?
