### ISSUE TITLE
AR store is being overridden in example code

### ISSUE THREAD

**Issue by bennick** [Shopify/shopify_app#111]
In your example [here](https://github.com/Shopify/shopify_app/blob/master/lib/generators/shopify_app/templates/config/initializers/shopify_session_repository.rb#L9) the class method `store` is overriding a built in AR class method: https://github.com/rails/rails/blob/0ac16326d20e1ce8d0b3af363012b17a3c8b6086/activerecord/lib/active_record/store.rb#L75

**Comment by kevinhughes27** [comment]
we do this using the SessionStorage class now so I don't think it clashes.
