### ISSUE TITLE
Redirect URI dropping https protocol in "TEST" ENV

### ISSUE THREAD

**Issue by Jonathan-Garber** [Shopify/shopify_app#1112]
How does shopify_app and redirect uri work itself out?
I am coming in from a subdomain say  https://myapp.mydomain.tld

However the app is not passing "https" in the redirect_uri parameter
I am getting
```
https://dummyshop.myshopify.com/admin/oauth/authorize?client_id=CLIENTIDHERE&redirect_uri=http%3A%2F%2Fmyapp.mydomain.tld%2Fauth%2Fshopify%2Fcallback&response_type=code&scope=read_orders%2Cread_products%2Cread_customers%2Cread_all_orders&state=blahblahblah
```

It keeps dropping the "https" for "http"
My RAILS_ENV is "TEST" when this happens. It seems perfectly fine in Production and Development ENVs

The subdomain is under a valid https certificate from Let's Encrypt and works fine in browsers. I just cannot find the reason for it not passing along "https". Origin, Referrer, etc all headers and urls are under "https" until the redirect_uri param drops it and breaks the process. Any pointers here on what causes this?

**Comment by paulomarg** [comment]
Thanks for reporting this @Jonathan-Garber, we will look into why the protocol is being changed.

I assume that this is happening when you're running tests? If that is the case, it would help to know if there are any specific steps to take in a test to trigger the error.

**Comment by Jonathan-Garber** [comment]
Closing issue -- after banging away on this I discovered I did something stupid on my end and resolved the issue. Sometimes best thing is to walk away for a few hours then come back LOL.
