### ISSUE TITLE
shopify deploy heroku - Internal Server Error (authenticating issue)

### ISSUE THREAD

**Issue by 90stareq** [Shopify/shopify_app#1116]
- deployed my app with: **shopify deploy heroku**
- updated **URL** in the app setup
- when i log to the auth url: **https://protected-peak-19352.herokuapp.com/auth?shop=my-app.myshopify.com**
- error appears: **Internal Server Error**

**Comment by andyw8** [comment]
@90stareq there's not enough information to know the problem, you would need to check the Heroku logs.

**Comment by 90stareq** [comment]
i didn't add .env files
but still it doesn't redirect to the app
