### ISSUE TITLE
Configuring the script tags is causing errors

### ISSUE THREAD

**Issue by yehiasalam** [Shopify/shopify_app#1128]
Hi,

I ran my custom app using the shopify-cli and shopify_app, and everything was working fine. I'm trying right now to add an external js file to the frontstore, using the config.scripttags as instructed in the docs:

```
ShopifyApp.configure do |config|
  config.application_name = "My Shopify App"
  config.api_key = ENV.fetch('SHOPIFY_API_KEY', '').presence || raise('Missing SHOPIFY_API_KEY')
  config.secret = ENV.fetch('SHOPIFY_API_SECRET', '').presence || raise('Missing SHOPIFY_API_SECRET')
  config.old_secret = ""
  config.scope = "write_script_tags" # Consult this page for more scope options:
                                 # https://help.shopify.com/en/api/getting-started/authentication/oauth/scopes
  config.embedded_app = true
  config.after_authenticate_job = false
  config.api_version = "2020-10"
  config.shop_session_repository = 'Shop'
  config.allow_jwt_authentication = true
  config.allow_cookie_authentication = false

  config.scripttags = [
    {event:'onload', src: 'https://x.x.com/widget/widget.js'}
  ]

end
```

However, whenever I install the app i keep getting the following error, and this happens after adding:

```
  config.scripttags = [
    {event:'onload', src: 'https://x.x.com/widget/widget.js'}
  ]
```

![Screenshot 2020-12-21 235958](https://user-images.githubusercontent.com/201734/102826352-26a94300-43e9-11eb-86c6-1bf0fc6e9dad.png)

Not sure what might the problem might be. It shouldn't be related to Auth i guess since it was working fine before adding the scripttags config.

**Comment by paulomarg** [comment]
Hey @yehiasalam, thank you for reporting this. We'll look into it!

**Comment by tanema** [comment]
Does this happen in all browsers? Was authentication seemingly successful before this error?

**Comment by m0n9oose** [comment]
Just got pretty much the same exception:

<img width="827" alt="Screenshot 2021-01-12 at 13 22 30" src="https://user-images.githubusercontent.com/1478556/104314107-3ba15f80-54d9-11eb-977e-38d5aa7a0064.png">

I'm using JWT authentication (in process of migration from OAuth), Rails 6.1, shopify_app 16.1.0.

We use `webhooks` setting, but not `scripttags`. Problem happened when I uninstalled my dev app and tried to install it again.

Here's my initialiser:

```ruby
ShopifyApp.configure do |config|
  config.application_name = 'App name'
  config.api_key = ENV['SHOPIFY_CLIENT_API_KEY'].presence || Rails.application.credentials.shopify_client_api_key
  config.secret = ENV['SHOPIFY_CLIENT_API_SECRET'].presence || Rails.application.credentials.shopify_client_api_secret
  config.scope = 'read_themes, write_themes, read_products, write_products, read_content, write_content'
  config.embedded_app = true
  config.shop_session_repository = Shop
  config.api_version = '2020-01'
  config.allow_jwt_authentication = true
  config.allow_cookie_authentication = false

  config.webhooks = [
    { format: 'json', topic: 'app/uninstalled', address: "https://#{ ENV['SHOPIFY_DOMAIN'].presence || Rails.application.secrets.domain }/uninstall" },
  ]
end
```

**Comment by yehiasalam** [comment]
@tanema Hi Tim, yes i check on Chrome/Firefox/Edge, authentication was happening successfully right before I added the script tag.

**Comment by anquinn** [comment]
I'm having the same issue when trying to add webhooks to the initializer. Referenced in #1145.

**Comment by resistorsoftware** [comment]
I am having this same issue. Rails 6.0.3, Shopify App 17.0.1

    NoMethodError (undefined method `token' for nil:NilClass):
    shopify_app (17.0.1) app/controllers/shopify_app/callback_controller.rb:135:in `install_webhooks'
    shopify_app (17.0.1) app/controllers/shopify_app/callback_controller.rb:54:in `perform_post_authenticate_jobs'
    shopify_app (17.0.1) app/controllers/shopify_app/callback_controller.rb:17:in `callback'

**Comment by resistorsoftware** [comment]
Seems pretty clear this has to do with JWT and oAuth. The JWT Shopify domain object is nil all the time coming from no value at   request.env['jwt.shopify_domain']

So what's up with that?
