### ISSUE TITLE
Since Rails 4.1, creating a new application is broken

### ISSUE THREAD

**Issue by gmalette** [Shopify/shopify_app#113]
![screen shot 2014-12-19 at 1 58 02 pm](https://cloud.githubusercontent.com/assets/351915/5509533/20162f32-8787-11e4-8f84-5dffb1e7f403.png)

The reason is that since https://github.com/rails/sprockets-rails/pull/84, Rails will not serve assets not in the compile path (to avoid surprises down the line). 

This has been addressed in [less-bootstrap-rails last year](https://github.com/metaskills/less-rails-bootstrap/pull/81). However, this gem is still stuck on a [2 year old version of less-bootstrap-rails](https://github.com/Shopify/shopify_app/blob/697028001f71cf52e47d93749de426a0b3d7cf7d/shopify_app.gemspec#L20).

I think the long-term solution is to upgrade the gem.

**Comment by kevinhughes27** [comment]
creating new apps works in rails 4.2 with the latest version
