### ISSUE TITLE
Shopify App with JWT token and Turbolinks doesn't work.

### ISSUE THREAD

**Issue by oliwoodsuk** [Shopify/shopify_app#1130]
Hi there,
I've been trying to upgrade my Shopify app to work with session token authentication for the last 10 days or so. I followed the steps [here](https://github.com/Shopify/turbolinks-jwt-sample-app), which all seem pretty simple and straight-forward.

The actual code of the project above doesn't seem to work (I've downloaded and tried it + also generated a new app with the shopify_app gem, then made the changes in the guide. Neither work).

On my own codebase I can get the app to work nicely as described in the guide, but then new stores can't install. Or I can change the app URL in Shopify partners to link to that of an authenticated controller. Which lets new stores install, but then the app won't work when opened from within a store. I actually ended up paying a more senior developer to help me with this issue and we're both stumped.

My main question is: how do I make the splash controller redirect to the store installation process when it's a new store, but not when it's an existing store?
(SplashController isn't meant to have ShopifyApp::LoginProtection (which starts the install process), but I don't know when/how to redirect to a controller that does in a way that satisfies the installation process + the app standard running).

One clue might be `current_shopify_domain` often doesn't work, I've had to change it to `@shop_origin = current_shopify_domain rescue params[:shop]` in the splash controller for example.

I've currently got my app hidden from the AppStore because of the problem.
Any help would be super appreciated.

Thanks,

Oli

**Comment by oliwoodsuk** [comment]
Just worked through this with Nabeel and got the app back up and running.

- So, I didn't include `include ShopifyApp::RequireKnownShop` in my splash controller, as the `current_shopify_domain` kept on failing.
- Solution: include `skip_before_action :verify_authenticity_token` and `protect_from_forgery with: :null_session` in the splash controller at the top.

- However, the store seemingly still wasn't installing on my test store. It would work when visting app_url, but not app_url/?shop=xxxx. Instead, I was taken to a grey screen with 'there's no page at this address'.
- Solution: If you already have the shop that you're trying to install in your database, this will happen. Was really hard to figure this out, as all of my test stores had entries in my local and production databases. I'm going to create a webhook linked up to Shopify's 'app/uninstalled' event.

Hope that helps someone.

Cheers,

Oli

**Comment by kirillplatonov** [comment]
I had the same error "there's no page at this address" with app reinstall. I also using JWT + Turbolinks. It seems like in the example app [here](https://github.com/Shopify/turbolinks-jwt-sample-app) there's no check if the token is still valid. So if the merchant removed the app - then the token is not valid anymore but we still keep the record in DB so the app won't trigger the auth process.

To solve it I added a call to `ShopifyAPI::Shop.current` in `SplashPageController`. This will trigger OAuth token check. If it will fail then `ActiveResource::UnauthorizedAccess` error will be raised. And `ShopifyApp::LoginProtection` will handle it - it will close the session and force new login.

```ruby
# app/controllers/splash_page_controller.rb

class SplashPageController < ApplicationController
  include ShopifyApp::EmbeddedApp
  include ShopifyApp::RequireKnownShop
  # required to trigger OAuth token check
  include ShopifyApp::LoginProtection

  def index
    @shop_origin = current_shopify_domain

    # required to trigger OAuth token check
    shop = Shop.find_by(shopify_domain: current_shopify_domain)
    shop.with_shopify_session do
      ShopifyAPI::Shop.current
    end
  end
end
```

It works but not sure if there's a better way to do it. Will appreciate the feedback.

**Comment by NabeelAhsen** [comment]
@kirillplatonov Thank you for bringing this up - we've noticed that our documentation lacks important instruction for handling app uninstalls. There is work underway to fix this.

When your app is uninstalled on a shop `sample_domain.myshopify.com`, Shopify notifies your app through the `app/uninstalled` webhook. Your app is then able to subscribe to this webhook notification and run a custom job when an app is uninstalled.

Luckily, this capability is [supported by the Shopify App gem out-of-the-box](https://github.com/Shopify/shopify_app#webhooksmanager) and is fairly easy to implement.
- **Note:** A shop will need to go through the login flow before it's able to start sending webhook notifications to your app.
- see: https://shopify.dev/docs/admin-api/rest/reference/events/webhook

If you'd like to see a sample implementation of this, check out the following PR: https://github.com/Shopify/turbolinks-jwt-sample-app/pull/16
- In this PR we create a job that takes the shopify domain sent by the webhook notification and marks the app as uninstalled on that shop in our db.
