### ISSUE TITLE
Improve multi-shop login with users

### ISSUE THREAD

**Issue by nickmealey** [Shopify/shopify_app#1139]
When using both online and offline access modes, multi-shop login doesn't work automatically with the second shop. Steps to replicate:

- Enable user and shop based tokens
- Login to two shops through Shopify
- Login to app on first shop
- Login to app on second shop (without logging out, ie. click on the app icon on apps page or navigating to `/login?shop=example.myshopify.com`)

This ends up redirecting to `/login` because `session[:shop_id]` is set to `nil` in the [CallbackController](https://github.com/Shopify/shopify_app/blob/7b367c6c7f17fae778fd1bf1e43eb52b8db27b30/app/controllers/shopify_app/callback_controller.rb#L120). Reasonably, this is being unset because there's a mismatch in the domain. It seems to make sense to also put this logic __before__ logging, so that it will follow the oauth flow to get offline access before getting online access.

Essentially, this means when a merchant clicks on the app, it will log them in without need to go through another step.

**Comment by axlekb** [comment]
Cross-referencing: https://github.com/Shopify/shopify_app/issues/1181
