### ISSUE TITLE
That's a mighty big jump

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1141]
Interesting jump from version 16 to 17. 

How come Shopify does not just do point released till eventually there is something significant to warrant a major version jump? What is the big difference between 16 and 17?

**Comment by andyw8** [comment]
Hi @resistorsoftware 

As mentioned in the CHANGELOG, the reason for the update is because the latest Rails release (6.1) does not currently work with shopify_app out-of-the-box. 

We aim to follow the [Semantic Versioning](https://semver.org/) standard. As this could be a non-backwards compatible update, it deserves a major version bump.

**Comment by resistorsoftware** [comment]
I like your wording. I might've selected to instead say, Shopify App does not currently work with Rails 6.1, but the other way around works too. If you are going to bite off a huge chunk of real estate and leave behind some major aspects of what got you to Rails 6.0 and App version 16, why not go all-in on the fact that you are really walking away from everything the last 16 versions has brought to the table, and leave 16 to the masses content to use it as it was, and go with a shiny new App that has none of the old baggage. Surely you could release a new App that:
- supports Polaris, App Bridge React nicely
- support Rails 6.x and on
- JWT auth

Would be nice to not have to constantly fight these minor point releases with their sometimes obscure 1-line changes that break old things but fix new things, mostly. 

Just saying... the hand-wringing that has gone into supporting as much as possible for as long as possible without causing pain is maybe the time to fork the road and force some passengers to pick their battles in a cleaner way?
