### ISSUE TITLE
NoMethodError in ShopifyApp::CallbackController#callback - Webhooks

### ISSUE THREAD

**Issue by anquinn** [Shopify/shopify_app#1145]
I've created a basic app with the CLI and the gem, but when I try and add a webhook with the generator I get a No MethodError when trying to install the app. `undefined method `token' for nil:NilClass`

```
WebhooksManager.queue(
        shop_name,
        shop_session&.token || user_session.token,
        ShopifyApp.configuration.webhooks
      )
end
```

It has issue with `shop_session&.token || user_session.token,`. Removing webhooks solves the issue, but I need webhooks. I've tried both the generator and the example from the read me. Both generate the same issue.

Rails 6.0.3.4
Ruby 2.7.1

**Comment by paulomarg** [comment]
Hi @anquinn, thanks for reporting this.

I believe this is the same issue as #1128, but for Webhooks. I'm going to close this issue so we can track everything under the previous one which has some more information.
