### ISSUE TITLE
"Too many redirects" when using :login_again_if_different_shop

### ISSUE THREAD

**Issue by JahBrewski** [Shopify/shopify_app#115]
Hello, I'm trying to utilize the `login_again_if_different_shop` method in my application_controller, but I keep getting a "Too many redirects" error whenever I try to use it.  Anyone else getting this error?

**Comment by ckhatton** [comment]
Has anyone picked this one up? :eyes:

**Comment by kevinhughes27** [comment]
now that more of this is done in concerns as part of the gem I would like to close. If people are still running into issues please open a new issue referring to the new code

**Comment by ericavmorris** [comment]
Fixed this by going to Domains>Connect Existing Domain>entering your domain name>OK. (Basically re-connecting your domain name 👍 )

**Comment by ericavmorris** [comment]
Was perpetually getting this error too, fixed by going to Domains>Connect Existing Domain>entering your domain name>OK. (Basically re-connecting your domain name)
