### ISSUE TITLE
Fulfillment Service CSRF Problem

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1161]
Rails 6.0.3.4, ShopifyApp 17.0.2

Route:  POST /fulfillment_order_notifications

I have a fulfillment service that is opt-in for fulfillment orders. So when the merchant presses the button Request Fulfillment, and makes that official, Shopify sends a POST to that endpoint in the App. Unfortunately, when I look at the logs, this is what I see. Why am I getting a CSRF 422 error? 

This controller is inheriting from ActionController, not AuthenticatedController, as I do not believe fulfillment service requests that originate at Shopify have any authentication. 

    Processing by FulfillmentsController#notification as */*
      Parameters: {"kind"=>"FULFILLMENT_REQUEST"}
    Can't verify CSRF token authenticity.
    Completed 422 Unprocessable Entity in 0ms (Allocations: 500)
    ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):

**Comment by andyw8** [comment]
@resistorsoftware you likely need to disable CSRF protection for that particular controller action in your app:

https://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection/ClassMethods.html#method-i-protect_from_forgery

**Comment by andyw8** [comment]
> `config.action_controller.default_protect_from_forgery` determines whether forgery protection is added on ActionController::Base.

(and this is enabled by default in new apps)

https://edgeguides.rubyonrails.org/configuring.html

**Comment by resistorsoftware** [comment]
Thanks! Worked out well.
