### ISSUE TITLE
After a fresh install webhooks are not listed on the index.html.erb template page

### ISSUE THREAD

**Issue by RobsonKing** [Shopify/shopify_app#1168]
After running the default generator and installing the app in my store I was able to see the following message at the bottom of the ui.

`This app has not created any webhooks for this Shop. Add webhooks to your ShopifyApp initializer if you need webhooks`

After adding a webhook to the initializer as described (again using the generator)

` config.webhooks = [
    {topic: 'products/update', address: 'https://*****.ngrok.io/webhooks/products_update', format: 'json'},
  ]`

It worked and the webhook fires as expected.  But the message ('This app has not created.... etc') remains at the bottom of the UI.

After looking at it, I fail to see how @webhooks that it relies on is set.

Am I missing something?  This caused me confusion for quite a while because I thought my webhook wasn't being picked up.

**Comment by paulomarg** [comment]
Hey @RobsonKing, thank you for your report! It seems that we aren't loading the webhooks as we do products for new embedded apps.

As you mentioned, you should be able to register and receive webhooks normally, they are just not being listed in the index action. We'll look into making sure that page is consistent.
