### ISSUE TITLE
Question about Webhook Code

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1173]
I set up a webhook on orders/paid and Shopify keeps sending my App the same order over and over again. I am curious as to why, since I return a 200 OK. What I see is this in my console:

    20:26:57 rails.1   | Processing by WebhooksController#receive as */*
       ... some background job is delegated and off we go there
    20:26:57 rails.1   | Completed 200 OK in 34ms (ActiveRecord: 0.0ms | Allocations: 17856)

So this order, I have seen maybe 4 or 5 times today since it first hit Shopify. The webhook code in the controller seems fine, fires up the background job, and returns a head(:ok) 

    def receive
      params.permit!
      job_args = { shop_domain: shop_domain, webhook: webhook_params.to_h }
      webhook_job_klass.perform_later(job_args)
      head(:ok)
    end

So why is Shopify continuing to send me this order over and over again? Should it not stop the first them it gets a 200 OK?

**Comment by andyw8** [comment]
Is there a possibility your app is taking > 5s to respond? https://shopify.dev/tutorials/manage-webhooks

**Comment by resistorsoftware** [comment]
From the timing I see in my logs, that particular response was 34ms. I am thinking that is sufficiently fast to let Shopify know that it need not re-send this webhook. While I do check for dupes in the background job spawned, I am curious as to why this particular implementation of webhook processing is not working out with Shopify.

**Comment by jiblits** [comment]
I had an issue similar to this and it turned out I was having Shopify echo back `order/updated` webhooks to me, to which I would perform some action and push a change again. The changes were effectively no-ops but it still caused a change which triggered another webhook.
