### ISSUE TITLE
JSON response not rendered correctly with Ruby 3

### ISSUE THREAD

**Issue by andyw8** [Shopify/shopify_app#1178]
See discussion in #1176

**Comment by resistorsoftware** [comment]
I am curious about Rails for this. JS in the front-end expects some ActiveRecord data like Model -> User with an attribute first_name to be firstName, but does vanilla rails not just return first_name, assuming you get the JSON you want? 

ie) I was seeing my calls for data returning { "user": { "first_name": "AppleJuice" } } in my typical responses. What do people do about this? I use a cheesy gem called Olive Garden or something.
