### ISSUE TITLE
Old Bootstrap Version

### ISSUE THREAD

**Issue by brahmadpk** [Shopify/shopify_app#118]
The gem installs an older version of Bootstrap.

/*!
 * Bootstrap v2.3.2
 *
 * Copyright 2012 Twitter, Inc
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Designed and built with all the love in the world @twitter by @mdo and @fat.
 */

Can this be changed to include the latest version. Thanks.

**Comment by ckhatton** [comment]
The plan of action is actually to remove Bootstrap :coffee:

**Comment by nakulpathak3** [comment]
Has this change been made yet? I wanted to use Rails 4.2.0 and was wondering if the app will work before I begin.

**Comment by csaunders** [comment]
Nope.

To be honest this gem is pretty much just generators. You can get most of what you want by simply using the [shopify_api gem](https://github.com/Shopify/shopify_api) and the [shopify-omniauth-oauth2 gem](https://github.com/Shopify/omniauth-shopify-oauth2).

**Comment by nakulpathak3** [comment]
Okay thanks. I'll look into those.

**Comment by ckhatton** [comment]
Yea the Bootstrap gem shouldn't hinder the running of the app. You can either remove or upgrade it yourself locally :8ball:

**Comment by kevinhughes27** [comment]
latest version doesn't include bootstrap anymore. closing
