### ISSUE TITLE
Per user auth from app list redirect with session query parameter

### ISSUE THREAD

**Issue by axlekb** [Shopify/shopify_app#1181]
Hi folks, Thanks for your work on this gem!

I've had non-embedded Shop session authentication working for years, and have been trying to follow the instructions for adding per-user session. I have it working when I use my own login page, however, when I click the link from a list of a shop's installed apps, I end up in an infinite loop.

From my research, the installed app list link redirects to app's URL with a `session` value in the query params.  From some debugging, it appears that session query param is tripping up part of `LoginProtection`.  After a successful Oauth login, `shopify_app` _returns_ to the original URL that has the `params[:session]`.  However, in `LoginProtection` the `session[:user_session]` from Oauth does not match the `params[:session]` from the redirect query string, triggering the session to be cleared, and login is forced again.  1. Successful login.  2. redirect to return URL. 3. sessions don't match in `LoginProtection`.  4. clear session.  Repeat.

I would guess that session param from the app list redirect should match the Oauth session?
Or should I be authenticating differently from the app list URL that has the session param?

What am I missing?

Thanks!

```ruby
# shopify_app/lib/shopify_app/controller_concerns/login_protection.rb

def login_again_if_different_user_or_shop
   if session[:user_session].present? && params[:session].present? # session data was sent/stored correctly
     clear_session = session[:user_session] != params[:session] # current user is different from stored user
   end
...
```

**Comment by mitchnick** [comment]
@axlekb Same exact thing on my app. Did you find a fix for this by chance?

**Comment by axlekb** [comment]
@mitchnick I wasn't able to discover a workaround, but now that someone has reproduced the same issue, hopefully we'll see some action from the maintainers as it involves some Shopify black box (outside gem) functionality

**Comment by mitchnick** [comment]
@axlekb When I'm debugging I see it sets the session[:user_session] value in the callbacks controller. 

```
def set_shopify_session
  ...
  session[:user_session] = auth_hash&.extra&.session  
end
```

I'm not entirely sure if the check on `login_again_if_different_user_or_shop` for if the session[:user_session]  matching the session param in the URL is even valid. Maybe the params[:session] was supposed to change somewhere along the lines and it's not getting passed correctly. All of the other checks and session values are getting set correctly in the CallbacksController. 

Here's my setup:

shopify_app (17.2.1)

shopify_app.rb
config.embedded_app = false
  config.api_version = "2021-01"
  config.shop_session_repository = "Account"
  config.user_session_repository = "User"
  config.old_secret = ""
  config.enable_same_site_none = true
  config.allow_jwt_authentication = false
  config.allow_cookie_authentication = true
  
  omniauth.rb
  Rails.application.config.middleware.use(OmniAuth::Builder) do
  provider :shopify,
    ShopifyApp.configuration.api_key,
    ShopifyApp.configuration.secret,
    scope: ShopifyApp.configuration.scope,
    setup: lambda { |env|
      configuration = ShopifyApp::OmniAuthConfiguration.new(env['omniauth.strategy'], Rack::Request.new(env))
      configuration.build_options
    }
end

**Comment by mitchnick** [comment]
Anyone know how terrible it would be to just overwrite the login_again_if_different_user_or_shop method to remove the check that's causing the error?

The rest of the method stays intact, but these lines are removed:

```
def login_again_if_different_user_or_shop
  # if session[:user_session].present? && params[:session].present? # session data was sent/stored correctly
  #   clear_session = session[:user_session] != params[:session] # current user is different from stored user
  # end

  if current_shopify_session &&
    params[:shop] && params[:shop].is_a?(String) &&
    (current_shopify_session.domain != params[:shop])
    clear_session = true
  end

  if clear_session
    clear_shopify_session
    redirect_to_login
  end
end

```

**Comment by wnm** [comment]
> I would guess that session param from the app list redirect should match the Oauth session?
> Or should I be authenticating differently from the app list URL that has the session param?
> 
> What am I missing?


maybe @slucaskim can help answer some of those questions?

**Comment by mitchnick** [comment]
This seems to be resolved in the most recent version of shopify_app (was 17.0.5, updated to 18.0.1). I also updated rails to 6.1 from 6.0 and ruby to 3.0 from 2.7. 

@axlekb Is this fixed for you as well if you update some of the underlying libraries?

**Comment by axlekb** [comment]
Thanks for the ping @mitchnick.  I tried to revive my old branch and update the gems, but still appear to be stuck with infinite redirections.  Will have to review docs and investigate further when I have more time.  Thanks, again.

**Comment by dustineichler** [comment]
I'm seeing this too. 

```Rails v6.1, Ruby v3.0.0. Shopify_app v18.0.1```

**Comment by asecondwill** [comment]
So am i
 rails (6.1.3) ruby '2.7.2'  shopify_app (17.2.1)

**Comment by asecondwill** [comment]
Tried updating shopify_app to 18.0.1.  The oAuth is still broken - redirects endlessly when opening from shop's app list.

**Comment by jvsidler** [comment]
I am experiencing this same issue [rails 6.1.3, ruby 3, and shopify_app 18.0.1].

It works locally but when I try to run it in a production environment, the infinite redirect occurs.

**Comment by wnm** [comment]
Yes, it's not something we can fix with changing settings. The issue is still as described in the opening bug report by @axlekb .

I asked a Shopify dev in a different repo, and he confirmed that the session which is passed as a parameter when opening an app from a store's app dashboard, should be the same as the session in the auth hash. Which it isn't. This probably isn't a bug in this gem, but rather something that needs to be fixed at Shopify.

The relevant line is here: https://github.com/Shopify/shopify_app/blob/e4b2d7fc10685581b50c1353dd28f58b0507cebe/lib/shopify_app/controller_concerns/login_protection.rb#L77

As long as the is a mismatch between the session parameter send back by Shopify's app dashboard, and the paramater send back by Shopify during oauth, there is going to be a redirect....

**Comment by dustineichler** [comment]
@wnm has anyone relayed when we might see this resolved? thanks for following up on this.

**Comment by wnm** [comment]
@dustineichler no, I'm not even sure someone from Shopify is aware of the issue... It honestly doesn't seem like anyone is actively reading issues here. The auth flow is a mess, and the redirect issue is just one of multiple well known bugs regarding authentication... To be fair, apart from opening and commenting on issues here in this repo, I haven't done anything else, since I don't know if there is a way to file a bug reports for stuff outside of this gem.

**Comment by dustineichler** [comment]
@wnm if Shopify isn't aware. Is anyone maintaining this gem? 🤦‍♂️

I really don't want to invest time into something that run so poorly.

**Comment by wnm** [comment]
not sure. there is probably just way much stuff to do, then there are developers... but it seems like they are h[iring developers to work on this gem too](https://github.com/Shopify/shopify_app/commit/61fc86856cf32b1fa320d4530fd0b5a9dbcc15fd)

**Comment by axlekb** [comment]
@nickmealey appears that there has been no effort to resolve it from Shopify
