### ISSUE TITLE
Should Webhook Manager Recreate The Webhook When Its `fields` Definition Changes? 

### ISSUE THREAD

**Issue by sshaw** [Shopify/shopify_app#1183]
Came across this recently and since I'm on an "ancient" version (5 major releases in a year, who can keep up really...) I thought: maybe the latest code would have it‽ But, I just took a looksy and; it does not. Currently only topic is looked at. 

Thoughts on looking at fields too? 

If the old hook had none specified but the config does or the config's differs then update the hook's `fields`. Seems to make sense especially since it can be done via a PUT call but it's certainly possible I'm missing an important point.

**Comment by resistorsoftware** [comment]
You know what else is interesting about this? When you examine an old Webhook, you might see API Version in it of say "2020-01" or something. But in reality, right now, all your code is using "2021-01" or something newer. So when API versions get changed in your App, old established webhooks do not update themselves. Not that intrinsically it matters, but in some ways, it represents the same dilemma. External things change but the fact that the old version exists means it is not updated to match any changes.
