### ISSUE TITLE
requires merchant approval for write_products scope

### ISSUE THREAD

**Issue by Ali1094** [Shopify/shopify_app#1206]
Failed. Response code = 403. Response message = Forbidden ([API] This action requires merchant approval for write_products scope.)

I'm getting this error above. However I also add 'write_products' scope in shopify_app.rb but still getting this error.
Please help me out. I'm creating public app for my shopify store.

**Comment by jiblits** [comment]
You need to re-authorize your application with Shopify in order for your new scopes to work.

Go to `http://localhost:3000/shopify/login` (or wherever your login screen is) and re-enter your myshopify domain.

**Comment by NabeelAhsen** [comment]
If your app only uses [shop-based token storage](https://github.com/Shopify/shopify_app/blob/master/docs/shopify_app/session-repository.md#shop-based-token-storage), then `v17.1.0` of the shopify_app gem can help handle this for you.

See the following: https://github.com/Shopify/shopify_app/blob/master/docs/shopify_app/handling-access-scopes-changes.md

**Comment by nelsonwittwer** [comment]
Closing as it seems like the questions were answered
