### ISSUE TITLE
Update instructions for how to setup `reauth_on_access_scope_changes`

### ISSUE THREAD

**Issue by lonroth** [Shopify/shopify_app#1211]
### Summary

First of all, thanks a lot to @rezaansyed and all of you that worked on implementing great updates in https://github.com/Shopify/shopify_app/pull/1197/  👏  I believe the documentation https://github.com/Shopify/shopify_app/blob/master/docs/shopify_app/handling-access-scopes-changes.md for how to add the flag `reauth_on_access_scope_changes` however could be improved to make it simpler for people to use this functionality.

### Motivation

Easier for people to get started with this great added functionality with easier documentation.

### Describe alternatives you've considered

That people could read the source code and figure it out themselves by looking at the templates the gem generates. But it should ideally be super easy to get it setup no matter if you run the generator or not :)

### Additional context

I'll create a PR for the change that I suggest to not take time from more important issues that you're working on.

**Comment by lonroth** [comment]
PR created for this https://github.com/Shopify/shopify_app/pull/1212

**Comment by lonroth** [comment]
PR is now merged so closing this Issue.

**Comment by skillmatic-co** [comment]
Adding either / both of the things in https://github.com/Shopify/shopify_app/blob/master/docs/shopify_app/handling-access-scopes-changes.md causes errors in my app.

**Comment by lonroth** [comment]
@skillmatic-co What error do you get and what version of the GEM do you use? Did you upgrade from an old GEM-version?

**Comment by skillmatic-co** [comment]
@lonroth sorry forgot to update this, but yes the issue was I was using an older version of the gem. Once I updated, all good. Although I was still experiencing a weird continuous redirect and browser cookie issue. But ultimately it worked.

**Comment by deartrudence** [comment]
> https://github.com/Shopify/shopify_app/blob/master/docs/shopify_app/handling-access-scopes-changes.md

What version of the shopify_app gem are you using?
