### ISSUE TITLE
Turbo link issues

### ISSUE THREAD

**Issue by Ali1094** [Shopify/shopify_app#1217]
Hi!
My issue is that I'm creating shopify multiple page app using rails and turbo link. I followed complete steps from the documentation but after installing my app than it redirect me to login page again and again. I don't know what's the issue behind it. 
If anyone help me I'll  very thankful to them.

**Comment by NabeelAhsen** [comment]
👋  Hey there, if you're still having issues, could you update your original comment here to fill out the following template? It'll help narrow things down: https://github.com/Shopify/shopify_app/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

**Comment by axlekb** [comment]
Could this be related to https://github.com/Shopify/shopify_app/issues/1181 ?
