### ISSUE TITLE
TAG filtering using URL - Include OR option instead of AND only.

### ISSUE THREAD

**Issue by MihaelBercic** [Shopify/shopify_app#1222]
### Summary

Using URL filtering regarding tags is amazing, but the fact that it only supports AND condition is seriously lacking.
Please implement a feature for OR tags.

### Motivation

It is an extremely basic functionality that'd benefit a lot if not all shopify stores.
Using and paying for an app for such a simple functionality seems like waste of good potential as well as relying on external servers for the basic functionality.

The expected outcome would for URL to include some sort of a OR where tags of either side would be used to filter the results.

### Describe alternatives you've considered

I've considered JavaScript solutions (ineffective), external applications (expensive) and attempted some solutions of my one that would count as _hacks_.

Thank you

**Comment by paulomarg** [comment]
Thanks for this @MihaelBercic, we'll look into it.

**Comment by MihaelBercic** [comment]
> Thanks for this @MihaelBercic, we'll look into it.

Great to hear! Thank you.

**Comment by MihaelBercic** [comment]
> Thanks for this @MihaelBercic, we'll look into it.

Hey, sorry for bothering you, but has this been thought about, perhaps even implemented?

Thanks

**Comment by MihaelBercic** [comment]
@paulomarg Hey, have you thought about it or perhaps looked into it?

Thank you!

**Comment by andyw8** [comment]
The Liquid repo seems more appropriate for this. I see you already created https://github.com/Shopify/liquid/issues/1480 so I'll close this.
