### ISSUE TITLE
Any module/method/class to filter shop url before install?

### ISSUE THREAD

**Issue by user7856** [Shopify/shopify_app#1228]
Hi, I want to filter shop URL before installation like I don't want to give permission to install any type of sex toy website so I want to filter the word 'sex' but how can I do it? 

I found a module for checking invalid URL **`sanitize_shop_domain`** but is there something I can use to filter any word?

**Comment by resistorsoftware** [comment]
Be aware that you're barking up the wrong tree here. A Shopify store name can be anything, and has zero to do with the products being sold. The day Shopify came out, I grabbed two domains. cars.myshopify.com and flowers.myshopify.com thinging, hey! People one day might want those domains. Silly me. I quickly realized the Shopify store name makes zero difference. Your real DNS store name is what the world sees. 

As for filtering, you could simply allow installs, and have READ scope access to products. Just run a scan on the products. If you see a product with any "Bad" word in your opinion, you could simply delete the shop from your database and wash your hands of this. Of course, you will wash your hand thoroughly with soap and water too.

**Comment by nelsonwittwer** [comment]
Closing as it seems there were great suggestions made
