### ISSUE TITLE
NoMethodError: undefined method 'login_path' (in login_protection.rb)

### ISSUE THREAD

**Issue by hendrikbeck** [Shopify/shopify_app#123]
Hey there,

in login_protection.rb there is this method:

    def redirect_to_login
      session[:return_to] = request.fullpath if request.
      redirect_to login_path(shop: params[:shop])
    end

I am getting the above error message, that ```login_path``` is not found. Since nobody else is complaining about this, I'm almost certain I am missing something very simple but I really am stuck. Can you help & guide me through this please?

Thanks a lot
Hendrik

**Comment by ckhatton** [comment]
(I am responding off the cuff here) Is the login form submitting the parameter 'shop' with a value? And if so, is value correctly formatted? I seem to remember it is a bit particular, as in, it has to be like 'example.myshopify.com' :fallen_leaf:

**Comment by hendrikbeck** [comment]
@ckhatton: thanks, let me check the 1st point you're mentioning. The login_path doesn't exist, I just wasn't sure where it should point to. So I would create a route that points to example.shopify.com, with ```example``` being the variable to fill in? Let me see what that does... :-)

**Comment by ckhatton** [comment]
Na I think you're confused. 'example.shopify.com' was literally that, an example :smile:

I have just had a look at the `routes.rb` file - all the paths should be there, so you should not need to tinker with it. So I think it might be that you have not set up the app properly. Make sure to set the Application URL of the application in your Shopify partner account to 'http://localhost:3000/login' (you will need to change this once you host it on a proper domain, and not your computer).

---

See what happens is when the '/login' is visited, the 'new' action is fired in the Sessions controller, which goes through the process of authenticating `if params[:shop].present`.
https://github.com/Shopify/shopify_app/blob/master/lib/generators/shopify_app/templates/app/controllers/sessions_controller.rb

**Comment by hendrikbeck** [comment]
Yeah, it was clear to me that the "example..." was an actual example ;-) The app was also running already with a proper configuration for months, this more or less just came up while upgrading from shopify_app version 5.0.0 to 5.0.2.

Which ```routes.rb``` file did you look at? The one in my project doesn't have any routes named ```login```. 

If you look at https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/login_protection.rb, you'll see ```login_path``` used 2 times in the last two methods, as parameters to ```redirect_to```. Should those redirects really redirect away from my app (which runs on myserver.com) to example.shopify.com?

**Comment by hendrikbeck** [comment]
Mmmh ok. Having read the method ```redirect_to_login``` one more time, I think I do understand it now :-) First line stores the current URL as ```return_to``` so that Shopify knows where the user actually wanted to go to. Okay, that makes sense, of course. So now the line ```redirect_to login_path(shop: example)``` should really just forward to example.shopify.com? Let me try and see if that works...

**Comment by ckhatton** [comment]
Na, there should be a **get** and **post** 'login' route in your `routes.rb` under the routes for the Sessions controller. As you see [here](https://github.com/Shopify/shopify_app/blob/334e844d4b09ba414cbe4f24fa20984dbed2e06e/lib/generators/shopify_app/shopify_app_generator.rb#L47), the routes are supposed to be inserted when the Shopify App is generated.

So this must be the problem :crocodile:

**Comment by ckhatton** [comment]
I would just create a new project, generate the files using this Shopify App, and then compare the new `routes.rb` file with the one from the project you are trying to fix :octocat:

**Comment by hendrikbeck** [comment]
Thanks a lot, @ckhatton, for giving me all the right pointers. Here's a quick summary of my findings:
* Apparentlich the named route login_path was introduced in shopify_app after 5.0.0, so that's why this problem appeared now (after working fine on the old version for quite a while)
* What I didn't realize is the extent to which Rails determines magical names of routes based on their properties, like the URL pattern defined. If I had realized that, I might have looked at the right line much earlier and realized what's going on
* What we did differently than all the examples and different from what shopify_app expected: our Shopify login is not under ```/login``` (where Rails can determine ```login_path``` from) but under ```/shopify/login``` (since we've got multiple login mechanisms in our app). That means our named route had the name ```shopify_login``` instead of just ```login```. Again, in hindsight something very easy to spot.

So it all works now, thanks again. I was wondering if it's good that shopify_app hard-codes ```login_path```, expecting that it has this very name. Or maybe at least mention it in the documentation, in case other people are doing the same thing as we do. I'd be happy to help out that sounds like a good idea. Other than that I'm happy it works again :-)

**Comment by ckhatton** [comment]
I hadn't realised the named route 'login_path' was introduced into the shopify app after 5.0.0.

I presume, as it is the default, it is not stated in the readme because one can change the setup after. But saying that, I guess it could be added as upgrade notes.

Glad to have helped :neckbeard:

**Comment by ckhatton** [comment]
This issue is to be kept open - Upgrade notes need to be added to the `readme.md` :octocat:

**Comment by kevinhughes27** [comment]
this should be clear in the latest version
