### ISSUE TITLE
There’s no page at this address - reinstall issue

### ISSUE THREAD

**Issue by robbyklein** [Shopify/shopify_app#1233]
I recently converted an app to use session tokens and now it's getting an error where if a user uninstalls then tries to reinstall from the app store it returns a page saying "There’s no page at this address".

I was reading another issue here: https://github.com/Shopify/shopify_app/issues/456 and it seemed like the answer was to delete the shop record from the database.

Is there any alternative to this? My app stores data in metafields and needs to stay in sync with my app database. Deleting the records would create problems for me.

I was reading the session token doc here: https://shopify.dev/tutorials/authenticate-your-app-using-session-tokens and I found this:

![image](https://user-images.githubusercontent.com/6813372/112781378-8bcf8e80-8fff-11eb-99ed-f6aebc4fe814.png)

Is this unrelated to the issue?

Thanks!

**Comment by NabeelAhsen** [comment]
👋  Hey there

The **Mark shops as uninstalled using the app/uninstalled webhook** guide is certainly related to the issue. When a shop uninstalls your app, Shopify sends the `app/uninstalled` webhook. 

In a cookie world, reinstalls were being handled for you by fluke (the shopify_app gem used to do this by making your app do the OAuth dance on session expiry). With session tokens (and no reliance on 3p cookies), your app's going to need to register this webhook to handle uninstalls for you.

Here's a sample app we built that runs a job each time it receives an `app/uninstalled` webhook from Shopify:

*  https://github.com/Shopify/next-gen-auth-app-demo/blob/master/app/jobs/app_uninstalled_job.rb
    * This job marks your shop as uninstalled
* https://github.com/Shopify/next-gen-auth-app-demo/blob/master/app/models/shop.rb
    * To the sample app, `uninstall` means to delete your record. But the idea is that you can really do anything you want inside `def uninstall`. Just make sure it gets called on that particular shop on each webhook event.
  
  
### Here's the gotcha
  
If you decide that your uninstallation looks custom, then your root/home controller needs to be made aware of this accordingly. Right now, we recommend that all `HomeControllers` and the like should be protected by the `RequireKnownShop` concern:

https://github.com/Shopify/shopify_app/blob/974f294a12789b8bb24ddc0e2476e9b7ef7ecdb8/app/controllers/concerns/shopify_app/require_known_shop.rb#L7-L10

This concern sends the user to the installation/login flow by checking two things:

1. Whether a `?shop=foo` parameter was passed in to the request
2. Whether that `shop` parameter corresponds to a known database entry for this shop

If your solution means that you cannot remove your db record, then your `HomeController` is going to need to do another action after this concern:

```rb
class HomeController < ApplicationController
  include ShopifyApp::EmbeddedApp
  include ShopifyApp::RequireKnownShop
  include ShopifyApp::ShopAccessScopesVerification

  before_action :check_shop_installed

  def index
    @shop_origin = current_shopify_domain
  end
  
  private
  
  def check_shop_installed
    shop = Shop.find_by(shopify_domain: current_shopify_domain)
    
    # If you determine that this shop is marked as "uninstalled", then send the user to the login page to start the installation flow
  end
end
```

**Comment by robbyklein** [comment]
Thanks @NabeelAhsen, I'll give this a try.

**Comment by nelsonwittwer** [comment]
Closing as it seems the issue was resolved.
