### ISSUE TITLE
PLEASE HELP - 3500+ stores effected

### ISSUE THREAD

**Issue by robbyklein** [Shopify/shopify_app#1240]
My apps been running for 2 years. I haven't made changes to it in weeks. I wake up today and it's no longer working an an embedded app, breaking the product selector windows used in the app and breaking it for 3500+ stores. No warning about breaking changes or anything from Shopify. Here's the error:

AppBridgeError {name: "AppBridgeError", message: "APP::ERROR::INVALID_CONFIG: host must be provided", action: undefined, type: "APP::ERROR::INVALID_CONFIG", stack: "AppBridgeError: APP::ERROR::INVALID_CONFIG: host must be provided"}

How do I fix this?

**Comment by NabeelAhsen** [comment]
Hey @robbyklein, we've had multiple reports of this following the latest App Bridge 2.0 release today.

**To immediately put out the fire:** 

Where ever you're using the CDN to load App Bridge, make sure to lock it to `@1`:

```diff
- <script src="https://unpkg.com/@shopify/app-bridge"></script>
+ <script src="https://unpkg.com/@shopify/app-bridge@1"></script>
```

The CDN unfortunately pulls in the latest, and so it most likely pulled in App Bridge 2.0.

Right now, the only place this is being imported in the shopify_app gem is here:

https://github.com/Shopify/shopify_app/blob/2c608f06cb2e74840613aa3b6da935038bf19463/lib/generators/shopify_app/install/templates/embedded_app.html.erb#L27

This behaviour has been updated in patch release `v17.2.1` released today of the shopify_app gem, but it does not fix anything for existing apps.

Also check to make sure that you NPM did not automatically update any of its App Bridge dependencies to App Bridge 2.0.

2. For a more permanent fix, you can find a guide to migrating to App Bridge 2.0 here: https://shopify.dev/tutorials/migrate-your-app-to-app-bridge-2

**Comment by robbyklein** [comment]
Thank you for the quick reply, that fixed it.

This was really not a cool change... I launched a new app yesterday and emailed 27000 people a broken install link because 
SessionToken.ActionType.RESPOND changed to SessionToken.Action.RESPOND .

I get you guys are trying to switch to session authentication (seems like a nightmare to do) but damn this really caused a ton of stress for me today and pissed off a ton of my customers.

**Comment by NabeelAhsen** [comment]
I understand the frustration!

> This was really not a cool change... I launched a new app yesterday and emailed 27000 people a broken install link because SessionToken.ActionType.RESPOND changed to SessionToken.Action.RESPOND .

`ActionType` -> `Action`

This change is definitely part of App Bridge 2.0, and so I believe the fix above will also help alleviate this as well. We've escalated this where possible to ensure app behaviour returns to normal for most partners.
