### ISSUE TITLE
Added a new webhook after app install, isn't registering

### ISSUE THREAD

**Issue by skillmatic-co** [Shopify/shopify_app#1242]
Hello, adding webhooks before app installation seems to work.

What is the process for adding a webhook after app installation? The app doesn't seem to be picking up my newly added webhook.

I know there is `config.reauth_on_access_scope_changes` for scope changes after app installation. Is there something like this for webhooks added after app installation?

**Comment by awd** [comment]
The gem will rerun the webhooks manager when the merchant flows through the `ShopifyApp::CallbackController`. 

However, if you needed all your shops to have an updated webhook, you can requeue the background job for all installed shops.

`ShopifyApp::WebhooksManagerJob.perform_now(shop_domain: shop.shopify_domain, shop_token: shop.shopify_token, webhooks: ShopifyApp.configuration.webhooks)`

Also the webhook manager itself has a `recreate_webhooks!` which you could call as well, to wipe all current hooks and re-adding them nice and fresh.

Start here: https://github.com/Shopify/shopify_app/blob/master/app/controllers/shopify_app/callback_controller.rb#L17 and follow it through for webhooks to see all the codified bits.

**Comment by nelsonwittwer** [comment]
After merging in #1492 and #1495 - I have not been able to reproduce this issue. If not, let us know and we will take another look!
