### ISSUE TITLE
Documentation for testing with JWT is missing

### ISSUE THREAD

**Issue by jagthedrummer** [Shopify/shopify_app#1249]
### Description

After updating my app to use JWT I'm able to get things working when I test manually, but my rspec and cucumber tests are broken. I'm not finding any documentation that points me in the right direction. If someone could give me some clues I could write some docs.

### Steps to Reproduce

Previously I could set a `:shop_id` in the `session` and then the `shopify_app` gem would act like it had a valid session for that shop.

Old way:
```ruby
@shop = create(:shop)
session[:shop_id] = @shop.id
get '/protected_path'
expect(response).to be_successful
```

After updating to JWT the response to `get '/protected_path'` is a redirect to `/login`.

### Browsers

N/A

### Gem versions

17.2.1

### Additional Information

N/A

### Security

- [x] I have redacted any private information from my logs or code snippets.

**Comment by itsniper** [comment]
I have not set this up yet myself, but I think you need to use Omniauth's test mode and mock?
https://philstories.medium.com/omniauth-integration-testing-with-rails-6-shopify-app-9e4a77084827

Might also be some clues in Shopify's own tests
https://github.com/Shopify/shopify_app/blob/master/test/controllers/callback_controller_test.rb

**Comment by jagthedrummer** [comment]
Not stale. Still not documented.
