### ISSUE TITLE
Handling Admin Links with JWT

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1250]
Using the latest V 17 Shopify App and thinking about how to handle Admin Links. In the Extensions of the App, we add an endpoint, to accept links from the Shopify Admin. So the controller to accept these calls has to be Authenticated. But Shopify is not sending a JWT token in the header. So that means any incoming request for Admin Links has to go through the oAuth Flow? 

I am seeing my hits to the admin links controller which is descended from AuthenticatedController just dying... on redirects to /login... not sure why that is, but is this all the right thinking? 

So the combo that works is anti-thetical to this JWT pattern.. but, it is what it is, right? 

    config.allow_jwt_authentication = true
    config.allow_cookie_authentication = true

**Comment by resistorsoftware** [comment]
I don't control the admin link. What do you mean send it to an un-authenticated endpoint? 

Shopify is sending data to an endpoint in an App. For the sake of this discussion, and embedded App. There is currently no way to ensure this is coming from Shopify if I am relying on JWT, as Shopify is not providing a token, and it is not structured like a webhook or app proxy call, with HMAC token in the header. 

So what are we supposed to do with these Admin Links?

**Comment by PixApplications** [comment]
Hey @resistorsoftware ,

If you are using the React components, I believe the bug actually exists in the @shopify/app-bridge-react Provider component.

As a workaround, we are manually generating the JWT for admin links using @shopify/app-bridge functions.

```
import createApp from "@shopify/app-bridge";
import { getSessionToken } from "@shopify/app-bridge-utils";
```

```
const app = createApp({
  apiKey: this.props.apiKey,
  shopOrigin: this.props.myshopifyUrl,
  host: Buffer.from(process.env.HOST_URL).toString("base64"),
  forceRedirect: true,
});

if (app){

  const sessionTok = getSessionToken(app);

  sessionTok
  .then((token) => {

   // Make authenticated calls here

  })
  .catch((error) => {
    console.log('Something wrong happens', error);
  });

}
```

**Comment by resistorsoftware** [comment]
@PixApplications so this is not part of the Shopify App. Which is my whole point about this. There is zero support for Admin Links as far as I can tell, although as you point out, the recipe to handle them is not terrible. But I find it bizarre that this is entirely skipped in this repo as if they are not a thing to worry about. It is like they don't think anyone will ever use Admin Links... so they don't bother showing off how to use them. Weird. Am I missing something?
