### ISSUE TITLE
Auth callback escaping the iframe with JWT

### ISSUE THREAD

**Issue by jagthedrummer** [Shopify/shopify_app#1251]
### Description

I'm working on updating my app for JWT and things are looking good for previously installed shops, but with newly isntalled shops the installation sequence is escaping the iframe after I confirm installation and I'm landing at my splash page and get stuck.

### Steps to Reproduce

1. Go to https://my-apps.public-url.com/login
2. Enter shop name
3. Click "Install app"
4. Land at the app Shopify installation page (inside the iframe)
5. Click "Install unlisted app"
6. Eventually get redirected to https://my-apps.public-url.com/auth/shopify/callback (outside the iframe)
7. That action redirects to https://my-apps.public-url.com/ (also outside the iframe)
8. 💥

**Expected behavior:**

After clicking "Install unlisted app" I would expect to hit the `/auth/shopify/callback` endpoint indide the iframe OR have that action redirect in a way that puts the root path of my app back inside the iframe.

**Actual behavior:**

After clicking "Install unlisted app" I end up at my splash page outside of the iframe and can't proceed.

**Reproduces how often:**

100%

### Browsers

Firefox
Safari

### Gem versions

17.2.1

### Additional Information

I followed this page for converting my app to JWT: https://shopify.dev/tutorials/authenticate-server-side-rendered-embedded-apps-using-rails-and-turbolinks

I have `config.allow_jwt_authentication` set to `true` and I've tried `config.allow_cookie_authentication` with both `true` and `false` and neither one seems to make any difference.

Seems similar to #1132 but my problem is happening during the auth callback phase instead of after creating a recurring application charge.

### Security

- [x] I have redacted any private information from my logs or code snippets.

**Comment by resistorsoftware** [comment]
I think if App Bridge is being used, and instantiated correctly, and it detects the environment as production, it takes care of redirecting to the iframe, but otherwise, you have to redirect yourself. I have been burned by this lots too, so my hack was just to detect if outside the iframe, and then redirect to the App... making up for App Bridge missing this. YMMV

**Comment by defkode** [comment]
try `forceRedirect: true` option
