### ISSUE TITLE
Reauth on Access Scope Changes is not working for Non-embedded apps

### ISSUE THREAD

**Issue by wnm** [Shopify/shopify_app#1257]
### Description

The combination of `config.reauth_on_access_scope_changes = true` and `config.embedded_app = false` doesn't seem to work.

As soon as `ShopifyApp::ShopAccessScopesVerification` is included in a controller, it keeps redirecting to login.

### Steps to Reproduce
See commit history and code here: https://github.com/wnm/reauth-test-app

rails new reauth-test-app
bundle add shopify_app
rails generate shopify_app --embedded false
rails db:migrate

The root url `/` (which is routing to home controller, is already not working at this point)
When I add `include ShopifyApp::ShopAccessScopesVerification` to the products controller it stops working there too.

**Expected behavior:**

We should be able to use the app on a store, after installing it.

**Actual behavior:**

It keeps redirecting to /login page.

**Reproduces how often:**

100%

### Browsers

Chrome, Firefox, Safari

### Gem versions

17.2.1

### Additional Information

My app is intended to be a non-embedded app

These are the authentication settings:

config.allow_jwt_authentication = false
config.allow_cookie_authentication = true

**Comment by wnm** [comment]
This [ShopifyApp::RequireKnownShop concern](https://github.com/Shopify/shopify_app/blob/f4fd2e13df0478cf7d6cf467afb93b8d63bafd87/app/controllers/concerns/shopify_app/require_known_shop.rb#L13) is also relying on params[:shop], so it probably doesn't work for non-embedded shops...

**Comment by khier996** [comment]
@wnm have you figured out a solution for this?

**Comment by ludoder-git** [comment]
Is this still an issue?

**Comment by wnm** [comment]
yes, this is still an issue, [the code](https://github.com/Shopify/shopify_app/blob/b0d29de4a30b60701c00b2b183cfb20e651e82ed/app/controllers/concerns/shopify_app/shop_access_scopes_verification.rb#L25) hasn't changed. @khier996 I have not found a work around...

**Comment by fluke** [comment]
@wnm I was able to resolve this. `ShopAccessScopesVerification` overrides the `current_shopify_domain` method in `Authenticated`. So I found that including `ShopAccessScopesVerification` before `Authenticated` makes it so that it works. Though this should be handled better in this gem.

```
include ShopifyApp::ShopAccessScopesVerification
include ShopifyApp::Authenticated
```

**Comment by netwire88** [comment]
@fluke Thanks for the suggestion, but I tried it and it doesn't work whether `include ShopifyApp::ShopAccessScopesVerification` is in `AuthenticatedController` or `SplashPageController`. It creates redirect loops continuously.

**Comment by sshaw** [comment]
> IS NULL. Not sure why Im getting that. Maybe it's the issue so this never matches.

It's from https://github.com/Shopify/shopify_app/issues/1257#issuecomment-826826857. @fluke's [comment](https://github.com/Shopify/shopify_app/issues/1257#issuecomment-956183868) seems to have fixed it....

**Comment by sshaw** [comment]
> It's from #1257 (comment). @fluke's comment seems to have fixed it....

@netwire88 what version are you using?

**Comment by netwire88** [comment]
@sshaw We are using 18.0.3.

**Comment by sshaw** [comment]
> @sshaw We are using 18.0.3.

@netwire88 me too. Maybe you're using an embedded app? I ditched this a long time ago 🤯

**Comment by sshaw** [comment]
@netwire88 

> we actually tried to pivot away from the embedded app (quite buggy), but we couldn't figure out how to do that, even with embedded_app = false.

I have several non-embedded apps that are using a pared down version of v9 with some customizations without any issues. Figured I'd give v18 (😳) a whirl and see what I've been missing. Well...

Nevertheless the current non-embedded v18 app has the following `shopify_app.rb` initializer:

```rb
ShopifyApp.configure do |config|
  config.application_name = "Foo"
  config.old_secret = ""
  config.scope = "whatever"
  config.embedded_app = false
  config.after_authenticate_job = false
  config.api_version = "2021-10"
  config.shop_session_repository = 'Shop'

  config.reauth_on_access_scope_changes = true

  config.allow_jwt_authentication = false
  config.allow_cookie_authentication = true # false for embedded_app

  config.api_key = ENV.fetch('SHOPIFY_API_KEY', '').presence
  config.secret = ENV.fetch('SHOPIFY_API_SECRET', '').presence
  if defined? Rails::Server
    raise('Missing SHOPIFY_API_KEY. See https://github.com/Shopify/shopify_app#requirements') unless config.api_key
    raise('Missing SHOPIFY_API_SECRET. See https://github.com/Shopify/shopify_app#requirements') unless config.secret
  end
end

ShopifyAPI::Base.logger = Rails.logger if Rails.env.development?
```

`AuthenticatedController`: 

```rb
class AuthenticatedController < ApplicationController
  include ShopifyApp::ShopAccessScopesVerification
  include ShopifyApp::Authenticated

  # snip amaaaaaazing code
end
```

And `Shop`:

```rb
class Shop < ApplicationRecord
  include ShopifyApp::ShopSessionStorageWithScopes
  # snip more amaaaaaaaazing code
end
```

Hope that helps!
