### ISSUE TITLE
Support for Ruby on Rails 6.1.1

### ISSUE THREAD

**Issue by marisveide** [Shopify/shopify_app#1262]
### Summary

Please, update the `shopify_app` gem to support the Ruby on Rails version 6.1.1.

### Motivation

We are using the Ruby on Rails 6.1.1 for certain features that come only in this version.
However, the `shopify_app` gem readme says that it does not support the Ruby on Rails version `6.1`.
It would be very good if we could use the newest version of `shopify_app` gem with all its improvements.

Thanks so much!

**Comment by marisveide** [comment]
Ahaa, thanks so much, @itsniper ! 👍

**Comment by awd** [comment]
@marisveide - close this as it's resolved?
