### ISSUE TITLE
Race condition with redirect.js

### ISSUE THREAD

**Issue by jesalerno84** [Shopify/shopify_app#1269]
### Description

When running an app with the `shopify_app` gem installed using `rails s` a race condition sometimes occurs between asset requests and the request to `/auth/shopify`.  This seems to be because the entire session is being stored inside a cookie with the default dev setup.

### Steps to Reproduce

**Expected behavior:**

The oauth flow should work as normal.

**Actual behavior:**

The oauth flow fails with a 401.

**Reproduces how often:**

This seems to happen intermittently.

### Browsers

Chrome.

### Gem versions

18.0.1.

### Security

- [x] I have redacted any private information from my logs or code snippets.

**Comment by awd** [comment]
@hannahchen @paulomarg - this issue is linked here: https://github.com/Shopify/shopify_app/blob/main/docs/Troubleshooting.md#my-app-wont-install

Maybe it's time for it to be removed as this issue is stale af.
