### ISSUE TITLE
Redirect When returning to app from Store

### ISSUE THREAD

**Issue by asecondwill** [Shopify/shopify_app#1281]
Running on my dev environment, via ngrok, I get a redirection loop when trying to return to the app a few days after installation as a test store.  My App is not embedded.

I click into the store, apps and click to open the app.  It gets into a redirection loop. 

/shopify/login
/auth/shopify
/shopify/dash
/shopify/login?return_to=%2Fshopify%2Fdash
/auth/shopify
/shopify/dash

etc.

I have my Shopify_App engine added like this
Routes:
`mount ShopifyApp::Engine, at: '/shopify'`

Shopify_app.rb initializer:

```
ShopifyApp.configure do |config|
  config.application_name = "PucttoShopifyApp"
  config.api_key = ENV['SHOPIFY_API_KEY']
  config.secret = ENV['SHOPIFY_API_SECRET']
  config.old_secret = ""
  config.scope = "read_products, write_themes, read_themes" # Consult this page for more scope options:
                                 # https://help.shopify.com/en/api/getting-started/authentication/oauth/scopes
  config.embedded_app = false 
  config.after_authenticate_job = false
  config.api_version = "2020-10"
  config.shop_session_repository = 'Shop'
  config.allow_jwt_authentication = true
  config.allow_cookie_authentication = false
  config.root_url = '/shopify'
  # config.after_authenticate_job = { job: "Shopify::AfterAuthenticateJob", inline: true }
end
```
And then the app runs in namespace shopify

```
module Shopify
  class ApplicationController < AuthenticatedController
  end
end

class AuthenticatedController < ApplicationController   
  include ShopifyApp::Authenticated
end
```
With my shop model 

```
class Shop < ActiveRecord::Base
  include ShopifyApp::ShopSessionStorage

  def api_version
    ShopifyApp.configuration.api_version
  end
end
```

Omni Auth.rb
```
Rails.application.config.middleware.use(OmniAuth::Builder) do
# frozen_string_literal: true
# TODO: needed?
provider :shopify,
  ShopifyApp.configuration.api_key,
  ShopifyApp.configuration.secret,
  scope: ShopifyApp.configuration.scope,
  callback_path: '/shopify/auth/shopify/callback',
  setup: lambda { |env|
    strategy = env['omniauth.strategy']

    shopify_auth_params = strategy.session['shopify.omniauth_params']&.with_indifferent_access
    shop = if shopify_auth_params.present?
      "https://#{shopify_auth_params[:shop]}"
    else
      ''
    end

    strategy.options[:client_options][:site] = shop
    strategy.options[:old_client_secret] = ShopifyApp.configuration.old_secret
    strategy.options[:per_user_permissions] = strategy.session[:user_tokens]
  }
end
```

In my App Setup, I have 
Allowed redirection URL(s)
https://xxxx.ngrok.io/shopify/auth/shopify/callback

App URL
https://xxxx.ngrok.io/shopify/dash

Rails rails (6.1.3) shopify_app (18.0.1) Ruby 2.7.2

This is a major blocker in finishing the app.   Looking at the Issues list, there are similar errors linked to User sessions.  Not sure if this is different or not.  

https://github.com/Shopify/shopify_app/issues/1246

**Comment by asecondwill** [comment]
And, just to add to my woe.  It redirects when trying to install the app on test stores now. Was fine on Tuesday.  The only thing I think I've changed is updating to shopufy_app 18.0.1 from shopify_app (17.2.1)

**Comment by asecondwill** [comment]
https://github.com/asecondwill/shopifydemo3

I've set up a demo here so the shopify developers can hopefully recreate and fix the problem (or point out what i'm doing wrong).

**Comment by asecondwill** [comment]
That demo has branches for different configurations trying to get it to work, nested, not nested, embedded, not.  Nothing works.

**Comment by kyleboss** [comment]
Hello, I'd like to chime in and mention that I am running into the same issue.

Version 18.0.1 (Although the issue persists in 17* as well).
Embedded app
Sessions stored as JWT.

The issue appears to occur only when the app is an embedded app using JWT sessions.

This is a big issue because Shopify required embedded apps to use JWT.

**Comment by asecondwill** [comment]
Hi @kyleboss 

I couldnt make not-embedded app authentication work.   

I followed this demo
https://github.com/Shopify/turbolinks-jwt-sample-app

And then adapted it to my use case.  Which for the most part worked.  A lot of redirecting happens, but i think that is expected.  Fingers crossed the App review passes.

**Comment by DamonClark** [comment]
Experiencing same issue here 

Rails 6
Shopify App 17.1.1
embedded app

**Comment by jvsidler** [comment]
@asecondwill were you able to make progress on the infinite redirect when using turbolinks? I see you were tracking this in multiple places but I have not been able to crack this.

**Comment by jvsidler** [comment]
I was able to get this to work after finding [this community post](https://community.shopify.com/c/Shopify-APIs-SDKs/App-frame-refusing-to-load-on-reloading-for-4-times/m-p/594434/highlight/true#M40118).

The way I got it to work:

1. Follow [this tutorial](https://shopify.dev/apps/auth/session-tokens/server-side-rendered-apps) 
2. Ensure your embedded app and redirect urls include 'host' since that tutorial needs to be updated for AppBridge 2.0.
3. Add a named route pointing to splash_page#index (I used /welcome)
4. Add a 'return_to' key to the session in the splash_page controller in the index action
