### ISSUE TITLE
Rails Engine Routes

### ISSUE THREAD

**Issue by kevinhughes27** [Shopify/shopify_app#129]
Currently the default routes as part of the engine are drawn on the engine itself. This means they have to be mounted in order to become part of the hose app. They are also behind a config var called `routes` on ShopifyApp configuration.

The routes should actually be drawn on Rails.application and then the `routes` config will be the only thing controlling the routes in the host app. This is cleaner and makes the engine more transparent (some engines make sense to be mounted some make more sense to be more seamless and use config). This change will also help make the tests cleaner.

btw @stephenminded this answers the engine mounting confusion we had when upgrading everyone. I want to wait until the next version after the security bump to fix this since this adds an extra layer of safety before this app will add routes.

**Comment by yinwai92** [comment]
Hi @kevinhughes27 , thank you for the project. I am new to ruby and shopify, I start using your api few days ago. However, after running install generator and rails server, I found "undefined method `login_path' for #<HomeController:0x007f8591b0f1f8>". Is this have to do with the issue you mentioned above? 

Appreciate if you can explain a little for me. Thank you very much!
