### ISSUE TITLE
Google Pub/Sub

### ISSUE THREAD

**Issue by netwire88** [Shopify/shopify_app#1297]
Per Shopify article on [Google Pub/Sub](https://shopify.dev/apps/webhooks/google-cloud), you can setup `pubSubWebhookSubscriptionCreate` to subscribe to webhooks. However, since this gem provides `WebhooksManager`, does it (shopify_app version 18.0.2) support Google Pub/Sub, are there plans to support it, or do we need to implement Google Pub/Sub on our own?

**Comment by nelsonwittwer** [comment]
no plans to generate these subscriptions in this gem for now, I'm afraid
