### ISSUE TITLE
Authentication Redirects

### ISSUE THREAD

**Issue by humansounds** [Shopify/shopify_app#130]
After removing the app from my dev shop and resetting my local database, i always get redirected back to my dev shop instead of the `sessions#new` page.  Therefore, I cannot reinstall the app.  Please advise?

**Comment by ckhatton** [comment]
Ooo.. a fellow Hatton :smiley:

I am thinking off the top of my head here... I don't suppose this is a build that you have updated past v5.0.0? Did you seed the database after resetting it? Are you sure it isn't a cookie that is doing this?

**Comment by humansounds** [comment]
I cleared the browser cache and cookies, tried in FF, Chrome, and Safari.  All reproduce the same issue.  I'm running `6.0.4` on a fresh rails build using the generators.

**Comment by ckhatton** [comment]
Okay, a bit weird. It was working before resetting the database right? Is the login path set correctly in your Shopify partners app page?

**Comment by humansounds** [comment]
it was working fine before because i had already installed the app in my shop.  once i removed it from the shop and cleared the database, i can no longer access that default `sessions#new` page.  it redirects straight to shop authentication: `https://www.shopify.com/login`, and then into the shop, where it can no longer find the app.

**Comment by humansounds** [comment]
I guess I should consider bumping back to `5.0.2` stable...

**Comment by ckhatton** [comment]
Yeh maybe...

@kevinhughes27 and @stephenminded I seem to remember you guys mentioning some caveat about the session store? Is this related to InMemorySessionStore? Cheers

**Comment by kevinhughes27** [comment]
InMemorySessionStore works fine locally its just on heroku and production that it doesn't work. 

Did you update your code when bumping to 6.0.4? Have a look at this PR to see what I did to the example app which I tested successfully. 

https://github.com/Shopify/embedded-app-example/pull/27

**Comment by humansounds** [comment]
i didn't have any code to update.  i built the app with the generators in `6.0.4`.

**Comment by kevinhughes27** [comment]
Okay - which generators did you run?

**Comment by humansounds** [comment]
`rails generate shopify_app` - the default behemoth.

**Comment by kevinhughes27** [comment]
hmm okay let me try this out on my machine and see whats up.

**Comment by humansounds** [comment]
everything ran perfectly, and installed to my dev shop great.  i dropped the database with a standard `rake db:migrate:reset` and removed the app from my shop.  now when i hit the development URL (puma, pow, using a procfile for logging) it redirects me straight to my dev shop.  not even sure how it's remembering that.  cache is cleared, database is clean, etc.

**Comment by kevinhughes27** [comment]
Can you explain your steps exactly? 
What Rails version? 
Did you add your api credentials to the initialize? 
They are oauth credentials from your partners page right? 
Is your callback url correct?

I just created a new rails app locally and ran the main generator, entered my keys it worked fine for me. I removed the app, cleared my db and it all worked fine.

**Comment by humansounds** [comment]
* Ruby 2.2.0
* Rails 4.2.0
* Key and Secret are properly set in env variables
* Callback URL is just the root domain `http://appname.dev` (using pow)

I used the generator to scaffold up the shopify_app stuff, adding some config stuff here and there, added some other code, etc.  Never had any issues running in my dev shop.  I reset the database and removed the app from my shop.  Now when i visit the root domain `http://appname.dev` i am automatically redirected into my dev shop.  No idea how it even knows that it exists.  I should be routed to the `sessions#new` view to input my shop url to install.

**Comment by kevinhughes27** [comment]
and the ShopifyApp.rb initializer reads your ENV vars? I read earlier that you cleared cookies - are you sure the cookies are gone for your domain? Check again because that's all I can think of.

**Comment by humansounds** [comment]
Yep, they're gone.  I'll keep digging.  Not sure what is wrong here.

**Comment by humansounds** [comment]
Oddly enough, I keep getting redirected here: `https://shop-name.myshopify.com/admin/auth/login`, although my log is actually hitting the right controller.  Really bizarre.

**Comment by kevinhughes27** [comment]
I would try running without pow and just use bundle exec rails server (copying in your creds for now)

**Comment by humansounds** [comment]
Started over completely.  Same issue after uninstall.

**Comment by humansounds** [comment]
UGH.  Finally found it.  I had the sdk initialization script in my `application.html.erb` layout. :tired_face: 

``` javascript
ShopifyApp.init({
  apiKey: "<%= ShopifyApp.configuration.api_key %>",
  shopOrigin: '<%= "https://#{ @shop_session.url }" if @shop_session %>'
});
```

Apparently this redirects to log you in instantly, without any console output.  Wowee that was a doozy.

**Comment by kevinhughes27** [comment]
glad you got it sorted out!

**Comment by marko-ivan** [comment]
@fulstop sorry I know this issue was closed but I have similar issue.

I have developed Shopify App using shopify_app gem.
I have installed my app on 2 stores.
For example,
One store's domain: **store-test.myshopify.com**
Other store's domain: **store.myshopify.com**

First, I have installed on **store.myshopify.com** and then I have installed on **store-test.myshopify.com**

But when I retrieve the Shopify domain from **session[:shopify_domain]**, I always get **store-test.myshopify.com**

**Comment by marko-ivan** [comment]
I have fixed this issue.

The issue was that HomeController is inherited from ApplicationController, not
ShopifyApp::AuthenticatedController
