### ISSUE TITLE
How to get Host

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1315]
With Shopify App Bridge 2 I need the host. 

How do I get the host from App 18.0.2?

I need it rendered in the embedded App layout so that the JS can use it to start off a Provider. What is the sauce to get it?

I made a before_action in Authenticated controller that grabs the host param and sets it to @host. Is that it?

**Comment by dan-gamble** [comment]
There's a good example here: https://github.com/kirillplatonov/shopify_app/blob/master/app/controllers/concerns/shopify_app/shop_host.rb

Worth noting @kirillplatonov's fork has a bunch of nice updates to it since this has stagnated slightly recently

**Comment by resistorsoftware** [comment]
Ok.. same thing then. I get it. Moving on then! 

But I am curious, what do you mean when you say this has stagnated lately? You mean Shopify and their contributions?

**Comment by dan-gamble** [comment]
A tad, yea.

[No meaningful change for ~4 months](https://github.com/kirillplatonov/shopify_app/blob/master/app/controllers/concerns/shopify_app/shop_host.rb)

And there is a couple of outstanding PR issues:
- https://github.com/Shopify/shopify_app/pull/1279
- https://github.com/Shopify/shopify_app/pull/1277#issuecomment-884092578
- https://github.com/Shopify/shopify_app/pull/1169

**Comment by resistorsoftware** [comment]
I do know that one of the prime drivers of this project quit in disgust, and perhaps that is the legacy we are left with. I myself cannot believe how awful this whole move into JWT and React has been, but no one has yet stepped up to the plate with a superior system, of which I am sure there are more than a few. It is too bad. Some people do rely on this project being in good shape and not busted for months over little bugs.

**Comment by kirillplatonov** [comment]
I think we can stay in the fork for now. As for JWT and React - those are hard challenges. 
But we have Hotwire Turbo + JWT integration now: https://github.com/kirillplatonov/shopify-hotwire-sample
And as an answer for React path, we have Polaris ViewComponents: https://github.com/baoagency/polaris_view_components

So things are not so bad. The current Rails + Hotwire + Polaris ViewComponents stack is very solid and probably will survive the current generation of Shopify React stack 😉

**Comment by resistorsoftware** [comment]
Thanks @kirillplatonov for this valuable contribution. Much appreciated.
