### ISSUE TITLE
Login/Install Page needs `unsafe-inline` styles to be allowed by CSP in order to render correctly

### ISSUE THREAD

**Issue by n33l4y** [Shopify/shopify_app#1321]
### Description
The login/install page seems to use `inline styles` and as such does not render as expected when a Content Security Policy that does not allow  `inline styles` is applied. The screenshots below show the login/install page in action without CSP and with a CSP that disallows `inline styles`

Note that even though the login/install page does not render as expected (when a CSP that disallows `inline styles` is applied), the `Install app` button functionality works perfectly fine when invoked.

**Login/Install Page (without any CSP)** - Renders as expected
><img width="670" alt="without_csp-app_install_page" src="https://user-images.githubusercontent.com/86799639/136108883-65284550-729a-4c5b-8f9a-e8ca435bae07.png">

**Login/Install Page (with a CSP that disallows inline styles)** - Does not render as expected
><img width="646" alt="with_csp-app_install_page" src="https://user-images.githubusercontent.com/86799639/136111427-40887470-67ab-43e6-bc9e-85894c599b52.png">

Is there a way I can configure/initialize `shopify_app` so that the styles it uses are external (instead of inline) or any other workaround that I can use in my app so that I don't have to relax the content security policy (to allow `inline styles`) just to ensure that the app login/install page renders correctly?

### Steps to Reproduce

1. I have created a sample app at [ns-sample-app](https://github.com/Shopify/ns-sample-app)
2. Cloning and running the sample app should reproduce the issue

**Expected behavior:**

The Login/Install page renders as expected even when a CSP that disallows `inline styles` is applied. See above screenshots for reference

**Actual behavior:**

The Login/Install page does not render as expected when a CSP that disallows `inline styles` is applied. See above screenshots for reference

**Reproduces how often:**

Every time

### Browsers

Tested (and observed) with Firefox but should also happen with other browsers

### Gem versions

`shopify_app 18.0.2`

### Security

- [x] I have redacted any private information from my logs or code snippets.

**Comment by nelsonwittwer** [comment]
#1474  should address the concerns pointed out here, so we are going to close this issue.

If you still encounter this issue with the latest stable version, please reopen using the issue template. You can also contribute directly by submitting a pull request– see the CONTRIBUTING.md(.github/CONTRIBUTING.md) file for guidelines

**Comment by nickpith** [comment]
Reopening because I'm still hoping to find some time to make a change for this.
