### ISSUE TITLE
Error using Rails 7: ShopifySessionRepository.shop_storage is not configured

### ISSUE THREAD

**Issue by Soleone** [Shopify/shopify_app#1322]
### Description

I created a new Rails app using `shopify-rails` which now uses `rails 7.0.0.alpha2`.

When I try `bundle generate shopify_app` or any other command after this I always receive the following error:

`ShopifySessionRepository.shop_storage is not configured! (ShopifyApp::SessionRepository::ConfigurationError)`

### Steps to Reproduce

1. Create new rails app using `shopify-rails`, confirm it uses `rails 7.0.0.alpha2`
2. `bundle add shopify_app`
3. `bundle generate shopify_app`

**Expected behavior:**

Generator should complete successfully.

**Actual behavior:**

Generator aborts at this step `rails  generate shopify_app:authenticated_controller` with the following error:

```
/Users/me/.gem/ruby/3.0.2/gems/shopify_app-13.0.0/lib/shopify_app/session/session_repository.rb:39:in `shop_storage': ShopifySessionRepository.shop_storage is not configured! (ShopifyApp::SessionRepository::ConfigurationError)
  from /Users/me/.gem/ruby/3.0.2/gems/shopify_app-13.0.0/lib/shopify_app/session/session_repository.rb:9:in `shop_storage='
  from /Users/me/.gem/ruby/3.0.2/gems/shopify_app-13.0.0/lib/shopify_app/configuration.rb:60:in `shop_session_repository='
  from /Users/me/workspace/shopify/my-new-app/config/initializers/shopify_app.rb:11:in `block in <main>'
  from /Users/me/.gem/ruby/3.0.2/gems/shopify_app-13.0.0/lib/shopify_app/configuration.rb:85:in `configure'
  from /Users/me/workspace/shopify/my-new-app/config/initializers/shopify_app.rb:1:in `<main>'
```

**Reproduces how often:**

100%

### Browsers

N/A

### Gem versions

shopify_app (13.0.0)
rails (7.0.0.alpha2)

### Additional Information

1. I have to uncomment this line in `config/initializers/shopify_app.rb` to avoid the error, but of course I still need this line: `config.shop_session_repository = "Shop"`
2. When I downgrade to Rails 6 it works, no error.
3. Two other stackoverflow issues I found with this error, but I don't think they are related to using Rails 7: [first](https://stackoverflow.com/questions/62808214/rails-activestorage-not-working-with-shopify-app-gem), [second](https://stackoverflow.com/questions/67005167/shopifysessionrepository-shop-storage-is-not-configured)

### Security

- [x] I have redacted any private information from my logs or code snippets.

**Comment by karimmtarek** [comment]
As far as I know this gem only works for Rails `< 6.2`, so you might wanna stick with that for now, or you may fork it and start hacking it to get it working.

**Comment by gonzaloriestra** [comment]
Rails 7 is supported since [v18.1.0](https://github.com/Shopify/shopify_app/pull/1357). Please let us know if you find any issue.

**Comment by resistorsoftware** [comment]
This issue is still an issue and just happened on a V20 App. Thanks Shopify!
