### ISSUE TITLE
access_scopes= must be defined to hook into stored access scopes

### ISSUE THREAD

**Issue by pinoytech** [Shopify/shopify_app#1324]
### Description

I am currently upgrading an existing rails app from using the gem, shopify_app 17.1.0 to shopify_app 18.0.2. But when I deploy it, on shops that already have the app installed, there one issue I seem to be having.

```
access_scopes= must be defined to hook into stored access scopes
```

The error can be traced here: https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/session/shop_session_storage_with_scopes.rb#L55

The 17.1.0 version seems to have the same line: https://github.com/Shopify/shopify_app/blob/v17.1.0/lib/shopify_app/session/shop_session_storage_with_scopes.rb#L55

Is that a requirement in version 18.0.2 now?

### Steps to Reproduce

1. Upgraded Gemfile 17.1.0 to 18.0.2
2. Added a migration for `access_scopes` in the Shop model
3. HomeController extends ApplicationController
4. The following are added to my HomeController
   ```
    include ShopifyApp::EmbeddedApp
    include ShopifyApp::RequireKnownShop
    include ShopifyApp::ShopAccessScopesVerification
    include ShopifyApp::LoginProtection
   ```
5. Deploy

**Expected behavior:**

Shop would be authenticated and be logged in to the app

**Actual behavior:**

Shops that have the app installed fails on 

```
access_scopes= must be defined to hook into stored access scopes
```

**Reproduces how often:**

All the time on shops that previously installed the app.

### Browsers

Firefox and Chrome

### Gem versions

18.0.2

### Security

* [x] My app uses session tokens

**Comment by resistorsoftware** [comment]
I have this issue in Shopify App 18.1.1 running Rails 7 when my config for the App is set with  
    
    config.reauth_on_access_scope_changes = true
    
With that set to **true** then the App won't work and throws this:
    
    access_scopes= must be defined to hook into stored access scopes
    
So the Shop table has an access_scopes column, and every shop has the old scopes string written in it. 
What are we doing wrong in our App config to trigger this?
