### ISSUE TITLE
There's a problem loading this page

### ISSUE THREAD

**Issue by robbyklein** [Shopify/shopify_app#1326]
Hey guys, my apps been running for several years, and all of a sudden we started getting a bunch of emails about people, receiving this error:

![image](https://user-images.githubusercontent.com/6813372/139149550-abba1d19-f0bd-4434-bfbc-35e00d021f36.png)

It's happening upon redirect to the confirm recurring charge page. This is the code the app uses:
```
    charge =  ShopifyAPI::RecurringApplicationCharge.find(@shop.charge_id)
    status = charge.status

    if status == "pending"
      fullpage_redirect_to(charge.confirmation_url)
    end
```

Edit: Here's the error I see in the network tab:

```
{
  "errors": [
    {
      "message": "Internal error. Looks like something went wrong on our end.\nRequest ID: 6f7194d0-71e9-4c36-8913-9c6a5064a8b6 (include this in support requests).",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "requestId": "6f7194d0-71e9-4c36-8913-9c6a5064a8b6"
      }
    }
  ]
}
```

![image](https://user-images.githubusercontent.com/6813372/139191720-7867e849-9f84-4702-8cec-e35605a00651.png)

Thanks!

**Comment by lggg123** [comment]
Hey all, I am also getting a similar issue. The app is not loading. Is there any fix for this?
