### ISSUE TITLE
Link in documentation is broken.

### ISSUE THREAD

**Issue by acflint** [Shopify/shopify_app#1330]
### Description

Link in documentation is broken. The link at the bottom of https://github.com/Shopify/shopify_app/blob/master/docs/shopify_app/authentication.md#shopifyappensureauthenticatedlinks that says "See Authenticate server-side rendered embedded apps using Rails and Turbolinks for more information." leads to https://shopify.dev/apps/auth/session-tokens/server-side-rendered-apps, which is returning a 404.

_Edit: Upon further investigation, it seems like many links on https://shopify.dev/ are broken. For example: https://shopify.dev/apps/webhooks (which is linked to from the navigation menu on https://shopify.dev/). Is there a new developer resource website I should be using to access your documentation?_

### Steps to Reproduce

1. Go to https://github.com/Shopify/shopify_app/blob/master/docs/shopify_app/authentication.md#shopifyappensureauthenticatedlinks
2. Click on "Authenticate server-side rendered embedded apps using Rails and Turbolinks"
3. It will try to load https://shopify.dev/apps/auth/session-tokens/server-side-rendered-apps, which will return a 404 Not Found.

**Expected behavior:**

Link will load page.

**Actual behavior:**

Link returns 404 Not Found.

**Reproduces how often:**

100%

### Browsers
All

### Additional Information
Could you please provide an updated link for the "Authenticate server-side rendered embedded apps using Rails and Turbolinks" documentation? Thanks!

**Comment by emmahyde** [comment]
All of these links appear to be working now.

**Comment by acflint** [comment]
Confirmed! Looks good, thanks.
