### ISSUE TITLE
Infinite login redirect when installed in sub-directory / folder.

### ISSUE THREAD

**Issue by mrpunkin** [Shopify/shopify_app#1333]
We are running into issues with infinite loops that result in the following error when trying to run the app in a folder/directory instead of at the root of our domain:

> The app couldn’t be loaded
> 
> This app can’t load due to an issue with browser cookies. Try enabling cookies in your browser, switching to another browser (opens a new window), or contacting the developer to get support.

We are able to reproduce this with a fresh demo app as well. We are running JWT authentication and have cookie based auth disabled. Versions of software used:

- Ruby 3.0.2p107
- Rails 6.1.4.1
- shopify_app gem v18.0.2
- Apache 2.4.48
- Passenger 6.0.4

In our Apache config we have both `PassengerBaseURI` and `RackBaseURI` set to our folder, say `/our-app-name`. We also added this to `shopify_app.rb` initializer under the `config.root_url = '/our-app-name'` config option. 

The first issue we are presented with is that the redirect that happens due to the `post_redirect_to_auth_shopify.html.erb` file included in the engine forces a redirect to `/auth/shopify` without any awareness of Rails `relative_url_root` configuration option or the ShopifyApp engine's own `root_url` option I referenced above. So immediately our OAuth cycle gets removed from the directory our app lives in and breaks.

I tried fixing this by adding that file to my own app under `app/views/shopify_app/post_redirect_to_auth_shopify.html.erb` and prefixing it like so:

`<%= form_tag "#{main_app.root_path}auth/shopify", id: 'redirect-form' %>`

This allows it to continue the authentication cycle, but then the next issue we run into is the following error:

> Oauth error invalid_request: The redirect_uri is not whitelisted

This is because by prefixing the shopify auth path in the prior step, this doubles up the directory in the `redirect_uri` parameter, resulting in this: `redirect_uri=https%3A%2F%2Fdomain.com%2Four-app-name%2Four-app-name%2Fauth%2Fshopify%2Fcallback`

The final step I tried when running into this was the following configuration option in `omniauth.rb`: 

`callback_path: "/auth/shopify/callback"`

This allows the full authentication flow from what I can tell as it seems to strip the duplicate folder name from the callback_uri parameter. However this is what triggers the infinite loop that then leaves us with ultimately the same original error about allowing third party cookies.

Again, this all works fine if we change the settings in both our app and in the shopify app settings in Shopify's developer portal to not have our app nested in a folder. The issue seems to be only with once we nest our app within a folder/subdirectory.

**Comment by mrpunkin** [comment]
A bit more info. I turned on Omniauth logging and it appears that the "Callback phase" isn't being triggered at all despite a request coming in to the ShopifApp::CallbackController to be handled. It immediately redirects to the login URL, which is perhaps what is causing the loop?

**Comment by mrpunkin** [comment]
Further inspection led me to seeing that request.env['omniauth.auth'] was blank when using a custom :callback_path option in omniauth.rb. I finally got it working by using a custom [:client_options][:redirect_uri] setting on the strategy in omniauth.rb. Example below:

```omniauth.rb
# frozen_string_literal: true

Rails.application.config.middleware.use(OmniAuth::Builder) do
  provider :shopify,
    ShopifyApp.configuration.api_key,
    ShopifyApp.configuration.secret,
    scope: ShopifyApp.configuration.scope,
    setup: lambda { |env|
      configuration = ShopifyApp::OmniAuthConfiguration.new(env['omniauth.strategy'], Rack::Request.new(env))
      configuration.build_options
      configuration.strategy.options[:client_options][:redirect_uri] = 'https://my.domain.com/our-app-name/auth/shopify/callback'
    }
end

```

**Comment by mrpunkin** [comment]
I'll give this a try when I have a few to see if it fixes our issues with the subdirectory installation. Manually passing the redirect_uri as above though has worked for now to keep me moving on development. Thanks @axlekb!

**Comment by i-am-gdan** [comment]
Just in case this helps anyone else, I also found myself in an infinite redirect but the cause was a missing a comma on my scopes in my initializer rather than a legitimate bug:
```
ShopifyApp.configure do |config|
  config.scope = 'read_products write_products'
end
```
should have been 
```
ShopifyApp.configure do |config|
  config.scope = 'read_products, write_products'
end
```
Without the comma it didn't throw an error but it does create an infinite redirect in [access scope verification](https://github.com/Shopify/shopify_app/blob/main/app/controllers/concerns/shopify_app/shop_access_scopes_verification.rb#L14). `scopes_mismatch` was always returning true, meaning it tried to login again and update the scopes!
