### ISSUE TITLE
App Bridge 2.0 and this Shopify App suck together? 

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1335]
It is true! This combo is so useless together. Does not work at all with Admin Links. Can't wait till it does.

**Comment by hannachen** [comment]
Confirmed that this is due to `host` parameter not being supplied in Admin Links.

**Comment by hannachen** [comment]
> Yes. It has been figured out. I have yet to hear a technical explanation for:
> 
> 1. why was it suddenly thrust upon us as a breaking change
> 2. is it working? Are we all better off now?
> 
> It is just a base64 encoding of a shop domain. Why the pain? Is there a post-mortem for us somewhere?

Apologies, that note was intended for the team to track this issue. This is indeed a bug as Admin Links were missed and should be addressed accordingly. I'm not sure if there were specific reasons why this was omitted during the `host` parameter introduction.

The `host` URL parameter (and as a result, App Bridge 2.0) was introduced to better support [Organization Management](https://help.shopify.com/en/manual/shopify-plus), a feature available to Plus merchants. Top level frame of an organization managed stores have a different domain name from the store, so `host` was added to properly handle the OAuth post-auth redirect without breaking existing apps.

I hope this sheds some light behind the changes. From my understanding, at this time not [upgrading from App Bridge 1.x to 2.x](https://shopify.dev/apps/tools/app-bridge/migrating) will not prevent apps from working, but it will enhance the Plus merchant experience and pave the way for performance improvements for regular stores.

**Comment by resistorsoftware** [comment]
Thanks for letting me know. Not only were Admin Links hosed, but in reality, a lot of things stopped working due to this. 

For now, we are back in action, better than ever, and leaving this niggling details in the dust. It is just unfortunate that these BIG changes by Shopify, are self-inflicted wounds due to silly marketing gimmicks like Plus. From a tech perspective, that whole silo of operations labeled Plus remains one of the worst things ever done in terms of our third-party developer sanity and the pleasure of working with Shopify.
