### ISSUE TITLE
How to use filter :login_again_if_different_shop

### ISSUE THREAD

**Issue by raecoo** [Shopify/shopify_app#134]
Hi,

I want to use __login_again_if_different_shop__ in my app. 
```ruby
def login_again_if_different_shop
  if shop_session && params[:shop] && params[:shop].is_a?(String) && shop_session.url != params[:shop]
    redirect_to_login
  end
end
```
I've added it like following:
```ruby
class ApplicationController < ActionController::Base
  before_filter :login_again_if_different_shop
```
```ruby
class SessionsController < ApplicationController
  skip_before_filter :login_again_if_different_shop
```
for now, I opened my app in Shop A, then open a new window(Chrome tab) to access my app in Shop B. 
the code always capture the url of Shop A from params[:shop], so redirect to Shop A.

If I remove __skip_before_filter__ from SessionsController then get the __Too many redirects__ error.
How to make it switch to the Shop B automatically?

**Comment by kevinhughes27** [comment]
I think this is happening because you already have a session and you aren't providing the shop param. If you were to open the second tab for Shop B and type the url of your app with a `?shop=...` url param then I think it would work.

**Comment by raecoo** [comment]
Yes, I have a session for Shop A.  But I opened the App from Shopify Admin -> Apps for Shop B in second tab. 
I think that link should be include auth info with shop params. right?

**Comment by kevinhughes27** [comment]
hmm you are right it should. I'll try and look into this shortly

**Comment by kevinhughes27** [comment]
I played around with this and ran into some other issues with helpers being shared between the host app and the engine. Its all fixed up in #133 now. I only needed to add the filter to the home controller no need to skip it. Then everything worked locally for me

**Comment by kevinhughes27** [comment]
can you try the latest version 6.1.0 and see if this works for you now? I am going to close since in my local testing this case worked fine

**Comment by raecoo** [comment]
@kevinhughes27 so need add the filter
```ruby
before_action :login_again_if_different_shop
```
to all controllers manually now?

**Comment by raecoo** [comment]
@kevinhughes27 I don't think it fixed with embedded app. In embedded app, the links doesn't include params[:shop] automatically, so if you click a link in the app, the second app will be load the first app content.

**Comment by kevinhughes27** [comment]
if you think this is still an issue can you post step by step reproduction steps please. Then I will be able to take a look

**Comment by qq99** [comment]
I think I know why this is happening:

Session on Shop A sets the following, at some point:
```rb
    def redirect_to_login
      session[:return_to] = request.fullpath if request.get?
      redirect_to login_path(shop: params[:shop])
    end
```
https://github.com/Shopify/shopify_app/blob/28b070d9dd0b302f82e15d66a005a8248847f242/lib/shopify_app/login_protection.rb#L35-L38

Later, you try to use the URL to login and end up in this block:
```rb
    def callback
      if response = request.env['omniauth.auth']
        sess = ShopifyAPI::Session.new(params[:shop], response['credentials']['token'])
        session[:shopify] = ShopifyApp::SessionRepository.store(sess)
        flash[:notice] = "Logged in"
        redirect_to return_address
      else
        flash[:error] = "Could not log in to Shopify store."
        redirect_to action: 'new'
      end
    end
```
https://github.com/Shopify/shopify_app/blob/28b070d9dd0b302f82e15d66a005a8248847f242/lib/shopify_app/sessions_controller.rb#L13-L23

`session[:shopify]` has been set to the new session, but `session[:return_to]` is still stale from a previous request from the same browser

**Comment by kevinhughes27** [comment]
ahhh so we need to blow away return_to on the session as well

**Comment by qq99** [comment]
Yeah, I think a patch of `session[:return_to] = nil` after you set `session[:shopify]` works and fixes this bug

**Comment by kevinhughes27** [comment]
do you want to whip that up then?

**Comment by qq99** [comment]
I could make the PR if you can do the release

**Comment by kevinhughes27** [comment]
its a deal
