### ISSUE TITLE
ShopAccessScopesVerification continuously redirect

### ISSUE THREAD

**Issue by netwire88** [Shopify/shopify_app#1350]
### Description

adding `include ShopifyApp::ShopAccessScopesVerification` causes app to continuously redirect to login page

### Steps to Reproduce

Scenario 1:
- per https://github.com/Shopify/turbolinks-jwt-sample-app/tree/master/app/controllers, I added `include ShopifyApp::ShopAccessScopesVerification` to `SplashPageController`

```
class SplashPageController < ApplicationController
  include ShopifyApp::EmbeddedApp
  include ShopifyApp::RequireKnownShop
  include ShopifyApp::ShopAccessScopesVerification
```

**Expected behavior:**

- After redirecting once and accepting permission updates, should redirect back to app

**Actual behavior:**

- Continuously redirect to login page

**Reproduces how often:**

100%

### Browsers

Chrome, Firefox

### Gem versions

18.0.3

### Additional Information

- I also tried various orders of `include ShopifyApp::ShopAccessScopesVerification` in `SplashPageController`
- I also tried instead add the code to `AuthenticatedController` as such
```
class AuthenticatedController < ApplicationController
  include ShopifyApp::EnsureAuthenticatedLinks
  include ShopifyApp::Authenticated
  include ShopifyApp::ShopAccessScopesVerification
```

**Comment by resistorsoftware** [comment]
I had this too and had to turn off the scope checking in the App config to avoid dealing with this problem. Would love to know what the simple and correct solution to this is.

**Comment by evansjp** [comment]
@resistorsoftware interesting...well at least my splash page renders. How did you handle redirecting the user to the permissions page, then, and getting a permanent access token?

**Comment by hoppergee** [comment]
I met this issue recently, and fixed it with `ShopifyApp::ShopSessionStorageWithScopes`

```diff
class Shop < ActiveRecord::Base
-  include ShopifyApp::ShopSessionStorage
+  include ShopifyApp::ShopSessionStorageWithScopes
  # ...
end
```

And you may also need to add `access_scopes` column to `shops` table

**Comment by netwire88** [comment]
Hi @hoppergee and @resistorsoftware , I tried @hoppergee 's approach and it still didn't work. Is `include ShopifyApp::ShopAccessScopesVerification` in your `SplashPageController` or similar? How are you testing it, by deleting & installing the test app, then adjusting access scopes for the app, or some other way?

**Comment by hoppergee** [comment]
@netwire88 Are you using AppBridge 2.0 and doing things similar to this doc(https://shopify.dev/apps/auth/oauth/session-tokens/server-side-rendered-apps)? If it is, please check my PR(https://github.com/Shopify/shopify_app/pull/1403/files).

**Comment by nelsonwittwer** [comment]
@netwire88 - Are you still having issues with this? We've shipped a few fixes for OAuth redirects and I'm hoping one of those fixes has fixed this issue. Let us know!

**Comment by netwire88** [comment]
Hi @nelsonwittwer, we are unable to get the latest shopify_app working (upgrading from v18). It looks like all GraphQL calling methods have changed, we can't even call GraphQL. The documentation at [shopify_api](https://shopify.github.io/shopify-api-ruby/usage/oauth.html) doesn't work.

Before, we'd call this and get an ActiveResource, now nothing works.

```
shopify_session = ShopifyAPI::Session.new(domain: account.shopify_domain, token: account.shopify_token, api_version: ShopifyApp.configuration.api_version)
ShopifyAPI::Base.activate_session(shopify_session)
ShopifyAPI::GraphQL.client.query(query, variables: variables)
```

**Comment by netwire88** [comment]
Shopify is forcing everyone to upgrade to v10+ in Jan 2023, so we have no choice but to upgrade. It's been horrible!

**Comment by netwire88** [comment]
After 2 weeks spent on this, we can confirm that the redirect loop still happens with shopify_app v21.1.0. However, I think the issue is that the default for `access_scopes` cannot be nil. It has to be "" or else you get errors.
