### ISSUE TITLE
Webhooks jobs argument error

### ISSUE THREAD

**Issue by karimmtarek** [Shopify/shopify_app#1351]
### Description

Recently I started getting this error, when webhooks jobs are called:
```
ArgumentError: wrong number of arguments (given 1, expected 0; required keywords: shop_domain, webhook)
```

### Steps to Reproduce

1. Generate a webhook `rails g shopify_app:add_webhook -t carts/update -a https://example.com/webhooks/carts_update`
2. Wait for a webhook to come in
3. Webhook argument error 🎉

**Expected behavior:**

I expect the webhook job generated by the generator to work.

**Actual behavior:**

Webhook job is erroring:
```
ArgumentError: wrong number of arguments (given 1, expected 0; required keywords: shop_domain, webhook)
```

**Reproduces how often:**

The error happens whenever a webhook job is called

### Browsers

N/A

### Gem versions

`18.0.3`

### Additional Information

It seems that the webhook job arguments `shop_domain`, `webhook`, are now combined in a hash which is them being passed to the webhook job from the webhooks controller

```
# app-name/app/controllers/shopify_app/webhooks_controller.rb
module ShopifyApp
  class MissingWebhookJobError < StandardError; end

  class WebhooksController < ActionController::Base
    include ShopifyApp::WebhookVerification

    def receive
      params.permit!
      job_args = { shop_domain: shop_domain, webhook: webhook_params.to_h } # 👈
      webhook_job_klass.perform_later(job_args) # 👈
      head(:ok)
    end
    ...
end
```

Am I missing something? Or should the generated job change to this:

```
class CartsUpdateJob < ActiveJob::Base
  def perform(job_args)
    shop = Shop.find_by(job_args[:shop_domain])
    ...
  end
end
```

Or maybe the controller change to this
```
webhook_job_klass.perform_later(shop_domain: shop_domain, webhook: webhook_params.to_h)
```

### Security

- [x] I have redacted any private information from my logs or code snippets.

**Comment by yourivdlans** [comment]
Are you on Ruby 3.x by any chance? There is an outstanding PR that fixes this issue: https://github.com/Shopify/shopify_app/pull/1342

**Comment by karimmtarek** [comment]
@yourivdlans yep I'm on Ruby `3.0`, thanks for bringing my attention to the PR, hopefully it gets merged soon 🙏

**Comment by kirillplatonov** [comment]
And the fix is merged! Thanks, @gonzaloriestra, and looking forward to the upcoming release 🙂

**Comment by gonzaloriestra** [comment]
[Version 18.1.0](https://github.com/Shopify/shopify_app/pull/1357) released!
