### ISSUE TITLE
Oauth error invalid_request: The redirect_uri is not whitelisted (nothing works)

### ISSUE THREAD

**Issue by Br3ikros** [Shopify/shopify_app#1367]
Hi guys, I have read the previous issue. However, nothing that I do works. I am more than 100% sure that the way I set up the proxy and my app is correct, but it still won't work.

ngrok is: https://dcf8-31-205-21-16.ngrok.io
on the partner dashboard app, the app URL is the above, that is: https://dcf8-31-205-21-16.ngrok.io
the redirect URL is: https://dcf8-31-205-21-16.ngrok.io/auth/callback

inside my code the redirect URL is the same as the redirect one in the proxy section for redirect url....

my API keys are the correct ones, these are the contents of my env file:
SHOPIFY_API_KEY=
SHOPIFY_API_SECRET=
SHOPIFY_API_SCOPES=read_orders
HOST=https://dcf8-31-205-21-16.ngrok.io

(of course I didn't write the keys over here but on the env they are there and they are NOT surrounded by quotes, nothing is in that file. I have followed letter by letter, word by word the shopify tutorial by Liz on how to code the auth process manually. 

However I still get this damn error:
![s1](https://user-images.githubusercontent.com/26491229/153580124-0ca4675e-98ab-4722-9c2d-a073bc88059f.PNG)

May someone help me out? I am using a custom app, not a public one

**Comment by hannachen** [comment]
@Br3ikros 👋 Would it be possible to include the entire URL that resulted in the error message? It'll probably look something like `https://[shop-name].myshopify.com/admin/oauth/authorize?scope=read_orders&callback=[your callback url]&.....`

**Comment by CostierLucas** [comment]
same issue here, tried everything

**Comment by gonzaloriestra** [comment]
We have just released a new version (2.15.6) that should fix an issue with the callback. Could you try with that version?

**Comment by skmahato** [comment]
@gonzaloriestra Finally it worked. I was stuck for last 2 days.

**Comment by gonzaloriestra** [comment]
Great, sorry for the inconvenience. I'm closing here, let me know if anyone still has problems.

**Comment by shahzadwaris** [comment]
> After I deployed my app to heroku and chang redirect uri, I will encounter this issue "Oauth error invalid_request: The redirect_uri is not whitelisted ". My app works fine locally.

did you find any solution?

**Comment by jlarosee** [comment]
The issue I had was that the API key in my heroku build config didn't match the app I was deploying. 🤷🏻
