### ISSUE TITLE
Implement default Content-Security-Policy that prevents clickjacking

### ISSUE THREAD

**Issue by fbeaudoin-shopify** [Shopify/shopify_app#1377]
## Details
The [Shopify CLI](https://github.com/Shopify/shopify-cli) uses the **shopify_app** gem to create a simple rails application by running `shopify app create rails`. Per our [security requirement](https://shopify.dev/apps/store/security/iframe-protection), apps on the Shopify App Store must set the proper Content Security Policy `frame-ancestors` directive to avoid clickjacking attacks. 

Therefore, the generated app should have a defined `Content-Security-Policy` that at least sets the `frame-ancestors` directive. As for other directives (i.e. `script-src`, `img-src`, ...), they should be as strict as possible.

**Comment by resistorsoftware** [comment]
It totally sucks that this issue remains open since February with zero resolution. A simple App from this gem will not pass Shopify robot on Clickjacking check, due to the CSP.

**Comment by resistorsoftware** [comment]
No. The problem is as I pointed out back then, the CSP seems to be run as part of the Rack response regardless of serving up a page in an embedded app or not. So during CSP initialization Shopify App gem helpers are not instantiated. Hence the Shopify App check that sends GDPR tests fails.

**Comment by resistorsoftware** [comment]
@fbeaudoin-shopify So what exact code should be in this gem. You talk around the issue, but no one has provided a solution to the actual issue. 

Thanks though for explaining it in more detail than anywhere else, by anyone else, for the most part. We learn piece by piece. Slowly.

**Comment by fbeaudoin-shopify** [comment]
@resistorsoftware Unfortunately the team owning the gem has better context than me to provide the implement hence this issue that I created.

**Comment by resistorsoftware** [comment]
It is so weird that such a small issue can take so many months to iron out. In the meantime, the crap shoot with the robot continues.

**Comment by denoyaro** [comment]
@fbeaudoin-shopify Since according to https://shopify.dev/apps/store/security/iframe-protection, the embedded app should only be frameable in an authenticated shop domain, shouldn't the fallback be `Content-Security-Policy: frame-ancestors 'none';`

**Comment by nelsonwittwer** [comment]
#1474 should address the concerns pointed out here, so we are going to close this issue.

If you still encounter this issue with the latest stable version, please reopen using the issue template. You can also contribute directly by submitting a pull request– see the CONTRIBUTING.md(.github/CONTRIBUTING.md) file for guidelines
