### ISSUE TITLE
Hey kids! What is the secret sauce links here

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1379]
App 18.1.1
Embedded in a store. 

Merchant is staring at a screen I rendered in the embedded App, for a product he got to, via an Admin Link. 

Now the merchant wants to return to the Admin, back to the product. WHAT IS THE LINK I use for this? I have no idea. I don't want to use a Polaris external link as that opens a new tab. How do we replace the embedded App in the tab with the Shopify Admin via a link click? Help!

**Comment by forsbergplustwo** [comment]
https://shopify.dev/apps/tools/app-bridge/actions/navigation/redirect#redirect-to-a-relative-path-in-shopify-admin

**Comment by resistorsoftware** [comment]
Ah yes. OK. Since I quit the React Polaris route and switched to the Hotwire Turbo Stimulus package, I have been not using any of the App Bridge specialty items much. I guess it is time to dive back into that and resurrect the old App Bridge for use... good timing. The people have filled my email box with hate since I replaced some links that now open new tabs and not just jump back into the Admin. Ingrates!
