### ISSUE TITLE
fullpage_redirect_to not working in embedded app (App Bridge 2.0)

### ISSUE THREAD

**Issue by CodeSchneider** [Shopify/shopify_app#1387]
We have recently updated our version of this gem to v18.1.2 due to the App Bridge 2.0 related deprecation messages from Shopify. 

When a user attempts to upgrade their plan, we create a new RecurringApplicationCharge and fire off a `fullpage_redirect_to` to the RecurringApplicationCharge's `confirmation_url`. In the browser we see the following:

<img width="1748" alt="Screen Shot 2022-03-08 at 4 28 30 PM" src="https://user-images.githubusercontent.com/7592718/157328235-b17e4579-f896-4d92-8b22-a23cf5377746.png">

Any help would be appreciated.

**Comment by khoimm92** [comment]
+1, I got the same issue. Temporarily solutions:
- Revert to shopify_app from 18.1.2 to 18.1.1, or
- Add the `host` param to the url

**Comment by hoppergee** [comment]
Currently, I think the `response.status = 303 # Makes Turbo render html response` can fix your issue.
The solution comes from: https://github.com/Shopify/shopify_app/issues/1287#issuecomment-966997051

**Comment by hoppergee** [comment]
@flavio-b I fixed all related issues recently. You can check my way to set the `params[:host]` with HTTP header here: https://github.com/Shopify/shopify_app/pull/1360

**Comment by rickmax** [comment]
I have same error from 19.0.1 
`response.status = 303 # Makes Turbo render html response` does not work too

**Comment by janklimo** [comment]
Since Shopify now requires all apps to be on v18.1.2 or higher, here's my approach hoping it will help the rest of you guys deal with the upgrade.

The key is to make sure you pass in `host` param to every action that performs a `fullpage_redirect_to`. So, as an example, I had to make the following change when redirecting to the `/upgrade` path:

```diff
+  const { host } = AppConfig;
   const isOverLimit = imagesCount > imagesLimit;

   const title = isOverLimit ? "Please upgrade your plan now" : "You're currently on the free plan";
@@ -53,7 +54,7 @@ const UsageBanner: FunctionComponent<Props> = ({ planStats, fetchPlanStats }) =>
       <Banner title={title} status={status}>
         <TextContainer>
           {message()}
-          <Button outline download url="/upgrade">
+          <Button outline download url={`/upgrade?host=${host}`}>
             {`Upgrade for $${proPlanPrice}/mo.`}
           </Button>
         </TextContainer>
```

My app is an SPA which receives the `host` param when the app is authenticated. I set the `@host` instance variable in the admin controller:

```ruby
class AdminController < ShopifyApp::AuthenticatedController
  # ...
  before_action :set_host

  private

  def set_host
    @host = params[:host]
  end
end
```

so it can be exposed to the frontend and passed into any redirect (as shown above).

For completeness I made the following changes to the charges controller:

```diff
 class ChargesController < AdminController
   def upgrade
-    charge = ChargesFactory.new_charge
+    charge = ChargesFactory.new_charge(@host)

     fullpage_redirect_to charge.confirmation_url if charge.save
   end

   def activate
     MailchimpEventsWorker.perform_async(@shop.id)
     @shop.update(current_charge: true)

-    fullpage_redirect_to root_url
+    redirect_to "#{root_url}?host=#{@host}&upgraded=true"
   end
```
And my charges factory:

```diff
 module ChargesFactory
   module_function

-  DEFAULTS = {
-    return_url: "#{ENV.fetch('HOST')}/activate_charge",
-  }.freeze
-
-  def new_charge
+  def new_charge(host)
     charge_options = {
       name: 'PRO plan. Big love!',
       price: Shop::PRO_PLAN_PRICE,
+      return_url: "#{ENV.fetch('HOST')}/activate_charge?host=#{host}",
     }

-    ShopifyAPI::RecurringApplicationCharge.new(DEFAULTS.merge(charge_options))
+    ShopifyAPI::RecurringApplicationCharge.new(charge_options)
   end
 end
```
This way the `host` param is present after the charge is accepted. Hope it helps!
