### ISSUE TITLE
Can't login to another shop

### ISSUE THREAD

**Issue by Jerskouille** [Shopify/shopify_app#140]
Hi there,

I have a weird issue with an embedded app and `login_again_if_different_shop`. On the first install, it redirects me to the first active shop I had a session active with.

So when I try to access http://my.app/login?shop=shop2 , it asks me to allow the app in shop2, but I always end up redirected to http://my.app/login?shop=shop1 .
But this only happen when I try to access the shop via http://my.app/login?shop=shop2 . If, once installed, I go to the admin dashboard of shop2 and open the app, then it works fine.

It is worth noting I did the update myself from v5 to v6 by running the generator on an empty app and comparing with my app.
Here are the main files that I think are involved in that redirect.

**application_controller.rb**
```ruby
class ApplicationController < ActionController::Base
  include ShopifyApp::Controller
  # ...
end
```

**home_controller.rb**
```ruby
class HomeController < ApplicationController
  before_action :login_again_if_different_shop
  around_filter :shopify_session
  # ...
end
```

**sessions_controller.rb**
```ruby
class SessionsController < ApplicationController
  include ShopifyApp::SessionsController
end
```

**layouts/application.html.haml**
```haml
    :javascript
      ShopifyApp.init({
        apiKey: "#{ShopifyApp.configuration.api_key}",
        shopOrigin: "#{"https://#{ @shop_session.url }" if @shop_session}"
      });
```
(Even if the syntaxic coloration is buggy here, the shopOrigin is actually complete in the end)

Am I missing anything or is there an actual issue with `login_again_if_different_shop`?

**Comment by kevinhughes27** [comment]
related to #134

can you clarify that this used to work and no longer does?

**Comment by Jerskouille** [comment]
I'm sorry but I can't be sure of this, because I'm in early stage of my app's development and didn't get the occasion to install it on a lot of shops. I think I'd probably have noticed before migrating, but I might just have ignored it at that time.
I actually talked about the migration just to emphasize the fact that I didn't run the generator directly on my app but did kind of a diff.

**Comment by Jerskouille** [comment]
I was actually meaning the migration from v5 to v6. I'm currently using v6.1.0.

**Comment by kevinhughes27** [comment]
I'll run through this flow again but I recently tested in #134 and it worked for me.

**Comment by Jerskouille** [comment]
Thanks for investigating!

**Comment by kevinhughes27** [comment]
okay here are the steps I followed and I what I was able to do.

```
rails new test-app
cd test-app
# add shopify_app 6.1.0 to gem file
bundle install
rails g shopify_app -api_key=... -secret=...
```

Then I:
1. Installed my app on my first test store
2. Revisited localhost:3000 and was redirected to the app in my test store since I had a session
3. Visited localhost:3000/login?shop=.. my second test store. I installed the app on my second store
