### ISSUE TITLE
V19.0.1 - sorbet error?

### ISSUE THREAD

**Issue by awd** [Shopify/shopify_app#1411]
Attempting to re-install my dev app, I foolishly uninstalled (knowing this is always a huge pain to debug on version bumps). 

But for once a new error has appeared which was not seen before v19 releases.

```ruby
Parameter 'scope': Expected type T.any(String, T::Array[String]), got type NilClass
Caller: /usr/local/bundle/gems/sorbet-runtime-0.5.9878/lib/types/private/methods/call_validation.rb:117
Definition: /usr/local/bundle/gems/shopify_api-10.0.2/lib/shopify_api/auth/session.rb:52
```

<img width="1052" alt="Screen Shot 2022-04-12 at 6 34 27 PM" src="https://user-images.githubusercontent.com/65078/163065700-c9e3d10d-0ebf-48ae-8e28-c5531e910867.png">

**Comment by awd** [comment]
I rolled back to `18.1.1` - reinstalling the app works as expected, no issues.

In `19.0.1` the install flow throws up an error about cookies (why??), and doesn't make it past the Session vs Callback controllers infinite redirection bug. The shop record is not modified on reinstall (no access scopes or token is set).

In `18.1.1` the install flow works, the shop record is updated with a new token and access scopes, and the merchant is redirected into the app as expected. There is no error related to cookies.

It's very difficult to debug and understand why this happens, as the logs don't have anything useful other than pages responding 200 OK and then redirecting (via JS?) over and over.

**Comment by elioncho** [comment]
Having the same error. This gem needs help. Lots of new issues since the session token requirement started.

**Comment by tomlober** [comment]
I have the same error with version `19.1.0`

`TypeError (Parameter 'scope': Expected type T.any(String, T::Array[String]), got type NilClass`
`Definition: /app/vendor/bundle/ruby/3.1.0/gems/shopify_api-10.1.0/lib/shopify_api/auth/session.rb:52):`
`Caller: /app/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.10101/lib/types/private/methods/call_validation.rb:117`

How to fix this ?

**Comment by Trimakas** [comment]
I'm still getting this error with the following: 

`gem 'shopify_api', '12.4.0'
gem 'shopify_app', '21.4.1'`
