### ISSUE TITLE
Install Error: ShopifyAPI::Context not setup, please call ShopifyAPI::Context.setup

### ISSUE THREAD

**Issue by iyerushalmi** [Shopify/shopify_app#1415]
### Description

I setup the gem according the Readme instructions, but when I turn on the server and input a myshopify store URL I get the following error: "ShopifyAPI::Errors::ContextNotSetupError (ShopifyAPI::Context not setup, please call ShopifyAPI::Context.setup)"

### Steps to Reproduce

Tested on Ruby 3.0.1/Rails 6 and Ruby 3.1.0/Rails 7.0.2.3

1. Run "rails new my_shopify_app" from terminal
2. Change directory and run "bundle add shopify_app" from terminal
3. Add dotenv gem to gemfile, bundle install, and create .env file in root app directory with SHOPIFY_API_KEY and SHOPIFY_API_SECRET from partners App listing
4. Run "rails generate shopify_app"
5. Run "rails db:migrate"
6. Run "rails server"
7. Load http://localhost:3000 in web browser, and input a valid myshopify domain and click "Install App"

**Expected behavior:**

For the browser to proceed to the app install page and/or any other page without producing an internal server error

**Actual behavior:**

Error and trace showing below: ShopifyAPI::Errors::ContextNotSetupError in ShopifyApp::SessionsController#new

Started GET "/login?shop=test.myshopify.com&top_level=true" for 72.134.190.206 at 2022-04-15 09:30:44 -0700
Cannot render console from 72.134.190.206! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by ShopifyApp::SessionsController#new as HTML
  Parameters: {"shop"=>"test.myshopify.com", "top_level"=>"true"}
Completed 500 Internal Server Error in 1ms (Allocations: 559)

  
ShopifyAPI::Errors::ContextNotSetupError (ShopifyAPI::Context not setup, please call ShopifyAPI::Context.setup):
  
shopify_api (10.0.2) lib/shopify_api/auth/oauth.rb:23:in `begin_auth'
sorbet-runtime (0.5.9889) lib/types/private/methods/call_validation.rb:161:in `bind_call'
sorbet-runtime (0.5.9889) lib/types/private/methods/call_validation.rb:161:in `validate_call'
sorbet-runtime (0.5.9889) lib/types/private/methods/call_validation.rb:90:in `block in create_validator_slow'
shopify_app (19.0.1) app/controllers/shopify_app/sessions_controller.rb:47:in `start_oauth'
shopify_app (19.0.1) app/controllers/shopify_app/sessions_controller.rb:40:in `authenticate'
shopify_app (19.0.1) app/controllers/shopify_app/sessions_controller.rb:14:in `new'
actionpack (7.0.2.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (7.0.2.3) lib/abstract_controller/base.rb:214:in `process_action'
actionpack (7.0.2.3) lib/action_controller/metal/rendering.rb:53:in `process_action'
actionpack (7.0.2.3) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
activesupport (7.0.2.3) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
actiontext (7.0.2.3) lib/action_text/rendering.rb:20:in `with_renderer'
actiontext (7.0.2.3) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
activesupport (7.0.2.3) lib/active_support/callbacks.rb:127:in `instance_exec'
activesupport (7.0.2.3) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
activesupport (7.0.2.3) lib/active_support/callbacks.rb:138:in `run_callbacks'
actionpack (7.0.2.3) lib/abstract_controller/callbacks.rb:233:in `process_action'
actionpack (7.0.2.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (7.0.2.3) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
activesupport (7.0.2.3) lib/active_support/notifications.rb:206:in `block in instrument'
activesupport (7.0.2.3) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (7.0.2.3) lib/active_support/notifications.rb:206:in `instrument'
actionpack (7.0.2.3) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
actionpack (7.0.2.3) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
activerecord (7.0.2.3) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (7.0.2.3) lib/abstract_controller/base.rb:151:in `process'
actionview (7.0.2.3) lib/action_view/rendering.rb:39:in `process'
actionpack (7.0.2.3) lib/action_controller/metal.rb:188:in `dispatch'
actionpack (7.0.2.3) lib/action_controller/metal.rb:251:in `dispatch'
actionpack (7.0.2.3) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
actionpack (7.0.2.3) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (7.0.2.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.2.3) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.2.3) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.2.3) lib/action_dispatch/routing/route_set.rb:850:in `call'
railties (7.0.2.3) lib/rails/engine.rb:530:in `call'
railties (7.0.2.3) lib/rails/railtie.rb:224:in `public_send'
railties (7.0.2.3) lib/rails/railtie.rb:224:in `method_missing'
actionpack (7.0.2.3) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (7.0.2.3) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (7.0.2.3) lib/action_dispatch/journey/router.rb:50:in `block in serve'
actionpack (7.0.2.3) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (7.0.2.3) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (7.0.2.3) lib/action_dispatch/routing/route_set.rb:850:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (7.0.2.3) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
actionpack (7.0.2.3) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.0.2.3) lib/action_dispatch/middleware/cookies.rb:693:in `call'
activerecord (7.0.2.3) lib/active_record/migration.rb:603:in `call'
actionpack (7.0.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (7.0.2.3) lib/active_support/callbacks.rb:99:in `run_callbacks'
actionpack (7.0.2.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (7.0.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.2.3) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (7.0.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
web-console (4.2.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.2.0) lib/web_console/middleware.rb:19:in `block in call'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.2.0) lib/web_console/middleware.rb:17:in `call'
actionpack (7.0.2.3) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
railties (7.0.2.3) lib/rails/rack/logger.rb:36:in `call_app'
railties (7.0.2.3) lib/rails/rack/logger.rb:25:in `block in call'
activesupport (7.0.2.3) lib/active_support/tagged_logging.rb:99:in `block in tagged'
activesupport (7.0.2.3) lib/active_support/tagged_logging.rb:37:in `tagged'
activesupport (7.0.2.3) lib/active_support/tagged_logging.rb:99:in `tagged'
railties (7.0.2.3) lib/rails/rack/logger.rb:25:in `call'
sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (7.0.2.3) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
actionpack (7.0.2.3) lib/action_dispatch/middleware/request_id.rb:26:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
shopify_app (19.0.1) lib/shopify_app/middleware/jwt_middleware.rb:24:in `call_next'
shopify_app (19.0.1) lib/shopify_app/middleware/jwt_middleware.rb:12:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (7.0.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.0.2.3) lib/action_dispatch/middleware/server_timing.rb:20:in `call'
actionpack (7.0.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.0.2.3) lib/action_dispatch/middleware/static.rb:23:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (7.0.2.3) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'
railties (7.0.2.3) lib/rails/engine.rb:530:in `call'
puma (5.6.4) lib/puma/configuration.rb:252:in `call'
puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'
puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.6.4) lib/puma/request.rb:76:in `handle_request'
puma (5.6.4) lib/puma/server.rb:441:in `process_client'
puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

**Reproduces how often:**

This happens every time I try to test the install page.

### Browsers

Google Chrome Version 100.0.4896.88 and Safari Version 13.1.1

### Gem versions

shopify_app 19.0.1 UPDATE: I have confirmed this issue does not exist with shopify_app 18.1.2

### Additional Information

N/A

### Security

- [x] I have redacted any private information from my logs or code snippets.

**Comment by kcamcam** [comment]
Can you verify that the contents of the `shopify_app.rb` initializer contains the `ShopifyAPI::Context.setup(...)` at the bottom of the file? If it was already there and is still not working try removing the `Rails.application.config.after_initialize` block around the context setup.

**Comment by iyerushalmi** [comment]
The solution proposed by @perryqh and @hungdinhvan resolved the issue for me. Thank you!

**Comment by netwire88** [comment]
Please update the documentation
