### ISSUE TITLE
Embedded app loads OK on Chrome, but not on Firefox or Safari

### ISSUE THREAD

**Issue by fairknowe** [Shopify/shopify_app#1417]
### Description

Embedded app loads OK on Chrome, but not on Firefox or Safari. See [forum post](https://community.shopify.com/c/technical-q-a/embedded-app-loads-ok-on-chrome-but-not-on-firefox-or-safari/td-p/1563168) for picture.

### Steps to Reproduce

1. bundle init
2. bundle add shopify-cli
3. bundle add dotenv-rails
4. shopify login
6. shopify app create rails (answering yes to public app)
7. shopify app serve
8. install app on Chrome, confirm install. Uninstall and repeat for Firefox & Safari

**Expected behavior:**

The app admin iframe should load with list of products in each browser

**Actual behavior:**

The Chrome browser performs as expected. With Firefox and Safari the installation process hangs after leaving the admin page and never returns.

If I refresh the Firefox/Safari page, the app admin iframe loads but the resulting text is the same, and the products do not load.

In all cases the app installs, but views/home/index.html.erb doesn't seem to load completely on Firefox & Safari. 

**Reproduces how often:**

Every time

### Browsers

Chrome (Version 100.0.4896.88 (Official Build) (x86_64)), Firefox (99.0.1 (64-bit)), Safari (Version 15.4 (15613.1.17.1.13, 15613)

### Gem versions

Using ruby-3.1.2
Gems:
Rails 7.0.2.3
shopify_api (10.0.2)
shopify_app (19.0.1)
shopify-cli (2.15.6)

### Additional Information

My naive troubleshooting seems to point to the Firefox & Safari browser installs stopping at line 13 in views/home/index.html.erb. In other words, I don't think the 'await import("lib/shopify_app")' is returning.

### Security

- [x] I have redacted any private information from my logs or code snippets.

**Comment by fairknowe** [comment]
I've added a repo with a Dockerfile and instructions that creates a simple app to illustrate this issue... https://github.com/fairknowe/Issue1417

**Comment by alfredoshopcreatify** [comment]
I'm seeing the same issue in Rails 7 with importmaps.
