### ISSUE TITLE
Add a README note about common troubleshooting problems

### ISSUE THREAD

**Issue by qq99** [Shopify/shopify_app#142]
EASDK issue, if you didn't use SSL and CSP is blocking you, you can see this in your Chrome console:

`[Report Only] Refused to frame 'yoururl.com' because it violates the following Content Security Policy directive: "frame-src 'self' https: safari-extension: chrome-extension-resource: chrome-extension: chromeinvoke: chromeinvokeimmediate: webviewprogressproxy: webkit-fake-url: chromenull: blob: data:".`

I stumbled on this for a good hour, we should add a note somewhere

cc @nt3rp @kevinhughes27

**Comment by kevinhughes27** [comment]
I agree this should live in the README here so people don't have to chase things down. We should also link to the ESDK docs somewhere and link to the appinfive screencast when it launches. cc @joshubrown

**Comment by qq99** [comment]
:+1: to all of those :)

**Comment by qq99** [comment]
Callback URL is a bit confusing in the partners section, I wasn't sure if it meant that Shopify's servers would actually do a communication with via HTTP.  Since it's a client-only thing, we should add a note that it should be some kind of landing page for your app and at least resolvable by your machine

**Comment by alrick** [comment]
hey there!

what's the way to fix this problem? we can't test the app in a local environment?

Thank you

**Comment by christianblais** [comment]
> what's the way to fix this problem? we can't test the app in a local environment?

If you have problem with your local environment, you can always use a tunnel such as (ngrok)[https://ngrok.com/].

**Comment by qq99** [comment]
:+1: for ngrok

It's a bit annoying for the free version (as you need to update your app URLs over time as your allotted ngrok subdomain changes) but it works quite well

**Comment by kevinhughes27** [comment]
you can just click the run unsafe scripts in chrome and then you can test locally

**Comment by cymen** [comment]
I wasn't sure where that setting was -- the realized it's on the little shield in the address bar (on right):

<img width="281" alt="screen shot 2016-06-29 at 9 12 32 am" src="https://cloud.githubusercontent.com/assets/121034/16459900/a5dd4600-3dd9-11e6-9606-db437411c051.png">
