### ISSUE TITLE
CSP and this Gem

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1423]
The approach to date has been adding this line to the Rails initializer.

    policy.frame_ancestors :https, -> { "https://#{current_shopify_domain} https://admin.shopify.com;" }

Interesting stuff. So the Rails App will indeed try and render this policy under certain circumstances. In all those circumstances, this helper method **current_shopify_domain** better exist. Where is it defined? In the controller includes for RequiresKnownShop. 

So anytime anything renders where that little ditty is not included, this App will blow chunks. Not all controllers have that little ditty. 

Is there some kind of direction on how to avoid that?

**Comment by resistorsoftware** [comment]
This sucks. This project can sit for weeks with an issue like that, and no one from Shopify has any opinion or vision on how to avoid it.

**Comment by lcanal** [comment]
Ahhh, thank you! It's still early in the morning here. That makes a lot of sense and yeah, completely unworkable from the app maker's point of view unless you go through extra steps to initialize the store domain ahead of time... With the potential for clashes.

This is ugly

**Comment by resistorsoftware** [comment]
I thought it was as simple as just checking to see if current_shopify_domain the method even existed. If it did, use it. If it did not, well, the frame policy was obviously being called into use outside the scope of a needed embedded App session, so use whatever value in there. That turned out to be wrong, as I submitted an App with that, and it was rejected due to CSP violations. 

Now to be fair, that could be because I was using the SHOPIFY CSP policy, as per the Shopify CLI, and that was not a match for the documentation. 

So again, this is outside my scope to fix once and for all. I am not into fixing contradictions whether they matter or not.

**Comment by yen-vo-latori** [comment]
Hi @resistorsoftware, were you able to fix it? We are facing the same problem.

**Comment by nelsonwittwer** [comment]
Apologizes it took us so long to respond. Responsibility for this gem recently changed teams here at Shopify and it took us a bit to free up engineers to work on it. Rest assured, we are here and are taking a look at this issue and all the others in the backlog :)

Assuming you have your apps configured for embedded use, CSP should work out of the box. If that isn't the case, I'll help get the bug fixed. 

I'm still trying to reproduce the issue on my end, but I thought I'd double check some things with y'all who are running into problems with CSP in approval:

### Verify that your configure has embedded apps turned on

```ruby
ShopifyApp.configure do |config|
   config.embedded_app = true
end
```

### Verify that your controller actions are authenticated

Assuming that config is set to true, controller actions that include the [Authenticated](https://github.com/Shopify/shopify_app/blob/main/app/controllers/concerns/shopify_app/authenticated.rb) controller concern will subsequently include the [EmbeddedApp](https://github.com/Shopify/shopify_app/blob/main/lib/shopify_app/controller_concerns/embedded_app.rb) controller concern which modifies the Rails [content_security_policy](https://edgeguides.rubyonrails.org/security.html#content-security-policy-header) via the [FrameAncestors](https://github.com/Shopify/shopify_app/blob/main/lib/shopify_app/controller_concerns/frame_ancestors.rb) concern. 

Essentially all of that is to say the gem will set the `Content-Security-Policy` header for you assuming your Rails action is authenticated.

### Verify the shop subdomain is present
The [current_shopify_domain](https://github.com/Shopify/shopify_app/blob/main/app/controllers/concerns/shopify_app/require_known_shop.rb#L13) that is used in that `FrameAncestors` controller concern is dynamically set based off subdomain of the shop. If your URLs somehow don't use the shop's subdomains, the `Content-Security-Policy` header will not be set as expected.

**Comment by nelsonwittwer** [comment]
If you aren't able to use the `Authenticated` controller concern, you could also include the [EmbeddedApp](https://github.com/Shopify/shopify_app/blob/main/lib/shopify_app/controller_concerns/embedded_app.rb) concern it should take care of CSP work for you.

**Comment by ziaulrehman40** [comment]
In our case, we were upgrading some old App, and were using old `ShopifyApp::Authenticated` concern in authenticated controller, replacing it with new `ShopifyApp::EnsureInstalled` solved the issue.
