### ISSUE TITLE
Clickjacking problems

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1426]
Shopify App 18.1.2

Shopify sends the GDPR webhook with a bad header. Generates a correct 401. But, the CSP is also executed and it blows a 500 error because current_shopify_domain does not exist. 

Why does the webhook controller even run the CSP? If the CSP is run, then it has to have to current Shopify domain. Since that is a mess of parameters or header items, what is the universal way to ensure the CSP has the correct value for this? 

What a mess this gem is.

**Comment by nelsonwittwer** [comment]
This should have been fixed with #1474 . If it hasn't and you are still having issues, feel free to reopen.
