### ISSUE TITLE
Server side render authentication

### ISSUE THREAD

**Issue by sblackstone** [Shopify/shopify_app#1427]
Are these directions supposed to still be valid?
`https://shopify.dev/apps/auth/oauth/session-tokens/server-side-rendered-apps`

For one, I'm unable to import getSessionToken:
```
import { getSessionToken } from "@shopify/app-bridge-utils";
```

As it appears the version currently published doesn't export this symbol.  

So I went to find the codebase for this utility and the repo doesn't seem to exist on github anymore: `git@github.com:Shopify/app-bridge.git`

What's the correct way to go about securing our server-rendered pages in an embedded app?

**Comment by nelsonwittwer** [comment]
Thanks for the feedback! I'll pass that on to the docs team and see if we can't get some more updated docs. I won't share that article again until it gets updated 😬 

I'm understanding that the issue you have is with the outdated documentation and not necessarily with this gem?

**Comment by sblackstone** [comment]
> Thanks for the feedback! I'll pass that on to the docs team and see if we can't get some more updated docs. I won't share that article again until it gets updated 😬
> 
> I'm understanding that the issue you have is with the outdated documentation and not necessarily with this gem?

The gem is working if you base your code (with modifications) off of `turbolinks-jwt-sample-app`

**Comment by nelsonwittwer** [comment]
Noting the gem is working as expected, I'm going to close this issue and pass your suggestion on to the dev docs team.


> I assume an intern was assigned to write this as a first assignment in the real world since we have this fabulous case true and case false. (and not to knock beginner programmers, but it doesn't belong in professional documentation)

As a reminder of the [code of conduct](https://github.com/Shopify/.github/blob/main/CODE_OF_CONDUCT.md), please try to show empathy when reporting issues like this. Mistakes happen and docs get outdated. Even if this was written by an intern, I'd imagine this feedback would hurt as it is written. 

Feedback is a gift and we will take it and apply it accordingly; just remember there is a person behind these docs ❤️
