### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by avra911** [Shopify/shopify_app#144]
Hi,

Small typo, I think ```<button type='submit'>Install</buttom>``` should be ```<button type='submit'>Install</button>``` in views/sessions/new.html.erb

R

**Comment by kevinhughes27** [comment]
it definitely should!

**Comment by avra911** [comment]
Is there any way we can sent PR to rubygem?

R

**Comment by kevinhughes27** [comment]
absolutely! If you send a PR to this repo it will make it into the gem next time we release

**Comment by avra911** [comment]
Perfect sense, thank you! I created the 100th fork :)

R

**Comment by kevinhughes27** [comment]
:100: :tada:

**Comment by petrvolny** [comment]
:heart:
