### ISSUE TITLE
OAuth Redirects from upgrading to 19.x

### ISSUE THREAD

**Issue by awd** [Shopify/shopify_app#1446]
I am working on updating to the latest `19.x` of this `shopify_app` gem and 10.x of `shopify_api`. I am coming from `18.x` / `9.x` respectively. 

Installing the app into a fresh/empty database is producing very strange results. I see the `shop` record get created in the shops table, but the app itself infinitely redirects, and there is no `user` record in the users table. 

Settings in `shopify_app.rb` initializer:
```
config.shop_session_repository = 'Shop'
config.user_session_repository = 'User'
```

Eventually after many redirects (the `shopify_app` gem isn't making it to my own application code), I am presented with this error image.

<img width="979" alt="Screen Shot 2022-06-12 at 4 56 57 PM" src="https://user-images.githubusercontent.com/65078/173254458-9e5525ec-5918-41f0-8cea-e53418b713ce.png">

Rails: `7.0.3`
ShopifyApp: `19.0.2`
ShopifyApi: `10.1.0`

I've tried this on multiple browsers: latest chrome, and latest safari, in both regular and incognito modes. 
All with cleared cookies, starting as fresh as you could be.

I've tried setting `config.action_dispatch.cookies_same_site_protection = :none` in the `application.rb` configuration.

I've tried manually visiting `<dev.app.domain>/login?shop=<dev.shop.here>`, and also through the partners dashboard via the `install app` link beside my dev app and dev store.

I've tried running the latest commit of this gem. Same effect. 

### What am I missing here? 
This really should not be so challenging to get up and running. Can someone let us partner/app developers know if this gem is to be used as stable or are we back to experimenting without documentation? The problem is there is zero feedback from this gem when something is not working. 

Debug mode that fails instead of infinitely redirecting with a message and next steps would be a big help.

The only solution is to revert back to `ShopifyApp: 18.x` and `ShopifyApi: 9.x`

@hannachen @paulomarg - please advise!

**Comment by redareda9** [comment]
It seems like Shopify is slowly giving up on all its public github repos. 
I migrated from Node to Rails just because I supposed Rails gems would be maintained.
I've spent countless hours on this gem trying to figure out how to make it work. Honestly couldn't make it if @kirillplatonov or Forsbergplustwo didn't share about their implementations.

**Comment by nelsonwittwer** [comment]
@awd - are you still having issues with OAuth redirects? If so, I'm curious if you do if you upgrade to the latest versions. We've shipped a few bug fixes that should have addressed this issue. Let us know!

**Comment by awd** [comment]
@nelsonwittwer - all good on my side, should have updated this or closed before. Thx for the ping!

**Comment by uurcank** [comment]
@netwire88 [comment out this rescue line](https://github.com/Shopify/shopify_app/blob/9436a8bca65e227bd10acec2461508d9651e4bac/app/controllers/shopify_app/callback_controller.rb#L20) so you can see what's going on. 

There must be an error in your app which leads to this redirect every time and resulting in an infinite loop. It may just be a validation error.
