### ISSUE TITLE
uninitialized constant ShopifyApp::MissingWebhookJobError

### ISSUE THREAD

**Issue by vfonic** [Shopify/shopify_app#1452]
### Description

In brand new Rails 7 app, when adding `config.webhooks` to ShopifyApp configuration (in initializer), this error is raised (if there's missing webhook job class):

```
....../gems/ruby-3.1.1/gems/shopify_app-19.0.2/lib/shopify_app/managers/webhooks_manager.rb:52:in `webhook_job_klass': uninitialized constant ShopifyApp::MissingWebhookJobError (NameError)
```

### Steps to Reproduce

1. `rails new missing_shopify_webhook`
2. `cd missing_shopify_webhook`
3. `bundle add shopify_app`
4. `rails generate shopify_app`
5. Add `config.webhooks = [{ topic: 'orders/create', address: 'https://example.com/webhooks/order_created' }]` to `config/initializers/shopify_app.rb`
6. `rails s`

**Expected behavior:**

I get `ShopifyApp::MissingWebhookJobError`

**Actual behavior:**

I get `uninitialized constant ShopifyApp::MissingWebhookJobError (NameError)` - this is a different error from above.

**Reproduces how often:**

Reproduces only when `ShopifyApp::WebhooksController` is not "touched", because `ShopifyApp::MissingWebhookJobError` is defined in `ShopifyApp::WebhooksController`'s file - `app/controllers/shopify_app/webhooks_controller.rb`:
https://github.com/Shopify/shopify_app/blob/main/app/controllers/shopify_app/webhooks_controller.rb#L4

### Gem versions

19.0.2

**Comment by ivorpad** [comment]
In 20.0.0, this issue remains unresolved.

**Comment by Trimakas** [comment]
I'm getting the same. I did nothing more than run the generator and add in a webhook in the `shopify_app` initializer

**Comment by fabriazza** [comment]
Same error trying to add webhooks either manually or using the cli
`config.after_authenticate_job = { job: "Shopify::AfterAuthenticateJob", inline: false }`
