### ISSUE TITLE
Webhooks documentation is incorrect

### ISSUE THREAD

**Issue by minichate** [Shopify/shopify_app#1471]
### Description

In https://github.com/Shopify/shopify_app/blob/main/docs/shopify_app/webhooks.md and http://shopify.github.io/shopify_app/ we note that the webhooks delivery address should contain the protocol and domain name of the delivery address. This was true in `shopify_app@18.0.0` and similar versions, but after the switch to ` ShopifyAPI::Webhooks::Registry` in v19 it isn't anymore.

In `ShopifyAPI` we fill in the protocol and hostname automagically based on `Context.host_name`; see https://github.com/Shopify/shopify-api-ruby/blob/main/lib/shopify_api/webhooks/registrations/http.rb#L12

### Steps to Reproduce

1. Register a webhook using the examples listed in the documentation
2. Webhook will never be delivered because the URI is malformed after the HTTP registry in ShopifyAPI concatenates strings together.
3. If you fetch the webhook registration you'll be able to observe the malformed `address` field value.

**Expected behavior:**

Webhooks delivered

**Actual behavior:**

Webhooks undelivered

**Reproduces how often:**

100%

### Browsers

n/a

### Gem versions

Version 18.1.3 was the last working version -- every version since v19.0.0 has exhibited the broken behaviour

### Additional Information

n/a

### Security

- [x] I have redacted any private information from my logs or code snippets.

**Comment by nelsonwittwer** [comment]
Thanks for pointing this out! Docs have been updated with #1492
