### ISSUE TITLE
EnsureBilling: fix wrong number of arguments

### ISSUE THREAD

**Issue by serhii-mishchenko** [Shopify/shopify_app#1484]
raising this place:
https://github.com/Shopify/shopify_app/blob/main/lib/shopify_app/controller_concerns/ensure_billing.rb#L122
https://github.com/Shopify/shopify_app/blob/main/lib/shopify_app/controller_concerns/ensure_billing.rb#L10

returns error:
wrong number of arguments (given 2, expected 0..1)

easy to reproduce by writing something like this in console:
ShopifyApp::EnsureBilling::BillingError.new("Error while billing the store", [{"field"=>nil, "message"=>"message"}])

**Comment by andyw8** [comment]
Sidenote: There is typo `userErrros`
