### ISSUE TITLE
  config.shop_session_repository = 'ShopifyShop' still working?

### ISSUE THREAD

**Issue by daniel-gato** [Shopify/shopify_app#1491]
We use this and we upgraded to latest. Is this still working?

How to get my shop from the callback controller?

**Comment by FelixSundqvist** [comment]
+1

**Comment by aidasayduck** [comment]
+1

**Comment by davidelamorte** [comment]
+1

**Comment by nelsonwittwer** [comment]
Yes it is still working :) 

In the callback controller you can access the shop that installed the app with the [params that Shopify sends you in the request params.](https://github.com/Shopify/shopify_app/blob/main/app/controllers/shopify_app/callback_controller.rb#L11)

```ruby
filtered_params(:shop)
``` 

will you give you the shop that installed your app.

Hopefully that helps clarify things! I'm going to close this issue, but if you still have questions feel free to re-open with more context. Thanks!
