### ISSUE TITLE
Webhook Manager Error on Pub/Sub Events

### ISSUE THREAD

**Issue by kcamcam** [Shopify/shopify_app#1505]
### Description

Webhook manager raises a missing webhook job error when registering Pub/Sub events and possibly Event Bridge events as well. It is working fine for HTTP webhooks though.

### Steps to Reproduce

1. Specify a pub/sub event in the shopify_app initializer, as per the [_shopify_api_](https://github.com/Shopify/shopify-api-ruby/blob/main/docs/usage/webhooks.md#add-to-webhook-registry) gems docs. For example:
    ```ruby
    config.webhooks = [{
      delivery_method: :pub_sub,
      topic: "orders/updated",
      path: "pubsub://my-gcp-project-id:my-gcp-pub-sub-topic-id",
    }]
    ```
2. spin up the application
    ```bash
    rails c
    ```

**Expected behavior:**

The pub sub event gets registered.

**Actual behavior:**

An error is raised

```bash
.rvm/gems/ruby-3.1.1/gems/shopify_app-20.1.1/lib/shopify_app/managers/webhooks_manager.rb:72:in `webhook_job_klass': uninitialized constant ShopifyApp::MissingWebhookJobError (NameError)

        webhook_job_klass_name(path).safe_constantize || raise(ShopifyApp::MissingWebhookJobError)
```

**Reproduces how often:**

Every time

Note that this does work fine for HTTP webhooks since the path corresponds to a webhook path and topic:
https://github.com/Shopify/shopify_app/blob/ed41165ca9598d2c9d514487365192f22b5eb096/lib/shopify_app/managers/webhooks_manager.rb#L49

### Browsers

N/A

### Gem versions

- _shopify_app_ `v20.1.0`
- _shopify_api_ `v11.1.0`
- _ruby_ `v3.1.1`
- _rails_ `v7.0.4`

**Comment by nelsonwittwer** [comment]
Thanks for reporting! This looks to be the same loading issue that is currently killing our pipelines periodically. We do have a fix for both of these issues that will go out during [our next release](https://github.com/Shopify/shopify_app/pull/1511) that will go out at the end of the month.

In the meantime, you can try pointing to that branch in your gemfile to see if that fixes it:

```ruby
gem "shopify_app", git: "git@github.com:Shopify/shopify_app.git", branch: "revert-1510-revert-1499-nelsonwittwer/dedicated_errors"

I'm going to close this issue as I think that will fix it. If it doesn't, feel free to reopen.

**Comment by kcamcam** [comment]
> Thanks for reporting! This looks to be the same loading issue that is currently killing our pipelines periodically. We do have a fix for both of these issues that will go out during [our next release](https://github.com/Shopify/shopify_app/pull/1511) that will go out at the end of the month.
> 
> 
> 
> In the meantime, you can try pointing to that branch in your gemfile to see if that fixes it:
> 
> 
> 
> ```ruby
> 
> gem "shopify_app", git: "git@github.com:Shopify/shopify_app.git", branch: "revert-1510-revert-1499-nelsonwittwer/dedicated_errors"
> 
> ```
> 
> 
> 
> I'm going to close this issue as I think that will fix it. If it doesn't, feel free to reopen. 

Thanks for the update.
