### ISSUE TITLE
Upgrade docs are inadequate

### ISSUE THREAD

**Issue by jagthedrummer** [Shopify/shopify_app#1526]
### Description

I'm trying to upgrade to v19, which seems to break almost everything, and the docs are completely inadequate. They basically say "lots of stuff moved to shopify_api, so go read that changelog" and that changelog basically says "we changed nearly everything, read the new library code and adjust your app accordingly".

### Steps to Reproduce

1. Have an app that works with v18
2. Upgrade to v19
3. 💥 

**Expected behavior:**

There should be docs that explicitly state which objects/methods have changed and it should suggest the new syntax to use.

**Actual behavior:**

Developers are left to fend for themselves.

**Reproduces how often:**

100%

### Browsers

N/A

### Gem versions

19

### Additional Information

Having been a Shopify app developer for 7+ years I find this to be extremely hostile to developers, and it makes me question whether our time enriching the Shopify ecosystem is appreciated by Shopify.

### Security

- [x] I have redacted any private information from my logs or code snippets.

**Comment by asecondwill** [comment]
Yikes!  now i dont want to update anything!

**Comment by matthewford** [comment]
+1 the docs are terrible

**Comment by slatem** [comment]
+1 - absolutely horrible experiencing updating from 18 -> 19+

**Comment by yogodoshi** [comment]
I had the same issue. I'm now trying to create a new app from scratch and moving the code over but I'm also having issues with this approach, even with a new app I'm getting errors that are difficult to debug like:

```
Processing by HomeController#index as HTML
Redirected to https://4ebe-2104-14d-5c59-4153-5c2-66ba-1ec3-1197.sa.ngrok.io/login
Filter chain halted as :check_shop_domain rendered or redirected
Completed 302 Found in 16ms (ActiveRecord: 0.0ms | Allocations: 1944)


  
TypeError (Passed `nil` into T.must):
  
sorbet-runtime (0.5.10626) lib/types/_types.rb:218:in `must'
shopify_api (12.2.1) lib/shopify_api/context.rb:157:in `host_scheme'
sorbet-runtime (0.5.10626) lib/types/private/methods/call_validation.rb:256:in `bind_call'
sorbet-runtime (0.5.10626) lib/types/private/methods/call_validation.rb:256:in `validate_call'
sorbet-runtime (0.5.10626) lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
shopify_app (21.2.0) lib/shopify_app/controller_concerns/frame_ancestors.rb:11:in `block (3 levels) in <module:FrameAncestors>'
actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:341:in `instance_exec'
actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:341:in `resolve_source'
actionpack (7.0.4) lib/action_dispatch/http/content_security_policy.rb:328:in `block in build_directive'
```

So I don't recommend this approach either.

**Comment by chrisedington** [comment]
I'm also having this problem - not sure how to proceed..

Same console output as @yogodoshi

**Comment by jagthedrummer** [comment]
Not stale, bot sucks.

**Comment by scart88** [comment]
This is a quick fix worked for us:

```ruby
# web/config/boot.rb
ENV["HOST"] = "https://#{ENV["HOST"]}" unless ENV["HOST"]&.match(%r{https?://})
```
