### ISSUE TITLE
Running the app from a sub-directory

### ISSUE THREAD

**Issue by ramananbalakrishnan** [Shopify/shopify_app#154]
Hi, 
I am trying to run my (non-embedded) app from a sub-directory, "/myapp" instead of "/" . 

#### issue
After following the instructions on [Rails guides](http://guides.rubyonrails.org/configuring.html#deploy-to-a-subdirectory-relative-url-root) and also modifying the deployment configurations, I noticed that this relative_url_root is not being respected in [`SessionsController`](https://github.com/Shopify/shopify_app/blob/22f73e1dbb5d10b1c67549bd51725119ab3f2cfb/lib/shopify_app/sessions_controller.rb) when redirecting a user who enters a shop_name in `/login`, 
i.e. the person is sent to "/auth/shopify?shop=test.myshopify.com"
instead of "/myapp/auth/shopify?shop=test.myshopify.com" 

#### possible fix
I am not sure if this issue is related to some earlier issues, but changing the redirect destination in [`SessionsController#authenticate`](https://github.com/Shopify/shopify_app/blob/22f73e1dbb5d10b1c67549bd51725119ab3f2cfb/lib/shopify_app/sessions_controller.rb#L38) from `"/auth/shopify?shop=#{shop_name}"` to 
`"#{main_app.root_url}auth/shopify?shop=#{shop_name}"` seems to fix the specific problem that I had faced. 

Not sure if it would break other parts though.

**Comment by kevinhughes27** [comment]
Nice find - yeah its tough to think through auth stuff. I think it will be fine, do you want to write up a PR and then we'll see if the test suite likes it.

In the meantime I would just overwrite that method in your app so you are not blocked by this.

**Comment by ramananbalakrishnan** [comment]
After an initial misstep, looks like my PR now passes the tests and also solves my problem. You can merge when suitable.

I have corrected my local version to fix things in the meantime
