### ISSUE TITLE
"Mount the Shopify App engine at nested routes" docs are out of date

### ISSUE THREAD

**Issue by asavageiv** [Shopify/shopify_app#1541]
### Description

[Mount the Shopify App engine at nested routes](https://github.com/Shopify/shopify_app/blob/main/docs/shopify_app/engine.md#mount-the-shopify-app-engine-at-nested-routes) is out of date. It mentions configuring OmniAuth initializers but omniauth is no longer included in the gem.

**Comment by netwire88** [comment]
Hi @asavageiv , there are a lot of documentation that's out of date (on GitHub and on Shopify.dev), I've discovered many. Should we create a new GitHub issue for each line or have a way to consolidate them all?

**Comment by asavageiv** [comment]
I think having specific issues is helpful because individual contributors may jump in and help on a specific issue, but a broad issue will be too overwhelming.

Now that I've looked at it for a while, I think I have figured out enough to update this page, for example.
