### ISSUE TITLE
"`setup': missing keyword: :host_name (ArgumentError)" on clean install

### ISSUE THREAD

**Issue by asavageiv** [Shopify/shopify_app#1542]
### Description

A clean shopify_app install currently fails with the error below on server start.

### Steps to Reproduce

Follow the quick start guide. Run `rails s`

**Expected behavior:**

Rails server starts

**Actual behavior:**

You get this error:
```
/Users/asavage/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/shopify_api-12.1.0/lib/shopify_api/context.rb:45:in `setup': missing keyword: :host_name (ArgumentError)
```

**Reproduces how often:**

100%

### Browsers

N/A

### Gem versions

shopify_app 21.1.0
shopify_api 12.1.0

### Additional Information

Likely caused by https://github.com/Shopify/shopify_app/pull/1518, as mentioned here: https://github.com/Shopify/shopify_app/pull/1518#discussion_r1000061445

**Comment by nelsonwittwer** [comment]
Thanks so much for reporting this! Apologizes I left that workflow out of my testing :( Patch is going out to fix today!
