### ISSUE TITLE
Get current shop with API

### ISSUE THREAD

**Issue by thierryskoda** [Shopify/shopify_app#156]
Hi, I'm currently using the Shopify-app gem with ruby on rails and i would like to know how can i get access to the current shop ? I know there is an API call like this : "ShopifyAPI::Shop.current" but this only works in my home_controller.rb. When i try to use get the current shop with this "ShopifyAPI::Shop.current" in an other controller. I receive the error =>  ArgumentError (Missing site URI):

Anyone have any idea why? I'm not sure to completely understand the patern .. :( 

Thank you very much

Thierry

**Comment by kevinhughes27** [comment]
If you add other controllers make sure they inherit from `AuthenticatedController` which will force the user to auth for that controller if they haven't already and then the shopify session will be set in a before action.

For the future this Repo is for code issues not questions, the correct place to post this would be the Shopify forums https://ecommerce.shopify.com/c/shopify-apis-and-technology
