### ISSUE TITLE
Authentication failure! csrf_detected

### ISSUE THREAD

**Issue by guillelopez** [Shopify/shopify_app#157]
Hi,

I am trying to build my first app, and everything works fine —I get into the app install page, the database adds the new store, and I get redirected to the app page inside the admin panel— but then I get an:

`ERROR -- omniauth: (shopify) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected`

Any idea from where that could be comming from?

I am using `ruby '2.2.1'` and `rails '4.2'`. Running in `localhost` using `thin` to have an `https` connection. My Callback URL is `http://test-shopify-app.dev:3000/auth/shopify/callback`.

Thanks in advance for your help. I have been stuck with this bug for a day, and I don't know what else to try...

<img width="1229" alt="screen shot 2015-08-18 at 12 32 11 pm" src="https://cloud.githubusercontent.com/assets/428680/9328007/325b55aa-45a5-11e5-899f-261627509af9.png">

**Comment by kevinhughes27** [comment]
Try putting your callback url as https. Also did you use the generator? There is some rails config required for using the ESDK that it takes care of

**Comment by guillelopez** [comment]
Thanks @kevinhughes27 for your quick reply. I changed to `https` but I am still having the same issue with the csrf. I also used the generator (`rails generate shopify_app`). Any other thing you might think it could be?

**Comment by kevinhughes27** [comment]
Is everything set properly on the app page in the partners area? I've never seen this before with the gem so I am not too sure

**Comment by guillelopez** [comment]
Yes, I think so:
<img width="1068" alt="screen shot 2015-08-18 at 11 08 48 pm" src="https://cloud.githubusercontent.com/assets/428680/9342790/28fba42a-45fe-11e5-832a-8ef74f1ffe94.png">
<img width="1042" alt="screen shot 2015-08-18 at 11 08 55 pm" src="https://cloud.githubusercontent.com/assets/428680/9342793/2c8bda88-45fe-11e5-97b3-83f5639d4288.png">

I think I am going to start the rails app from scratch again and see if it still happens.

**Comment by kevinhughes27** [comment]
there is a checkbox for using the ESDK - is that checked?

**Comment by guillelopez** [comment]
Yes:

<img width="907" alt="screen shot 2015-08-18 at 11 19 32 pm" src="https://cloud.githubusercontent.com/assets/428680/9343031/a1817914-45ff-11e5-8a10-016e9b975fc2.png">

**Comment by kevinhughes27** [comment]
hmm sorry I can't be more help!

**Comment by guillelopez** [comment]
Thanks anyhow. I will let you know if I figured it out.

**Comment by guillelopez** [comment]
I figured out my problem! I was using for both Application URL and Redirection URL: `https://test-shopify-app.dev:3000/auth/shopify/callback`. 

And it needs to be, for Application URL: `https://test-shopify-app.dev:3000` and for Redirection URL: `https://test-shopify-app.dev:3000/auth/shopify/callback`. 

That's it. I am closing this issue. Thanks @kevinhughes27 for your help.

**Comment by kevinhughes27** [comment]
I'm glad you got it figured out! getting all the auth stuff done is never fun!

**Comment by hirowatari** [comment]
Thanks @guillelopez for coming back and posting your solution.  Had the same issue today.
