### ISSUE TITLE
Typo in the directions for Shop model

### ISSUE THREAD

**Issue by Trimakas** [Shopify/shopify_app#158]
I am a pretty new dev.. and I'm actually sort of giddy I found this and fixed it!! My shop model wasn't working.. and I realized why!!  (I'm pretty sure atleast!)

This line in the shop model def self.retrieve(id) 
ShopifyAPI::Session.new(shop.domain, shop.token)

Should actually be:
ShopifyAPI::Session.new(shop.shopify_domain, shop.shopify_token)

**Comment by kevinhughes27** [comment]
do you mean this line: https://github.com/Shopify/shopify_app/blob/master/lib/generators/shopify_app/shop_model/templates/session_storage.rb#L12 it looks correct. How did you run the generator?

**Comment by Trimakas** [comment]
Quick question.. any setting I can update so that when I refresh the browser I don't have to sign in again? Seems like I'm killing the session somehow??

Ok, back to the issue:
Yes, but if you look at the Gem page here:
https://github.com/Shopify/shopify_app

and then go down to this section:
ShopifyApp::SessionRepository

it still has this..
class Shop < ActiveRecord::Base
  def self.store(session)
    shop = self.new(domain: session.url, token: session.token)
    shop.save!
    shop.id
  end

  def self.retrieve(id)
    if shop = self.where(id: id).first
      ShopifyAPI::Session.new(shop.domain, shop.token)
    end
  end
end

**Comment by kevinhughes27** [comment]
oh yeah I see its a readme issue. Technically you can have whatever you want for a shop model - the one we generate has the domain as shopify_domain. 

Yeah you're probably using the in memory session so thats why. If you generate the shop model and save you access token somewhere permanent than you won't have to login every time.

**Comment by kevinhughes27** [comment]
If you want to make a PR to update the readme I'll happily accept
