### ISSUE TITLE
Can't seem to find a way to switch credentials per store

### ISSUE THREAD

**Issue by matthewford** [Shopify/shopify_app#1592]
Hello, 

We're trying to migrate a private app installed in 6 plus stores for a client into 6 custom apps. However, I can't seem to find a way to dynamically load credentials per store, also to load the right creds per webhook.

**Comment by nelsonwittwer** [comment]
Hi @matthewford - It sounds like they are all using the webhook service to receive webhooks? They might all be running on the same backend service as well?

Assuming that is the case, I'd recommend looking at [the docs on webhooks](https://github.com/Shopify/shopify_app/blob/main/docs/shopify_app/webhooks.md) - specifically the namespacing. If you had a namespace per custom app that is how you'd know what app you work working with. Changing context to a store is done by using the 

It sounds like you are sending all 6 apps to the same webhook service? If that is the case, you use an [offline access token](https://shopify.dev/apps/auth/oauth/access-modes#offline-access) to get the context of a store.

It doesn't sound like this is a bug but more of a question on how to architect your apps. I'm going to close this issue hoping those tips help. I'd recommend reaching out to support if you need more detailed help :)
