### ISSUE TITLE
Redirects in the app mess with http/https

### ISSUE THREAD

**Issue by andrewromanenco** [Shopify/shopify_app#160]
cc @kevinhughes27 no sure if this is qualifies as an issue

Use case:
Run rails app on port 3000
Have stunnel running to map https port 8888 to http port 3000
Access application with url: https://localhost:8888
Result: application get redirected to http://localhost:8888/login (http->https)

Expected behaviour: if application was accessed via https, all redirects should let user to stay in https.

**Comment by kevinhughes27** [comment]
maybe? your setup is complicated. Can you find exactly where the app is re-directed and changing from https to http?

**Comment by andrewromanenco** [comment]
I'll get back to you, I am working on an app
tnx
