### ISSUE TITLE
Add some helpers for common operations

### ISSUE THREAD

**Issue by qq99** [Shopify/shopify_app#161]
I feel like I might have seen these before in the source, but maybe they were removed?
# In `application_helper`:

``` ruby
  def js_fullpage_redirect_to(title, url, options = {})
    link_to(title, "javascript: window.top.location.href = #{url.to_json}", options).html_safe
  end

  def js_new_window(title, url, options = {})
    link_to(title, "javascript: window.open(#{url.to_json})", options).html_safe
  end

```

`html_safe` above is dubious, but I'm throwing things together here.  These have the same signature as `link_to`

It mirrors the ruby method, but perhaps it should be called `js_link_to` or `easdk_link_to`?

You might use this kind of thing in the erb of your EASDK, e.g., you need to redirect someone to a 3rd party's Oauth page for integration between Shopify<->another.  Or you just want to bring people out-of-app, for whatever reason.  There's some overlap with https://docs.shopify.com/embedded-app-sdk/methods#redirect-path here
# In `application_controller`:

``` ruby
  def shop
    return unless shop_session.present?
    @shop ||= Shop.find_by(shopify_domain: shop_session.url)
  end
```

This is handy for having direct access to the model behind the current session.  I hope my memoization there hasn't opened up a sec.vuln. -- I'm pretty sure it's nil'd across requests, but now I'm doubting myself.

What do you think?

cc @kevinhughes27

**Comment by kevinhughes27** [comment]
I don't think those were ever in here but they look good to me.

As for the shop helper yeah we should probably have it - the weird thing about this repo is that it supports not persisting the shop model although I assume almost everyone does. But because of this it makes it hard to add helpers like this because they assume the shop model.

**Comment by qq99** [comment]
Ah good point! Not sure if it's worth writing the method to branch and check if `Shop` is defined, or just let the user see an exception if they try to use this

**Comment by kevinhughes27** [comment]
I often think it might be better if we were just more opinionated here and forced the shop model ...

**Comment by qq99** [comment]
that'd be so great :)

**Comment by kevinhughes27** [comment]
maybe for v7 we can look into that

**Comment by orenmazor** [comment]
> I often think it might be better if we were just more opinionated here and forced the shop model ...

:+1: opinionated

**Comment by kevinhughes27** [comment]
It'll be v8 now :p

**Comment by kevinhughes27** [comment]
We're working on version 8.0.0 in a branch so now is the time to push this stuff in. I'm not sure what the protocol for shipping helpers with an engine is so someone would need to look into that.

As for the current_shop helper it should use the SessionRepository object and return whatever the app has configured to store. That way we are still generic behind the scenes. I cleaned this configuration up a fair bit so I think its worth keeping now.

**Comment by sshaw** [comment]
Is this available yet? Been adding these helpers manually for years. Just started something new with 18.0.2 and docs don't mention anything. 

Looking at the source it seem that `ShopifyApp::Authenticated` gives `current_shopify_session` but I don't know if this is public even though it's `public`.  There's also `user_session`, `shop_session` —what's the difference, etc...

**Comment by nelsonwittwer** [comment]
Closing this as the API library and this app gem have evolved quite a bit since it was opened.
