### ISSUE TITLE
how to rename the sessions controller

### ISSUE THREAD

**Issue by mankind** [Shopify/shopify_app#162]
I have read through your documentation, stackoverflow questions and a little bit through the code in this gem but I can see how to rename the **session controller**.  I can see how to rename **shop model**  with   **ShopifyApp::SessionRepository.storage = 'Shop'** but what I want is to rename the **sessions controller**,  because I want to build a shopify app into an existing rails app and I already have a controller named sessions that handles authentication for users of my app.

I thought the **sessions controller** ought to be namespaced to the rails engine but the example app shows that what is copied to the app is not namespaced to the rails engine:

https://github.com/Shopify/embedded-app-example/blob/master/app/controllers/sessions_controller.rb

Also can I mount the route as shown here: 
https://github.com/Shopify/shopify_app/blob/master/lib/generators/shopify_app/install/install_generator.rb#L83-L86

This because the route in the example app pasted below will conflict with the route for my session:

       controller :sessions do
         get 'login' => :new, :as => :login
         post 'login' => :create, :as => :authenticate
         get 'auth/shopify/callback' => :callback
         get 'logout' => :destroy, :as => :logout
       end

Kindly advice on the best way to rename the sessions controller and the route that points to the session controller. will this work and will I need to add anything in the initializers for this to work besides changing the route:

    class ShopifySessionsController < ApplicationController
       include ShopifyApp::SessionsController
   end

**Comment by kevinhughes27** [comment]
You should be able to run the controllers generator which will copy the controllers to your host app and then rename the sessions controller how you like it. You might want to backup your current session controller of just git checkout on it after the generator runs. Then route to your new sessions controller.

This is a more complicated use case so the generator probably won't generate exactly what you want. If you run the full thing though and then don't mount the engine its all just regular rails code and you can do whatever you want with it.

**Comment by mankind** [comment]
thanks @kevinhughes27 for clarifying.
