### ISSUE TITLE
Use threadsafe ActiveResource

### ISSUE THREAD

**Issue by qq99** [Shopify/shopify_app#163]
I'm not sure if this has been addressed yet, but I ran into problems today because we weren't using the threadsafe version of AR. Sidekiq worker threads + ShopifyAPI without threadsafe gem = bad news

`gem 'activeresource', github: 'Shopify/activeresource', branch: 'threadsafe'`

I propose we add this as a dep somehow (deps flow down into the user of the gem, correct?), or add a note in the README strongly encouraging people to use this AR

cc @kevinhughes27

**Comment by kevinhughes27** [comment]
This gem doesn't specify a worker queue though so I don't know if we really require that in here. It sucks that you guys got hung up on this though.

What I would be okay with is if you added some code into this gem that did generate a proper sidekiq setup as an optional generator and then that generator could change the shopify_api include to be the threadsafe one.

**Comment by qq99** [comment]
That's fair @kevinhughes27 

I imagine sidekiq (or other non-threadsafe job runners) are pretty popular amongst `shopify_app` users though?  There's a small argument at least from that perspective to mention it in the README.  I don't have enough familiarity with non-Sidekiq job runners to know if they are threadsafe or not.

The real risk is showing/using data from Shop B when you were expecting it to be from Shop A (in the job), which is a pretty terrible unexpected behaviour if you're not aware.

Perhaps I should have made this issue in `shopify_api` itself?

**Comment by kevinhughes27** [comment]
yeah - slash is there any reason to not always use the threadsafe version? I would still like to see a sidekiq generator in here :p

**Comment by swalkinshaw** [comment]
I don't think is needed anymore. The latest/default version of this Gem pulls down activeresource 4.1 which is threadsafe. The Shopify fork of it is no longer needed.

**Comment by kevinhughes27** [comment]
👍
