### ISSUE TITLE
Fullpage redirect not working

### ISSUE THREAD

**Issue by vmatiyko** [Shopify/shopify_app#1637]
Some users encountered the fullpage redirect issue when making an application subscription. In this case, the browser does not matter, the fullpage redirect does not occur for specific users, but for some users, it works properly. This is what the page looks like when a user has an issue:

<img width="1293" alt="Screenshot 2023-01-06 at 18 33 55" src="https://user-images.githubusercontent.com/915929/211046426-81a9c93e-2505-47b2-bef6-6695d35e426f.png">

- `shopify_api` version: 9.5.1
- `shopify_app` version: 18.1.2
- App Bridge version: 2.0.5
- Ruby version: 2.6.10

Similar issue: https://github.com/Shopify/shopify_app/issues/1387
Also, we have the `host` in the URL and receive it in params.

Any help would be appreciated.

**Comment by vasaf** [comment]
My fix for now is by adding a `shopify_host` attribute to my `Shop` model and checking / setting it on initial load. Shopify states ["You should re-use the same App Bridge instance because the host parameter is only guaranteed on initial load of your app."](https://shopify.dev/apps/tools/app-bridge/getting-started/app-setup#initialize-shopify-app-bridge-in-your-app).

`splash_page_controller.rb`
```
class SplashPageController < ApplicationController
  include ShopifyApp::EmbeddedApp
  include ShopifyApp::EnsureInstalled
  include ShopifyApp::ShopAccessScopesVerification

  def index
    @shop_origin = current_shopify_domain
    if request.params.has_key?("host")
      host = Base64.urlsafe_decode64(request.params["host"])
      shop = Shop.find_by(shopify_domain: current_shopify_domain)
      unless shop.shopify_host == host
        shop.update_attribute(:shopify_host, host)
      end
    end
  end

end
```

`subscriptions_controller.rb`
```
unless current_shop.shopify_host.nil?
  params["host"] = Base64.urlsafe_encode64(current_shop.shopify_host, padding: false)
end
fullpage_redirect_to recurring_charge.confirmation_url
response.status = 303
```

I think if the host was retrievable using the API, that would be ideal. 🤷‍♂️

**Comment by khoimm92** [comment]
This works for me:
`params["host"] = Base64.urlsafe_encode64("admin.shopify.com/store/#{current_shopify_domain}", padding: false)
fullpage_redirect_to @recurring_application_charge.confirmation_url.to_s + '&host=' + params["host"]
response.status = 303
`

**Comment by jackculpan** [comment]
> This works for me: `params["host"] = Base64.urlsafe_encode64("admin.shopify.com/store/#{current_shopify_domain}", padding: false) fullpage_redirect_to @recurring_application_charge.confirmation_url.to_s + '&host=' + params["host"] response.status = 303 `

Thanks for this - was really hoping it would solve it for me but still no redirect to the confirmation url
