### ISSUE TITLE
no errors, no nothing!

### ISSUE THREAD

**Issue by tynichol** [Shopify/shopify_app#164]
I have followed the instruction well, and after installing the app it attempts to load and I get an error from the heroku app saying something has gone wrong. When I log it, I see no errors. Here is its below:

<code>at=info method=GET path="/favicon.ico" host=infinite-waters-2523.herokuapp.com request_id=fc00f56a-cd13-4200-abcd-ffc8e3a64c5b fwd="104.7.208.77" dyno=web.1 connect=0ms service=1ms status=304 bytes=48</code>

And that's all that is there. Please help!!!

**Comment by kevinhughes27** [comment]
I am going to need more details if I am going to help - what generator did you run? and is this on trying to auth or does the install page not even load?

**Comment by tynichol** [comment]
shop model generator. I click install and the embedded app begins to load. Then it says something went wrong. When I do a log trail, I get this now.

ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "shops" does not exist

**Comment by kevinhughes27** [comment]
you need to run migrate to update your heroku db. If this is a new project I would run all the generators so just `rails g shopify_app`

**Comment by derrickrc** [comment]
@kevinhughes27 I am new to Heroku and just deployed (after following their [instructions](https://devcenter.heroku.com/articles/sqlite3) on how to migrate from sqlite to pg) and am getting this same error at the OAuth callback step. How do I update my Heroku db? The same app is still working on ngrok / localhost. Thank you.
