### ISSUE TITLE
Missing ShopifyAPI resources

### ISSUE THREAD

**Issue by Romaaan3** [Shopify/shopify_app#1645]
# Issue summary

For some reason, I cannot access ShopifyAPI rest constants. When I open rails console and try to call it, it says that there is no such constant. 
Looks like it is partially loaded, but resources are missing.
And the same with all resources. What may be the reason?

- `shopify_api` version:  12.4.0
- `shopify_app` version:  21.4
- Ruby version: 3.2.0
- Operating system: Macos

```
ShopifyAPI::Shop
uninitialized constant ShopifyAPI::Shop (NameError)


ShopifyAPI.constants
[:Context,
 :Inflector,
 :Webhooks,
 :VERSION,
 :AdminVersions,
 :SUPPORTED_ADMIN_VERSIONS,
 :LATEST_SUPPORTED_ADMIN_VERSION,
 :Clients,
 :Auth,
 :Errors,
 :Rest,
 :Logger,
 :Theme,
 :Utils]
```

**Comment by flavio-b** [comment]
I got the same error when migrating to the newest `shopify_app` gem.

Make sure to run the console with all the environment variables used in `config/initializers/shopify_app.rb`, like `HOST` etc, so the API gets initialized correctly. If you use a Jetbrains IDE, they make it easier to manage these. Not sure about others.

**Comment by nelsonwittwer** [comment]
We might need to do a better job loading the api library from within the app gem. We will investigate.
