### ISSUE TITLE
config.redirect_uri setting ignored in authentication flow

### ISSUE THREAD

**Issue by lulessa** [Shopify/shopify_app#165]
1. In config/initializers/shopify_app.rb, set `config.redirect_uri` to any URL other than the standard https://myapp.example.com/auth/shopify/callback.
2. Submit a request to your app's /login route and watch your network logs' query string parameters.
3. The `redirect_uri` request param sent to the /admin/oauth/authorize endpoint is *always* equal to the /auth/shopify/callback route on the host and port where the app is running rather than the `config.redirect_uri` setting.

This is a corner case, for sure. Always submitting the /auth/shopify/callback route as the redirect_uri param may work just fine for your standard app setup, but when developing and using a different port for https vs http (#160), for example, it rears its ugly head.

The setting is there, but it has no effect. A search for `redirect_uri` in this repo shows ~~zero~~ evidence of the redirect_uri URL param being set during Shopify API's authentication flow. (Edit: It's in config/initializers/omniauth.rb)

It looks like `create_permission_url(scope, redirect_uri)` has to be called on the ShopifyAPI session at some point, as seen here:
https://github.com/Shopify/shopify_api/blob/4fb8f572136b9641157ecc177551e12744c27959/test/session_test.rb#L86

**Comment by kevinhughes27** [comment]
Its used here: https://github.com/Shopify/shopify_app/blob/master/lib/generators/shopify_app/install/templates/shopify_provider.rb#L5

Can you confirm that it is present in your generated shopify oauth provider? if you updated the gem and didn't add this yourself then it would be missing (the generators don't re-run on update)

**Comment by lulessa** [comment]
Yes, it is present in config/initializers/omniauth.rb. Here's the full file, unmodified since generation:
```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :shopify,
    ShopifyApp.configuration.api_key,
    ShopifyApp.configuration.secret,

    :redirect_uri => ShopifyApp.configuration.redirect_uri,

    :scope => ShopifyApp.configuration.scope
end
```
I started a new Rails app and ran `rails generate shopify_app` using shopify_app 6.2.0

**Comment by lulessa** [comment]
Take a look at https://github.com/Shopify/omniauth-shopify-oauth2/issues/29

They were getting the same message I was getting "Oauth error invalid_request: The redirect_uri is missing or invalid" — even though my `ShopifyApp.configuration.redirect_uri` matches what's set in the partner dashboard.

If I'm interpreting @dylanahsmith's closing reply on that issue, the redirect_uri must have the same scheme (and host?) as the request that redirects to shopify. Otherwise, you must add a `:callback_url` in `OmniAuth::Builder` with the full url matching the redirect_uri.

This gets it working to set the redirect_uri query param to the configuration.redirect_uri path:
```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :shopify,
    ShopifyApp.configuration.api_key,
    ShopifyApp.configuration.secret,

    :redirect_uri => ShopifyApp.configuration.redirect_uri,

    :callback_url => ShopifyApp.configuration.redirect_uri,

    :scope => ShopifyApp.configuration.scope
end
```
Without that `:callback_url` setting, however, the issue remains that `ShopifyApp.configuration.redirect_uri` gets ignored by the oauth authentication flow.

Now what? Do I make a pull request adding callback_url to the shopify_provider generator?

**Comment by kevinhughes27** [comment]
That sounds like a reasonable approach to me.

**Comment by uurcankaya** [comment]
I created a new app with 6.2 version of the gem, authentication seems to be working fine on local host, when replaced the link with heroku domains it worked as well on the same store (uninstalled and installed again), however when I tried to install the app on some other store it gave me  "Oauth error invalid_request: The redirect_uri is missing or not whitelisted" error, it gives the same error on the first store as well.

when I add  :callback_url => ShopifyApp.configuration.redirect_uri as explained above by @lulessa  to shopify_app.rb, error goes away, permission screen shows up, though then installation does not proceed and gives "invalid signature" error.

Am I missing something or is it related with this change? What do you guys think?

**Comment by lulessa** [comment]
This is a good chance to clarify: If the URL protocol/scheme (e.g., _https://_) and host (e.g., _example.herokuapp.com_) used through your app's entire installation process matches the App URLs set in your partner dashboard, then you don't need the modifications I outlined in this issue, at all.

@uurcankaya — Make sure the app API key and secret set on your Heroku app's config vars are matching your app's credentials in the Shopify partner dashboard and that the redirection URL also matches the app's auth endpoint (e.g., _https://example.herokuapp.com/auth/shopify/callback_). I actually tried your steps above as I was staging my app — switch app URL from localhost to heroku domains, install, uninstall, install different shop. It all worked fine for me.

**Comment by hosh** [comment]
I identified a similar problem and traced it to omniauth-oauth2 1.4.x. https://github.com/Shopify/omniauth-shopify-oauth2/issues/31

Version locking it in my Gemfile to omniauth-oauth2 1.3.x fixed it. If you guys are generating a new app, it is probably pulling 1.4.x.

**Comment by uurcankaya** [comment]
you got it right! It fixed it for me too

**Comment by hosh** [comment]
@uurcankaya :+1:

**Comment by kevinhughes27** [comment]
Thanks for the report! I am going to lock it in the gemfile and make a new release

**Comment by kevinhughes27** [comment]
I just tried with a fresh app that pulled down omniauth 1.4x and it worked fine for me

**Comment by hosh** [comment]
@kevinhughes27 if it isn't `omniauth-oauth2 1.4.x` then it is something. I know that I had it working. Then it broke. It was passing the `shop=domain` params back to redirect_uri, which the ShopifyAPI then rejects.. Then I version locked it back to 1.3.x and it works. Please try to reproduce this -- it's obviously broken for some people even if 1.4.x might not be the root cause.

**Comment by kevinhughes27** [comment]
For these auth type issues its very hard for me to reproduce - if I can't help out with a quick conversation then I think the best next steps are for the person with the issue to create a minimal github repo with the issue reproduced so I can take a look. Thanks.
