### ISSUE TITLE
shopify app deploy Invalid hook call

### ISSUE THREAD

**Issue by immakdas** [Shopify/shopify_app#1661]
# Issue summary

Have a successfully working and live app based on this repo. Recently Shopify forced us to [migrate](https://shopify.dev/docs/apps/tools/cli/migrate#step-3-add-shopify-cli-as-a-project-dependency) to from shopify cli v2 gem to _new node shopifyCli v3_ as well as shutdown Assets API to force migration to theme app extensions. Following the "migrate guides" catch up the bug. Looks like the shopify_app on RubyOnRails is not compatible with "new shopify way"
when I run
npm run deploy

got 
> shopify app deploy
  ERROR Invalid hook call.

I have one very simple theme-app extension without anything related to React or hooks.

- `shopify_api` version: 11.1.0
- `shopify_app` version: 20.0.2
- Ruby version: 3.0.1
- Operating system: ubuntu

```

```

## Expected behavior

Expected theme app extension block code pushed to shopify
```
<p>
 Hello World
</p>
{% schema %}
{
  "name": "Block",
  "target": "section",
  "class": "class",
  "available_if": "{{ app.metafields.myapp.global_enable }}",
  "stylesheet": "swiper-bundle.min.css",
  "javascript": "swiper-bundle.min.js",
  "settings": [
    {
      "type": "header",
      "content": " Block"
    },
    {
      "type": "paragraph",
      "content": "Please select appropriate Block"
    },
    {
      "type": "number",
      "id": "id_to_display",
      "label": "Please enter ID you want to display",
      "default": 1,
    },
    {
      "type": "checkbox",
      "id": "enable_fullwidth",
      "label": "Force fullwidth",
      "info": "Each theme",
      "default": false
    },
    {
      "type": "radio",
      "id": "logo_aligment",
      "label": "Logo alignment",
      "options": [
        {
          "value": "left",
          "label": "Left"
        },
        {
          "value": "centered",
          "label": "Centered"
        }
      ],
      "default": "left"
    }
  ]
}
{% endschema %}
```

## Actual behavior

Shopify cli v3 for an unknown reason check somewhere react hooks (wich I dont have in theme app extension)!?

## Steps to reproduce the problem

1. npm run deploy
![appdeploy](https://user-images.githubusercontent.com/58421407/222194782-98d3b71a-1dc4-45b3-83a0-eabe11a62a7f.jpg)

## Why shopify cli v3 not compatible with shopify_app gem?
I do not have any react code/ react hooks in the theme app extension!

**Comment by jmcilhargey** [comment]
I didn't dig completely into the Shopify CLI but I ran into this same error.. I see there is a `prerun` script that has dependencies on their React hook code from other Shopify libraries as part of CLI command execution. 

I'm baffled as to why, but to get this to work you need to have the specific file structure they outline in the CLI 3.X docs OR create a subdirectory within your project where you can store your extension / app code that needs to be built. It is what it is..

Generate the sample project and make sure you conform to the app structure and include TOML files.. 
https://shopify.dev/docs/apps/tools/cli/migrate
