### ISSUE TITLE
21.4.1 WOWOW OW! OW!

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1662]
I just updated to 21.4.1 and wow, is a lot of stuff broken now. Constant redirect (but App eventually installs), webhooks don't get initialized properly (so no nice automatic App/Uninstalls happening... 

Yikes.. I am not comfortable with this. Seems like I need to be ROLLING BACK to try and regain my sanity.. what the heck happened here? This App used to be pretty nice a few months ago...

**Comment by andrewle** [comment]
I just tried the exact steps from the README starting with `rails new` and could not get a working app to be installed in a dev store. There seems to be something very wrong
