### ISSUE TITLE
Google has deemed our app login page to be deceptive

### ISSUE THREAD

**Issue by Trimakas** [Shopify/shopify_app#1668]
# Issue summary
Our embedded app installs are being blocked by google now because of routes generated by the Gem. I was able to verify ownership of our app's domain hosted on Heroku. And they specifically list these URL's as being "deceptive"

https://sync-bytestand.herokuapp.com/login

Among others with session, HMAC and timestamps included in the URL
See this screenshot: https://nimb.ws/unM1gZ

- `shopify_api` version: 9.5.1
- `shopify_app` version: 18.0.3
- Ruby version:
- Operating system:

```
// Paste any relevant logs here
```

## Expected behavior

Users should be able to install our app from the Shopify app store.

## Actual behavior
Users cannot install our app from the app store because of Gem created routes

## Steps to reproduce the problem

1. try and install the SnapSync app from the app store and you'll get this: https://ostarasadventure.nimbusweb.me/share/8515769/b3p0s6xof8p1ywemy9mf
1.
1.

**Comment by Trimakas** [comment]
I tried switching our URL from one with heroku, to another domain. That worked for 2 days and now we are back in the same boat.

One of the links deemed suspect is `\login`

**Comment by Keemtaker** [comment]
I am facing the same issue and have no idea how to fix this

**Comment by Keemtaker** [comment]
What channels did you use to get Google to manually review your site ? I have made a request via the Google Search console but no response yet @Trimakas
