### ISSUE TITLE
Offline access token not refreshed if app uninstalled then reinstalled 

### ISSUE THREAD

**Issue by nickpith** [Shopify/shopify_app#1678]
# Issue summary

When an app has not setup webhooks to listen for the `app/uninstalled` event and is using online access tokens (i.e. user sessions), reinstalling the app on a shop the previously installed the app will no longer update the offline access token for the shop. The appears to be due to the fact that [the SessionsController#start_oauth](https://github.com/Shopify/shopify_app/blob/19739be9d9d14ebea216c03272ab6c1c14537e39/app/controllers/shopify_app/sessions_controller.rb#L63) is requesting an online access token because the [LoginProtection#user_session_expected?](https://github.com/Shopify/shopify_app/blob/19739be9d9d14ebea216c03272ab6c1c14537e39/lib/shopify_app/controller_concerns/login_protection.rb#L265-L269) is not checking if the session is still valid. It is only checking if the access scopes have changed. 

The JS package handles this by [checking if the offline token stored in the session is still valid](https://github.com/Shopify/shopify-app-js/blob/8c101837d6a741e9d8a08fa4aaa7d94d5741b2f3/packages/shopify-app-express/src/middlewares/ensure-installed-on-shop.ts#L52-L64) and if not will redirect to OAuth for a new offline token. It does look like prior to [this commit](https://github.com/Shopify/shopify_app/commit/efc0a28faa99a819b75e1de5a6233a017701292e#diff-803ce68328acb123cd75fa367146084814fe02a24e3bdb9734c21e263f3f5888L112-L117) a similar behavior was done to prevent this problem.

We have temporarily worked around this limitation by listening for a 401 response when attempting to use the offline token. If we get a 401 using `shopify_api` to make those calls, we will redirect to OAuth and obtain a new offline token. 

- `shopify_api` version: `12.4.0`
- `shopify_app` version: `21.4.1`
- Ruby version: 3.2.1
- Operating system: Mac / Linux

```
// Paste any relevant logs here
```

## Expected behavior

Whenever the app is reinstalled the OAuth process will always request a new offline access token. This way the access token for the shop is updated as part of the CallbackController.

## Actual behavior

Whenever the app is reinstalled without any access scope changes, the OAuth process will request an online access token instead of an offline access token.

## Steps to reproduce the problem

1. Setup an app without any webhooks that can delete shop sessions when the `app/uninstalled` event occurs
2. Install the app on a shop and note the access token stored for the shop session
3. Uninstall the app
4. Reinstall the app.
5. The shop session will not update the access token

**Comment by zernie** [comment]
we're having the same issue

https://github.com/Shopify/shopify_app/issues/1886 seems relevant
