### ISSUE TITLE
How to add app block in rails app?

### ISSUE THREAD

**Issue by hardik355** [Shopify/shopify_app#1694]
## Overview
 Does anyone know how to implement the Shopify app block in Rails? I read many blogs but I can't find any good docs.If anyone knows please share some details so it will help me a lot.

**Comment by Muttahhar** [comment]
Just in case you haven't already found the answer, here's what I know:
App blocks A.K.A theme app extensions can only be created through the Shopify CLI. You will need to add it to your application to be able to create app blocks. You can also use the Shopify CLI to create a new rails shopify app.

Link for information on Shopify CLI:
https://shopify.dev/docs/apps/tools/cli

The template which is used for generating a rails shopify app:
https://github.com/Shopify/shopify-app-template-ruby

Migration guide for upgrading your existing shopify app to Shopify CLI 3:
https://shopify.dev/docs/apps/tools/cli/migrate

Info about theme app extensions and how to create them:
https://shopify.dev/docs/apps/online-store/theme-app-extensions

P.S. I think you would get better and hopefully quicker responses for questions like these on the [Shopify Community forums](https://community.shopify.com/c/shopify-discussion/ct-p/shopify-discussion).

**Comment by hardik355** [comment]
Found the docs
