### ISSUE TITLE
/login Should Redirect if the User Is Already Logged In

### ISSUE THREAD

**Issue by sshaw** [Shopify/shopify_app#170]
Currently one can visit `/login` if they're already logged. I think it should redirect, the question is where? `main_app.root_path`?

**Comment by kevinhughes27** [comment]
You can change this in your app if you would like - if you redirect this url then it would be harder to install the app on 2 different shops since it would redirect the 2nd time.

**Comment by sshaw** [comment]
> You can change this in your app if you would like

Of course

> if you redirect this url then it would be harder to install the app on 2 different shops since it would redirect the 2nd time.

Ah got it.

**Comment by getshoplaunch** [comment]
@sshaw how can I configure it if I want to change default login_path to my install_path for example?
@kevinaln
