### ISSUE TITLE
HTTP 400... Can this be used for a custom app?   

### ISSUE THREAD

**Issue by porterbayne** [Shopify/shopify_app#1703]
# Issue summary
When I run my app, with or without the shopify_api gem installed, I hit localhost:3000 and enter my shopname, and click "Install". I the get a 400 error at this URL:

`https://worldspicemerchants.myshopify.com/admin/oauth/authorize?client_id=<client ID redacted>&scope=read_products%2Cread_content&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fshopify%2Fcallback&state=e7r1BEGsT8eOJ3S&grant_options%5B%5D=`

The error message is:
`Oauth error invalid_request: The redirect_uri and application url must have matching hosts`

I do have the host set in the .env file `HOST=http://localhost:3000`

And I am loading the page at `http://localhost:3000` and not 127.0.0.01...

- `shopify_api` version:  12.2.1
- `shopify_app` version: 21.2.0
- Ruby version:  3.0.3
- Operating system: MacOS 13.0.1 (Ventura)

**Comment by tarun-pacifica** [comment]
Hi @porterbayne I'm hitting the exact same issue, can you share how you resolved this? TIA

**Comment by porterbayne** [comment]
I never did. You can try some of the solutions people had here to see if it helps. 

https://github.com/Shopify/shopify-api-ruby/issues/911

A Shopify unlisted app may be an easier path. I have not tried that yet, we gave up!
