### ISSUE TITLE
Invalid API key or access token (unrecognized login or wrong password)

### ISSUE THREAD

**Issue by Uysim** [Shopify/shopify_app#1708]
# Issue summary
After omniauth success and `ShopifyApp::WebhooksManagerJob` execute then I got error response
```
 {"errors":"[API] Invalid API key or access token (unrecognized login or wrong password)", "error_reference":"If you report this error, please include this id: a050f299-40bb-4604-8c82-69c78c9645ed."}
```

- `shopify_api` version: 13.1.0
- `shopify_app` version: 21.6.0
- Ruby version: 3.0.4
- Operating system: MacOS for local development, Amazon Linux for production

## Expected behavior

Install webhook without any error

## Actual behavior

Raise error from `ShopifyApp::WebhooksManagerJob` 

## Steps to reproduce the problem

1. Install app with Test your app
2. Omniauth successfully 
3. The error raised

**Comment by nelsonwittwer** [comment]
I haven't been able to reproduce this issue with the latest version of this gem and the API. Do you have any other pointers to recreate this?

**Comment by nelsonwittwer** [comment]
I believe this is happening when 1) apps use user sessions and 2) the user sessions are expiring before the webhook jobs run. As @jagthedrummer pointed out, these jobs are getting retried and making the problem seem much worse.

The unfortunate part of this implementation is we queue these jobs for every oauth user login event. Depending on the size of your user base, this could be a super aggressive/expensive flow. Ideally this would be done on a cron basis to see if desired webhook subscriptions changed.

**Comment by Uysim** [comment]
@nelsonwittwer To me it seem the problem happen when I try to config both `shop_session_repository`. and `user_session_repository` since I need shop token for webhook installation and user info for user login. I still in stage of more debugging.
