### ISSUE TITLE
Sorbet host check fails

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1710]
# Issue summary

Installing a new app and the Sorbet is failing to find the host even though it is set. 

So what is the culprit here? ENV['HOST'] exists as https://something.herokuapp.com/ for the Shopify App context setup.

- `shopify_api` version:  12.5.0
- `shopify_app` version:   21.4.1
- Ruby version:  3.2
- Operating system:  *nix

```
// Paste any relevant logs here
```
Filter chain halted as :check_shop_known rendered or redirected
Completed 302 Found in 3ms (ActiveRecord: 0.7ms | Allocations: 753)
FATAL -- : [efae465b-28b7-4517-8731-1aa969182bf2]
TypeError (Passed nil into T.must):
sorbet-runtime (0.5.10827) lib/types/_types.rb:222:in must' shopify_api (12.5.0) lib/shopify_api/context.rb:175:in host_scheme'

## Expected behavior

App should install

## Actual behavior

errors out on Sorbet type check on host

**Comment by resistorsoftware** [comment]
For me this error only comes up if I accidentally add a trailing slash like my example above. That slash kills it. I removed the slash, it works.

**Comment by codev009** [comment]
Removing the trailing slash isn't working for me.

**Comment by resistorsoftware** [comment]
Are you using App Bridge 4? I think you can ignore host issues once you go with that. I no longer set any HOST in my localhost and it works fine with App Bridge 4.
