### ISSUE TITLE
Error on fresh installation: "[ ShopifyApp | WARN | Shop Not Found ] Invalid JWT token for current Shopify session"

### ISSUE THREAD

**Issue by felixding** [Shopify/shopify_app#1713]
# Issue summary

I've got the same error every time I tried to install the app on a new Rails app:

![Screen Shot 2023-08-14 at 8 47 10 AM](https://github.com/Shopify/shopify_app/assets/111456/bd7db6ea-aaa1-497b-8fa3-8c56e44ba398)

- `shopify_api` version: (I'm not sure)
- `shopify_app` version: 21.6.0
- Ruby version: 3.1.3
- Operating system: Asahi Linux (server) + Mac OS 12.6

```
Started GET "/products" for my_ip at 2023-08-13 23:28:46 +0000
Cannot render console from my_ip! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by ProductsController#index as */*
[ ShopifyApp | WARN | Shop Not Found ] Invalid JWT token for current Shopify session
[ ShopifyApp | WARN | Shop Not Found ] Invalid JWT token for current Shopify session
[ ShopifyApp | WARN | Shop Not Found ] Invalid JWT token for current Shopify session
Completed 401 Unauthorized in 3ms (ActiveRecord: 0.0ms | Allocations: 2637)
[ ShopifyApp | WARN | Shop Not Found ] Invalid JWT token for current Shopify session
[ ShopifyApp | INFO | Shop Not Found ] Installed store  -  deduced from user session
[ActiveJob] [ShopifyApp::WebhooksManagerJob] [31f2f0bc-904c-40b5-b4be-212b620c73fc] Performed ShopifyApp::WebhooksManagerJob (Job ID: 31f2f0bc-904c-40b5-b4be-212b620c73fc) from Async(default) in 2953.97ms
```

## Expected behavior

I assume the sample products would show?

## Actual behavior

The products doesn't load.

## Steps to reproduce the problem

I followed the exact steps on README, except:

1. I dockerized the Rails app
2. I use Cloudflare Tunnel so the `HOST` is something like `my-shopify-app.mydomain` in the `.env` and Shopify Partner dashboard
3. I use Postgresql and enabled the UUID extension
4. The Rails app is running on my Asahi Linux server, while I'm coding and testing on another Mac.

**Comment by sle-c** [comment]
Hi @betelgeus13 

Thank you for sharing your solution in this issue, as this is an OS clock sync issue with the JWT signing algorithm we won't be able solve it in this repo. Therefore, I'll close this issue.

Si Le
