### ISSUE TITLE
The app couldn’t be loaded

### ISSUE THREAD

**Issue by tayyab910629** [Shopify/shopify_app#1729]
# Issue summary

I am using rails 7, whenever i install then app i get this The app couldn’t be loaded , "This app can’t load due to an issue with browser cookies. Try enabling cookies in your browser, [switching to another browser]or contacting the developer to get support."

![image](https://github.com/Shopify/shopify_app/assets/21190055/223f3a68-713c-4123-b2f5-a14781d3b58d)

I am using Windows, but tried Ubuntu as well with the same error , Please let know if anyone have the solution

**Comment by TimFletcher** [comment]
We're on Rails 7 with the latest version of `shopify_app`. We also get this message on installation but a) only in development and b) the app actually installed just fine and can be used without issue. No issues in production.

**Comment by tayyab910629** [comment]
@TimFletcher Thank you for the response, i tried to upload to Heroku and got the same error, one thing is strange that i am able to install this from Brave browser even if its a develpment mode, I can install in brave browser only, all other browsers giving me the above error.

**Comment by tayyab910629** [comment]
I attempted several versions. Initially, I used the latest version, 21.7.0, with Rails 7, but it didn't work. I then tried it with version 6.1 and encountered the same issue. Eventually, I resolved the problem by using version 18 of the 'shopify_app' gem in conjunction with Rails 6.1, which proved successful. Also, I am indeed utilizing App Bridge.

**Comment by TimFletcher** [comment]
Our app started life in Jan 2023 using app bridge.

These were the deps back then:

```
# Ruby
shopify_app 21.3.1
rails 7.0.4

# JS
"@shopify/app": "3.21.0",
"@shopify/app-bridge": "^3.4.3",
"@shopify/app-bridge-react": "^3.4.3",
```

And today:

```
# Ruby
shopify_app 21.6.0
rails 7.0.4

# JS
"@shopify/app": "3.49.5"
"@shopify/app-bridge": "^3.7.9"
"@shopify/app-bridge-react": "^3.7.9"
```

IIRC this `The app couldn’t be loaded` issues has persisted through a couple of intermediate version upgrades too.

**Comment by nelsonwittwer** [comment]
Thanks for the context! Do you have any other tips on how to reproduce the error? That'll be the next step in zeroing in on the problem and providing a fix. I'll try and reproduce the issue with a fresh app install using our [ruby app template](https://github.com/Shopify/shopify-app-template-ruby) to see if I see anything, but if you have any other steps to reproduce the issue that'll be key in finding a fix.

**Comment by ziaulrehman40** [comment]
Following, same issue on a fresh install on newly created app(with old codebase which is upgraded and tested on another store with another app distro, working fine there).

And yes, app is there in the list, but when i open it i get a weird errors:
```
Access to XMLHttpRequest at 'https://SHOP.myshopify.com/admin/oauth/authorize?client_id=xxx&scope=xxxxxxxxx' (redirected from 'https://MY_APP_URL/api/v1/suppliers?shop=SHOP.myshopify.com') 
from origin 'https://MY_APP_URL' has been blocked by CORS policy: 
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by nelsonwittwer** [comment]
Using the latest version of the version of the [ruby app template](https://github.com/Shopify/shopify-app-template-ruby) that uses rails 7, I wasn't able to reproduce this issue. I'd recommend looking at the code base and validating your apps follow similar patterns and you have the correct API keys/secrets.

I'm going to close this issue, though if you have concrete steps to reproduce the issue feel free to re-open.

**Comment by TimFletcher** [comment]
I updated our app to Rails 7.1.1 (without any changes from the Rails 7 ruby app template) and this issue does, at least for me, seem resolved.
