### ISSUE TITLE
Does this gem support jobs for the manually created webhooks

### ISSUE THREAD

**Issue by zernie** [Shopify/shopify_app#1769]
## Overview

I really like how easily `shopify_app` allows me to set up jobs for the webhooks. I have an `order.created` webhook that I need to listen to for select users. For that, I'm gonna ask them to manually enter the webhook address via the admin dashboard since Shopify doesn't support dynamically requesting access scopes for some users.

Question: Will adding a new item to `config.webhooks` automatically prompt my app to request access scopes from all users? If the answer is yes, how can I skip it and make it work only for those users that manually entered the webhook address in the dashboard?

**Comment by lizkenyon** [comment]
Hi there 👋 

It seems like you figured it out with trial and error, but you can find more information on [handling access scope changes here](https://github.com/Shopify/shopify_app/blob/main/docs/shopify_app/handling-access-scopes-changes.md).

The library will not automatically add new scopes for you, but if you add a new scope to the `shopify_app` config it will handle asking the merchant to reauthorize.

**Comment by weizheheng** [comment]
Hi @zernie, did you manage to figure out how to add the "orders/create" webhook for selected users? I have the same use case but don't seem to figure out how to add it dynamically.

What I have tried:
1. Manually register the webhook using the shopify_api gem, the problem with this is it will raise the `NoWebhookHandler` as the registry is not "reloaded" I am assuming, as the registry only contains all the webhooks in `config.webhooks`
2. Adding "orders/create" to `config.webhooks`, but this will register the webhooks for all the users

**Comment by zernie** [comment]
@weizheheng we are just asking our users to add the webhook via an admin dashboard lol

**Comment by weizheheng** [comment]
> @weizheheng we are just asking our users to add the webhook via an admin dashboard lol

Ohh, okay, thanks man. I will see how to handle it! Thank you
