### ISSUE TITLE
[DOCS] Broken links for Generator documentation

### ISSUE THREAD

**Issue by dklassen** [Shopify/shopify_app#1782]
## Overview/summary

On https://github.com/Shopify/shopify_app/blob/main/docs/shopify_app/generators.md the links for "Shop-based token strategy" and "User-based token strategy" return a 404.

![Screen Shot 2024-01-23 at 2 22 07 PM](https://github.com/Shopify/shopify_app/assets/348219/a4d8725e-63bd-4d52-8853-8381191c9114)

**Comment by paulomarg** [comment]
Thanks for raising this issue, I set up a PR fixing the links.
