### ISSUE TITLE
Webhooks not being generated in client shops (Webhooks are not getting subscribed)

### ISSUE THREAD

**Issue by bilalahmad3013** [Shopify/shopify_app#1790]
I am working on a shopify rails app which is built upon Shopify CLI, in which i need multiple webhooks to be subscribed once I run the command "npm run dev -- --reset ,  I get the logs that webhooks are delivered.
17:13:15 │ webhooks     │ Sending APP_UNINSTALLED webhook to app server
17:13:19 │ webhooks     │ APP_UNINSTALLED webhook delivered
and once a mearchent installs my app the job given by the shopify "WebhooksManagerJob "  is running it means webhooks are configured.
[ActiveJob] Enqueued ShopifyApp::WebhooksManagerJob (Job ID: fb7f7917-5f2f-475c-beda-1544da344d23) to Sidekiq(default)
17:05:01 │ web-backend  │ Redirected to https://admin.shopify.com/store/bilaxxxxxxxxx/apps/7b0xxxxxxxxxxxxxxxxxxxxxxxxxd8127
17:05:01 │ web-backend  │ Completed 302 Found in 556ms (ActiveRecord: 5.1ms | Allocations: 8775)
17:05:01 │ web-backend  │ 
But I dont now why there are no webhooks are getting triggured not even app uninstalled.
I also called the  API given by the shopify https://bilxxxxxxxxxxxxxxx.myshopify.com/admin/api/2024-01/webhooks.json but the response is always coming out tobe a blank array.
{
  "webhooks": [ ]
} 
This is how my shopify_app.rb looks like   
config.webhooks = [
    { topic: "shop/update", path: "api/webhooks/shop_update" },
    { topic: "bulk_operations/finish", address: "api/webhooks/bulk_operations_finish" },
    { topic: "app/uninstalled", address: "api/webhooks/app_uninstalled" }
  ]
  add_privacy_webhooks
  ShopifyApp::WebhooksManager.add_registrations
  Please Help.

**Comment by lizkenyon** [comment]
Hi there 👋 

Unfortunately I was not able to reproduce this issue. Could you please correct my steps to reproduce or provide a repository that is able to reproduce the issue.

My testing was as follows: 

1. Create a new app using the ruby template (`npm init @shopify/app@latest -- --template=ruby`)
2. Install app on store
3. Verify webhook subscriptions were made
4. `npm dev -- --reset` 
5. Install app on new store
4. Verify that webhook subscriptions were made.

**Comment by bilalahmad3013** [comment]
@lizkenyon All these steps are correct this is exactly how we can subscribe to webhooks and if I am making new app with the commad (npm init @shopify/app@latest -- --template=ruby) everything are working fine I am getting my triggered webhooks but in my existing project after running command (npm run dev -- --reset), I get the logs my webhooks are delivered but none of them getting triggered.

**Comment by bilalahmad3013** [comment]
The thing is, when I ran the "npm run dev -- --reset" command, the logs showed the message "App uninstall webhooks delivered". But when a store installs my app, my webhooks are not being subscribed to in their shop. For example, when my app was installed in a store, the WebHookManager job ran and its logs also showed that it was performed. But if I call the API from that store to get the list of webhooks, it is blank. No webhooks are triggered when any activity happens in the shop, like shop/update or shop/install.
This is the log when i run command npm run dev -- --reset
17:13:15 │ webhooks │ Sending APP_UNINSTALLED webhook to app server
17:13:19 │ webhooks │ APP_UNINSTALLED webhook delivered.

This is the log when a shop install my app
[ActiveJob] Enqueued ShopifyApp::WebhooksManagerJob (Job ID: fb7f7917-5f2f-475c-beda-1544da344d23) to Sidekiq(default)
17:05:01 │ web-backend │ Redirected to

This is what i get when i called webhook.json API
{
"webhooks": [ ]
}
