### ISSUE TITLE
Embedded app not loading in incognito

### ISSUE THREAD

**Issue by sudharshan-tagalys** [Shopify/shopify_app#1831]
## Shopify app version:
  - `shopify_app` version: 18.1.3
  - Ruby version: 2.6.0
  - Operating system: Ubuntu

## Expected behavior

What do you think should happen?

- The embedded app should load in the incognito browser too.

## Actual behavior

What actually happens?
- The embedded app fails to load in the incognito browser, with the following errors in the browser console. Please find the following screenshot:
![image](https://github.com/Shopify/shopify_app/assets/104345194/a3b00968-c8fb-4c18-932c-9434443df276)

On further debugging through the shopify_app gem code, looks like the session[:shop_id] is nil and shopify_app is rendering the "request_storage_access.html.erb" which includes the "request_storage_access.js" file. This JS file is trying to access the sessionStorage and causing the code to crash as the third-party cookies are disabled in the incognito.

Other information:
ShopifyApp is configured to use `allow_cookie_authentication` and is set to `true`.

How can I resolve this issue?

**Comment by sudharshan-tagalys** [comment]
Hi,
I can use shopify_app 18.1.3 gem and still be able to transition to use session tokens(using `config.allow_jwt_authentication`) right?

**Comment by lizkenyon** [comment]
Yes you should be able to use session tokens. Take a look at the documentation [here](https://github.com/Shopify/shopify_app/blob/v18.1.3/docs/Troubleshooting.md#jwt-session-tokens)

**Comment by sle-c** [comment]
I recommend upgrading to v19.0 for better JWT session token support.
