### ISSUE TITLE
Broken `new embedded app authorization strategy` url

### ISSUE THREAD

**Issue by BaggioGiacomo** [Shopify/shopify_app#1846]
# Issue summary

On [this paragraph](https://github.com/Shopify/shopify_app/blob/main/docs/README.md#new-embedded-app-authorization-strategy) the `new embedded app authorization strategy` link redirects to a not found page since it doesn't exist a README.md in `/shopify_app/docs/README.md`.

The user should be redirected [here](https://github.com/Shopify/shopify_app/blob/main/README.md#new-embedded-app-authorization-strategy-token-exchange) instead

## Expected behavior

I except to be redirected to the README on the `New embedded app authorization strategy (Token Exchange)` paragraph

## Actual behavior

I'm being redirected to a Not found page

## Steps to reproduce the problem

1. Click on the `new embedded app authorization strategy` link on [this paragraph](https://github.com/Shopify/shopify_app/blob/main/docs/Upgrading.md#upgrading-to-v2220)

**Comment by sle-c** [comment]
PR opened for this issue https://github.com/Shopify/shopify_app/issues/1846
