### ISSUE TITLE
WebhooksController enable configuring shopify_hmac header

### ISSUE THREAD

**Issue by JArmando** [Shopify/shopify_app#186]
Currently shopify is sending the requests with the `hmac` in the `X_SHOPIFY_HMAC_SHA256` header and the WebhooksController module expects it to be in `HTTP_X_SHOPIFY_HMAC_SHA256`

If it was configurable thorugh the `shopify_app` initializer it would be easier to fix

**Comment by kevinhughes27** [comment]
I'm assuming you closed on purpose? This code was/is working for me so I believe we are grabbing the right header

**Comment by JArmando** [comment]
Yes it is working as expected. I was not understanding correctly the way
rails handles the headers. Thanks.

**Comment by kevinhughes27** [comment]
cool :+1:
