### ISSUE TITLE
Redirect Problem (redirect_to)

### ISSUE THREAD

**Issue by uurcankaya** [Shopify/shopify_app#187]
I was just trying to add a billing controller to a test the gem. It used to work with a filter like this:

Home Controller: 
```
before_filter :paid_shop?

def paid_shop?
  if  ##### Checking whether Recurring charge exist
    redirect_to billing_create_path  
  end
  end
```
Billing Controller: 
```
def create
    charge = ShopifyAPI::RecurringApplicationCharge.create(
      name: 'The Best Plan',
      price: 1.99,
      return_url: billing_confirm_url,
      trial_days: 2,
      test: Rails.env.development? || ENV['SHOPIFY_TEST']    )
    redirect_to charge.confirmation_url
  end

  def confirm
    begin

      ShopifyAPI::RecurringApplicationCharge.find(params[:charge_id]).activate

       redirect_to "/admin"  
   
    rescue
      redirect_to login_url, alert: "Sorry, but we're failed to charge your Shopify account."
    end
  end
```
Now redirection is not happening:

Screenshot: http://take.ms/bck7m

Logs give this error: 
```
Filter chain halted as :paid_shop? rendered or redirected

 302 Found in 324ms (ActiveRecord: 30.8ms)
```
What am I missing?

**Comment by uurcankaya** [comment]
could not get "redirect_to"  working for embedded apps in the controllers, achieved redirection with 

```
  ShopifyApp.redirect('destination_url_here');   
```

command in the header, in case anybody expriences the same problem

**Comment by kevinhughes27** [comment]
@uurcankaya this is because of the embedded app sdk trying to pull the link inside the shopify admin. If you need to link outside of the admin then use the fullpage_redirect_to helper instead and it will jump out of the esdk

https://github.com/Shopify/shopify_app/blob/7459ae0f3fb8a11daeb4490e34f93dff386a80ad/lib/shopify_app/controller.rb#L9

**Comment by uurcankaya** [comment]
alright! thanks!
