### ISSUE TITLE
Webhooks don't subscribe correctly

### ISSUE THREAD

**Issue by BaggioGiacomo** [Shopify/shopify_app#1871]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the package
  - `shopify_app` version: `22.2.1`
  - Ruby version: `3.3.0`
  - Operating system: `macOS Sonoma 14.5`
- [x] Set `log_level: :debug` [in my configuration](https://github.com/Shopify/shopify-api-ruby#setup-shopify-context), if applicable
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

I've added the `app/uninstalled` webhook using the generator provided by this gem: `rails g shopify_app:add_webhook --topic app/uninstalled --path webhooks/app_uninstalled`

Here's the config on the `shopify_app.rb` file: 
```ruby
config.webhooks = [
  { topic: "app/uninstalled", path: "webhooks/app_uninstalled" }
]
```

`app/jobs/app_uninstalled_job.rb` file has been created:
```ruby
class AppUninstalledJob < ActiveJob::Base
  extend ShopifyAPI::Webhooks::Handler

  class << self
    def handle(topic:, shop:, body:)
      perform_later(topic: topic, shop_domain: shop, webhook: body)
    end
  end

  def perform(topic:, shop_domain:, webhook:)
    shop = Shop.find_by(shopify_domain: shop_domain)

    if shop.nil?
      logger.error("#{self.class} failed: cannot find shop with domain '#{shop_domain}'")

      raise ActiveRecord::RecordNotFound, "Shop Not Found"
    end

    shop.destroy
  end
end
```

When I run the app and install it on one store, the webhook isn't added to the webhooks scription. If I run this GraphQL query, I get an empty array:

```graphql
query webhookSubscriptions{
  webhookSubscriptions(first: 20){
    nodes{
      id
      topic
      createdAt
    }
  }
}
```

## Expected behavior

I expect all the webhooks I have on the `config.webhooks` to be always subscribed.

## Actual behavior

Sometimes the webhooks are not subscribed

## Steps to reproduce the problem

1. Create a Shopify app
2. Add a webhook using the generator: `rails g shopify_app:add_webhook --topic app/uninstalled --path webhooks/app_uninstalled`
3. Run the app
4. Install it on your store
5. Check which webhook subscriptions you have using the graphQL query:
```graphql
query webhookSubscriptions{
  webhookSubscriptions(first: 20){
    nodes{
      id
      topic
      createdAt
    }
  }
}
```

## Logs
![image](https://github.com/Shopify/shopify_app/assets/58849430/7f988e7d-7c2a-4c53-8e43-744d8e8dda76)

## More context
- I've created my own shopify app template made with Rails + Hotwire
- I'm using `solid-queue` as queue adapter
- Job that installs webhooks is correctly enqueued and performed, but the webhook subscriptions array is still empty

**Comment by BaggioGiacomo** [comment]
Since none hasn't answered yet, I've taken a deeper look to the post authenticate task/webhooks installing process
This is what happens:

1. The default post authenticate task enqueue the `ShopifyApp::WebhooksManagerJob`
2. This job calls a method from the `ShopifyAPI` library -> `ShopifyAPI::Webhooks::Registry.register_all(session: session)`
3. The `register_all` method takes all topics on the `@registry` instance variable

My question is, who is actually populating the `@registry` variable? Isn't it empty?
I've seen that only the [`ShopifyApp::WebhooksManager.register_all`](https://github.com/Shopify/shopify_app/blob/59c5f1bdaba082a137a17ae34ac9386c83c7c799/lib/shopify_app/managers/webhooks_manager.rb#L41C11-L41C28) populates the `@registry` but this method is only called by `recreate_webhooks!` method

I hope to get an answer soon because the documentation doesn't explain this concept well and receiving support from the support team takes ages.

Thanks

**Comment by matteodepalo** [comment]
Hi @BaggioGiacomo, thank you for opening this issue, the team will take a look.

**Comment by BaggioGiacomo** [comment]
I've found the problem, I've deleted the `ShopifyApp::WebhooksManager.add_registrations` on the `shopify_app.rb` file
This is why the `@registry` variable was empty and no webhook were installed on install
