### ISSUE TITLE
EnsureAuthenticatedLinks not working?

### ISSUE THREAD

**Issue by netwire88** [Shopify/shopify_app#1872]
# Issue summary
The documentation for [EnsureAuthenticatedLinks](https://github.com/Shopify/shopify_app/blob/v21.4.0/docs/shopify_app/controller-concerns.md) is a bit unclear how to use it, or it could be a bug. When we enter a URL to the app, shopify_app redirects to `login_url`. The user then needs to enter their myshopify URL (which apparently Shopify app review team is not allowing anymore), and then when it redirects back to the app `return_to` is now nil. It was in `ShopifyApp::EnsureAuthenticatedLinks#redirect_to_splash_page` but not anymore

Before opening this issue, I have:

- [x] Upgraded to the latest version of the package
  - `shopify_app` version: 21.10.0
  - Ruby version: 3.2.2
  - Operating system: mac OS X
- [x] Set `log_level: :debug` [in my configuration](https://github.com/Shopify/shopify-api-ruby#setup-shopify-context), if applicable
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

## Expected behavior

1. Go to https://<app_url>/deep_link_url which implements `EnsureAuthenticatedLinks`
2. Should authenticate and redirect back to app with return_url = /deep_link_url

## Actual behavior

2. Redirect back to app with return_url = nil

**Comment by matteodepalo** [comment]
Hi @netwire88, thank you for opening this issue, the team will take a look.

**Comment by zzooeeyy** [comment]
hey @netwire88, what is your `/deep_link_url`? shopify_app redirects to the login page  if `shop` or `host` params isn't in the requested path.

**Comment by netwire88** [comment]
Thanks @zzooeeyy I think I figured it out. The deep_link_url cannot have /store/xxxx in it. Was this in the instructions somewhere? I think I missed it.
