### ISSUE TITLE
`debugger` does not work out of the box - any help appreciated

### ISSUE THREAD

**Issue by straversi** [Shopify/shopify_app#1879]
Hi, I'm using shopify_app out of the box (I just started yesterday) and I'm trying to start a `debugger` session in the `ProductsController`. As soon as the `debugger` is hit, the `shopify app dev` process exits.

Anyone have a suggestion on how to use debugger sessions with this app? Thank you in advance!

**Comment by paulomarg** [comment]
Hi, thanks for raising this. In order for us to see if there is something in the package that's breaking this, could you please clarify:

- Are you using the Shopify CLI to run the app?
- Are you using the Ruby app template?
- Could you share the code that's failing?
- Could you share the error message you get?

Thanks!
