### ISSUE TITLE
Embedded App, oAuth fails with iOS 

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#189]
When I click on an Embedded App Banner, using iOS 9 -> Safari, the oAuth with Shopify fails on csrf_detected for the strategy. Desktop versions of Chrome, Safari and Firefox all work perfect. Why would iOS have this issue? Is this that silly cookie issue with Safari? If so, how does Shopify not have million of Safari people screaming at them?

**Comment by kevinhughes27** [comment]
Can you elaborate on the cookie issue you referenced? Sounds like this might be an issue with the ESDK and not with this rails engine.

**Comment by resistorsoftware** [comment]
Most browsers allow third party cookies. In the oAuth flow, in the exchange of tokens etc, dealing with sessions, etc, there is usually also a need to write cookies. In this case, most browsers work well. However, Safari by default allows no third party cookies. Thus in any embedded App connection attempt, when exchanging tokens and dealing with the sessions, Safaro chokes and the result is an oAuth failure, labelled as CSRF_detected.

Only by setting Safari to allow cookies does the embedded App session get initialized properly.

**Comment by kevinhughes27** [comment]
Thanks for the details! So it does work if you set safari to allow cookies.

Sounds like this is not an issue with the engine and a generic issue with the ESDK auth process

**Comment by resistorsoftware** [comment]
It does work when Safari gets tweaked to allow cookies. Remarkable how many people use Safari and have to adjust to this tweak.

**Comment by meltingice** [comment]
Not to raise an old issue from the dead, but this is still happening to me almost 2 years later. I believe it's related to this behavior:

> Safari by default discards cookies set in an iframe unless the host that’s serving the iframe has set a cookie before, outside the iframe. Safari is the only browser that does this.

**Comment by kjschulz** [comment]
Same here...can this be possible that Safari users have to enable this in their preferences so use the embedded app sdk????

**Comment by jamiemtdwyer** [comment]
I'd say this is an issue with Safari rather than the gem.

**Comment by 0ptimusrhyme** [comment]
I'm going to close this issue in favour of #533 since it contains more information regarding this. Any further discussion on he latest version of the gem can be had there. What meltingice stated is true, Safari does discard cookies set from within an iframe. There are some workarounds noted in the newer issue for the time being.
