### ISSUE TITLE
`companies/update` webhooks not firing when a customer is added to the company

### ISSUE THREAD

**Issue by b-wall** [Shopify/shopify_app#1901]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the package
  - `shopify_app` version:
  - Ruby version:
  - Operating system:
- [x] Set `log_level: :debug` [in my configuration](https://github.com/Shopify/shopify-api-ruby#setup-shopify-context), if applicable
- [x] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API
  - If it is, please create a post in the [Shopify community forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or report it to [Shopify Partner Support](https://help.shopify.com/en/support/partners/org-select)

## Expected behavior

When  a customer is added to a company in the admin, the `companies/update` webhook should fire.

## Actual behavior

Currently, adding a customer does not fire a webhook

## Steps to reproduce the problem

1. Subscribe to the `companies/update` webhook.
2. Set up a server to listen for the webhook.
3. Create a company, adding the name of the company only.
4. Add a customer once the company is created.
5. Observe that the webhook does not fire.

**Comment by paulomarg** [comment]
Hi, just a couple of points to clarify before we investigate:

- Which packages are you using? `shopify-api`, remix, express?
- Are you using the `webhooks` configuration, or are you configuring them in your TOML file?

One thing worth noting is that webhook subscriptions are registered when the app is installed. I'd recommend uninstalling and reinstalling the app to refresh the subscriptions if you're not seeing the webhooks fire.

**Comment by b-wall** [comment]
Hey @paulomarg this was purely subscribing to the webhook via the REST API, nothing special. When I make a GET request to get all webhooks, I can see it there in the list.

On the server side, I have a Supabase edge function set up which console logs the request. This works fine for most edits to the company state (metafields, name, ID etc) but I don’t see anything when a staff member is added.

Is this working on your internal tests?

**Comment by paulomarg** [comment]
If there are other actions that trigger this event and your app is receiving it, it could be that there is a problem with the webhook itself. I'm going to raise this with the appropriate team!

**Comment by paulomarg** [comment]
I looked into it, and for new customers, you'd actually get the `company_contacts/create` event instead of `companies/update`. So you'd probably need to subscribe to that topic as well in your configs.

Hope this helps!

We only track bugs in this gem's code in this repo, so there's no action for us to take here. I'm going to go ahead and close the issue, but please feel free to open another if you have any issues with the gem itself!
