### ISSUE TITLE
What is auth/shopify?shop=aaa.myshopify.com doing?

### ISSUE THREAD

**Issue by ysyyork** [Shopify/shopify_app#192]
I find this part of code and I don't understand what is the path start with auth/shopify. I cannot see this path in routes. And when I use it with devise gem, it says cannot match this path. 

```
def authenticate
    if shop_name = sanitize_shop_param(params)
        fullpage_redirect_to "#{main_app.root_path}auth/shopify?shop=#{shop_name}"
    else
        redirect_to return_address
    end
end
```

**Comment by kevinhughes27** [comment]
all the shopify auth stuff is done using an `omniauth` provider which will create those routes. Have a look at omniauth to understand this. Does that answer your question?

**Comment by EiNSTeiN-** [comment]
Closing since this is probably not an actionable issue
