### ISSUE TITLE
Add support for 2024-10 API version

### ISSUE THREAD

**Issue by nurupoi** [Shopify/shopify_app#1921]
## Overview

Please add support for 2024-10 by bumping the `shopify_api` version.

As this is a regular task, may I suggest adding an internal TODO note to always bump the `shopify_api` dependency version in `shopify_app` after a new Shopify API version is supported in `shopify_api` when possible?

@lizkenyon is there a reason to not do this right after https://github.com/Shopify/shopify-api-ruby/pull/1340 (Oct 2)?

**Comment by lizkenyon** [comment]
Hi there 👋 

You should be able to run `bundle update shopify_app` to pull in the most recent version of `shopify_api`.

**Comment by remy727** [comment]
I can confirm that the latest version supports `2024-10`

```bash
[1] pry(main)> ShopifyAPI::AdminVersions::LATEST_SUPPORTED_ADMIN_VERSION
=> "2024-10"
```
