### ISSUE TITLE
redirect_uri not used correctly

### ISSUE THREAD

**Issue by JanC89** [Shopify/shopify_app#203]
I'm "merging" shopify_app into our existing Rails project.

To avoid routing conflicts, I'm using the following routes:
```ruby
scope :modules do
    scope :shopify do
      controller :shopify_sessions do
        get 'login' => :new, :as => :login
        post 'login' => :create, :as => :authenticate
        get 'auth/shopify/callback' => :callback
        get 'logout' => :destroy, :as => :logout
      end
    end
  end
```

This means that the login pages is accessible via `localhost:3000/modules/shopify/login`, and the callback from `localhost:3000/modules/shopify/auth/shopify/callback`

On the parther dashboard, the URL's are changed accordingly.

The problem is that when installing the app, OmniAuth (at least I think this is the module doing it), will not add the correct direct_uri to the URL. 

When installing, it will redirect to:
`https://mytestshop.myshopify.com/admin/oauth/authorize?client_id=<trimmed>&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fshopify%2Fcallback&response_type=code&scope=read_customers%2C+read_orders%2C+write_orders%2C+write_fulfillments&state=<trimmed>`

(decoded this becomes `http://localhost:3000/auth/shopify/callback`)

Shopify detects that this doesn't match with the URI specified in the parther dashboard, so it will give an error: Oauth error invalid_request: The redirect_uri is missing or not whitelisted

**omniauth.rb**
```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :shopify,
    ShopifyApp.configuration.api_key,
    ShopifyApp.configuration.secret,

    :scope => ShopifyApp.configuration.scope,
    :redirect_uri => ShopifyApp.configuration.redirect_uri,

    :setup => lambda {|env|
       params = Rack::Utils.parse_query(env['QUERY_STRING'])
       site_url = "https://#{params['shop']}"
       env['omniauth.strategy'].options[:client_options][:site] = site_url
    }
end
```

**shopify_app.rb**
```ruby
ShopifyApp.configure do |config|
  config.api_key = "mykey"
  config.secret = "mysecret"
  config.embedded_app = true
  config.scope = 'read_customers, read_orders, write_orders, write_fulfillments'
  config.redirect_uri = 'http://localhost:3000/modules/shopify/auth/shopify/callback'
end

```

I cannot tell if it is a bug, or a simple misconfiguration on my part.

**Comment by kevinhughes27** [comment]
Your routes will be affected because you put them in the scope but omniauth
defines it's routes on its own. You'll have to look into how to overwrite
those specifically.

**Comment by JanC89** [comment]
Oh, I see. 

But, shouldn't it use the `redirect_url` if it is specified?
I mean, wouldn't you otherwise always be forced to use `<domain>/auth/shopify/callback`as domain?

In other words, what would the preferred way of of achieving these custom URLs be?
I could of course just use the default URL, but I would prefer if I could use the above mentioned URLs.

**Comment by kevinhughes27** [comment]
I think (not 100% sure) that when you spec that redirect_uri that is just a param that gets sent along it doesn't actually affect where it redirects.

Omniauth does sort of force you with its urls. I'd check their docs and see if they mention how to override it.

**Comment by wnm** [comment]
Hey, I think omniauth-shopify-oauth2 expects an option called callback_url see https://github.com/Shopify/omniauth-shopify-oauth2/blob/d4f119be212a1e259e291621f07259e956accfff/lib/omniauth/strategies/shopify.rb#L114

so in **omniauth.rb**
it should be
`:callback_url => ShopifyApp.configuration.redirect_uri,`

**Comment by kevinhughes27** [comment]
That certainly looks like where the discrepancy could be coming from. I agree that it is weird that the callback url is generated automatically unless provided and then there is this separate concept of the redirect_uri which is just whitelisting the callback url

@EiNSTeiN- can you weigh in here please - there is lots of confusion around the redirect_uri

**Comment by EiNSTeiN-** [comment]
The URL you specify in your Shopify partner area needs to match exactly the one you give when redirecting to oauth. In omniauth, you can pass arbitrary parameters to the authorize step by [initializing the provider strategy](https://github.com/Shopify/shopify_app/blob/d5f3cb9bd9f906a9a414e1e78117c78b38a0ff4d/example/config/initializers/omniauth.rb) with a `authorize_params[:redirect_uri]` option. For example, something like `provider :shopify, authorize_params: { redirect_uri: ... }`. Note that I didn't test this, but it seems to be the correct way to pass in a redirect_uri param according to the base strategy [here](https://github.com/intridea/omniauth-oauth2/blob/26152673224aca5c3e918bcc83075dbb0659717f/lib/omniauth/strategies/oauth2.rb#L26).

However picking the correct callback url should be done for you, since Omniauth will automatically generate the `redirect_uri` parameter based on your callback route, so you don't need to worry about it unless you have a complex omniauth setup with multiple callback endpoints. In your case, it seems that Omniauth is not picking up the correct route for the callback, so most likely that's the source of your problem. 

Looking at [this code](https://github.com/intridea/omniauth/blob/32c4165919ab34189faa443cea66dfb11ba4fbff/lib/omniauth/strategy.rb#L383-L391) you need to give a callback_path option when you initialize the provider, like this: `OmniAuth.provider :shopify, callback_path: '/modules/shopify/auth/shopify/callback'` and Omniauth should then pick the correct redirect_uri for you.

Once you verify that Omniauth picks up the correct `redirect_uri` that matches what you want, the last point is to ensure that the uri is an exact match for one of the values you have configured in your Partner panel. In your case it should look like this:
<img width="802" alt="screen shot 2016-03-08 at 12 41 31 pm" src="https://cloud.githubusercontent.com/assets/2053039/13610321/210da8b8-e52b-11e5-9652-f56d998168a7.png">

You can configure multiple URLs there, so you can have one for your production environment, one for your staging environment, etc.

**Comment by kevinhughes27** [comment]
@EiNSTeiN- so are we handling redirect_uri properly for the common use case in ShopifyApp?

**Comment by EiNSTeiN-** [comment]
As far as I know we are @kevinhughes27

**Comment by kevinhughes27** [comment]
That was my understanding as well. It is a bit confusing for people especially anyone with a non default setup

**Comment by wnm** [comment]
hey guys, thanks for taking the time to look into this. I don't think it's handled properly in the current version of shopify_app, though. As far as I can tell from reading the code, the gem **omniauth-shopify-oauth2** is expecting an option called **callback_url**. not **redirect_uri**. https://github.com/Shopify/omniauth-shopify-oauth2/blob/master/lib/omniauth/strategies/shopify.rb#L18

There was a merge request a while back to include the callback_url option for the shopify_provider.rb template (see #166), but then it was removed again see https://github.com/Shopify/shopify_app/commit/ea5884c91d148e204ea787a2e6b48889a9666216

I tested it locally with shopify_app-6.4.2 and setting redirect_uri in omniauth.rb had no effect. This config worked however:
```
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :shopify,
    ShopifyApp.configuration.api_key,
    ShopifyApp.configuration.secret,
    :callback_url => ShopifyApp.configuration.redirect_uri,
    :scope => ShopifyApp.configuration.scope
end
```

**Comment by EiNSTeiN-** [comment]
> As far as I can tell from reading the code, the gem omniauth-shopify-oauth2 is expecting an option called callback_url. not redirect_uri.

You're right, as far as I know `redirect_uri` is not a valid provider option and never was, I'm not sure why it was added to `shopify_app`. I think `callback_path` is the proper way to replace the default `/auth/shopify/callback`.

**Comment by kevinhughes27** [comment]
It was added here https://github.com/Shopify/shopify_app/pull/152 and it was my understanding that we did need to pass this parameter along with the request as a url param or else Shopify would return an error to us. This is independent of the actual route afaik.

The callback url thing was a separate issue that we used the redirect uri to temporarily fix until upstream omniauth was fixed. @EiNSTeiN- does Shopify not validate that we send a param called redirect uri in the auth request?

**Comment by EiNSTeiN-** [comment]
> does Shopify not validate that we send a param called redirect uri in the auth request?

Yes, but that parameter is calculated based on the callback_url, so as far as I know passing that option to the omniauth strategy provider has no effect (I could be wrong).

**Comment by kevinhughes27** [comment]
@EiNSTeiN- found that omniauth looks like it is setting redirect_uri already: https://github.com/intridea/omniauth-oauth2/blob/26152673224aca5c3e918bcc83075dbb0659717f/lib/omniauth/strategies/oauth2.rb#L48

I'll run through some auth flows removing this param and see what I am able to determine

**Comment by MassMadankumar** [comment]
config/initializers/omniauth.rb:33: syntax error, unexpected end-of-input, expecting keyword_end (SyntaxError)

code:
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :shopify,
           ShopifyApp.configuration.api_key,
           ShopifyApp.configuration.secret,

           :callback_url => ShopifyApp.configuration.redirect_uri,
           :scope => ShopifyApp.configuration.scope

           #:redirect_uri => ShopifyApp.configuration.redirect_uri,
           #scope: ShopifyApp.configuration.scope,

          
           #:setup => lambda {|env| 
                #params = Rack::Utils.parse_query(env['QUERY_STRING'])
                #site_url = "https://#{params['shop']}"
                #env['omniauth.strategy'].options[:client_options][:site] = site_url


             #setup: lambda { |env|
             setup = lambda do |env| 
                   strategy = env['omniauth.strategy']
                   shopify_auth_params = strategy.session['shopify.omniauth_params']&.with_indifferent_access
                   shop = if shopify_auth_params.present?
                        "https://#{shopify_auth_params[:shop]}"
                    #else
                      #''
                    #end

                    strategy.options[:client_options][:site] = shop
           
         end
end

this syntax error?

**Comment by MassMadankumar** [comment]
/mnt/disks/brady/zapapp/zapstore/config/initializers/shopify_app.rb:5:in `block in <top (required)>': undefined method `redirect_uri=' for #<ShopifyApp::Configuration:0x0000557ee0dd2cc8> (NoMethodError)
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/shopify_app-8.2.4/lib/shopify_app/configuration.rb:70:in `configure'
        from /mnt/disks/brady/zapapp/zapstore/config/initializers/shopify_app.rb:1:in `<top (required)>'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:655:in `block in load_config_initializer'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications.rb:168:in `instrument'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:654:in `load_config_initializer'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:611:in `each'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/engine.rb:611:in `block in <class:Engine>'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `instance_exec'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:30:in `run'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:59:in `block in run_initializers'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `each'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:48:in `tsort_each_child'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:415:in `call'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `call'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/initializable.rb:58:in `run_initializers'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/application.rb:353:in `initialize!'
        from /mnt/disks/brady/zapapp/zapstore/config/environment.rb:5:in `<top (required)>'
        from config.ru:3:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
        from config.ru:in `new'
        from config.ru:in `<main>'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:319:in `build_app_and_options_from_config'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:219:in `app'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:24:in `app'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-2.0.3/lib/rack/server.rb:354:in `wrapped_app'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:80:in `log_to_stdout'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:42:in `start'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:135:in `block in perform'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `tap'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands/server/server_command.rb:130:in `perform'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command/base.rb:63:in `perform'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/command.rb:44:in `invoke'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
        from /mnt/disks/brady/zapapp/zapstore/bin/rails:9:in `require'
        from /mnt/disks/brady/zapapp/zapstore/bin/rails:9:in `<top (required)>'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
        from /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /mnt/disks/brady/zapapp/zapstore/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'

**Comment by kevinhughes27** [comment]
The `redirect_uri` configuration option has been deprecated for several versions.

**Comment by Snehal2509** [comment]
I am getting same error (Oauth error invalid_request: The redirect_uri is not whitelisted) in codeigniter. all thing try but not working.

anyone have idea about it?
