### ISSUE TITLE
Create ScriptTags automatically when shop is added to app 

### ISSUE THREAD

**Issue by redronin** [Shopify/shopify_app#209]
Similar to how the webhooks manager works, it would be nice to have ScriptTags created automatically once a shop is added to an app.

**Comment by kevinhughes27** [comment]
:+1: I'd also like to add fulfillment and carrier services in a similar way. PRs welcome!

**Comment by buggy** [comment]
You can already install Script Tags automatically by using a custom class that implements the SessionRepository (you specify the class in your config/shopify_session_respository.rb). I wrote an article about doing this a few days ago http://www.growingecommerce.com/handling-post-install-tasks-with-the-shopify-app-gem/

While PR #210 solves installing Script Tags post installation it doesn't help with any other scenarios. For example: The developer might not care about install Script Tags but instead want to synchronize Products and Customers. This is different from Webhooks as every application should be installing at least one webhook (the unsinstall webhook) during installation.

A better solution would allow the developer to configure an ActiveJob that is run post installation so the developer can install scripts, synchronize data or do anything else they require. The default could be nil to indicate that no post installation ActiveJob should be run (similar to now).

**Comment by redronin** [comment]
You could also just run an `after_create` callback on the shop model that would run whatever jobs you needed after.

For example, I'll need to sync products and orders of a shop, as well as set a theme partial. I think I'd probably just define a `post_install` method on my shop model and then in do a `after_create :post_install` or an `after_commit :post_install, on: :create`. Within that `post_install` I might do something like:
`
def post_install
  SynchronizeShopProductsJob.perform_later(self)
  SynchronizeShopOrdersJob.perform_later(self)
  InstallThemePartialJob.perform_later(self)
end
`

**Comment by kevinhughes27** [comment]
Thanks for sharing your post @buggy and you are right queuing a job in the SessionRepository is a good generic solution for tasks like this. In fact [shopify-sinatra-app](https://github.com/kevinhughes27/shopify-sinatra-app) has something like this. These specific managers are an even higher abstraction though and  I think it would be worth while to have all the basics covered with config and then leave the job option for really custom thing like synchronizing products like @redronin brings up. Using a callback on the shop model also works although for now ShopifyApp is not forcing the shop model on users so I'd like to keep this stuff separate from the model.

I'd be okay with a catch all after_install job configured from the initializer in addition to the full suite of specific managers for the basics (webhooks, services, scripttags)

**Comment by cefigueiredo** [comment]
@redronin the `after_create` solution is not a properly solution, because if some shop uninstall your app and in a future return and install it again, if you never deleted the shop from your database a `create` event will not be triggered, because your app will identify that there are already a registry for the shop by its `domain` and will just update its token.
So, depend only on `after_create` to install the scripttags is weak, and the ScriptTags will never be installed on a "returning" shop
