### ISSUE TITLE
Where is the token saved? Need it for Proxy to API calls

### ISSUE THREAD

**Issue by chwarnow** [Shopify/shopify_app#222]
Hello Guys,

It is awesome how fast one can start coding with the shopify_app. Good work!
Now what do I have to do to be able to make api calls from a proxy? I guess one has to set up a session for ShopifyAPI and provide the permanent api token. Where is it stored? As far as I understand it is retreived when installing the app. But how do I get it to start the session from the proxy controller?

Thanks

Chris

**Comment by kevinhughes27** [comment]
Technical answert - the token is saved on whichever object you have configured with the ShopifySessionRepository initializer.

Short answer - if you ran the default generator the token is stored on the Shop model that was configured for you.
