### ISSUE TITLE
Missing Webhooks Generator, Controller, etc.

### ISSUE THREAD

**Issue by joshreeves** [Shopify/shopify_app#229]
I was attempting to run the `shopify_app:add_webhook` generator and discovered that my installed gem does not contain the necessary code. The repository still appears to contain the code, but the releases and the published gem doesn't seem to have it. Wondering why this is the case. Thanks!

**Comment by kevinhughes27** [comment]
Yup the code has been merged but we haven't released the gem yet. If you want the latest code set bundler to use a github dependency. 7.0.0 should ship next week.
