### ISSUE TITLE
App during installation does not redirect me back to shopify

### ISSUE THREAD

**Issue by ssuperczynski** [Shopify/shopify_app#232]
I am redirect strict to my app without Shopify Iframe (without Shopify menu at left hand side), and from console.log I am getting&nbsp;
<blockquote>
<p>Failed to execute &#39;postMessage&#39; on &#39;DOMWindow&#39;: The target origin provided (&#39;https://shoptest.myshopify.com&#39;) does not match the recipient window&#39;s origin (&#39;https://846e6adb.ngrok.io&#39;).</p>
</blockquote>

<p>But when I click once again&nbsp;Apps -&gt; Installed -&gt; myapp i am redirecting correctly to Shopify with an iframe.</p>
<p><img alt="" src="http://i.imgur.com/4XjTKXA.png" style="height:319px; width:853px" /></p>

<p><img alt="" src="http://i.imgur.com/taT1YrI.png" style="height:580px; width:862px" /></p>

<p>As you see I am using ngrok https tunnel.</p>

How can I fix it?

This is my config on Shopify page:

<p><img alt="" src="http://i.imgur.com/SgYzIkn.png" style="height:516px; width:676px" /></p>

and this my config from `config/initializers/shopify_app.rb`

```ruby
ShopifyApp.configure do |config|
  config.api_key = "KEY"
  config.secret = "SECRET"
  config.redirect_uri = "https://846e6adb.ngrok.io/auth/shopify/callback"
  config.scope = "read_orders, read_products, read_themes, write_themes"
  config.embedded_app = true
end
```

**Comment by kevinhughes27** [comment]
How are you redirecting to your app the first time? (what url)

**Comment by ssuperczynski** [comment]
I actually didn't change anything from base template. This is my routing:

```ruby
Rails.application.routes.draw do
  
  controller :sessions do
    get 'login' => :new, :as => :login
    post 'login' => :create, :as => :authenticate
    get 'auth/shopify/callback' => :callback
    get 'logout' => :destroy, :as => :logout
  end

  # get 'home' => 'home#index'
  root :to => 'home#index'
```

**Comment by ssuperczynski** [comment]
Well I found it.
The problem is located in `app/views/layouts/embedded_app.html.erb`

```
    <script type="text/javascript">
      ShopifyApp.init({
        apiKey: "<%= ShopifyApp.configuration.api_key %>",
        shopOrigin: "<%= "https://#{ @shop_session.url }" if @shop_session %>",
        debug: <%= Rails.env.development? ? 'true' : 'false' %>,
        forceRedirect: true
      });
    </script>
```

`forceRedirect: true` should be `true` but by default is set to `false`

**Comment by kevinhughes27** [comment]
When did you generate your app? The default is true in the generator now.

**Comment by ssuperczynski** [comment]
Around two weeks ago

**Comment by kevinhughes27** [comment]
hmmm what version of ShopifyApp are you using?

**Comment by ssuperczynski** [comment]
Maybe it is stupid question, but how can I find it?

**Comment by kevinhughes27** [comment]
You can check your gemfile and see if it is specified directly there or you can check your gemfile lock. In a rails console you should also be able to type ShopifyApp::VERSION and it should print.

**Comment by ssuperczynski** [comment]
Thanks,

```
    shopify_api (4.0.7)
      activeresource
      rack
    shopify_app (6.4.2)
      omniauth-shopify-oauth2 (~> 1.1.11)
      rails (>= 4.2, < 5.0)
      shopify_api (~> 4.0.2)
    spring (1.6.4)
```

**Comment by kevinhughes27** [comment]
hmm interesting. Maybe I thought the default to true was in the latest release. It will be in v7 for sure!

**Comment by ssuperczynski** [comment]
thanks for your help in investigating

**Comment by kevinhughes27** [comment]
my pleasure!

**Comment by prasanthrubyist** [comment]
Thank you lot @ssuperczynski  , @kevinhughes27

**Comment by kevinhughes27** [comment]
you're welcome!

**Comment by prasanthrubyist** [comment]
I need one more help I'm new to shopify.....How can I get current shop domain url in my rails controller ? Can you help me...

**Comment by kevinhughes27** [comment]
If you ran the main generator then you will have a variable called current_shop available which is an instance of the Shop model. The Shop model has a field called shopify_domain.

**Comment by prasanthrubyist** [comment]
any examples please.....

**Comment by kevinhughes27** [comment]
Sorry the current_shop helper is not actually provided. But it looks like this:

```ruby
def current_shop
    return nil unless session[:shopify]
    @current_shop ||= Shop.find(session[:shopify])
  end
```

Then you can use `current_shop.shopify_domain`

The shopify_domain is also stored in the session: `session[:shopify_domain]`

**Comment by prasanthrubyist** [comment]
Hi @kevinhughes27 , I used above method to get shop url I'cant get, I tried 
@shop_name = ShopifyAPI::Shop.current.domain  in my controller, It's get shop domain, But my problem is if I login two shop in same browser, I not getting currently used shop, please help me correct me rignt way....Thanks

**Comment by prasanthrubyist** [comment]
I need another help, I completed my I want to set 'ShopifyAPI::RecurringApplicationCharge'. I don't have Idea how to set shopify billing API in rails application, So please help me..

**Comment by kevinhughes27** [comment]
I'd recommend emailing dev-support@shopify.com with that question since its not really related to this code per say.

As for your first question you can use the `shop` method in any controller that inherits from `ShopifyApp::AuthenticatedController`

**Comment by prasanthrubyist** [comment]
Thanks @kevinhughes27

**Comment by prasanthrubyist** [comment]
Hi @kevinhughes27 , How can I get  Carrier Service  API to return current shop name??

**Comment by kevinhughes27** [comment]
This isn't an issue with Shopify app. Can you ask your question on the forums or email dev-support@shopify.com

**Comment by prasanthrubyist** [comment]
okay thanks
