### ISSUE TITLE
Webhooks Controller

### ISSUE THREAD

**Issue by Mochaka** [Shopify/shopify_app#236]
Hey all,

I'm trying to create an app for Shopify, first time coding in Ruby let alone RoR.

I've generated my WebHooks controller etc. What do i do from here?

**Comment by kevinhughes27** [comment]
If you add the webhook you want to your ShopifyApp initializer then the webhook subscription will be created when the app is installed on a shop. When that webhook is triggered it will be sent to your app and the controller will receive it (provided your routes are setup properly for the address of the webhook you created). Then you can process the webhook and do whatever you need to do.

I am going to close this issue and direct you to the [Shopify api forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology) for general questions like this.
