### ISSUE TITLE
How can I do some action during app instalation

### ISSUE THREAD

**Issue by ssuperczynski** [Shopify/shopify_app#237]
Hey, 
this is not a bug, just a short question
How can I do some operations during first installation. I am not asking about scripttag (https://github.com/Shopify/shopify_app/issues/209)

But well, it might be connected. I'd like to ask user for some additional permissions ( another oAuth call to 3rd party application, send some POST message to register user etc..)
Now I am doing it in **HomeController** class in **index** method, which is not a good idea, because every time somebody enter `/` url those actions are executed

I see that there is no webhook when app is installed https://docs.shopify.com/api/reference/webhook
Any reason, why?

**Comment by ssuperczynski** [comment]
Well I probably answered my question by myself.
I am going to add some another filter in `authenticated_controller.rb`

```ruby
class AuthenticatedController < ApplicationController
  before_action :login_again_if_different_shop
  after_action: MY_CUSTOM_ACTION
  around_filter :shopify_session
  layout ShopifyApp.configuration.embedded_app? ? 'embedded_app' : 'application'
end
```

If you just could confirm, I am doing it right? ;) :beer:

**Comment by kevinhughes27** [comment]
Adding a before filter in the AuthenticatedController will run on every request to the shopify portion of your app. This doesn't sound like its what you want - you can avoid this by storing when this action is complete and then skipping this action conditionally. E.g  `return if shop.is_onboarded?`
