### ISSUE TITLE
config.scripttags not working in initializer

### ISSUE THREAD

**Issue by uurcankaya** [Shopify/shopify_app#238]
I generated a simple app with shopifyapp 7.0 and I was able to deploy it to Heroku succesfully.

Then configured webhooks as suggested with "config.webhooks", still deploys succesfully

However config.scripttags gives the following errror

` 

NoMethodError: undefined method `scripttags=' for #<ShopifyApp::Configuration:0x007f255baa2c60>
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/config/initializers/shopify_app.rb:9:in `block in <top (required)>'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/shopify_app-7.0.0/lib/shopify_app/configuration.rb:35:in `configure'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/config/initializers/shopify_app.rb:1:in `<top (required)>'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `block in load'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:268:in `load'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/notifications.rb:166:in `instrument'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/engine.rb:651:in `load_config_initializer'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/engine.rb:615:in `each'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `instance_exec'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:30:in `run'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:55:in `block in run_initializers'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:44:in `each'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:44:in `tsort_each_child'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/initializable.rb:54:in `run_initializers'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/application.rb:352:in `initialize!'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/config/environment.rb:5:in `<top (required)>'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/application.rb:328:in `require'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/application.rb:328:in `require_environment!'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/railties-4.2.5.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
remote:        /tmp/build_dbacae4684e430039b8b5341ae0b2960/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'`

`
The  code I used shopify_app.rb

`config.scripttags = [
    {event:'onload', src: 'https://myapp.herokuapp.com/myscript.js'}
  ]`

**Comment by kevinhughes27** [comment]
The code was just merged yesterday and isn't included in a released version
yet. If you need to use this code you can set your gemfile to pull the
github master dependency.

**Comment by uurcankaya** [comment]
I checked some docs but not really sure how to do that. If I add this to gem file will it pull it?

gem 'shopify_app', :git => "https://github.com/Shopify/shopify_app', :branch => 'master'

**Comment by kevinhughes27** [comment]
I think that will work. You can also use `github: 'shopify/shopify_app'`

**Comment by uurcankaya** [comment]
I tested this, it works great.

**Comment by kevinhughes27** [comment]
Its also been released now! (7.0.2)
