### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by onpaws** [Shopify/shopify_app#240]
Thanks for your efforts on this gem! Nice to have a great starting point here.

I’m trying to stand up my first Shopify app on Rails using shopify_app 7.0.0.

I can tell things are really close but am encountering a hard to diagnose issue, that only seems to affect when the app is hosted (e.g. on Heroku). However the Heroku app log doesn’t seem to display whatever the problem is. Checked the [forum](https://ecommerce.shopify.com/ecommerce/shopify_app) but didn't find anything that seemed to match.

Any pointers are most welcome!

### So far
I've:
- created a Shopify partner account
- created some fake products on a new [store](https://antipodean-fashion.myshopify.com/)
- created a new Rails 4 app
- added `shopify_app` to Gemfile & run `bundle`
- ran the generator with the corresponding api_key and secret
- deployed the app to [Heroku](https://antipodean-shopify.herokuapp.com)

![image](https://cloud.githubusercontent.com/assets/182515/13972236/401687b4-f06d-11e5-9557-df68f15460ee.png)

I enter the name of the store as depicted and click Login. 
However, then I get this:

![image](https://cloud.githubusercontent.com/assets/182515/13972238/48619fc6-f06d-11e5-8ebc-498145f8573f.png)

What I'm finding strange is that running the same code on `localhost:3000` (and updating the corresponding URLs on the store settings) appears to work.

Per @kevinhughes27 request over at #165 I've tried to create a minimal github [repo](https://github.com/onpaws/antipodean-shopify)

Here are the other details:
Rails 4.2.6
shopify_app 7.0.0
Chrome Canary, 51.0.2686.0 (latest or near-latest)
Mac OS X 10.11.3

**Comment by kevinhughes27** [comment]
Did you run rake db:migrate on heroku?

**Comment by onpaws** [comment]
@kevinhughes27 You sir are a gentleman and scholar! That sorted things out nicely. 

BTW, I see @peterjm has been working on ActiveResource 5 over on branch `experimental`. In the interest of helping the Rails 5 compat effort, is there a good place I could chat with whoever is working on that?

Closing this. Thanks Kevin!

**Comment by peterjm** [comment]
@onpaws feel free to ping me in the https://github.com/Shopify/shopify_api repo -- it might make sense to open a new issue, or you could jump onto https://github.com/Shopify/shopify_api/issues/194

**Comment by kevinhughes27** [comment]
@onpaws Glad I could help!
