### ISSUE TITLE
there is an error parsing 'gemfile': you cannot specify the same gem twice with diffrent version requirements.

### ISSUE THREAD

**Issue by NaliniMane** [Shopify/shopify_app#242]
I am getting this error after modifying gemfile.

there is an error parsing 'gemfile': you cannot specify the same gem twice with diffrent version requirements.
you specified: rails (=7.0.0) and rails (=4.2.6). Bundler cannot continue.

**Comment by kevinhughes27** [comment]
Can you past your Gemfile please

**Comment by NaliniMane** [comment]
source 'https://rubygems.org'

gem 'shopify_app', '7.0.1'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
"gem 'shopify_app'"

**Comment by NaliniMane** [comment]
source 'https://rubygems.org'

gem 'shopify_app', '7.0.1'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
"gem 'shopify_app'"

**Comment by NaliniMane** [comment]
source 'https://rubygems.org'

gem 'shopify_app', '7.0.1'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.15'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
"gem 'shopify_app'" 
``

**Comment by NaliniMane** [comment]
this bold lines are comments.

**Comment by kevinhughes27** [comment]
why is shopify_app in there twice? also when posting code snippets please put inside the ``` fences so its readable. 

This looks like s legit error in your gemfile and nothing related to Shopify App

**Comment by NaliniMane** [comment]
sorry I didn't know about ``` fences 

source 'https://rubygems.org'

'# Bundle edge Rails instead: gem 'rails', github: 'rails/rails''
gem 'rails', '4.2.6'
'# Use sqlite3 as the database for Active Record'
gem 'sqlite3'
'# Use SCSS for stylesheets'
gem 'sass-rails', '~> 5.0'
'# Use Uglifier as compressor for JavaScript assets'
gem 'uglifier', '>= 1.3.0'
'# Use CoffeeScript for .coffee assets and views'
gem 'coffee-rails', '~> 4.1.0'
'# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library'
gem 'jquery-rails'
'# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks'
gem 'turbolinks'
'# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder'
gem 'jbuilder', '~> 2.0'
'# bundle exec rake doc:rails generates the API under doc/api.'
gem 'sdoc', '~> 0.4.0', group: :doc

'# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development'

group :development, :test do
 ' # Call 'byebug' anywhere in the code to stop execution and get a debugger console''
  gem 'byebug'
end

group :development do
'  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
end

'# Windows does not include zoneinfo files, so bundle the tzinfo-data gem'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

**Comment by kevinhughes27** [comment]
I updated your comment - the fences go around the entire code block one at the top and the other at the bottom. Then it looks like it does now
