### ISSUE TITLE
Issue with generator

### ISSUE THREAD

**Issue by NaliniMane** [Shopify/shopify_app#244]
Please check my issue in attached file.
![errror](https://cloud.githubusercontent.com/assets/12440064/14228250/44bb5b32-f92d-11e5-84f0-d0a89892af40.png)

**Comment by kevinhughes27** [comment]
This error is because ShopifyApp is not part of your gemfile or you aren't running the command with bundler. Try bundle exec rails ...

This is not an issue with this gem.
