### ISSUE TITLE
Uninstall app, re-install again redirects without oauth

### ISSUE THREAD

**Issue by quocble** [Shopify/shopify_app#245]
I'm so stumped on this issue.  I got rejected from the beta approval and really want to get this in. I appreciate anyone can help.

Steps to reproduce
---------------------------
1. Install app
2. Remove app
3. Install app again

Expected: Send to "Install app" prompt screen
Result: The default /login with the input box

If I re-install again, then it shows properly.  It happens exactly once after the app is removed.

Gem: ShopApp 6.4.2

Logs
-------------------------

From the logs, you can clearly see the request shows shopify_domain, redirected, and the domain gets lost.

```
Started GET "/main?hmac=d65d07d6ae0fb25d1b89c5aa2ea7afdeaea2c338a25800ede276679dc3c14437&shop=teststorequoc.myshopify.com&signature=ff49dfcd7a0e7df52bface23eefa2221&timestamp=1459878395" for 12.251.228.138 at 2016-04-05 17:17:54 -0700
Cannot render console from 12.251.228.138! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by HomeController#index as HTML
  Parameters: {"hmac"=>"d65d07d6ae0fb25d1b89c5aa2ea7afdeaea2c338a25800ede276679dc3c14437", "shop"=>"teststorequoc.myshopify.com", "signature"=>"ff49dfcd7a0e7df52bface23eefa2221", "timestamp"=>"1459878395"}
  Shop Load (0.2ms)  SELECT  "shops".* FROM "shops" WHERE "shops"."id" = $1 LIMIT 1  [["id", 4]]
  Shop Load (0.2ms)  SELECT  "shops".* FROM "shops" WHERE "shops"."shopify_domain" = $1 LIMIT 1  [["shopify_domain", "teststorequoc.myshopify.com"]]
Redirected to https://b4d3b2af.ngrok.io/login
Completed 302 Found in 448ms (ActiveRecord: 0.5ms)

Started GET "/login" for 12.251.228.138 at 2016-04-05 17:17:54 -0700
Cannot render console from 12.251.228.138! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by SessionsController#new as HTML
  Rendered sessions/new.html.erb within layouts/application (0.1ms)
Completed 200 OK in 117ms (Views: 116.5ms | ActiveRecord: 0.0ms)
```

**Comment by kevinhughes27** [comment]
Sounds like a session issue. If you clear cookies in between does it work as expected?

**Comment by quocble** [comment]
Yes.  How do suggest to fix this in the code? I believe I use standard boilerplate code..

**Comment by kevinhughes27** [comment]
Are you using the embedded app sdk? I am pretty sure thats just how it works. Let me follow up with the apps team.

**Comment by quocble** [comment]
I'm using embedded app sdk. Thanks.

**Comment by forsbergplustwo** [comment]
Hey Guys,

I had a similar issue on one of my apps, and the fix was to make sure the link to your app in the Partner Dashboard is pointing at your /login url of the app.

Sounds like the ?shop= param is not being passed along on the redirect.

Would be great to know the ultimate cause, but at least this can be used as a workaround.

Ps. I'm not a Shopify employee, just another app developer ;)

**Comment by kevinhughes27** [comment]
We're looking into it! I want approval to be smooth if you use ShopifyApp.

**Comment by kevinhughes27** [comment]
@ShayneP any update here?

**Comment by uurcankaya** [comment]
any update on this :) ?
