### ISSUE TITLE
undefined method `variable_size_secure_compare' after rails destroy

### ISSUE THREAD

**Issue by Trimakas** [Shopify/shopify_app#250]
I get this error now after I removed the controller, and lines in the initializer and then ran

rails destroy shopify_app:add_webhook #and then my topic and address..

the POST is still going to: ShopifyApp::WebhooksController#receive even though I deleted it, and that's not the address I provided..

How can I get rid of this??

Thanks

**Comment by kevinhughes27** [comment]
I need more information about this issue - which controller did you remove and what did you remove from the initializer? It sounds like you removed the webhooks controller and the webhook config.

rails destroy shopify_app is not a command so it won't do anything. If the app created a webhook on Shopify then you need to deleted the webhook using an api call to delete that webhook. Changing you config won't affect data already persisted to Shopify thats why you are still getting the POST.

If you uninstall the app from the Shop then shopify will delete all its webhooks and you can start again.

**Comment by Trimakas** [comment]
Thanks for getting back.. I'm just trying to remove any configurations the engine installed into my code.. Nothing to do with the app in a store.. I continue to get this undefined method error 
"variable_size_secure_compare" and I just need to kill/destroy/delete anything to do with the gem and webhooks within my Ruby code.. Including this route shopify_app/webhooks#receive

**Comment by kevinhughes27** [comment]
So remove the gem and reset your source control?
