### ISSUE TITLE
Webhook controller only works with Rails 4.2.6

### ISSUE THREAD

**Issue by Trimakas** [Shopify/shopify_app#251]
After 2 days of troubleshooting I realized that this method:
'variable_size_secure_compare' for ActiveSupport::SecurityUtils:Module

Only works with Rails 4.2.6, and it not available in 4.2.5.

After upgrading my version of rails I no longer get a NoMethodError.

Might want to let folks know.

Thanks
Todd

**Comment by kevinhughes27** [comment]
@Hammadk can you bump our gemspec please.

**Comment by kevinhughes27** [comment]
Thanks @Hammadk ✨
