### ISSUE TITLE
Embedded App Headers 

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#254]
I am trying to ensure a subscription exists for an App. A before_action method call detects and sets that all up. A redirect_to charge.confirmation_url executes. Log fills with redirect notification. However the Chrome JS console tells me another story. The old X-FRAME-ORIGIN set to DENY ??

In Rails I see the action dispatch blurb about deleting this header key... so what gives?

I am not sure how to redirect from within the App to the confirmation charge_url, outside the App if this header is deleted but still present? Any hot tips on how to ensure this header key is actually not rendered?

Log from server look OK:

    Processing by HomeController#index as HTML
    Started GET "/?hmac=bfcecf1d38c08eb31cb53022aaafbfdf03ff7629bf24baa3bfd7a95c58aa63fc&protocol=https%3A%2F%2F&routing_method=shop_from_host&shop=fizzbuzz.myshopify.com&signature=8d070ac23517d6eeb96434f72bade3e4&timestamp=1462467757" for 67.70.27.77 at 2016-05-05 17:02:38 +0000
    Parameters: {"hmac"=>"bfcecf1d38c08eb31cb53022aaafbfdf03ff7629bf24baa3bfd7a95c58aa63fc", "protocol"=>"https://", "routing_method"=>"shop_from_host", "shop"=>"fizzbuzz.myshopify.com", "signature"=>"8d070ac23517d6eeb96434f72bade3e4", "timestamp"=>"1462467757"}
    Shop has NO subscription, so we make one up now and redirect to it
    Shop Load (1.1ms)  SELECT  "shops".* FROM "shops" WHERE "shops"."id" = $1 LIMIT 1  [["id", 1]]
    Inside the require_subscription check
    at=info method=GET path="/?hmac=bfcecf1d38c08eb31cb53022aaafbfdf03ff7629bf24baa3bfd7a95c58aa63fc&protocol=https%3A%2F%2F&routing_method=shop_from_host&shop=fizzbuzz.myshopify.com&signature=8d070ac23517d6eeb96434f72bade3e4&timestamp=1462467757" host=dave-o-shopify.herokuapp.com request_id=4fffe751-edbb-433a-bc53-dabbdc47e153 fwd="67.70.27.77" dyno=web.1 connect=1ms service=597ms status=302 bytes=1168
    Filter chain halted as :require_subscription rendered or redirected
    Redirected to https://fizzbuzz.myshopify.com/admin/charges/2201263/confirm_recurring_application_charge?signature=BAhpA6%2BWIQ%3D%3D--3f0582a06dda278ce4b07555612bb1cf20f54f74
    Completed 302 Found in 555ms (ActiveRecord: 6.6ms)

**Comment by kevinhughes27** [comment]
I think you need to use the `fullpage_redirect_to` function which loads a tiny partial and then uses javascript to jump out of the ESDK. This is already used for the authentication flow. The helper it here https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/login_protection.rb#L80.

Is there somewhere in the docs that we should mention this?

**Comment by resistorsoftware** [comment]
Thanks... I missed that since in Sinatra, I only do the JS escape once to get into the embedded App, and from within the App, I never redirect back out like in the Rails App... not sure how to express it any better than you already did.

**Comment by kevinhughes27** [comment]
Cool. I'll let you close the issue after you get this working to confirm.

I was more just wondering if you were following docs elsewhere where we could mention this.
