### ISSUE TITLE
changing html / css for login screen

### ISSUE THREAD

**Issue by uurcankaya** [Shopify/shopify_app#255]
this can be a stupid question but how can we modify the login screen? Generator does not create any views for it so where do we do that?

**Comment by kevinhughes27** [comment]
The way engines work is that if you supply your own version of a file that the engine provides your app's version takes precedence thus letting you override it.

If you run `rails g shopify_app:views` (the views generator) then it will copy this view from the engine to your app so you can get started overriding it.

**Comment by uurcankaya** [comment]
it generated 

app/views/shopify_app/sessions/new.html.erb

why another "shopify_app" folder? Is there a specific reason?

**Comment by kevinhughes27** [comment]
Thats just how isolated engines work (devise for example is the same way). If the extra folder bugs you you can override the sessions controller and override the view path but its probably not worth it.

**Comment by uurcankaya** [comment]
thanks!  yes not really worth the time :)

**Comment by polyrhythmm** [comment]
I'm using

$ mount ShopifyApp::Engine, at: '/nested'

and I'm getting 

mount: too many arguments

any ideas?
