### ISSUE TITLE
WebHooksManager create problem

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#257]
The documentation shows that in the application.rb one can add a webhook that the shopify_app will manage. The problem is the example in the docs does not include the format. Without a format key, the App fails with CreationFailed error. 

The reason is the reverse_merge! on the attributes looking for the format key probably bums out, and hence the failure. Perhaps a better flow would be to not freak out if the format key is missing, and use the default of JSON? Or add the format to the docs so that others do not get burned by a failure to create a webhook.

**Comment by kevinhughes27** [comment]
I think we should just default to json.

**Comment by kevinhughes27** [comment]
> The reason is the reverse_merge! on the attributes looking for the format key probably bums out

Are you sure this happening?

I was looking into fixing this but looking at the test suite it looks like its already working the way I expect it to. Can you share what code you have that isn't working?

**Comment by resistorsoftware** [comment]
Configure Webhooks without the format key! From the initializers for Shopify App, as an example: 

    config.webhooks = [
        { topic: 'orders/create', address: 'https://poo.fwd.wf/webhooks/created_order' },
        { topic: 'orders/paid', address: 'https://poo.fwd.wf/webhooks/paid_order' }
      ]

With no **format** key, this code caused crashes whenever authenticating to the Shop, as the Webhook Manager tries to create these missing Topics. One thing to note, I am also configuring the background jobs to be set, in my case telling the App to use DelayedJobs. 

Note that once a **format** key was provided, everything started working as expected. Only this missing **format** key generated the consistent error. Hence my guess that it was the reverse_merge method. Clearly that could working fine, but then why would the creation request fail?

**Comment by kevinhughes27** [comment]
Very strange. Could you inspect the contents of the webhook create request without adding the key?

**Comment by resistorsoftware** [comment]
Worked like a charm today... closing issue.
