### ISSUE TITLE
invalid signature error

### ISSUE THREAD

**Issue by kunwoo309** [Shopify/shopify_app#262]
Hello! 

my app was running fine, butI suddenly get 

OmniAuth::Strategies::OAuth2::CallbackError
invalid_signature | Signature does not match, it may have been tampered with.

 
I have reinstalled several times but same error occurs. 

I have check all the api-key ,secret  , also the url and  redirect_url.
I have used to use ngrok for local develpment, but facing this error , so tried just use localhost:3000, but faced same error.
 
REPO
https://github.com/kunwoo309/shopify_invalid_signature

**Comment by kevinhughes27** [comment]
Everything looks setup fine. Can you try bumping the `omniauth-shopify-oauth2` gem? You're a couple of versions behind.

**Comment by kunwoo309** [comment]
Isn't `omniauth-shopify-oauth2 1.1.4 `the latest version ?

**Comment by kunwoo309** [comment]
reinstall ubuntu and its working now...

**Comment by kevinhughes27** [comment]
strange. Thanks for reporting back.

**Comment by rahuldstiwari** [comment]
Same issue happens to me. It was due to different time setting in Ubuntu. Now it works after setting 'automatically time from Internet'.

**Comment by ebbflowgo** [comment]
I came across the same, I was using the refresh token instead of the secret token :D

**Comment by fullstackdevs14** [comment]
Hi. I have the same problem. I am using correct api_key and secret. Can anyone help me?
