### ISSUE TITLE
Soften dependency to allow support for Rails 5

### ISSUE THREAD

**Issue by andriytyurnikov** [Shopify/shopify_app#265]
Any chance to get rails 5 support?
```
shopify_app was resolved to 7.0.5, which depends on
      rails (< 5.0, >= 4.2.6) was resolved to 5.0.0.rc1, which depends on
        actionpack (= 4.2.6)
```

**Comment by kevinhughes27** [comment]
I have not tested with rails 5 yet. I don't recall anything that affects engines or generators in the changelog when I read through it so it should be fine. I'd accept a PR that loosens the dep and adds a rails5 build to the test suite.

**Comment by alanhill** [comment]
I just updated the title to reflect that this is to support Rails 5.

**Comment by kevinhughes27** [comment]
@swalkinshaw this can be close eh?
