### ISSUE TITLE
Support for App Proxies

### ISSUE THREAD

**Issue by mikeyhew** [Shopify/shopify_app#273]
We're going to need to use an app proxy for one of our new apps. I'm working on a fork of shopify_app that adds support for them, and will hopefully be sending a PR your way pretty soon.

Since this will be one of my first open source contributions, what do you need to see in the PR for it to be accepted? Is there any work already in progress on adding App Proxy support to this engine?

**Comment by kevinhughes27** [comment]
No work in progress yet but I would love to see this feature added! 

As far as what you need to do it isn't too complicated - add your code to the engine and provide tests for the functionality. A Readme section is probably in order as well. That should be it, I'm excited to see it!

**Comment by CgColorsnyc** [comment]
Add a proxy to your app

1. Click to open the Apps section of the Partners dashboard

2. Click on your App's name, then click Edit app settingsfind the "App Proxy" section near the bottom.

3. Find the "App Proxy" section near the bottom.

**Comment by mikeyhew** [comment]
#275
