### ISSUE TITLE
Current Master - 0554b47 does not load app_proxy/index.html by default

### ISSUE THREAD

**Issue by ashmaroli** [Shopify/shopify_app#286]
Current Master - 0554b47 does not load index.html
------------------------

I'm working on a test-app in rails, deployed to Heroku with 2 new controllers and routes.rb configured as per the Readme file.The app has also been set up properly at the Partner's Dashboard.

On trying to access the app from the storefront, I'm served a 404 Status with the URL:
```
https://appname.herokuapp.com/app_proxy/?shop=shopname.myshopify.com&path_prefix=%2Fapps%2Fappname&timestamp=
```
The page does not open the associated index.html inside _\app\views\app_proxy\index.html.erb_ by default.
but it loads if I were to *manually* insert 'index' or 'basic' into the url as 
```
https://appname.herokuapp.com/app_proxy/index?shop=shopname.myshopify.com&path_prefix=%2Fapps%2Fappname&timestamp=
```

**Comment by kevinhughes27** [comment]
I believe that is intended. You need to specify what action should be used.
cc @mikeyhew

**Comment by mikeyhew** [comment]
@ashmaroli why would you expect your index.html file to be rendered if there is no controller action for it?

**Comment by mikeyhew** [comment]
Oh wait, I guess you do have a controller action for basic. OK, I'm assuming this is what your `config/routes.rb` file looks like:
```ruby
namespace :app_proxy do
  get :index
  get :basic
end
```
If that's the case, then you don't have a route for "/app_proxy/" - so of course you'll get a 404 at that url

**Comment by ashmaroli** [comment]
@mikeyhew, I was testing the proxy verification as per the changes you made to the readme file.
Yes, my routes.rb does look like that.. I even added a get 'app_proxy/index' and get 'app_proxy/basic' in a later commit..but that didnt work obviously.

So, shouldn't the image you added to the readme file be showing instead:

**Proxy URL**
`https://your_app_website.com/app_proxy/index`

or did I fail to see something entirely?
Thanks in advance. 
:)

**Comment by mikeyhew** [comment]
No, the proxy url in the image is correct. Assuming the proxy url you chose is "apps/your-app", a request to [some-store-name.myshopify.com/apps/your-app/some/sub/url]() will be routed to  [https://your_app_website.com/app_proxy/some/sub/url](). Does that make sense?

**Comment by ashmaroli** [comment]
Yes, @mikeyhew it does make sense and it works correctly too.
I was thinking that app proxy was intended to be used to 'mask the url' to a certain page in my app like so:

```ruby
# routes.rb

namespace app_proxy do
  get :charlie
end
```
```ruby
# app_proxy_controller.rb

include ShopifyApp::AppProxyVerification

def charlie
  render 'products/splash', layout: false, content_type: 'application/liquid'
end
```

**App Proxy Settings:**
Path-prefix : `apps`
URL: `longhorn`
Proxy URL: `https://appname.heroku.com/app_proxy/charlie`

**End-user Menu Configurations:**
name: Trends
link: Web Address
url: `/apps/longhorn`

So, if the customer clicks on the menu item, `Trends`, he will be shown the rendered data (hopefully as a standalone liquid page) from 
`https://appname.heroku.com/app_proxy/charlie` via `AppProxyController` & `ProductsController`
with his address bar simply showing:
`https://shopname.myshopify.com/apps/longhorn`

**Comment by ashmaroli** [comment]
If the above logic is correct in every sense,
-- why is my 'splash' page being rendered outside myshopify.com after being redirected to appname.heroku.com/app_proxy/longhorn (for default content-type.)
or 'splash' being downloaded as a file (If content-type is set to 'application/liquid'.) 

-- shouldn't the readme file image reflect the necessary change that proxy url can point to any sub-page under app_proxy ?

**Comment by mikeyhew** [comment]
OK, I think I see what is going on. You want the url of your splash page to
be `apps/longhorn`, not `apps/longhorn/some_sub_url`, for aesthetic
reasons. That makes sense.

I recommend you keep the app proxy pointed directly at `/app_proxy`. It's
up to you, but it'll make things easier for you later on if you add another
app proxy route.

In order to have `/app_proxy`, the root of the `:app_proxy` namespace,
point at `AppProxyController#charlie`, use the `root` method:

```ruby
# config/routes.rb

namespace :app_proxy do
  root action: 'charlie'
end
```

As for being redirected, I've had problems when visiting the store using
https when `force_ssl` is configured. Is that true in your case?

**Comment by ashmaroli** [comment]
Thank you @mikeyhew . Adding the root action under the namespace solved the issue.
:)

**Comment by ashmaroli** [comment]
Hi @mikeyhew, if possible can you show me the error that occurs when I call the following using App Proxy:

```ruby
# app_proxy_controller.rb

def index
  @products = ShopifyAPI::Product.find(:all, :params => {:limit => 10,:product_type => 'Jeans'})
  render layout: false, content_type: 'application/liquid'
end
```
```html+erb
# views/app_proxy/index.html.erb

<h2>All Jeans</h2>
<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.title, app_proxy_products_path %></li>
  <% end %>
</ul>
```
```ruby
# routes.rb

namespace :app_proxy do
  root action: 'index'
  resources :products
end

``` 
Error Message: 
```
There was an error in the third-party application.
```

All is fine if the index.html.erb contains only regular static HTML markup, the entire page is rendered like any  shopify page. 
So wondering if the above is even possible with App Proxy.

Thanks in advance.

**Comment by kevinhughes27** [comment]
I don't see how erb vs static html could affect the app proxy since all of this happens on your server before sending anything to shopify. Eg.

Static html request - your server returns html
ERB request - your server renders the erb into html and returns html

In both cases it looks the same to Shopify at the end. I suspect you have some other error in your template or application code. Look at your own rails logs and see what error occurred.

**Comment by ashmaroli** [comment]
@kevinhughes27, I agree about my server returning html corresponding to static/erb request. That's how it is when I access a page containing HTML, + ERB + Liquid tags ( through the same app_proxy_controller but _ProxyVerification disabled_ and _default content-type_ ) on my localhost and herokuapp subdomain as expected:

**ERB** rendered to **HTML**
**HTML** rendered as **HTML**
**Liquid** rendered as **plain-text**

But if I access the same page via App Proxy ( _ProxyVerification enabled_ and _Content-Type_ set to _'application/liquid'_ ), the error mentioned in my previous post is thrown. My server log simply has a
```
HTTP 500. Internal Server Error. .....
```
Now if I were to remove the ERB component from the page, and reload with just the following, the page renders correctly:

```liquid
<!-- views/app_proxy/index.html.erb -->

<h2>All Product Types</h2>
<ul>
  {% for type in shop.types %}
    <li>
      {{ type | link_to_type }}
    </li>
  {% endfor %}
</ul>
```
```
All Product Types

- T-Shirts
- Shirts
- Jeans
```

**HTML** displayed as **HTML**
**Liquid** tags rendered by Shopify and displayed as **HTML**

**Comment by kevinhughes27** [comment]
I can't say what is happening sorry. I would try and step through the case that errors with a debugger and see what happens and try and narrow in on exactly what is going wrong

**Comment by ashmaroli** [comment]
Thanks anyways, @kevinhughes27.
Any idea, @mikeyhew? Do you have any sample ruby code that pulls shop data via Shopify API and project it back via Liquid API?

**Comment by mikeyhew** [comment]
@ashmaroli not at the moment, but I'll let you know if that changes

**Comment by fighella** [comment]
This get resolved? I have pretty much the same issue.

**Comment by ashmaroli** [comment]
@fighella Its been quite some time since I opened this ticket. I don't remember the circumstances surrounding this ticket anymore, especially since I dropped the project I was working on at that time.
I suggest you try again with the latest version of `ShopifyApp` and open a new ticket if its still an issue.
