### ISSUE TITLE
Rails 5 Support

### ISSUE THREAD

**Issue by djones** [Shopify/shopify_app#287]
I notice the `gemspec` file states:

```ruby
s.add_dependency('rails', '>= 4.2.6', '< 5.0')
```

I'm wondering if there's a plan to support Rails 5 now it's out. I couldn't see any branches working on this.

**Comment by alanhill** [comment]
Hey @djones there's an open issue for this already (https://github.com/Shopify/shopify_app/issues/265). 

There's an open PR currently as well https://github.com/Shopify/shopify_app/pull/272

**Comment by djones** [comment]
Cool. 👍 on updating the issue title to reflect Rails 5.
