### ISSUE TITLE
raise: false in WebhookVerification breaks in Rails 4

### ISSUE THREAD

**Issue by mrlamroger** [Shopify/shopify_app#304]
https://github.com/Shopify/shopify_app/blob/v7.0.11/lib/shopify_app/webhook_verification.rb#L6

`skip_before_filter :verify_authenticity_token` works but `skip_before_filter :verify_authenticity_token, raise: false` gives CSRF error

**Comment by Beans0063** [comment]
Confirming this behavior in 4.2.6, removing raise: false resolves it.

**Comment by kevinhughes27** [comment]
@swalkinshaw added this for Rails 5 compatibility - we were under the impression it didn't affect older versions of rails.

Come to think of it this is in production on one of my rails 4.2.6 apps. Can you write clear reproduction steps please

**Comment by swalkinshaw** [comment]
Yeah looks like that was a naive assumption. I'll try and take a look at this today as well.

**Comment by kevinhughes27** [comment]
I'm running this fine though ...

**Comment by swalkinshaw** [comment]
Yeah I'm having a hard time seeing why this behaviour would happen. Adding `raise: false` should just restore how it worked in Rails 4.

4.2.6:
https://github.com/rails/rails/blob/v4.2.6/activesupport/lib/active_support/callbacks.rb#L660-L683

5.0.0: https://github.com/rails/rails/blob/v5.0.0/activesupport/lib/active_support/callbacks.rb#L622-L653

The methods are basically the same with this addition:

```ruby
if !callback && options[:raise]
  raise ArgumentError, "#{type.to_s.capitalize} #{name} callback #{filter.inspect} has not been defined"
end
```

**Comment by kevinhughes27** [comment]
Can someone submit a demo app that reproduces for us please

**Comment by mrlamroger** [comment]
```
class ShopifyController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create_order_callback
    puts 'entered create_order_callback'
    # The webhook doesn't require a response but let's make sure
    # we don't send anything
    render nothing: true
  end
end
```

```
  scope '/shopify', :controller => :shopify do
    post :create_order_callback
  end
```

```
gem 'shopify_app', '~> 7.0.11'

gem 'rails', '4.2.6'
```

Sorry for not having a complete app but it's a simple route and controller.

**Comment by kevinhughes27** [comment]
We need the full app so we can clone it in order to reproduce. I have an app running this with rails 4.2.6 so something else must be up.

**Comment by tobymarsden** [comment]
Sorry, I don't have a demo app, but I'm also seeing this in production. Webhooks are failing with CSRF error on Rails 4.2.6 using the built-in webhook controller.

**Comment by tobymarsden** [comment]
I suppose this is happening because of https://github.com/rails/rails/blob/v4.2.6/activesupport/lib/active_support/callbacks.rb#L674-L677 in Rails 4:

```
if filter && options.any?
  new_filter = filter.merge(chain, options)
  chain.insert(chain.index(filter), new_filter)
end
```

The callback is being reinserted into the chain because `raise: false` makes `options.any?` return `true`. In Rails 5 the conditional is `if callback && (options.key?(:if) || options.key?(:unless))`, so `raise: false` doesn't reinsert it.

**Comment by swalkinshaw** [comment]
@tobymarsden good eye, that looks like what's happening. I thought it might work to supply an `if` condition to check if its defined but that's not enough.

We might have to do an ugly look up to see if its been defined:

```ruby
  if _process_action_callbacks.map(&:filter).include?(:verify_authenticity_token)
    skip_before_action :verify_authenticity_token
  end
```

**Comment by swalkinshaw** [comment]
Or we could check Rails version and use the `raise` version for >= 5.0

**Comment by tobymarsden** [comment]
@swalkinshaw or, perhaps (and this is also nasty, and untested):

```
skip_before_filter :verify_authenticity_token, raise: false, if: -> { true }
```

**Comment by kevinhughes27** [comment]
Update from my side - I was incorrect my production app is not using the webhooks controlller only the webhook manager.

I'd prefer the Rails 5 check explicitly vs the bogus proc.

**Comment by swalkinshaw** [comment]
Yeah I'm in favour of the explicit Rails version check. I'll try and get a PR up today.

**Comment by swalkinshaw** [comment]
PR for fix is here: https://github.com/Shopify/shopify_app/pull/315

**Comment by uurcankaya** [comment]
Confirming this behavior in 4.2.6...

**Comment by swalkinshaw** [comment]
This has been fixed in master and a new release be done soon.
