### ISSUE TITLE
Incorrect and old documentation

### ISSUE THREAD

**Issue by vfonic** [Shopify/shopify_app#311]
Hi,

The documentation you provide for app development is different on every single page I find it.

I'm using latest rails 5 supported gems:
`shopify_api (4.2.2)`
`shopify_app (7.0.11)`

This generator doesn't exist:
https://github.com/Shopify/shopify_app#app-proxy-controller-generator

Usage instructions are wrong:
http://shopify.github.io/shopify_app/

I've added my secrets with: `rails generate shopify_app your_app_api_key your_app_secret` and it outputted this in `shopify_app.rb`:
```ruby
ShopifyApp.configure do |config|
  config.api_key = "<api_key>"
  config.secret = "<secret>"
  config.scope = "read_orders, read_products"
  config.embedded_app = true
end
```

Please keep the documentation more centralized and better updated. I'm disappointed and annoyed with the amount of legacy stuff laying everywhere in your code and the amount of features missing in Shopify in general (without paying for each of these features)...to the point that I'm considering moving to other platform and advising everyone else to do the same.

**Comment by ashmaroli** [comment]
Hi vfonic, if you can give us the exact steps to how you tried to generate the App Proxy Controller, we can provide a solution.

**Comment by kevinhughes27** [comment]
The github page is out of sync - I am working on getting that sorted out. This is why you arguments didn't work when passed to the generator. The repo readme is up to date with how to do this.

The app-proxy generator does exist just only on the master branch and not in the last release since we haven't made a release that includes it yet. 

Sorry for the confusion!

**Comment by vfonic** [comment]
```sh
$ rails generate shopify_app:app_proxy_controller                                                                                                    Running via Spring preloader in process 16846
Could not find generator 'shopify_app:app_proxy_controller'. Maybe you meant 'shopify_app:home_controller', 'shopify_app:controllers' or 'shopify_app:shop_model'
Run `rails generate --help` for more options.
```

```sh
$ rails generate --help
Running via Spring preloader in process 16911
Usage: rails generate GENERATOR [args] [options]

General options:
  -h, [--help]     # Print generator's options and usage
  -p, [--pretend]  # Run but do not make any changes
  -f, [--force]    # Overwrite files that already exist
  -s, [--skip]     # Skip files that already exist
  -q, [--quiet]    # Suppress status output

Please choose a generator below.

Rails:
  assets
  channel
  controller
  generator
  helper
  integration_test
  job
  mailer
  migration
  model
  resource
  scaffold
  scaffold_controller
  task

Coffee:
  coffee:assets

Js:
  js:assets

ShopifyApp:
  shopify_app:add_webhook
  shopify_app:controllers
  shopify_app:home_controller
  shopify_app:install
  shopify_app:routes
  shopify_app:shop_model
  shopify_app:shopify_app
  shopify_app:views

TestUnit:
  test_unit:generator
  test_unit:plugin
```


Brand new rails 5 application `rails new <app_name>`. I've replaced `sqlite` with `pg` and added `figaro` gem. If needed, I can create a new app and push it to github and send you a link?

**Comment by kevinhughes27** [comment]
Its because the proxy generator isn't in version 7.0.11 which you are using. If you need it point your gemfile to a github sha or wait for us to make a release

**Comment by ashmaroli** [comment]
To use the latest unreleased version of the gem, please update your gemfile as follows:

```ruby
gem 'shopify_app', github: 'Shopify/shopify_app'
```

**Comment by vfonic** [comment]
Ok, I'll just use the `master` branch or live without the generator.

Thanks for help!
