### ISSUE TITLE
Allow One to Add a `call`able Value to The scripttag List

### ISSUE THREAD

**Issue by sshaw** [Shopify/shopify_app#316]
The caller should pass in the Shopify domain and token. This will allow for all sorts of things. #285 comes to mind.

**Comment by kevinhughes27** [comment]
If I understand correctly you're talking about adding an arbitrary hook that is called after the auth is completed? I did something similar in https://github.com/kevinhughes27/shopify-sinatra-app. PRs welcome!

**Comment by sshaw** [comment]
Sorry, should have been more clear. I meant a scripttag hook. Something like:

```ruby
ShopifyApp.configure do |config|
  config.webhooks = [
    {topic: 'carts/update', address: ShopScript.new}
  ]
end

class ShopScript
  def call(domain, token)
    shop = Shop.find_by_shopify_domain(domain)
    cdn_url_for_shop(shop) # or something
  end
end
```

**Comment by kevinhughes27** [comment]
Can you elaborate a bit more on the use cases that this enables? I'm not a big user of script tags

**Comment by sshaw** [comment]
> Can you elaborate a bit more on the use cases that this enables?

It allows one to generate store specific scripts without having to incur the overhead of looking up a  specific script at load time.

Currently the shop name gets tacked on to the script URL. In general this is fine but, since async scripts are (in most cases) [The Way :tm: for an app to add functionality to a store's frontend](https://help.shopify.com/api/guides/use-javascript-responsibly), it presents a few issues that can be easily solved by a caching:

1. User experience: an async script usually results in a "flash of unaugmented content" as it takes some time for them to load. 
1. Server load: apps used by shops that get a ton of traffic can cause a heavy load on the app's server just for script loading. 

As far a I can tell, the current scripttags config does not allow one to configure cache friendly URLs.

**Comment by kevinhughes27** [comment]
Okay I think I understand. This would require a change inside the ScriptTag manager to check if the object for `src` responds to some method (like `call`) and if it does pass the current shop to that method otherwise assume it is a sting and use it directly.

I would be okay with this. @redronin - you added the script tag manager. Does this make sense to you?

**Comment by sshaw** [comment]
Any update on this? I can submit a PR with the quickness ⚡

**Comment by kevinhughes27** [comment]
I think submitting a PR is the best course here. We can understand the code better after we see it and continue the discussion on the PR.

**Comment by sshaw** [comment]
PR here: #341

**Comment by sshaw** [comment]
Closing as #341 has been merged into master.
