### ISSUE TITLE
Proxies that fail authentication should raise a forbidden error, not unauthorized.

### ISSUE THREAD

**Issue by travishaynes** [Shopify/shopify_app#318]
When the authentication of a proxy fails, it returns an unauthorized error: https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/app_proxy_verification.rb#L16

Receiving an unauthorized response from a server is basically telling the user that they are not authenticated, and that they should re-authenticate and try again. It's also a requirement to include a `WWW-Authenticate` header to describe how the user can do so when you respond with a 401 error.

From [RFC2617](http://www.ietf.org/rfc/rfc2617.txt):

> The 401 (Unauthorized) response message is used by an origin server to challenge the authorization of a user agent. This response MUST include a WWW-Authenticate header field containing at least one challenge applicable to the requested resource.

Application proxies are only supposed to be accessed from Shopify's server. So any other source that attempts to access it should actually receive a 403 forbidden error, since there is no way for them to re-authenticate.

Here's how [W3](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) describes a 403 error:

> The server understood the request, but is refusing to fulfill it. Authorization will not help and the request SHOULD NOT be repeated.

Which is exactly what is going on when the application proxy fails to authenticate. It's failing because the request is not coming from Shopify, not because the request is coming from an unauthenticated user.

**Comment by kevinhughes27** [comment]
Sounds reasonable to me. PR's welcome

**Comment by ashmaroli** [comment]
gez, this is a suitable thread to pose the following question. I've been trying to wrap my head around it. Do either of you have a simpler explanation?  

>HTTP 407 Proxy Authentication Required
> ----
> This code is similar to 401 (Unauthorized), but indicates that the client must first authenticate itself with the proxy. The proxy MUST return a Proxy-Authenticate header field (section 14.33) containing a challenge applicable to the proxy for the requested resource. The client MAY repeat the request with a suitable Proxy-Authorization header field (section 14.34). HTTP access authentication is explained in "HTTP Authentication: Basic and Digest Access Authentication"

The referenced sections being:  

> 14.33 Proxy-Authenticate
> 
> The Proxy-Authenticate response-header field MUST be included as part of a 407 (Proxy Authentication Required) response. The field value consists of a challenge that indicates the authentication scheme and parameters applicable to the proxy for this Request-URI.
> 
>        Proxy-Authenticate  = "Proxy-Authenticate" ":" 1#challenge
> The HTTP access authentication process is described in "HTTP Authentication: Basic and Digest Access Authentication" [43]. Unlike WWW-Authenticate, the Proxy-Authenticate header field applies only to the current connection and SHOULD NOT be passed on to downstream clients. However, an intermediate proxy might need to obtain its own credentials by requesting them from the downstream client, which in some circumstances will appear as if the proxy is forwarding the Proxy-Authenticate header field.

---

> 14.34 Proxy-Authorization
> 
> The Proxy-Authorization request-header field allows the client to identify itself (or its user) to a proxy which requires authentication. The Proxy-Authorization field value consists of credentials containing the authentication information of the user agent for the proxy and/or realm of the resource being requested.
> 
>        Proxy-Authorization     = "Proxy-Authorization" ":" credentials
> The HTTP access authentication process is described in "HTTP Authentication: Basic and Digest Access Authentication" [43] . Unlike Authorization, the Proxy-Authorization header field applies only to the next outbound proxy that demanded authentication using the Proxy- Authenticate field. When multiple proxies are used in a chain, the
> 
> Proxy-Authorization header field is consumed by the first outbound proxy that was expecting to receive credentials. A proxy MAY relay the credentials from the client request to the next proxy if that is the mechanism by which the proxies cooperatively authenticate a given request.

**Comment by kevinhughes27** [comment]
Not familiar with this sorry.

**Comment by ashmaroli** [comment]
no probs. :smiley: 
cc: @mikeyhew

**Comment by travishaynes** [comment]
@ashmaroli This does not apply to Shopify apps, because they're not actually acting as a proxy. That term is actually kind of misleading because Shopify is the real proxy in this case. Just break it down to see what I mean: The request goes from a browser to a Shopify store, then from Shopify to our app which  in turn replies back to Shopify, which then hands that request back to the client that made the request. That puts Shopify in the middle, making it the proxy.

407 would come in to play if we were writing a proxy that needed to make sure to authenticate clients before they make a request through our server. A Shopify app is actually responding to a request made through a proxy, it isn't the actual proxy itself.

**Comment by ashmaroli** [comment]
Thanks Travis, its a lot more clear now, as you explained with the context of shopify apps.

**Comment by mikeyhew** [comment]
@travishaynes Sounds good, and should be a simple switch. I'll post a PR shortly

**Comment by jamiemtdwyer** [comment]
Closed by https://github.com/Shopify/shopify_app/pull/323
