### ISSUE TITLE
Oauth error invalid_request: The redirect_uri is missing or not whitelisted

### ISSUE THREAD

**Issue by SylarRuby** [Shopify/shopify_app#329]
Ruby 2.3.1
Rails 5.0.0.1
shopify_api (4.3.0)
shopify_app (7.1.1)

App URL: http://demo.herokuapp.com/
Redirection URL: https://www.demo.herokuapp.com/auth/shopify/callback

```
ShopifyApp.configure do |config|

  config.api_key = "somekey"
  config.secret = "somesecret"
  config.scope = "read_orders, read_products" # corrected to use one scope.
  config.scope = 'read_customers, read_orders, write_products'
  config.embedded_app = true
end

```

When entered `mystore.myshopify.com` I get error as in title. Nothing's wrong with your gem, correct? So what's the way forward? Not compatible with Rails 5?

This is a new app so I assume issue our your end?

**Comment by SylarRuby** [comment]
Now Im getting `The authorization code was not found or was already used`

**Comment by kevinhughes27** [comment]
I haven't tried with rails 5 yet but I think it should still work. Probably not the issue but you have the scope set twice.

Can you install the app locally?

**Comment by SylarRuby** [comment]
Yes. I did corrected the scope but still same issue. I havent tried locally because the redirect will have issues so I push to heroku and install from there. The app installed but redirected with tat message. The app wont open from the store either.

**Comment by kevinhughes27** [comment]
I would recommend setting the app up locally first and then deploying to heroku once you have it working. I usually work with 3 sets of configuration which all work at any given time: development, staging and production. You can create multiple API clients no problem or add multiple callback urls to a single (I recommend multiple clients).

Deploying to heroku is a slow iteration cycle to fix problems and you can't debug as effectively. If you can't get it working locally please create a minimal repo that reproduces the problem and send me a link as per the issue guidelines.

**Comment by SylarRuby** [comment]
Ok. Just did this locally. When pressed install to install the app, it redirects with `The authorization code was not found or was already used` 

I'll try with Rails 4 and see.

**Comment by SylarRuby** [comment]
@kevinhughes27 Ok. Not compatible with Rails 5; works with Rails 4.2.7.1. Since Im new to Shopify, Should I see something:

<img width="1149" alt="screen shot 2016-08-17 at 15 27 47" src="https://cloud.githubusercontent.com/assets/7381195/17740116/56fff10e-648f-11e6-814a-1829880cde1e.png">

**Comment by alanhill** [comment]
At first glance it looks like you just need to click the shield in the address bar to allow insecure content since it's just running locally.

**Comment by kevinhughes27** [comment]
What app server are you running and what is your session store / did you create a shop model in your database. I wonder if the in memory session doesn't work with Rails 5 because of puma.

**Comment by SylarRuby** [comment]
@alanhill Was correct. Thanks guys. I'll close this but still an issue with Rails 5 ;)

**Comment by kevinhughes27** [comment]
Can you answer my question about the the shop model?

**Comment by SylarRuby** [comment]
@kevinhughes27 Oh. I have not created a Model for Rails 4x. I did created a model for Rails 5 but still got the issue. Is that the issue for Rails 5?

**Comment by kevinhughes27** [comment]
nah I was thinking that rails 5 without the model might not work because of puma

**Comment by SylarRuby** [comment]
This was in Rails 5:

```

class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
  include ShopifyApp::SessionStorage
end

```

**Comment by kevinhughes27** [comment]
Thanks. Not sure what the issue is then. We'll have to look into it

**Comment by rafasegat** [comment]
Did someone fix that? 

Its displaying this error... 

`NoMethodError: undefined method `redirect_uri=' for #<ShopifyApp::Configuration:0x007f91ded3e9e8>`

When `git push heroku master`

**Comment by kevinhughes27** [comment]
That setting was removed several versions ago. You no longer need to set this in your config just make sure your api client is setup properly.

**Comment by rafasegat** [comment]
I got it.

Thanks

**Comment by adamw005** [comment]
I'm also running into 'Oauth error invalid_request: The redirect_uri is missing or not whitelisted'. I'm running 7.2.0 shopify_app with 4.2.3 shopify_api. Is there nowhere to set the redirect_uri now?

' just make sure your api client is setup properly.' 
How can I check this?

**Comment by kevinhughes27** [comment]
In your [partner dashboard](https://app.shopify.com/services/partners) there are settings for your api clients.

**Comment by marisveide** [comment]
Did someone find solution to this issue?
I have the same problem on Rails 5.
It works locally just fine (through ngrok tunnel), but as soon as I deploy it to Heroku (or AWS), it gives the same error: Oauth error invalid_request: The redirect_uri is missing or not whitelisted.

**Comment by marisveide** [comment]
Solved:
1. Updated to newest versions:
```ruby
gem 'shopify_app', '~> 7.2.10'
gem 'shopify_api', '~> 4.9.0'
gem 'omniauth-shopify-oauth2'
```
2. Made sure that app installation URL is https://

**Comment by AmitPatel-BoTreeConsulting** [comment]
@marisveide I have exactly same situation. 

![selection_922](https://user-images.githubusercontent.com/1289894/29855532-39dad8dc-8d6a-11e7-98ef-5ff1eb1a9b15.png)

I am facing that issue with 

```
Rails 5.1.3
omniauth-shopify-oauth2 (1.2.0)
    shopify_api (4.9.0)
    shopify_app (7.4.0)
```

App settings in Partner account:
![selection_923](https://user-images.githubusercontent.com/1289894/29857100-800e653a-8d74-11e7-9a45-bb090dcc3138.png)

Also enabled embedded sdk.

It works perfectly on local using ngrok tunnelling but gives error on a staging(engine yard)

@kevinhughes27

**Comment by marisveide** [comment]
@kevinhughes27 - what I can think of to help:

1. Check that in your staging the same gems are installed.

2. Check if your staging maybe has a proxy which changes paths with some prefix.

3. Check if you have valid SSL on your staging server, and that it is actually using SSL.

I have spent so much time and nerves dealing with this, that I don't wish anybody should ever has to do that.
Know from my bones how this feels...

Maris

**Comment by AmitPatel-BoTreeConsulting** [comment]
@marisveide thanks.

I verified 1 and 3. Seems 2 is the issue. I deployed the app on heroku and tested the app. I am not facing the issue there.

**Comment by AmitPatel-BoTreeConsulting** [comment]
Here is what I see in the log while installing the app which may help to identify the issue.

![selection_936](https://user-images.githubusercontent.com/1289894/30014055-c5271882-9167-11e7-8753-c9fc34bb9837.png)

**Comment by marisveide** [comment]
Please, show the whole Controller file.

Maris

Sent from phone while driving.

On Mon, 04 Sep 2017 at 09:25 Amit Patel

<
mailto:Amit Patel <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Here is what I see in the log while installing the app which may help to identify the issue.

https://user-images.githubusercontent.com/1289894/30014055-c5271882-9167-11e7-8753-c9fc34bb9837.png

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/Shopify/shopify_app/issues/329#issuecomment-326876144
, or

**Comment by AmitPatel-BoTreeConsulting** [comment]
Thanks @marisveide. The issue was the API key/secret configuration. I forgot to configure for production so it was taking default one I configured for development environment.

**Comment by marisveide** [comment]
Yey, glad to hear that there's no mystery, @AmitPatel-BoTreeConsulting.
Good luck moving forward.
You helped yourself eventually, remember that when things get hard. ;)
I was here only so you don't feel alone while solving that.
