### ISSUE TITLE
Custom Session Controller

### ISSUE THREAD

**Issue by SylarRuby** [Shopify/shopify_app#332]
Rails 4
Ruby 2.3.1
Shopify_app 7.1.1

App works great. My issue is with the session. Can you create a custom session controller that works with other api providers? When I authenticate with another api, my token is not saving.

I've created a custom controller with the api logic etc and custom routes. When I'm redirected from the api's website, I get invalid token.

How to have two or more open sessions?

**Comment by kevinhughes27** [comment]
Every part of the engine can be overwritten - I have an app in production that is actually 2 different Api Clients as far as the app store is concerned (2 different but similar integrations sharing some common code).

I need some more details to point you in the right direction.

**Comment by SylarRuby** [comment]
@kevinhughes27 Great!

Im messing with [Xerioxzer](https://github.com/waynerobinson/xeroizer). So I have a `XeroSessionsController` in `app/controllers/xero_sessions_controller.rb` with the xeroizer's controller information. `new` method takes me to xero's website to be authenticated and redirects to the home page (homecontroller). I'm lost from there.

**Comment by kevinhughes27** [comment]
Ha my app also uses Xeroizer!

Xero should redirect you back to that controller as long as your callback routes are setup properly. Then you can store that session wherever. This doesn't conflict with ShopifyApp at all so you'll be fine. 

If its not working I would look at where Xero is redirecting and if it is hitting your app try and get into a debugger session

**Comment by SylarRuby** [comment]
@kevinhughes27 Ha! Ok.

Well at first it was redirecting to the same controller. I created a `show` action with the view template. So when on the `show.html.erb` I get "Token has not been provided".

**Comment by SylarRuby** [comment]
Shyt! My mistake! I should have renamed `create` to `show`. I also need a partner account for longer sessions ;) Thanks for the clues!

**Comment by kevinhughes27** [comment]
Happy to help!
