### ISSUE TITLE
How to create a product with variants?

### ISSUE THREAD

**Issue by SylarRuby** [Shopify/shopify_app#339]
Not an issue, just an how to.

I see that [Product has many variants association](https://help.shopify.com/api/reference/product_variant) but how to create a product with variants?

```
internal_db.map do |i|
  ShopifyAPI::Product.new({
    title: i.title,
    ...
    # How to assign variants?
    i.variants.each do |v|
      variants: [
        {price: v.price, ...}
      ]
    end
  }).save
end

```

If I could:

```
ShopifyAPI::Variant.new({...})

```

How to get the product_id that was **just** created?

Was looking at:

```
ShopifyAPI::Product.new({...}).variants.build({...}).save

```

But does not work.

**Comment by kevinhughes27** [comment]
Hey @SylarRuby can you give the issue template a read. Please only create issues on this repo for actual issues with ShopifyApp not ShopifyAPI or general how to questions. It adds a lot of noise for us and you'll actually get help if you post on the forum where as I won't answer this type of inquiry here. Thanks for understanding.
