### ISSUE TITLE
Could not find generator 'shopify_app:app_proxy_controller'

### ISSUE THREAD

**Issue by Trimakas** [Shopify/shopify_app#345]
I'm just creating a new app, and I wanted to use proxies, but when I run
`rails generate shopify_app:app_proxy_controller`

I get
`Could not find generator 'shopify_app:app_proxy_controller'`

All I've done is install the gem, the Shop model, and the other controllers..

**Comment by kevinhughes27** [comment]
what version of the gem? that generator is only in the lastest version

**Comment by Trimakas** [comment]
Hmm, there might be a conflict between the versions of these gems. Are there any versions between 4.0.2 and 4.0.7?

shopify_api and the shopify_app gems.. 
   
shopify_api (4.0.7)
      activeresource
      rack
shopify_app (7.0.2)
      omniauth-shopify-oauth2 (~> 1.1.11)
      rails (>= 4.2, < 5.0)
      shopify_api (~> 4.0.2)

**Comment by kevinhughes27** [comment]
latest version of ShopifyApp is `7.2.0`

**Comment by Trimakas** [comment]
Ahh, thanks.. might want to update the Gem as I just downloaded it yesterday and that's the version I got..

**Comment by kevinhughes27** [comment]
The gem is updated and released. Bundler doesn't always fetch the latest depending on your project and system.
