### ISSUE TITLE
Cannot login from sub-directory

### ISSUE THREAD

**Issue by SylarRuby** [Shopify/shopify_app#348]
I have seen that this issue was mentioned in https://github.com/Shopify/shopify_app/issues/154, was merged but still open. I face the same issue  with this gem on Rails 5.

My routes:

```
Rails.application.routes.draw do
  root :to => 'home#index'
  get '/dashboard' => 'dashboard#index', as: 'dashboard'
  mount ShopifyApp::Engine, at: '/dashboard'

  [...]

end
```

Now I log in from `/dashboard/login`. Once logged in, I get `Oauth error invalid_request: The redirect_uri is missing or not whitelisted` dispite I edited the app's `Redirection URL` in Shopify to `https://www...../dashboard/auth/shopify/callback`

Having the app mounted at root, I have no issues.

How to solve, please?

**Comment by kevinhughes27** [comment]
I would double check the redirect uri settings in the partner dashboard. Otherwise you'll have to see where you are being redirected and compare.

**Comment by SylarRuby** [comment]
I'll update on this later. Thanks

**Comment by ebbflowgo** [comment]
@SylarRuby I see the same, would you happen to have any updates on this?

**Comment by kevinhughes27** [comment]
You might need to make some specific edits in the omniauth initializer that is generated for you. The omniauth readme might help. Please post back on this issue if you figure it out!

**Comment by StephenKelly94** [comment]
Perhaps it could be because the authenticate method in the SessionsConcern controller is redirection to the main_app.root_path on line 43. 

```ruby
def authenticate
  if sanitized_shop_name.present?
    fullpage_redirect_to "#{main_app.root_path}auth/shopify?shop=#{sanitized_shop_name}"
  else
    redirect_to return_address
  end
end
```

**Comment by tyler-king** [comment]
Correct. Same issue here. Used this Gem many times but this was the first I needed to namespace the front and backends.

@kevinhughes27 is right, mod the omniauth path and it will work. Just tried it.

```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :shopify,
    ShopifyApp.configuration.api_key,
    ShopifyApp.configuration.secret,
    scope: ShopifyApp.configuration.scope,
    callback_path: '/dashboard/auth/shopify/callback'
end
```

**Comment by kevinhughes27** [comment]
FYI we need this for an internal project now and I am working on improving this in version 8.0.0. I am going to close this issue now though since this does work.

**Comment by SylarRuby** [comment]
Apologies for the distant communication. When Im back on this task, I'll use latest version as I do not remember my last issue with this plugin. I guess I was a "basic junior" at that time 😎

**Comment by kevinhughes27** [comment]
👍 How to do this is going to be documented in the readme by the time you're back 😸

**Comment by SylarRuby** [comment]
@kevinhughes27 How time flies? I'm back on the project with a bang. Any time frame for v8?

**Comment by kevinhughes27** [comment]
We haven't set a hard release date yet. There is a branch for development though and it is stable https://github.com/Shopify/shopify_app/pull/442. I am using it in production for a project already.

**Comment by codemicky** [comment]
I have added a sub-directory. **/myapp**

But when I go to `http://mysite.com/myapp`, it redirects to `http://mysite.com/login?return_to=%2Fmyapp%2F%3F`, not `http://mysite.com/myapp/login`

That's why when installing an App, it redirects to
`http://mysite.com/login?return_to=%2Fmyapp%2F%3Fhmac%3D5d81dbc6102603c6fc35931cba40f868614cf378f141ab151166d43868b4a97e%26shop%3Ddev.myshopify.com%26timestamp%3D1585300456&shop=dev-test1.myshopify.com`
And I got `Not Found: /login` error.

**routes.rb**

```
Rails.application.routes.draw do
  root :to => 'home#index'
  get '/myapp' => 'myapp#index', as: 'myapp'
  mount ShopifyApp::Engine, at: '/myapp'
end
```
**ominiauth.rub**

```
provider :shopify,
  ShopifyApp.configuration.api_key,
  ShopifyApp.configuration.secret,
  scope: ShopifyApp.configuration.scope,
  callback_path: '/myapp/auth/shopify/callback',
  setup: lambda { |env|
    strategy = env['omniauth.strategy']

    shopify_auth_params = strategy.session['shopify.omniauth_params']&.with_indifferent_access
    shop = if shopify_auth_params.present?
      "https://#{shopify_auth_params[:shop]}"
    else
      ''
    end

    strategy.options[:client_options][:site] = shop
    strategy.options[:old_client_secret] = ShopifyApp.configuration.old_secret
    strategy.options[:per_user_permissions] = strategy.session[:user_tokens]
  }
end
```
Anyone had same issue?
