### ISSUE TITLE
Example app uses wrong config in initializer

### ISSUE THREAD

**Issue by tonycchung** [Shopify/shopify_app#354]
The example app is locked to `~> 7.0.0` for the `shopfiy_app` gem. Unfortunately this version doesn't have `application_name` as an `attr_accessor` in the configuration yet the initializer is trying to set the config in the initializer.

Perhaps the shopify gem and rails versions need to be bumped or the optional config removed from the initializer.

**Comment by kevinhughes27** [comment]
The example should be updated. The example is not intended to be ran though its just there for browsing. The source of truth is what happens when the generator is run.

**Comment by tonycchung** [comment]
Ah. Yeah ran into some other issues trying to run the example app as well. It's a bit confusing as the README.md in the example looks like it gives instructions to actually run the sample app - perhaps it could updated to reflect that it's simply source code that can be browsed.

**Comment by kevinhughes27** [comment]
The full history is it used to be a fully separate repo and that confused even more people. I moved in here to try and fix some of that confusion but it still happens from time to time. Ideally it would be runnable but its secondary to the generator.

There is some example code in there about how to use the ESDK or else we could delete the entire folder and only have the generator. The ESDK examples could be moved into their own generator.

cc @ShayneP
