### ISSUE TITLE
uninitialized constant ShopifyApp::AppProxyVerificatiion

### ISSUE THREAD

**Issue by CaseJnr** [Shopify/shopify_app#363]
Hi, I am receiving the following error:

Unable to load application: NameError: uninitialized constant ShopifyApp::AppProxyVerification

My proxy controller looks like this

```
class ProxyController  < ApplicationController

    include ShopifyApp::AppProxyVerification 
```

Any ideas?

**Comment by kevinhughes27** [comment]
what gem version do you have installed?
