### ISSUE TITLE
Webhooks not generated

### ISSUE THREAD

**Issue by uurcankaya** [Shopify/shopify_app#367]
Hi,

We noticed our app was not responding to webhooks, issue is fixed now but no new webhooks are being generated anymore upon installation.

What can be the reason for this?

**Comment by kevinhughes27** [comment]
You'll have to provide more information - is the webhook manager running? (check your logs). Are you running it with a background queue (i.e. sidekiq). There should be logs that indicate if it is running and if so why it isn't creating webhooks properly.

**Comment by uurcankaya** [comment]
Kevin,

I am using delayed job, just tested once again and it started to receive webhooks and job gets queued now.

For some reason webhooks were not being created, not sure if this was Shopify issue (contacted today) or perhaps it had something to do with the fact that app had not been responsive to hooks?

**Comment by kevinhughes27** [comment]
That shouldn't affect you ability to create webhooks. Sounds like this was on your end.
