### ISSUE TITLE
Oauth error invalid_request: Could not find Shopify API application with api_key <api_key> 

### ISSUE THREAD

**Issue by behcetilhan** [Shopify/shopify_app#369]
I followed the instruction here: https://www.youtube.com/watch?v=DB48N8rRHFw

but i'm getting this error, during installation

![screenshot_2](https://cloud.githubusercontent.com/assets/5682542/21751364/bb791614-d5ce-11e6-8be9-1d3e7c2f8d8d.jpg)

Any help?

**Comment by EiNSTeiN-** [comment]
Search the  string `<api_key>` in your application and replace that by your actual API key from your partner dashboard. I'll close this issue now since this is not the right place for technical help.
