### ISSUE TITLE
Shopify App Example minimum version needs a bumb

### ISSUE THREAD

**Issue by natemacinnes** [Shopify/shopify_app#374]
The Shopify App Example needs a minimum version of the `shopify_app` gem higher then 7.0.0

Ex.: Having shopify_app 7.0.2 installed and attempting to `rake db:migrate` will result in a `NoMethodError: undefined method 'application_name' for #<ShopifyApp::Configutration....>`.

Digging I found the application_name method was added to the configuration in commit [7be7158](https://github.com/Shopify/shopify_app/commit/7be71585f88a92f21dec4a148b10ce3a33e73e41)
Meaning the minimum version needs to be, `~> 7.1`. ([75f0669](https://github.com/Shopify/shopify_app/commit/75f066939719ceccef101d9eccc555248bf1ce60))

**Comment by kevinhughes27** [comment]
Yes the example gets out of date quickly. The example serves 2 main purposes in my view:

* Gives users a look at what their app will look like after adding this gem without actually having to install it (note the same can be achieved by just running the generator and git reseting if you don't like it)
* The example includes some usage of the ESDK. I would like to see this moved into an optional generator instead and then we just remove the example

The example app is not really intended to be ran.

**Comment by kevinhughes27** [comment]
I've bumped this in the version 8.0.0 branch.
