### ISSUE TITLE
Oauth error invalid_request: The Shopify API application does not support oauth

### ISSUE THREAD

**Issue by amankumarglobussoft** [Shopify/shopify_app#375]
I am getting the error `Oauth error invalid_request: The Shopify API application does not support oauth`
I have created the app in partner's account, still why I am getting this error, Please help me out as I am stucked

**Comment by jamiemtdwyer** [comment]
Have you passed the - - api_key parameter when generating your application?
Can you please provide your API key?

**Comment by amankumarglobussoft** [comment]
@jamiemtdwyer Yes I passed the api_key when generating the application. Here is my Api_key
`bd1166d85aa53d09756b138fcd494795`

**Comment by jamiemtdwyer** [comment]
That is a private application. `shopify_app` is only intended to work with partner-created applications. You can sign up for a free partner account at https://www.shopify.ca/partners
