### ISSUE TITLE
Dependency Issue Remains a Problem

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#378]
**gem update shopify_app**
Updating installed gems
Updating shopify_app
ERROR:  Error installing shopify_app:
	Unable to resolve dependency: 'activeresource (>= 0)' requires 'activesupport (= 2.3.0)'
Nothing to update

**Comment by kevinhughes27** [comment]
Are you using Rails 5?
https://github.com/Shopify/shopify_app#rails-5

**Comment by resistorsoftware** [comment]
I will be, but first I would not mind having the latest shopify_app gem install. This issue with respect to ActiveSupport = 2.3.0 has been a pain for some time now. Is there some underlying cause? It seems to affect all the Shopify CLI gems like the shopify_cli and theme gem too.

**Comment by resistorsoftware** [comment]
The shopify_app gem does install correctly using a bundle, that does specify the activeresource to be the rails/activeresource version.

Why can't we just do a plain jane gem update shopify_app? Has to happen as a bundler combo?

**Comment by kevinhughes27** [comment]
I think that is related to how bundler works with non-release dependencies. Someone should look at updating https://rubygems.org/gems/activeresource since apparently its at version 4 now.

@jamiemtdwyer can someone from your team look into this?

**Comment by ashmaroli** [comment]
@resistorsoftware To update the `shopify_app` gem, simply run `bundle install` or `bundle update shopify_app`  from your app directory instead of `gem update --`

Bundler will resolve the correct versions based on your `Gemfile` and will install accordingly.

**Comment by resistorsoftware** [comment]
The issue is I often want to use the gems shopify_cli and shopify_theme which do not have a Gemfile with dependencies. So when I load a shell with Ruby 2.3.x or 2.4 for example, and try the gem install, it fails. That is whole point of this thread I think. It is true, that with a Gemfile and bundler, it worked. Thanks

**Comment by extremeshannon** [comment]
Has anyone found a solution for this. I have not been able to get the shopify_app to work yet.

**Comment by wnm** [comment]
@extremeshannon yes, if you use rails 5, you need to put this in your Gemfile:

gem 'activeresource', github: 'rails/activeresource', branch: 'master'

**Comment by kevinhughes27** [comment]
Newest active resource was shipped so this shouldn't be an issue any more.
