### ISSUE TITLE
Problem with running application

### ISSUE THREAD

**Issue by Pelcomp** [Shopify/shopify_app#381]
Hello
I try to run application according to README.md with tunelling.
When I go to  Url app (http://46ef1561.ngrok.io/) I see Ruby welcome page,
when I go to redirection url (http://46ef1561.ngrok.io/auth/shopify/callback) and click install,
I have an error:
```
NoMethodError in ShopifyApp::SessionsController#new
undefined method `root_path' for #<ActionDispatch::Routing::RoutesProxy:0x000000068d6020>
```
What is wrong with my code?

**Comment by kevinhughes27** [comment]
As per the issue guideline can you create a new repo that reproduces the problem and link to it? Then we'll have someone investigate.

**Comment by Pelcomp** [comment]
Hi kevinhughes27
I hosted my app on Heroku end it works perfectly,
but I have another problem: could you give me a instruction or link to tutorial or apps
how to build Embedded app page with settting or configuration options (including create and submit form and retrive submited values from database)
Thank you.

**Comment by kevinhughes27** [comment]
I would start looking at some Rails tutorials. Google should be able to find plenty!
