### ISSUE TITLE
Draft Orders, Mark as Payment Pending

### ISSUE THREAD

**Issue by LeumasDigital** [Shopify/shopify_app#382]
Hello All, 

I'm not 100% sure this is the right place to post this, I don't think the problem is with this gem as such... 

I'm trying to change a draft order in to an order, I'm doing this 

order = ShopifyAPI::DraftOrder.find(@application.shopify_order_id)
order.status = 'pending'
order.save

Its posting to the API just fine, I get back => true, the API repsonse is

Response status Net::HTTPOK (200)

However in the response body, the status is changed back to 'open' and obviously no order is created. I've trired order.status = 'completed' but that doesn't seem to be either. I'm guessing this is a 'read only' field. 

I though maybe I had to create a transaction for the DraftOrder but the Transaction method doesn't accept draft_order_id, only order_id which isn't created yet. 

Permissons on the app are correct and I get the same results from Shopify CLI

What am I missing?

the API documentation says " the draft order can be paid, set to pending, or paid by credit card; in each case, the draft order is set to completed and an order is created. "

**Comment by kevinhughes27** [comment]
Hi there,

You're right this isn't the right place to post this. Is the issue template not working? I'd recommend posting this on the Shopify forums

**Comment by LeumasDigital** [comment]
Ok thanks
