### ISSUE TITLE
Do some action upon omniauth confirmation

### ISSUE THREAD

**Issue by uurcankaya** [Shopify/shopify_app#390]
Hi everyone,

What is the best practice to enable some action right after customer installs the app?

There is a line called

 `mount ShopifyApp::Engine`

in routes file, i am assuming that's the code which adds all omniauth redirections. How can i override this? basically we need something like

`get 'auth/shopify/callback' => 'some_controller#some_method' `

**Comment by uurcankaya** [comment]
i guess i am wrong, redirection happens in the session controller but not sure how to override that as well

**Comment by kevinhughes27** [comment]
You can re-define the session controller in your app and do whatever you need to do. If you need to do something *after install* I would probably do it after the shop model is created rather than messing with the session controller.

This is the code in question btw: https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/sessions_concern.rb#L22

There was some talk in the past of adding a generic after install hook there that could be configured.

**Comment by kevinzen** [comment]
I'm looking to solve this same issue -- setting up webhooks and customer accounts after a shop installs the app. What is the 'recommended' approach for this for someone using `shopify_app`? There doesn't seem to be a clean way to connect into the process directly.

**Comment by kevinhughes27** [comment]
Webhooks can be managed using the provided class. Check out this section of the readme: https://github.com/Shopify/shopify_app#webhooksmanager

As for other actions I still think a generic after installed/authenticated hook for ShopifyApp would be useful. It would be pretty straight forward to add if you or someone is interested in doing it. It would need to hook in here: https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/sessions_concern.rb#L21-L22. I think ideally in after authenticated hooks would be configured in the initializer and likely just dispatched to a class controlled by the main application.

**Comment by Dragas** [comment]
+1 on this. There's no elegant way to add assets (for example liquid templates) to shop using this framework. There's also no clear way how `WebHooksManager` and `ScriptTagManager` work, as they're written in WET manner. Instead you have to resort to hacks by rewriting half of `SessionConcerns` module regarding authentication callback and shop session login.

For example:
```ruby
module ShopifyApp
  class Configuration
    attr_accessor :assets

    def has_assets?
      assets.present?
    end

    def assets_manager_queue_name
      @assets_manager_queue_name ||= Rails.application.config.active_job.queue_name
    end
  end

  module SessionsConcern

    def callback
      if auth_hash
        login_shop
        install_webhooks
        install_scripttags
        install_assets
        ShopifyAPI::Base.clear_session
        redirect_to return_address
      else
        flash[:error] = I18n.t('could_not_log_in')
        redirect_to login_url
      end
    end

    def login_shop
      sess = ShopifyAPI::Session.new(shop_name, token)
      session[:shopify] = ShopifyApp::SessionRepository.store(sess)
      session[:shopify_domain] = shop_name
      ShopifyAPI::Base.activate_session(sess)
    end

    def install_assets
      return unless ShopifyApp.configuration.has_assets?

      ShopifyApp.configuration.assets.each do |asset|
        asset[:content] ||= File.open(asset[:value]).read
      end
      ShopifyAPI::Theme.all.each do |theme|
        ShopifyApp.configuration.assets.each do |asset|
          ShopifyAPI::Asset.new(theme_id: theme.id, key: asset[:key], value: asset[:content]).save
        end
      end
    end
  end
end
```

Do note that for this in particular you need `read_themes` and `write_themes` permissions, even though they do not show up when installing the application.

**Comment by kevinhughes27** [comment]
This would be a great first contribution for someone :)

**Comment by Dragas** [comment]
Sadly, that hack breaks `rails g shopify_app:add_webhook` generator.
```ruby
ShopifyApp.configure do |config|
  config.application_name = "My Shopify App"
  config.api_key = ENV["API_KEY"]
  config.secret = ENV["SECRET"]
  config.scope = "read_orders, write_orders, read_products, write_products, read_themes, write_themes,
 read_script_tags, write_script_tags"
  config.embedded_app = true
  config.assets = [
      {key: "snippets/snippet-liquid.liquid", value: 'app/assets/liquid/liquid.liquid'},
      {key: "snippets/snippet-cal  config.webhooks = [
    {topic: 'foo', address: 'bar', format: 'json'},
  ]
endar.liquid", value: "app/assets/liquid/snippet-cal  config.webhooks = [
    {topic: 'foo', address: 'bar', format: 'json'},
  ]
endar.liquid"}
  ]
  config.webhooks = [
    {topic: 'foo', address: 'bar', format: 'json'},
  ]
end
```

**Comment by kevinhughes27** [comment]
added in 7.3.4!
