### ISSUE TITLE
Script tag stops loading after browser restart

### ISSUE THREAD

**Issue by jeffleeder** [Shopify/shopify_app#397]
I have a storefront script tag being added with the script tag manager.

It works fine, but after I close the browser and reopen it.  even if I am logged in still the script doesnt load.

Any Idea why?

If i go to the app page it will start working again, but I dont want anyone to have to do that.

**Comment by kevinhughes27** [comment]
I'd recommend posting this on the forums or emailing dev-support@shopify.com since this is more of a general API issue and not a specific to ShopifyApp
