### ISSUE TITLE
Invalid Signature http request on redirection after install 

### ISSUE THREAD

**Issue by pisanmc** [Shopify/shopify_app#399]
Hello:

I have been working on this issue without success. Any help will be more than appreciated!!

I install a new app using ruby on rails on cloud9 platform and shopify_app.  I follow all the instruction given on the shopify video tutorial: created app and api and secret ID on my shopify partner site, which I installed on env variable in my app.  I push my app to heroku successfully and was able to open it to the home page where I entered my dev web site to install it. 
I succesfully got the installation page but when I click the install, the redirection page gives me a 404 page. 
The http message indicate an invalid signature.  

Here is my heroku app address: 
**https://pacific-bastion-70267.herokuapp.com/**
The http message: 
https://pacific-bastion-70267.herokuapp.com/auth/failure?message=invalid_signature&origin=https%3A%2F%2Fpacific-bastion-70267.herokuapp.com%2Flogin%3Fshop%3Dchloesdev.myshopify.com&strategy=shopify

I tried on chrome, firefox and explorer with the same resuts.  

My github repo is: 
https://github.com/pisanmc/shopifyapp

Thank you for any help.

Marc Pisan

Authentication Issues
---------------------

A great deal of the issues surrounding this repo are around authenticating (installing) the generated app with Shopify.

If you are experiencing issues with your app authenticating/installing the best way to get help fast is to create a repo with the minimal amount of code to demonstrate the issue and a clearly documented set of steps you took to arrive there. This will help us solve your problem quicker since we won't need to spend any time figuring out how to reproduce the bug. Please also include your operating system and browser.

**Comment by mysticaltech** [comment]
@pisanmc I'm having the same error, how did you solve this, please?
