### ISSUE TITLE
Add support for User-driven authentication.

### ISSUE THREAD

**Issue by gavinballard** [Shopify/shopify_app#406]
In a similar way to how the shop-level OAuth authentication is driven, it would be nice for a lot of `shopify_app` users to have an OAuth flow for the user-level authentication.

@Legsman built this into our in-house app framework, but I'm thinking we could open up a discussion of how we can port this into the base gem.

/cc @kevinhughes27

**Comment by kevinhughes27** [comment]
Love this idea! I had some questions at Unite about the current user aspect of Shopify Apps and I haven't personally used it yet so I don't know much. I imagine it would be pretty helpful for developers.

Maybe we can start wit a brief overview of how you've got this built out now and go from there.

**Comment by kevinhughes27** [comment]
I've started a version 8.0.0 branch with some other larger changes. If you'd like to pick this up again now would be a good time to talk about it!

**Comment by gavinballard** [comment]
Cool! Could be a good chance for us to get our own app framework upgraded to `8.0.0` of `shopify_app` as we're still languishing on `6.x`. 

I'm going to be hard pressed to find much time to work on this but maybe we can find some time for @Legsman to take a look at it. Is there something tracking the feature list for `8.0`?

**Comment by Legsman** [comment]
@kevinhughes27 @gavinballard sounds good I can definitely look into it when I got a little time

**Comment by kevinhughes27** [comment]
@gavinballard I have this PR for the next version and we are currently merging things into that branch leading up to the release https://github.com/Shopify/shopify_app/pull/442.

We could add some check boxes to that PR with features we'd like to get in.

**Comment by kevinhughes27** [comment]
Minimal support was added in v8

**Comment by gavinballard** [comment]
Thanks @kevinhughes27! Guess we just didn't get the time to properly look at this, sorry.

**Comment by kevinhughes27** [comment]
No worries! If you do get around to it I'd be curious to see the what other stuff you've got on top of what I added.
