### ISSUE TITLE
Rails 5.1 with latest gem using undefined method 'to_prepare' for ActionDispatch

### ISSUE THREAD

**Issue by mingersoll** [Shopify/shopify_app#407]
The gem package for shopify_app (7.2.6) doesn't include the latest merge request (https://github.com/Shopify/shopify_app/pull/404) which fixes an issue with the session initializer.

I'm trying to generate the shopify app locally using the instuctions in the quickstart.mdb and am getting the error below. I'm using Rails 5.1.0 on Linux Mint 18.1

I'll try going back to Rails 5.0 but the gem should probably be updated to include the latest fixes.

Thanks!

rails generate shopify_app --api_key=MYKEY --secret=MYSECRET
/home/mike/test-app/config/initializers/shopify_session_repository.rb:4:in `<top (required)>': **undefined method `to_prepare' for ActionDispatch::Reloader:Class**
Did you mean?  to_param (NoMethodError)
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:286:in `load'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:286:in `block in load'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:286:in `load'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/engine.rb:655:in `block in load_config_initializer'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.0/lib/active_support/notifications.rb:168:in `instrument'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/engine.rb:654:in `load_config_initializer'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/engine.rb:611:in `each'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/initializable.rb:30:in `run'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/initializable.rb:59:in `block in run_initializers'
	from /home/mike/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
	from /home/mike/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/mike/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /home/mike/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/mike/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/initializable.rb:48:in `each'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/initializable.rb:48:in `tsort_each_child'
	from /home/mike/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `call'
	from /home/mike/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /home/mike/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/mike/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each'
	from /home/mike/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `call'
	from /home/mike/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/mike/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
	from /home/mike/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/initializable.rb:58:in `run_initializers'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/railties-5.1.0/lib/rails/application.rb:353:in `initialize!'
	from /home/mike/test-app/config/environment.rb:5:in `<top (required)>'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/application.rb:92:in `require'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/application.rb:92:in `preload'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/application.rb:143:in `serve'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/application.rb:131:in `block in run'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/application.rb:125:in `loop'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/application.rb:125:in `run'
	from /home/mike/.rvm/gems/ruby-2.4.1/gems/spring-2.0.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/mike/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/mike/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

**Comment by mingersoll** [comment]
I modified the gem locally with the changes suggested in the latest commit and my error went away, so updating the gem online should do the trick :D

**Comment by StraubCreative** [comment]
I'm getting the same error and need more information. What suggestions? What gem version?

**Comment by mingersoll** [comment]
@StraubCreative I modified the shopify_app gem which is version 7.2.6. 

Sorry my last comment wasn't clear, the commit I was referring to was part of the merge request in my original comment. This merge request here:  https://github.com/Shopify/shopify_app/pull/404. In this merge request changes were made to the initializer template (lib/generators/shopify_app/shop_model/templates/shopify_session_repository.rb). I made the same change locally and stopped getting the error about the ActionDispatcher::Reloader. 

My gem file for the shopify_app example includes these two lines and it works:
gem 'shopify_app', '~> 7.2', '>= 7.2.6'
gem 'activeresource', github: 'rails/activeresource', branch: 'master'

Hopefully this helps!

**Comment by StraubCreative** [comment]
@mingersoll it worked! Thanks for your help 👍

**Comment by IAM07** [comment]
@mingersoll @StraubCreative  How exactly do i make these changes? Could you provide screenshots?

**Comment by mingersoll** [comment]
@IAM07 The Merge request that I linked too shows the commits that were made and the file changes. The files to update will be found in your shopify_app directory. The GemFile will also be in there, just make sure the two lines I mention at the bottom of my post are in there.

**Comment by IAM07** [comment]
/Users/iam07/newmltagr/config/initializers/shopify_session_repository.rb:4:in `<top (required)>': undefined method `to_prepare' for ActionDispatch::Reloader:Class
Did you mean?  to_param (NoMethodError)

This is the error that won't go away. Any help you can offer?

**Comment by mingersoll** [comment]
@IAM07 Yes, the changes I made and included in this comment thread fix exactly that error.

**Comment by IAM07** [comment]
@mingersoll I'm a beginner so please bear with me. So, I changed the gem file using  vim Gemfile and pasted the two lines you suggested. I then installed the bundle using bundle install and then tried to generate. Am i missing a step or where do you think i've gone wrong? Thanks in advance

**Comment by mingersoll** [comment]
@IAM07 No worries, I'm also new to ruby. You missed the changes in the other files that I mentioned (the initializer template). Try a bundle update first before the install as well. This will update your gem lock file which is then used in your install. If you don't do the update I don't think the install will pull anything different. Part of being a beginner is trying lots of different things and failing until it works. Don't be afraid to fail!

**Comment by shashrao** [comment]
@mingersoll  I'am using rails 5 and installed gem "activemessaging"  and bundle update for app/processors...but its giving <class:Railtie>': undefined method `to_prepare' for ActionDispatch::Callbacks:Class (NoMethodError)...the same gem was working fine in rails 4.x....

**Comment by shashrao** [comment]
thf

**Comment by imam-scs** [comment]
I'am using rails 5 and installed gem "devise_google_authenticator" and bundle install, but while using it gives Gem Load Error is: undefined method `to_prepare' for ActionDispatch::Callbacks:Class (Bundler Error Backtrace:)

**Comment by imam-scs** [comment]
I'am using rails 5.2.1 and installed gem "devise_google_authenticator" and bundle install, but while using it gives (Bundler::GemRequireError)
Gem Load Error is: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Bundler Error Backtrace:
