### ISSUE TITLE
Testing webhooks controller

### ISSUE THREAD

**Issue by vrehm** [Shopify/shopify_app#413]
Hello,

We've got a ruby on rails app connected to our shop courtcircuit.myshopify.com.
We use the shopify_app gem and we've got this concern :

We cannot figure out how to test our custom webhooks_controller.rb with RSpec. We have following code  
```
context 'when order/paid' do
    it 'returns a 200 OK' do
      params = File.read('spec/fixtures/files/webhook_order_paid.json')
      headers = {
        'HTTP_X_SHOPIFY_SHOP_DOMAIN' => shop.shopify_domain,
        'HTTP_X_SHOPIFY_HMAC_SHA256' => calculate_webhook_hmac(params),
        'HTTP_X_SHOPIFY_TOPIC' => 'orders/paid',
        'CONTENT_TYPE' => 'application/json; charset=utf-8',
        'ACCEPT' => 'application/json'
      }
      post :orders_paid, body: params, headers: headers
      expect(response.code).to eq('200')
    end
  end
```
that raises a `NoMethodError: undefined method `bytesize' for nil:NilClass` on post.

I found out that this error is raised in the `shopify_app/lib/shopify_app/webhook_verification.rb`
params is a hash that I got from an API call with same fields as our webhook.

Do have an idea on how to make it works or do you have a sample code on how to test a custom webhook_controller ?

Thanks.
Greetings

Vincent

**Comment by vrehm** [comment]
@RomainMorlevat @damienlethiec

**Comment by RomainMorlevat** [comment]
I found a workaround. In the webhooks controllers, I've put :
`include ShopifyApp::WebhookVerification unless ENV['RAILS_ENV'] == 'test'`
And in my specs, I've created a new class that inherit from the respective webhook controller to overload some methods in order to work. And I run my test on this class.

**Comment by kevinhughes27** [comment]
@vrehm I can't see anything obviously wrong with your code. It must be a subtle difference in param names or an issue with what your rails controller actually receives from the test. I'd recommend putting a debugger statement in the concern and seeing if one of the params is nil. If you still can't figure it out can you make a repo that reproduces the issue that I can pull down? Either way let me know how it goes :)
