### ISSUE TITLE
Webhook doesnt create

### ISSUE THREAD

**Issue by RedNoo** [Shopify/shopify_app#418]
Hi,

I am adding webhook via webhooks manager with following code. Webhook rows added in shopfy_app.rc in inititilazer folder. And job created. But there is no webhook in store settings when I installed the app.

How can I fix this?

Thanks in advance. 

`rails g shopify_app:add_webhook -t carts/update -a https://example.com/webhooks/carts_update`

**Comment by kevinhughes27** [comment]
How are you checking that the webhook is installed? If you are using the
browser that will show the shop owned webhooks not the app owned ones. You
need to use an api call with your apps credentials to see your webhooks.

**Comment by RedNoo** [comment]
Hi Kevin,

Thanks your reply, I was looking at the webhooks on the store settings screen

Best
Onder


![2017-05-29_16-13-52](https://cloud.githubusercontent.com/assets/527050/26551248/37e03302-448a-11e7-84ed-61df43efbbe6.png)

**Comment by kevinhughes27** [comment]
App created webhooks won't show there. Hit the webooks Json endpoint with
your credentials and you'll see it. This can be closed.

**Comment by RedNoo** [comment]
Thanks a lot.
