### ISSUE TITLE
Consider removing 'Logged in' Message 

### ISSUE THREAD

**Issue by Hammadk** [Shopify/shopify_app#424]
We currently show a [`Logged in` message everytime](https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/sessions_concern.rb#L24) someone visits an app from the Shopify admin. I think that we should remove this message because:
* Merchants see a `Logged in` message on every single app -- and that can get annoying if you use many different apps
* From a merchant's point of view, `Logged in` doesn't make sense because they are not explicitly passing their credentials to the app every time. All of that happens under-the-hood so the `Logged in` message seems unnecessary.
* When a merchant does use an app, it is obvious that they able to use it.

What do you think about this? @davekilljoy  @kevinhughes27 

<img width="257" alt="screenshot" src="https://user-images.githubusercontent.com/129764/27495473-fcbb0f46-581f-11e7-878d-e03dbd8826ea.png">

**Comment by kevinhughes27** [comment]
I agree we should remove this as it is confusing.
