### ISSUE TITLE
Updating an app

### ISSUE THREAD

**Issue by Dragas** [Shopify/shopify_app#441]
Recently I've come into issue that my shopify app whould require an update. For example it now requires additional metafields, has to install an additional asset to the theme or etc. Besides providing an additional metafield that holds the version used by that shop and then running migration-like pipeline to update the shop's metadata to current one used by the app, is there a simpler way to push an update? Are Shopify Apps even meant to be updated?

**Comment by kevinhughes27** [comment]
You can definitely update your app (defined as updating what things your app has registered on each shop that has installed it). Any of these actions can be performed at any time this Gem just happens to include some helpers to do these actions on install which is typically what people want. In your case you'll need to write a script/job/task that loops through all the shops who have installed your app and make any required changes. This Gem doesn't provide any constructs for such a thing but its pretty straightforward with ruby code:

```ruby
Shop.find_each do |shop|
  shop.with_shopify_session do
    # register new things
  end
end
```

**Comment by Dragas** [comment]
Are you sure? Executing that from a `rake` task returns `401: Unauthorized` on each shop that has your app installed.

**Comment by kevinhughes27** [comment]
I'm 100% sure. Its the same code that runs after a web request comes in to your app for a given shop - Rails looks for that shop in the database and uses its token to authenticate Shopify API calls. 

If you are not listening to app uninstall webhooks its very likely that you have a lot of shops in your database that have been uninstalled and thus the tokens are not valid. You can try manually doing one iteration of the loop with a Shop you know still works.
