### ISSUE TITLE
How to authenticate the Shopify Customer from App Proxy

### ISSUE THREAD

**Issue by bharder** [Shopify/shopify_app#448]
I have created an unlisted app, defined an app proxy URL, and installed it into a development store.

When I call the App Proxy URL, I see that an "X-Logged-In-Customer: 1" header is being passed if the customer has logged into the store.  However, there is apparently no way to determine who the customer is.  Our only workaround for this has been to pass the Shopify customer_id and e-mail, and then to query the customer using the Admin API, and verify the e-mail matches (basically treating the combination of e-mail and customer id as a secret).

Am I missing something?  Could Shopify make App Proxy changes to add an "X-Logged-In-CustomerId" header that will contain the Shopify customer.id ?

**Comment by kevinhughes27** [comment]
Can you post the issue on the forums or open a dev-support ticket please? This isn't an issue with this gem but more of a general question for app development and proxy use.
