### ISSUE TITLE
New Error - The authorization code was not found or was already used

### ISSUE THREAD

**Issue by charlesemarsh** [Shopify/shopify_app#449]
Hello All, 

I have a live Shopify App which was last updated 3 months ago, however new users are unable to install the application and get the error "The authorization code was not found or was already used"

The app is running:

rails 5.0.1
shopify_app (7.3.0)
omniauth-shopify-oauth2 (1.2.0)

The error appears during the Shopify callback to Omniauth 

https://order-tagger.herokuapp.com/auth/shopify/callback?code=df9f132ab1b82384f26301dd3c3fc1d3&hmac=b074bc08fc775b0542012ecb8506310374f01d15bd6e9d0e5b7ce58025689ef1&shop=leumasappstesting.myshopify.com&state=ae07b2abe1c219adffc8b10672f1a0d44526b1a97b5ad321&timestamp=1502094554

The 'code' is present, so I'm guessing that the code has already been used for some reason? I have seen this issue on Stackoverflow "https://stackoverflow.com/questions/42780268/error-generated-while-trying-to-create-shopify-access-token" but this case in different, I'm not doing any fancy redirecting. 

Does anyone have any idea what could be causing this issue?

**Comment by tanema** [comment]
👋 @charlesemarsh Do you have any information when this error started to happen or has this always been happening?

**Comment by tanema** [comment]
Also is there a possibility that this link is being loaded twice? Like the solution of the SO issue you linked they were loading it once and pressing their back button. The access code is expired after viewed once so upon loading that link the second time you will receive this error.

**Comment by mikeletscher** [comment]
I upgraded from `7.3.0` to `8.0.0` and am now having this issue as well. I enter my Shopify domain on my app's install screen, hit Authorize in the Shopify admin page, and am immediately hit with this:

<img width="1680" alt="screen shot 2017-08-27 at 6 50 50 pm" src="https://user-images.githubusercontent.com/6666411/29754705-e2d16744-8b58-11e7-996f-b6f94dfcec34.png">

Within the giant HTML dump I also see
```
Oauth error invalid_request: The authorization code was not found or was already used
```

After running `bundle update shopify_app` I reset the database, restarted the app, and uninstalled the app from my Shopify store. Still getting the same error each time.

**Comment by mikeletscher** [comment]
Figured it out! Running the generator duplicated the provider in the omniauth initializer. Removing that extra provider for shopify solved the issue.

**Comment by kevinhughes27** [comment]
You shouldn't need to run the generator to update the gem. We try our best to keep as much code as possible in the gem to avoid this.

**Comment by FeSens** [comment]
> Figured it out! Running the generator duplicated the provider in the omniauth initializer. Removing that extra provider for shopify solved the issue.

I was having a problem using it with devise, removing the `omniauth.rb` initializer solved my problem thank you!!
