### ISSUE TITLE
Scheduling job right after app install not working.

### ISSUE THREAD

**Issue by amorimlucas** [Shopify/shopify_app#450]
Hey guys,

My app is pretty much done and working great! This gem was a huge help, and much appreciated.

Now I'm trying to figure out how to schedule a job to send out an email right after a user installs my app. I've been trying to use the code you guys mention on the docs for this:

```
ShopifyApp.configure do |config|
  config.add_after_authenticate_job = { job: Shopify::AfterAuthenticateJob }
end
```

I can't get it to work. Do I need to just replace `Shopify::AfterAuthenticateJob` by a call to my custom job?

Thanks, Lucas.

**Comment by kevinhughes27** [comment]
Yup! We'll queue that job each time the auth flow is finished:
https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/sessions_concern.rb#L23
https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/sessions_concern.rb#L91

**Comment by amorimlucas** [comment]
Thanks @kevinhughes27! Also, I forgot to ask: How should I pass the new user's shop data into this job? Will ShopifyAPI::Shop work in this config block?

**Comment by kevinhughes27** [comment]
the shop_domain is passed to the job so you'll need to loop up the shop and use `with_shopify_session`

**Comment by amorimlucas** [comment]
I think I'm misunderstanding how it works a bit. Would this code be correct:

```
ShopifyApp.configure do |config|
  config.add_after_authenticate_job = { job: Delayed::Job.enqueue MyCustomJob.new(params) }
end
```

I'm not sure if I should schedule my job like this or inside the Shopify::AfterAuthenticateJob definition? In the latter case, where would I define this Shopify::AfterAuthenticateJob?

**Comment by kevinhughes27** [comment]
you need to pass a job class to the `job:` param. Shopify App will queue it for for with the right params. You need to be using ActiveJob for this to work. Have a look at the code I linked above it will be more clear if you see it.

**Comment by amorimlucas** [comment]
I'm using `config.add_after_authenticate_job = { job: AppInstalledJob }`

But I'm getting `NameError: uninitialized constant AppInstalledJob`

**Comment by kevinhughes27** [comment]
does your app define that job somewhere? Check that its in the right folder / filename for rails to load it. You can try adding an explicit require in that file as well.

**Comment by amorimlucas** [comment]
Now I'm getting:

`NoMethodError: undefined method `add_after_authenticate_job='`

**Comment by kevinhughes27** [comment]
make sure you are using the latest version of the gem. This was only added in 7.4.0

**Comment by amorimlucas** [comment]
Was that app version released yet? It can't be found when I try to install it.

**Comment by kevinhughes27** [comment]
hmm looks like perhaps no one pushed that version to ruby gems. @alanhill can you cut a release for 7.4.0 please!

@amorimlucas in the meantime you can point to github master or the v8 branch if you want to get ahead :) https://github.com/Shopify/shopify_app/pull/442

**Comment by amorimlucas** [comment]
I'm using the master branch:

`Using shopify_app 7.4.0 from https://github.com/Shopify/shopify_app (at master@6efe521)`

But I'm still getting this:

`NoMethodError: undefined method `add_after_authenticate_job=' for #<ShopifyApp::Configuration:0x00564171804dd8>`

**Comment by kevinhughes27** [comment]
I looked at the config class this is what the method is called `after_authenticate_job`.

**Comment by amorimlucas** [comment]
I got everything working, thanks for your help! My app's already in production and I'd like to specify the version in my Gemfile. When do you think the latest version will be pushed?

**Comment by kevinhughes27** [comment]
Probably within the next 2 weeks
