### ISSUE TITLE
New "after_authenticate_job" not working as expected.

### ISSUE THREAD

**Issue by amorimlucas** [Shopify/shopify_app#451]
Hey, guys. I chatted yesterday with @kevinhughes27 about the "after_authenticate_job" feature that will be released with 7.4.0. I have it implemented like so:

`config.after_authenticate_job = { job: InstalledAppJob }`

And my `InstalledAppJob` triggers correctly on an app install.

**BUT** it is also randomly triggering this job long after the app has been installed. What could be causing this?

**Comment by amorimlucas** [comment]
I should mention that I'm trying to implement a script that updates a RecurringApplicationJob object, but so far I have **only** retrieved data to inspect, and haven't updated any yet.

**Comment by amorimlucas** [comment]
Indeed it looks like this line of code is triggering the job:

`ShopifyAPI::RecurringApplicationCharge.find(:all).sort_by(&:created_at).reverse.first`

**Comment by kevinhughes27** [comment]
This job will get triggered any time the app is authenticated. That is why the hook is called `after_authenticate_job` not `after_install_job`. We recommend to make this job idempotent to avoid issues.

How did you confirm that that line of code triggers the job?

**Comment by amorimlucas** [comment]
I see, that might explain it then. Right next to that code I run:

```session = ShopifyAPI::Session.new(params[:shop_domain], token)
ShopifyAPI::Base.activate_session(session)```

Which re-authenticates the app, right?

**Comment by amorimlucas** [comment]
@kevinhughes27 Another question on this same topic: Is it possible to update a RecurringApplicationCharge object? I want to extend the trial period of an app install. I tried this yesterday:

```
@rac_def = ShopifyAPI::RecurringApplicationCharge.find(:all).sort_by(&:created_at).reverse.first
@rac_def.trial_days = "7" 
@rac_def.save 
```

But this code returns a 406 Not Acceptable error.

**Comment by kevinhughes27** [comment]
Adding a column will solve this for you. Deploys shouldn't necessarily cause you to re-authenticate but it could depending on how your sessions are configured. In general re-authentication will happen though so you need to plan for it.

I'm not sure about that API call. I'd recommend posting on the Shopify API forums.
