### ISSUE TITLE
Install - favicon error

### ISSUE THREAD

**Issue by tonylinde** [Shopify/shopify_app#452]
Apologies if this is an inappropriate post - I'm new to github & just trying to get started with Shopify app development.

I went through the process of installing the shopify_app (into Rails environment installed in _Bash on Ubuntu on Windows_). When I clicked the Install button, I got this error: 

```
Sprockets::Rails::Helper::AssetNotFound in Home#index
Showing /mnt/c/Users/tony/Dropbox/Development/apps/thirdone/app/views/home/index.html.erb where line #6 raised:

The asset "favicon.ico" is not present in the asset pipeline.

4      ShopifyApp.Bar.initialize({
5        title: "Home",
6        icon: "<%= asset_path('favicon.ico') %>"
7      });
8    });
9  </script>

Rails.root: /mnt/c/Users/tony/Dropbox/Development/apps/thirdone

Application Trace | Framework Trace | Full Trace
app/views/home/index.html.erb:6:in `block in _app_views_home_index_html_erb___707325732876759868_70368593507960'
app/views/home/index.html.erb:1:in `_app_views_home_index_html_erb___707325732876759868_70368593507960'
Request

Parameters:
None

Toggle session dump
Toggle env dump
Response

Headers:
None
```

I just deleted the offending line 6 and it seemed to install ok. Had another error after that but will post separate.

**Comment by kevinhughes27** [comment]
This bug started with Rails 5 since the favicon changed I think. I removed this line from the generator for v 8.0.0.

Thanks for reporting!
