### ISSUE TITLE
Products listed then disappear

### ISSUE THREAD

**Issue by tonylinde** [Shopify/shopify_app#453]
I got the shopify_app installed ok. It then listed the first ten products in the store on an otherwise blank web page - [screenshot](http://i.imgur.com/DRc9i9V.png) - which almost immediately disappeared (found that I could freeze the page by pressing CTRL-S to save it) to be replaced by a blank App page - [screenshot](http://i.imgur.com/mzHaBzC.png). 

I'm new to Shopify app development (& Ruby & Rails!) and just trying to get something to work: apologies if questions like this are inappropriate here but questions on ecommerce.shopify.com have not been answered.

BTW, I'm using latest 7.3.0 version of shopify_app but the same thing happened previously with v7.2.11. Browser is latest version of _Chrome Windows_. Rails installed & running in _Bash on Ubuntu on Windows_.

**Comment by kevinhughes27** [comment]
When you first see the products is your app outside the admin? And then it gets pulled inside the admin and the products disappear?

I think this is because the ESDK doesn't support non ssl content. You need to develop locally using ngrok or forward or another method to allow ssl on your local server.

**Comment by tonylinde** [comment]
> When you first see the products is your app outside the admin? And then it gets pulled inside the admin and the products disappear?

Exactly that, Kevin. 

> I think this is because the ESDK doesn't support non ssl content. You need to develop locally using ngrok or forward or another method to allow ssl on your local server.

Thanks. You wouldn't have a link that shows how to use ngrok or forward would you?

**Comment by kevinhughes27** [comment]
ngrok's website should explain it fairly well. There is also a small section in our readme about it: https://github.com/Shopify/shopify_app#app-tunneling. Tunneling will change your URL so you'll need to update the app settings in the Partner Dashboard as well.
