### ISSUE TITLE
Uninstall and installing again is not working - Persistent cookies

### ISSUE THREAD

**Issue by flavio-b** [Shopify/shopify_app#456]
Hello, I'm working on an app built with Rails 5.1 (Ruby 2.3.3) and ShopifyApp 7.4.0. 

I believe I've narrowed down the cause, but I can't figure out what I'm doing wrong:
If I uninstall and try to install my app again, the browser still sends the original session cookie, which messes up the installation process. If I clear the cookies, everything works. 

How can I make sure the cookie is deleted after the app is uninstalled? I haven't done anything different in other app that I have published (7.2.0 and 7.3.0), and the uninstall/install process works just fine. Thank you.

**Comment by kevinhughes27** [comment]
This is a known issue that can't really be avoided since there is no way to know that you need to remove the cookie from the client. I'm pretty sure this issue is present in all versions of this gem.

**Comment by flavio-b** [comment]
Thanks Kevin! This problem is holding up an app approvel for me. Can I link your reply to the review team?  I just don't know why or how my other 2 apps work when I uninstall and install again though. I haven't changed anything in the auth process. I've inspected the requests, and they look similar. On my other apps, even when the browser resends the session cookie, somehow it ignores i, redirects to login and sets a new cookie correctly.

**Comment by kevinhughes27** [comment]
Sure.

I should mention that I think this only affects embedded apps since its the fact that it tries to render inside the admin for an app that doesn't exist anymore that is the problem.

**Comment by flavio-b** [comment]
Yeah, that's it. The server seems to assume it's a valid session and tries to render the app. I can see the home screen of the app appear for a second, then it redirects to admin and it gives a "Page not found" for acme.myshopify.com/admin/apps/appkeyhere     
My other apps are also embedded though.

**Comment by kevinhughes27** [comment]
I'm pretty sure this happens on your other apps as well then - have you tested them? Are they all configured to use the same Rails session?

**Comment by flavio-b** [comment]
Yes, I've just tested them. Please give it a try here and perhaps you can see something I don't: 
https://apps.shopify.com/multi-label-barcodes

**Comment by kevinhughes27** [comment]
I believe you :)

Can you share your session config for each app?

**Comment by flavio-b** [comment]
Hm.. I'm not too familiar with Rails yet, but I believe this is the file you're looking for:
**config/initializers/session_store.rb**
`Rails.application.config.session_store :cookie_store, key: '_multi-printer-barcodes_session'`

Both working apps are identical except for the key name string. I just realized my new app doesn't have a session_store.rb file... though. Let me know if you need to take a look at any other file.

**Comment by kevinhughes27** [comment]
it might have moved in Rails 5. Can you search for `Rails.application.config.session_store` or `session_store` in general?

**Comment by flavio-b** [comment]
No, I can't find that config or session_store within the new app files. The other 2 apps are both Rails 5, the new one is 5.1.
There's only a config/initializers/shopify_session_repository.rb file:
```
if Rails.configuration.cache_classes
  ShopifyApp::SessionRepository.storage = Shop
else
  reloader = defined?(ActiveSupport::Reloader) ? ActiveSupport::Reloader : ActionDispatch::Reloader

  reloader.to_prepare do
    ShopifyApp::SessionRepository.storage = Shop
  end
end
```

**Comment by kevinhughes27** [comment]
If you use version 8 you don't need that file anymore :)

Can you try adding that session config to your rails 5.1 app (maybe look at the docs for sessions in the new rails in case something changed)

**Comment by flavio-b** [comment]
Hi Kevin, thanks for following up. Adding session config didn't work, but I believe to have found the problem: Check out `login_protection.rb` . There's a rescue clause there for `ActiveResource::UnauthorizedAccess`, which closes the session. This wasn't being called on my new app because **my root handler does not make any call with `ShopifyAPI`, so no error was raised.**

So, here's what was happening with my working apps, wherever the user goes to **reinstall** it:

1. GET / --> There's a session still, so tries execute root action.
2. Root action calls `ShopifyAPI`, an error is raised.
3. Error is rescued inside `login_protection.rb`, which closes the session and redirects to login.

So, now I've added a _dummy_ `ShopifyAPI::Shop.current` to my root action and everything works as expected. I'm not sure this is the best way to solve the issue. Any thoughts on this?
Thanks.

**Comment by kevinhughes27** [comment]
Ah that makes sense. I'm glad you figured it out. Your solution makes sense to me

**Comment by alex-espinoza** [comment]
In case anyone else runs into this problem, my app also did not call the Shopify API in its root action:

`root :to => 'home#index'`

Like flavio-b described, just put a Shopify API call in the root route controller action.

In my case:

`class HomeController < AuthenticatedController
  def index
    ShopifyAPI::Shop.current
  end
end`

This fixed the issue and my app can now be uninstalled and reinstalled without issue. Weird edge case indeed.

**Comment by netwire88** [comment]
This is still happening in v12 of this gem using AppBridge. Adding `ShopifyAPI::Shop.current` in `home#index` solves it.

**Comment by dianedouglas-thrive** [comment]
I'm still having this issue if anyone has any suggestions. I'm on  rails 6.0.3.4, version 17.0.5 of this engine, ruby 2.7.1, using the `allow_jwt_authentication` authentication strategy. If I uninstall and reinstall I get the 'There’s no page at this address.' error.

Here is my home controller:

```
# frozen_string_literal: true

class HomeController < ApplicationController
  include ShopifyApp::EmbeddedApp
  include ShopifyApp::RequireKnownShop

  def index
    @shop_origin = current_shopify_domain
  end
end
```

If I call the recommended `ShopifyAPI::Shop.current` from index it just results in `ApiVersionNotSetError` or if I make any other api calls I get `ActiveResource::UnauthorizedAccess (Failed.  Response code = 401.`.  

Any advice very appreciated please. Is the recommended fix to delete the shop record entirely using the app/uninstalled webhook?

**Comment by flavio-b** [comment]
@dianedouglas-thrive, I haven't had the chance to try JWT yet, so don't really know how it all works.

But that API call was just a way to make it detect a stale session, raising `ActiveResource::UnauthorizedAccess`. This error was rescued by `login_protection.rb`, which redirected to login.

Check if you can redirect manually, upon seeing that error. I have no idea if that's the best way though.

On a separate note, I think the API version is set when the application boots up, so maybe there's a bug. Double check if the version is specified in `config/shopify_app.rb`.

Some users often uninstall and reinstall apps quickly to try to get rid of bugs/errors, so fully deleting the `shop` record could create some issues here, like losing app preferences etc. I hope there's a better way.

**Comment by dianedouglas-thrive** [comment]
Hi @flavio-b thanks so much for the response! 

> I haven't had the chance to try JWT yet

As I understand it, this is the only way to authenticate an embedded app. My app came back from review and I was told to implement session tokens, which as far as I understand it is what JWT is. 

> Check if you can redirect manually, upon seeing that error. 

I looked in the login_protection.rb file and tried using the `redirect_to_login` method but it's undefined and so is the `login_url` itself oddly, even though I see it in rake routes. 

> Double check if the version is specified in config/shopify_app.rb

Yup, confirmed. 

```
config.api_version = '2021-01'
```

> fully deleting the shop record could create some issues here, like losing app preferences etc. I hope there's a better way.

Yeah, that's what I'm hoping. Fully deleting fixes this, but it does erase shop dependencies too that would cause problems after reinstalling. I have a db model that the Shop has a has_many relationship with, so the merchant would have to recreate these db records after a reinstall, which is not ideal. 

It seems like the session token is invalid on a reinstall, and the user is not making it to the permissions screen at all where they would grant access to scopes. Instead they are redirected to a page that doesn't exist.

Please let me know if you have any other suggestions.  Thanks!

**Comment by flavio-b** [comment]
Hi @dianedouglas-thrive, 

Using JWT in this gem is somewhat new. Before, it used to rely exclusively on cookies for authentication, which has its troubles. So JWT is the recommended way to go now.

BTW, ShopifyApp is a "Rails Engine", so routes added by it are kind of separate. You can access them in your controllers and views using `shopify_app.login_path`, for example. ([docs](https://guides.rubyonrails.org/engines.html#routes))

Perhaps try creating your own `redirect_to_login` and see if it works. When I have more time to migrate to JWT's, I'll post something back with any findings too. Meanwhile, I hope someone will point out the best practices for this.

**Comment by dianedouglas-thrive** [comment]
Hi again @flavio-b, I appreciate the context. I initially used the cookie auth and had no issues with that, but apparently that isn't allowed for an embedded app for some reason and we have to use JWT (according to my app review). 

I tried creating a redirect to login as you suggested, but that did not allow the installation to complete because I am just continually redirected to login. Perhaps I wasn't following what you were suggesting though, so here is my index method in my home controller. 

```
  def index
    begin
      ShopifyAPI::Shop.current
    rescue Exception => e
      redirect_to(shopify_app.login_path)
    end
    @shop_origin = current_shopify_domain
end
```

I think I'm getting the API version not set errors because the session is not activated, and when I try to activate the session like this, I get a 401 error which says my token/password is invalid after an uninstall/reinstall: 

```
      session = ShopifyAPI::Session.new(
        domain: shop.shopify_domain,
        token: shop.shopify_token, 
        api_version: API_VERSION
      )
      ShopifyAPI::Base.activate_session(session)
```

This way of making api calls after activating the session as above works generally for other api calls in the app, and I get 'version not set errors' if I don't do this before an api call. But after an uninstall I can't activate the session this way because of the 401 errors.

I think my only option at this point is to delete the Shop record on uninstall to prevent this, but please do let me know if you have any other ideas. Thanks so much again for your time!

**Comment by robbyklein** [comment]
Is there any alternative here beside deleting the record from the database? 

My app stores data as metafields and needs to remain in sync with the database. Deleting the record would create problems.
