### ISSUE TITLE
Unable to change asset through the API

### ISSUE THREAD

**Issue by amorimlucas** [Shopify/shopify_app#458]
I have an app that generates product images as part of its functionality. I've noticed that some themes have an img_url that is too small, and the generated image looks blurry. So I want my app to update the product image img_url tags (in the product.liquid file) so they are always "1000x1000".

I'm able to retrieve the asset as shown here, but I haven't found a way to update the asset through the API. Is there a way? Also, is this the recommended way to accomplish what I'm trying to do? Thanks.

**Comment by kevinhughes27** [comment]
This question is more about Shopify's API and not about the rails engine. Can you post on the API forums or contact dev-support@shopify.com
