### ISSUE TITLE
Generator issues

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#461]
/Users/dlazar/Documents/Workspace/fuztky/config/initializers/shopify_app.rb:9:in `block in <top (required)>': undefined method `add_after_authenticate_job=' for #<ShopifyApp::Configuration:0x007f871533c248> (NoMethodError)
Did you mean?  after_authenticate_job=

I found that when playing with the newer features of the gem, there is a typo in the generator? 

    ShopifyApp.configure do |config|
        config.add_after_authenticate_job = { job: Shopify::AfterAuthenticateJob }
    end

I think it is simply:
    add_authenticate_job as a method and not add_after_authenticate_job. Anyone else notice this? Iam using gem as per my bundle listing here. Not sure I get why this method is a problem, the source code seems to provide the method.  

    shopify_app (8.0.0)
        omniauth-shopify-oauth2 (~> 1.2.0)
        rails (>= 5.0.0)
        shopify_api (>= 4.3.2)

**Comment by kevinhughes27** [comment]
`add_after_authenticate_job` is the name of the generator and `after_authenticate_job` is the config variable. I think the issue here is probably more with the readme/documentation than the code. Does that sound right to you? How did you end up with `add_after_authenticate_job` in your initializer?

**Comment by resistorsoftware** [comment]
the docs...
 
    config.add_after_authenticate_job = { job: Shopify::AfterAuthenticateJob }

**Comment by kevinhughes27** [comment]
ah those are wrong. Sorry about that.
