### ISSUE TITLE
Merchant Awareness Issue

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#462]
If I setup a scope as such:
    
    config.scope = 'write_products, write_orders, write_shipping'

The merchant is told the App will be modifying products and orders, but there is zero indication shipping is also in play. Is that expected?

**Comment by kevinhughes27** [comment]
@EiNSTeiN- who owns the grant screen right now? Sounds like an issue to me (although not related to ShopifyApp)

**Comment by EiNSTeiN-** [comment]
@Shopify/apps-platform

**Comment by tanema** [comment]
I am not sure why this is, it should show up because this is how they are excluded from view 

https://github.com/Shopify/shopify/blob/master/components/apps/app/models/access/scope_set.rb#L29

and it is querying scopes.yml which does not exclude it from authorization.

https://github.com/Shopify/shopify/blob/master/db/data/access/scopes.yml#L164

I can take a quick look into this. Do you have an app that requests this that I can test on?

**Comment by thuva** [comment]
@tanema I created an issue https://github.com/Shopify/shopify/issues/128140 to update the grant screen and added the `Component: Apps` label. Feel free to assign it to yourself.

**Comment by resistorsoftware** [comment]
This remains a problem. Apps with scope on Shipping fail to inform the merchant. 

    config.scope = 'write_products, write_orders, write_shipping'

produces a screen of just this for the install:

<img width="791" alt="tag_home_decor___authorize_tag_home_decor_shipping___shopify" src="https://user-images.githubusercontent.com/123307/30921841-79f40f76-a375-11e7-9b09-a743f4a2daea.png">

**Comment by peterjm** [comment]
@resistorsoftware 

Hi David,

Sorry for the lack of response earlier. I believe the notification that shipping access has been requested is visible after clicking on "View details", beside "Manage orders". The "write_shipping" scope is what creates the "shipping information" piece of that text.

<img width="720" alt="screen shot 2017-09-27 at 1 13 39 pm" src="https://user-images.githubusercontent.com/55985/30927261-e777b4d4-a385-11e7-979a-ce3f6d1550e4.png">

I'm going to close this issue as "working as expected". However, I'll forward a link to our UX team, so they can take note of the fact that at least some people are confused by the way that our permission notifications are displayed.

**Comment by resistorsoftware** [comment]
Good enough. It is not like screen real-estate is at a premium here, so hiding information behind links is not needed and seems like Yak shaving as an internal effort. Why bother with the extra UX when you can clearly just present the implications.
