### ISSUE TITLE
Uncaught Error: Can't resolve all parameters for AuthService: (?).

### ISSUE THREAD

**Issue by mayordwells** [Shopify/shopify_app#466]
I have this very confusing error and I have no idea what to ask google.
I am using auth0 on an angular + rails app to help with authentication between a Shopify App in Rails and the front end of the app in Angular, I am using webpacker. 
The rails app currently works with Shopify but we are currently working a separate interface on the front end in angular in.
When I remove AuthService from the providers array in app modeul everything works fine.
But when AuthService is available in providers array, I am getting this error:
My AuthService is exactly same as what I found in the documentation and git commit.
I am trying to use Auth0 the Authentication of our app to allow the user to login and logout with a shopify account, create a shopify store.
 
Somebody Please help me out.
Here's what my AuthService parameters look like:

auth0 = new auth0.WebAuth({
    clientID: AUTH_CONFIG.clientID,
    domain: AUTH_CONFIG.domain,
    responseType: 'token id_token',
    audience: `https://${AUTH_CONFIG.domain}/userinfo`,
    redirectUri: 'http://localhost:5000/callback',
    scope: 'openid'
  });
Currently, when I authenticate with Rails, Everything works fine. But once we work the redirect to angular app. The session is lost.
How can we get the session parameters/request parameters from rails in my angular 4 app.

**Comment by kevinhughes27** [comment]
Are you using the ShopifyApp gem? If so you shouldn't need Auth0 we handle all the authentication and token storage as part of the gem. I am closing this issue since it looks to me like it is not related with this repo. This question would be better suited for the Shopify developer forums.
