### ISSUE TITLE
First request hangs

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#468]
Using the new 8.1 gem, the idea is to use a session to store some OmniAuth info, rather than using a redirect with a GET parameter. Ok... 

I still have the same issue as before now, and cannot quite grasp the solution. If I start a new session with the App, it hangs on first hit. If I refresh, the second hit works instantly. If I stop Rails server in my console and restart it, and refresh the App, it hangs. It works perfect second hit. 

So it seems that something is up with the authentication code? I am not sure this is related to the Asset pipeline hanging. Why is it that any new Rails server on localhost will hang the App. The console shows the delivery of the App with a 200 OK status... but nothing is rendered. 

So this remains a mystery to me, on how to solve. Is annoying to have to manually refresh the browser every time a session expires and not have the App just refresh itself to get a new session going.

**Comment by kevinhughes27** [comment]
Can you create an example repo that reproduces the problem? I don't experience this on new apps or in my production app.

**Comment by resistorsoftware** [comment]
will do... can I give you access to a private repo?


514.795.9601
Book an Appointment!
https://calendly.com/dlazar

**Comment by kevinhughes27** [comment]
I guess that would work. Part of the idea behind asking for a new repo is to break the problem down to it simplest version

**Comment by resistorsoftware** [comment]
Got it... will whip up a sample that exhibits the problem with nothing
else...


514.795.9601
Book an Appointment!
https://calendly.com/dlazar

**Comment by resistorsoftware** [comment]
If I use the config properties in application.rb like this:
  
    config.action_dispatch.default_headers.delete('X-Frame-Options')
    config.action_dispatch.default_headers['P3P'] = 'CP=\"Not used\"'

The App works fine. Remove those lines, and the App no longer works on first load after a restart, even with the code from the July 26 commit 2ff442e26320a5ca2a2ef266e6546a089f20d0fa  that converts the App to using the method set_easdk_headers in Authenticated controller:

    response.set_header('P3P', 'CP="Not used"')
    response.default_headers.delete('X-Frame-Options')

My curiosity is piqued about this. Even though the set_easdk_headers method fires, the App hangs without a refresh after restarting a server but with the application wide config setting on Action Dispatch for the headers, it works fine.

**Comment by kevinhughes27** [comment]
Just summing up the issue since the original description suggests a different cause:
* new version of the engine causes the first request in development to hang. 2nd and future requests work correctly
* cause was tracked down to setting headers in a `before_action` compared to setting it in `application.rb`

@resistorsoftware  can you create a repo with the minimal code to reproduce this? Then we can ask for help from @rafaelfranca or another rails member to help figure this out.

@meulmees are you still noticing issues in development with our app hanging? It could be related.

@resistorsoftware have you been able to reproduce in production? I guess it would be difficult since you'd have to be the first request after a restart right?

**Comment by meulmees** [comment]
Yep I definitely notice it still

**Comment by resistorsoftware** [comment]
I would guess something in Rails is adding the X-FRAME-OPTIONS after they are removed in the **before_action**, whereas when they are removed in the application.rb, that happens later in the render pipeline, and all is good. Just a guess though. This is the one reason I stayed away from Rails for so long!! Too many thing are hidden in it, leaving developers in a lurch once problems surface.

**Comment by kevinhughes27** [comment]
I am pretty sure `application.rb` runs at boot which is before any requests come in.

**Comment by resistorsoftware** [comment]
Ok.. well I am not supposed to guess at things, so I will stop. All I know, is any sample Rails effort with the **shopify_app** gem, should have this behaviour demonstrable. We just tested a stock effort with no custom code other than to ditch ActiveRecord for Sequel, with the result of a first load hang. I am doubting Sequel is the problem, but hey, if ActiveRecord works without a hitch, I will blame Sequel...
