### ISSUE TITLE
Session / Auth issue on Shopify App vs Shopify POS App on iOS

### ISSUE THREAD

**Issue by jayesbe** [Shopify/shopify_app#470]
Hey Guys I am having a really peculiar issue between Shopify POS and Shopify App's on my iPad.

iOS 10 on iPad

My Stack is LAMP. View is html / javascript. My app is Rewardify (apps.shopify.com/rewardify) 

When on Shopify POS, everything works as expected, you're authenticated on the initial load of the Rewardify embedded app and subsequent requests to different links and sections use the session id cookie that is part of the initial response.

When using the Shopify App however, the initial load does pull up the dashboard for the Rewardify embedded app, however if I click on any link or try to go into any other section, the session cannot be validated on my end and I throw an authentication / session error.  I verified that subsequent requests do not provide the session ID cookie.

Can someone provide some insight here.. the app works perfectly on Shopify POS and on the browser (/admin)  but the Shopify App on iOS (and presumably Android) does not.

**Comment by kevinhughes27** [comment]
This repo is for the Ruby on Rails engine. Please ask this question on the general forums.
