### ISSUE TITLE
Webhooks doesn't install when activating app using Rails 5

### ISSUE THREAD

**Issue by superrordev** [Shopify/shopify_app#471]
I've configured ShopifyApp Gem in Rails 5:

config.webhooks = [
  { topic: 'orders/paid', address: "#{ENV['HOST']}/webhooks/shopify/orders/paid" }
]

When I install shopify store via rails project, the webhooks doesn't add to the store settings.

Please check this problem and let me know how I can fix this issue.
Thanks.

**Comment by jamiemtdwyer** [comment]
How are you confirming the presence of the webhook?

**Comment by superrordev** [comment]
I've just checked the webhooks in store admin.
Goto {storeurl}/admin/settings/notifications
Under webhooks seciton:
![image](https://user-images.githubusercontent.com/15209029/30283747-32b58c4c-9719-11e7-9c34-9e39a1cf21ef.png)

**Comment by jamiemtdwyer** [comment]
Webhooks created through the API are only visible to your app, not the store administrator.

You can retrieve a list of webhooks created  by your app by using `Webhook.find(:all)`.

**Comment by superrordev** [comment]
If I create webhook through the API, it will be automatically chained with that notification?

**Comment by jamiemtdwyer** [comment]
What do you mean by chained with the notification?

**Comment by superrordev** [comment]
linked notification topic to webhooks(I created by API)

**Comment by superrordev** [comment]
What I was expecting is that when I install the shopify app, the webhooks are automatically added to webhooks section and we can receive the notification via webhook.
So without adding webhook in admin section manually, we think we can add and receive notification by this configuration.
Is it wrong?

**Comment by superrordev** [comment]
Btw, where can I check the registered webhook?
I can't find any model like Webhook ( Webhook.find(:all) )

**Comment by kevinhughes27** [comment]
ShopifyAPI::Webhook is a resource. If you make that call you will see the webhooks belonging to your app: https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/resources/webhook.rb
