### ISSUE TITLE
NoMethodError - undefined method `<<' for {:read_timeout=>90, :continue_timeout=>nil, :debug_output=>nil}:Hash Did you mean?  <

### ISSUE THREAD

**Issue by firdausmaarof** [Shopify/shopify_app#476]
Hi I got this error. I'm using ruby 2.4.2 and rails 5.0.2.

```
undefined method `<<' for {:read_timeout=>90, :continue_timeout=>nil, :debug_output=>nil}:Hash
Did you mean?  <
```

Thanks.

**Comment by alanhill** [comment]
How did you get that error? Do you have any replication steps?

I've run into that trying to record responses with VCR before.

**Comment by firdausmaarof** [comment]
@alanhill when i tried to use any of the api. for example, ShopifyAPI::Product.count, then i will get that error.

**Comment by alanhill** [comment]
It's going to be code specific to your application.. I just created a fresh app on ruby 2.4.0 and rails 5.1.4 without any issues.

There's likely an error in your config somewhere.

Can you link to your repo or post some example code? Even a full stack trace would be beneficial here.

If you just create a fresh app, run the generator, rails server then visit localhost, are you able to enter your shop name, then get redirected to that shop, showing a handful of products?

**Comment by firdausmaarof** [comment]
I found the problem already. Its related to fakeweb gem. There's compatibality issue with ruby 2.4 onwards. The solution is you need to load the gem using github. Then everything's gonna be ok. Thanks @alanhill for your help.

**Comment by jesyontop01** [comment]
@firdausmaarof ................God bless you
