### ISSUE TITLE
After Authenticate job - possible error in the docs.

### ISSUE THREAD

**Issue by flavio-b** [Shopify/shopify_app#478]
Hello, the documentation for the After authenticate job states that:

> If your app needs to perform specific actions after it is installed...

But it also fires after every authentication, (as the name says...). I wonder if there's any other option to fire something after it's **installed** only. 
Thanks!

**Comment by kevinhughes27** [comment]
I'd recommend making any after_action idempotent so it can run multiple times. For example if someone were to install and then uninstall there would be a race condition and you might not end up in the right state.

If you still want to do this then the way to do it is to add an after_create hook on the shop model and make sure the shop model gets destroyed using an uninstall webhook.
