### ISSUE TITLE
Redirection loop

### ISSUE THREAD

**Issue by karlcoelho** [Shopify/shopify_app#484]
I'm getting into a redirect loop with my embedded app. I think its the shopify.js script for creating modals that is triggering the redirects, which should be happening. But something when my app loads in the Shopify dashboard that causes it to redirect to the app url outside the embed. Anyone else having this?

**Comment by karlcoelho** [comment]
I imagine its the script here:

`<script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>`

**Comment by kevinhughes27** [comment]
Can you re-open this issue with an example repo and reproduction steps. This is too vague for me or anyone to help out unfortunately.
