### ISSUE TITLE
Can't deploy app on heroku - shopify_app/utils.rb syntax error

### ISSUE THREAD

**Issue by pelcomppl** [Shopify/shopify_app#493]
Hi
I can't deploy my app on heroku, a few weeks ago it worked ok.
I didn't make any changes.

The error is:
`Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
remote: ensure you can run `$ bundle exec rake -P` against your app
remote: and using the production group of your Gemfile.
remote: rake aborted!
remote: SyntaxError: /tmp/build_272a285b5c94dfeb2db5c1099a4f5529/vendor/bundle/ruby/2.2.0/gems/shopify_app-8.2.2/lib/shopify_app/utils.rb:10: syntax error, unexpected '.'
remote:       u.host if u.host&.match(/^[a-z0-9][a-z0-9\-]*[a...
remote:                         ^`

**Comment by EiNSTeiN-** [comment]
The syntax `&.` was introduced in ruby 2.3.0, try updating to this version.

**Comment by pelcomppl** [comment]
My ruby version is 2.3.3p222

**Comment by alanhill** [comment]
It looks like you bundled with 2.2.0

```
tmp/build_272a285b5c94dfeb2db5c1099a4f5529/vendor/bundle/ruby/2.2.0/gems/shopify_app-8.2.2/lib/shopify_app/utils.rb:10
```

**Comment by pelcomppl** [comment]
Command: `ruby --version` 
gives me output: `ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]`
How to use bundler with this ruby version?

**Comment by alanhill** [comment]
Sorry on Heroku it looks like it's bundling with the wrong version at least. Have you specified the ruby version? https://devcenter.heroku.com/articles/ruby-versions

**Comment by pelcomppl** [comment]
Thanks alanhill for advice.
I changed ruby version on Gemfile and the error is not showing, but I have another one:
`remote:        Bundle complete! 14 Gemfile dependencies, 71 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.2.
remote:        To update, run 'gem install bundler --pre'
remote:        Bundle completed (41.43s)
remote:        Cleaning up the bundler cache.
remote:        The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.2.
remote:        To update, run 'gem install bundler --pre'
remote: -----> Installing node-v6.11.1-linux-x64
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        NameError: uninitialized constant ShopifyApp::Shop
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/app/models/shop.rb:2:in '<class:Shop>'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/app/models/shop.rb:1:in '<top (required)>'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies/interlock.rb:12:in 'block in loading'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/concurrency/share_lock.rb:150:in 'exclusive'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/dependencies/interlock.rb:11:in 'loading'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/config/initializers/shopify_session_repository.rb:2:in '<top (required)>'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:648:in 'block in load_config_initializer'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.6/lib/active_support/notifications.rb:166:in 'instrument'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:647:in 'load_config_initializer'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:612:in 'block (2 levels) in <class:Engine>'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:611:in 'each'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/engine.rb:611:in 'block in <class:Engine>'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in 'instance_exec'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/initializable.rb:30:in 'run'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/initializable.rb:55:in 'block in run_initializers'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/initializable.rb:44:in 'each'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/initializable.rb:44:in 'tsort_each_child'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/initializable.rb:54:in 'run_initializers'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/application.rb:352:in 'initialize!'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/config/environment.rb:5:in '<top (required)>'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/application.rb:328:in 'require'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/application.rb:328:in 'require_environment!'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/railties-5.0.6/lib/rails/application.rb:448:in 'block in run_tasks_blocks'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:62:in 'block (2 levels) in define'
remote:        /tmp/build_c3a25d3996a06b24fc347242bd02e6d6/vendor/bundle/ruby/2.3.0/gems/rake-12.1.0/exe/rake:27:in '<top (required)>'
remote:        Tasks: TOP => environment
remote:        (See full trace by running task with --trace)
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed`
