### ISSUE TITLE
Update flash trigger event for new Turbolinks

### ISSUE THREAD

**Issue by flavio-b** [Shopify/shopify_app#494]
Hello there,

on the `_flash_messages` partial, the `eventName` used `page:load` is for the classic version of Turbolinks.
According to [the docs](https://github.com/turbolinks/turbolinks#running-javascript-when-a-page-loads) of the newer version (I think >= 5.0.0), it looks like the event to be used in this case should be `turbolinks:load`.

Even with `turbolinks:load` an issue that I noticed is that if I open one page which sets a `flash` message, the event handler will keep firing on every page after that, even the ones that don't set a `flash` message. It's like each time it adds a new event handler without deleting the old ones, which is at odds with this [explanation on MDN](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Older_way_to_register_event_listeners). 
I got around it by naming the handler function `flash` and adding this at the end of the handler:
` document.removeEventListener(eventName, flash) `

It works normally though with the regular `DOMContentLoaded `. 

Any thoughts or suggestion?

**Comment by kevinhughes27** [comment]
Sounds like this partial should be updated to the latest version of rails / turbolinks. The gem is Rails 5 and greater now.

**Comment by flavio-b** [comment]
Yes, and perhaps add that code to explicitly remove the event listener. 
I can send a PR, however, I still have no idea why a listener set by a previous flash doesn't get replaced when you render a page without flash. It works fine with `DOMContentLoaded`.

**Comment by kevinhughes27** [comment]
That would be great!

**Comment by flavio-b** [comment]
Ok, just sent it #495
