### ISSUE TITLE
embedded issue

### ISSUE THREAD

**Issue by almeidaz** [Shopify/shopify_app#500]
Hi,

After sending my app for reviews before selling on Shopify Appstore. The Review team tell me there is a problem with the app.
> When accessing the app from the app dashboard the app is redirecting to the embedded version. Merchants should be redirected to the embedded URL only.

>The merchant is briefly brought to the page where the app is hosted before redirecting back to the embedded SDK where the merchant can interact with the app.

>The SDK should be initialized with the API key and shop’s origin immediately after including the app.js file. Right now, it looks like the redirect might be happening first and then initializes the script that is loading the page in the iframe. We essentially need to be initializing first and then the redirect can happen from there. This should hopefully prevent the redirect from happening.

This thing happen also with the example app from this repo.

I've made a video to show you   https://youtu.be/oO4rH0jaAQQ

At 00:15 you can see the app appear and after it's reloading to embed in shopify SDK
after that if you came back to the app in the same browser session , this is not happening.

Do you get the same thing as me  ? What can i do to solve this problem ?

----------------------------------------------------------------------
i' ve also join log from console from 00:00 to 00:20
[example_app.txt](https://github.com/Shopify/shopify_app/files/1437877/example_app.txt)

and my gemfile 
[gemfile.txt](https://github.com/Shopify/shopify_app/files/1437912/gemfile.txt)
I've replace rails with the latest version and i'm using shopify_app 8.2.2
In the current example app repo, rails 4 is not compatible with shopify_app 8.x

Thanks, sorry for my english.

**Comment by Alex1sz** [comment]
+1

**Comment by tanema** [comment]
This is expected behaviour because to complete the Oauth authentication process we need to do a fullpage redirect back to your app to complete the process. Then after that easdk took over and redirected back into the admin. 

This is not a bug however we are working on things that will mitigate this in the future.
