### ISSUE TITLE
Trying to manually trigger webhook but not working

### ISSUE THREAD

**Issue by amorimlucas** [Shopify/shopify_app#501]
So I made some edits yesterday to my Shopify app but forgot to migrate a table change, which resulted in 7 merchant orders not getting processed correctly. My app processes merchant orders as soon as the webhook for a new order fires. I’ve now fixed the deployment issue, and it won’t happen again, but now I need to process these orders. 

I've been trying a few things to manually/programmatically trigger these webhooks again, but nothing seems to work. How should I go about doing this?

**Comment by kevinhughes27** [comment]
The webhook body is the same data as fetching the order. You'll need to write a task that fetches each order and calls your code to process it.

**Comment by amorimlucas** [comment]
@kevinhughes27  I'm trying to retrieve an order by order_number:

`ShopifyAPI::Order.where(order_number: 1005)`

But this is returning all orders, not just 1005. Can we not use the `where` method here?

**Comment by kevinhughes27** [comment]
Correct active resource doesn't support where (some queries are supported though https://help.shopify.com/api/reference/order#index). I would keep track of the order_id in your app not the order name.
