### ISSUE TITLE
current_shopify_store returns other shop when opening multiple shops in browser tabs

### ISSUE THREAD

**Issue by AmitPatel-BoTreeConsulting** [Shopify/shopify_app#502]
Steps to reproduce

1. Login to a store(https://foo.myshopify.com) from Managed store
2.` current_shopify_store.try(:myshopify_domain)` returns `foo.myshopify.com` in shopify app's HomeController index action
3. Login to another store(https://bar.myshopify.com) from Managed store keeping previous store unclosed
4. ` current_shopify_store.try(:myshopify_domain)` returns `foo.myshopify.com` in shopify app's HomeController index action instead `bar.myshopify.com`

This issue is with Development Stores as well.

I suppose @EiNSTeiN- has already logged a suggestion in #350

**Comment by kevinhughes27** [comment]
`current_shopify_store` is not a method provided by this gem. Can you provide the contents of this method?

We also need to know what session repository you are using (it will be in your shopify_app initializer)

**Comment by AmitPatel-BoTreeConsulting** [comment]
apology @kevinhughes27. `ShopifyAPI::Shop.current` called within `current_shopify_store` precisely.

**config/initializers/shopify_session_repository.rb**
```
if Rails.configuration.cache_classes
  ShopifyApp::SessionRepository.storage = ShopifyDetail
else
  reloader = defined?(ActiveSupport::Reloader) ? ActiveSupport::Reloader : ActionDispatch::Reloader

  reloader.to_prepare do
    ShopifyApp::SessionRepository.storage = ShopifyDetail
  end
end
```

**config/initializers/shopify_app.rb**
```
ShopifyApp.configure do |config|
  config.application_name = 'Shopify - Feed Champion'
  config.api_key = Settings.shopify.api_key
  config.secret = Settings.shopify.api_secret
  config.scope = Settings.shopify.scope
  config.embedded_app = true
  config.after_authenticate_job = { job: ShopifyAfterAuthenticateJob, inline: true }
  config.webhooks = [  Shopify::AppUninstalledWebhook::PARAMS  ]
end
```

**Comment by EiNSTeiN-** [comment]
Indeed, this app does not support multiple shops.

It might be tricky to modify your app to support this, what I thought would work is:
1) scope all your authenticated routes to some unique path per store (like `yourapp.com/123/` where 123 is the store id), the tricky part will be to set the cookie on return from oauth authorization
2) make sure the session store in Rails uses a `path=/123` on all authenticated routes, this can be done with a `before_action`

**Comment by jamiemtdwyer** [comment]
Closing as this is expected behaviour
