### ISSUE TITLE
Webhook initialization problem

### ISSUE THREAD

**Issue by StephenSullivan** [Shopify/shopify_app#505]
I can't seem to get webhooks to install properly from the app initializer.

Here's what I have in shopify_app.rb:
```ruby
ShopifyApp.configure do |config|
  config.application_name = "My Shopify App"
  config.api_key = "123456"
  config.secret = "abcdef"
  config.scope = "read_products, write_products"
  config.embedded_app = true
  config.webhooks = [
    {topic: 'products/create', address: 'http://myapp.com/webhooks/products_create'},
    {topic: 'products/delete', address: 'http://myapp.com/webhooks/products_delete'},
    {topic: 'products/update', address: 'http://myapp.com/webhooks/products_update'}
  ]
end
```

And here's what I get when I check for webhooks via the Rails console:

`irb(main):002:0> ShopifyAPI::Webhook.all
=> []
`

Have I found a bug or am I just failing to understand how this works?

**Comment by kevinhughes27** [comment]
Have you installed the app on a store and are you authenticated with that store when you check for webhooks? The next thing I can think of is that you aren't running the background job worker and the job to create the webhooks was queued but never executed.

**Comment by StephenSullivan** [comment]
Well I'm running background jobs from another gem (qbwc), so If be
surprised if that's it. I should be authorized since everything else works.
Will have to check tomorrow.

**Comment by StephenSullivan** [comment]
I found the problem. The webhooks WERE being generated by the app. I was attempting to verify this via the Rails console using a private app connection string with different credentials than the Shopify app, not realizing that context matters.
