### ISSUE TITLE
Shop Records not destroyed when app is uninstalled

### ISSUE THREAD

**Issue by morales257** [Shopify/shopify_app#506]
Started noticing that my records were not being destroyed from the database upon app uninstall.

I checked the development.log and found this in there:

`DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false= is deprecated and will be removed in Rails 5.2. (called from <top (required)> at /my_shopify_app/config/initializers/new_framework_defaults.rb:21)`

Which corresponds to this line in `new_framework_defaults.rb:21`:

```
# Do not halt callback chains when a callback returns false. Previous versions had true.
ActiveSupport.halt_callback_chains_on_return_false = false

```
I would assume failed callback chain shouldn't interrupt a record from being destroyed though, so I'm not sure this is the culprit

**Comment by kevinhughes27** [comment]
This gem doesn't delete shops on uninstall for you. If you want this behaviour you'll need to register an uninstall webhook and clean up the shop manually.
