### ISSUE TITLE
README doesn't reflect removal of ShopifyApp::Shop

### ISSUE THREAD

**Issue by marytal** [Shopify/shopify_app#510]
According to the CHANGELOG `ShopifyApp::Shop` has been removed, but the README doc still has multiple references to it, which is confusing when trying to debug.

**Comment by kevinhughes27** [comment]
So sorry about that! I'll try and update the README today. What are you trying to debug the generated app should still be ready to use.

**Comment by marytal** [comment]
It's alright we got it now 😸 
We were upgrading the gem from 7.2.3 to 8.2.4 - the fix was in the changelog under 8.1.0, we just didn't notice. It might have helped to have the error/fix stand out more - but it was in there so really can't complain :P 

Thanks!
