### ISSUE TITLE
Is it possible to release new version?

### ISSUE THREAD

**Issue by vfonic** [Shopify/shopify_app#515]
I just spent ~2h debugging and fixing 'X-Frame-Options' error that I was getting. I realized it's the issue with the login action and there has already been a fix merged into `master` branch half a month ago (Nov 16th!).

Remove X-Frame-Options header on login route: https://github.com/shopify/shopify_app/pull/504

Is there any valid reason why you can't release a new gem version when you already have a fix in place?

Thanks!

**Comment by kevinhughes27** [comment]
new version is out. Sorry about that!

**Comment by vfonic** [comment]
Thanks @kevinhughes27! 🤘
