### ISSUE TITLE
Refused to display login page

### ISSUE THREAD

**Issue by kirillplatonov** [Shopify/shopify_app#518]
When I open an embedded app from Shopify admin with cleaned cookies, for example, I see this error in js console:
```
Refused to display 'https://APP_URL/login?shop=oh-my-flowers.myshopify.com' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
```

Looks like we need to reset 'X-Frame-Options' for the login page too.

I using Rails 5.2.0 beta 2 (maybe this also causing this issue)

**Comment by kevinhughes27** [comment]
I think this is fixed on master with https://github.com/Shopify/shopify_app/commit/2f8051fea45b38e6c83b84ca6bf3826e4c31e836 can you confirm?

**Comment by kirillplatonov** [comment]
@kevinhughes27 it works fine in master. Thank you! Waiting for release

**Comment by kevinhughes27** [comment]
I pushed it earlier today! 8.2.5
