### ISSUE TITLE
X-Frame-Origin is still not fixed

### ISSUE THREAD

**Issue by vfonic** [Shopify/shopify_app#522]
Hi,

X-Frame-Origin issue seems to have not been fixed yet properly.

If you remove/don't have these lines in your `application.rb`:

```rb
    config.action_dispatch.default_headers['P3P'] = 'CP="Not used"'
    config.action_dispatch.default_headers.delete('X-Frame-Options')
```

Then, the app will fail in the following scenario (due to it being in an iframe):

1. Install an app A to shop X
2. Open the shop X admin in incognito (you must not have app A cookies)
3. Navigate to Apps => App A
4. It will present you with an app login page inside an iframe
5. Type in the same shop's url (??? this wasn't needed before) in the login input field
6. Nothing

The app loads login page from `SessionsController#new` action because of the following code:
https://github.com/Shopify/shopify_app/blob/master/app/controllers/shopify_app/sessions_controller.rb#L5
```rb
    after_action only: :new do |controller|
      controller.response.headers.except!('X-Frame-Options')
    end
```

However, trying to login (calling `SessionsController#create`), results in a X-Frame-Origin error.

Not sure if simply changing `only: :new` to `only: [:new, :create]` works, or whether it's an acceptable solution.

**Comment by kevinhughes27** [comment]
> Type in the same shop's url (??? this wasn't needed before) in the login input field

If you look at the [authenticate](https://github.com/Shopify/shopify_app/blob/master/app/controllers/shopify_app/sessions_controller.rb#L39) method you'll see that it does actions if the shop param is present. Maybe the incognito tab is preventing this query param from being passed through

Sounds like we might need to removed the headers for the create action as well. If you make that change does it fix is for you?

**Comment by vfonic** [comment]
@kevinhughes27 it does.

I don't think that incognito strips shop param. Could it be that Shopify used to have shop param appended to the link in the /admin/apps and now it doesn't append it anymore?
Just tried it in a normal browser window (no incognito) and it still renders login page. This wasn't the case in the past. What if user types in another shop's domain?

**Comment by kevinhughes27** [comment]
> What if user types in another shop's domain? 

It would start another oauth flow.

>  Could it be that Shopify used to have shop param appended to the link in the /admin/apps and now it doesn't append it anymore?

@jamiemtdwyer can you look into this or delegate

@vfonic can you put up a PR to whitelist the create action as well. Sorry for the trouble.

**Comment by vfonic** [comment]
https://github.com/Shopify/shopify_app/pull/523

**Comment by jamiemtdwyer** [comment]
> Could it be that Shopify used to have shop param appended to the link in the /admin/apps and now it doesn't append it anymore?

Do you have an example of this or is this just a thought?

**Comment by vfonic** [comment]
@jamiemtdwyer it's a thought. I don't know why it would instantly login/redirect before and now renders the login page and let's user type in the shop domain.

**Comment by jamiemtdwyer** [comment]
Might be triggering an edge case in the auth flow where there's an active session on the server but no session present for the client (since it's a new incognito session).

Can you still replicate this on latest master?

**Comment by vfonic** [comment]
Yes.

**Comment by vfonic** [comment]
@jamiemtdwyer I believe this is a separate issue. The bug explained in this issue has been fixed. User can login now and open the app page, X-Frame-Origin is not preventing users to use the app anymore.

The other issue, where the user is asked to login inside of an iframe in Shopify admin, is still not fixed.

**Comment by jamiemtdwyer** [comment]
Cool, sounds good. I've opened a separate issue.
