### ISSUE TITLE
server is already running

### ISSUE THREAD

**Issue by MassMadankumar** [Shopify/shopify_app#525]
root@instance-2:/mnt/zapstore.com/shopifyapp/zap# rails s
=> Booting Puma
=> Rails 5.1.4 application starting in development
=> Run `rails server -h` for more startup options
A server is already running. Check /mnt/zapstore.com/shopifyapp/zap/tmp/pids/server.pid.
Exiting
any solution ?

**Comment by alanhill** [comment]
This is a Rails related question, not a shopify_app related question. I'd suggest checking out StackOverflow or other resources for help with these.

Issues in this repo should only be opened if you're running into an issue with the actual gem, not with the Rails framework in general. For that reason I'm going to close this issue out.

I'd suggest a quick Google search with the error message Rails spit out at you, you'll find plenty of resources to help debug depending on your OS.
