### ISSUE TITLE
Cannot verify CSRF token when processing webhook.

### ISSUE THREAD

**Issue by yeoenggu** [Shopify/shopify_app#527]
I am creating a new app using shopify_app.  Setting it up from scratch.  I had encountered an error when I uninstall the app.

Processing by HomeController#uninstall as */*
  Parameters: {"id"=>7041073, "name"=>"Sg Drinks .....
Can't verify CSRF token authenticity.

This repo will recreate the error.  
https://github.com/yeoenggu/test_shopify_app

Please add in proper secret, key in the shopify_app.rb.

**Comment by kevinhughes27** [comment]
Are there any other reproduction steps or do you just click uninstall? Is the back button involved at all?

**Comment by yeoenggu** [comment]
Just click uninstall.  Back button is not involved.

regards,
Eng Guan Yeo

**Comment by kevinhughes27** [comment]
There is no uninstall button in the app that I can see. Where are you clicking?

**Comment by kevinhughes27** [comment]
I added the following in the home index.html.erb file to test the route:

```
<%= form_tag '/uninstall', method: :post do %>
  <%= submit_tag 'test' %>
<% end %>
```

I was **not** able to reproduce. I should note that I generated my own app to try this.

**Comment by yeoenggu** [comment]
The app is embedded within shopify admin.  Just click apps on the shopify admin and delete/uninstall the app.  Sorry, I should have been clearer in documenting it.  Will make more effort to make it clearer next time.

regards,
Eng Guan Yeo

**Comment by kevinhughes27** [comment]
I just realized that you were hitting this endpoint via a webhook.

CSRF is for ensuring browser requests are not forged. We can never verify CSRF for a webhook, it doesn't make any sense to do so. Instead we verify the HMAC signature.

ShopifyApp has a built in webhook controller and job architecture I would recommend using. If you want your own controller then you need to skip csrf checks.
