### ISSUE TITLE
Had to use ShopifyApp::InMemorySessionStore for first deploy to Heroku

### ISSUE THREAD

**Issue by onedanshow** [Shopify/shopify_app#528]
**Problem:** Developed the app locally using ngrok for tunneling and everything is great. Deployed to Heroku for first time and get `ArgumentError: storage must respond to :store and :retrieve` during `Running: rake assets:precompile` on Heroku's build.  I have to change my config to:

```config.session_repository = ShopifyApp::InMemorySessionStore```

to make it work.  Normally doing the traditional route of 

```config.session_repository = Shop```

My `Shop` model looks how it should:

```
class Shop < ActiveRecord::Base
  include ShopifyApp::SessionStorage
  ...
end
```

I thought this was just for my first deploy because the database wasn't migrated yet, but it still continues.

On `shopify_gem` version 8.2.5

Any thoughts on this?

**Comment by kevinhughes27** [comment]
Here is the code that triggers this error: https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/session/session_repository.rb#L9

so one of those conditions must be true. I would suggest adding some logging in the ShopifyApp initializer to see which condition is being hit. Is it possible you have another object called `Shop` in your code and the code loading order is affecting this?

**Comment by onedanshow** [comment]
@kevinhughes27  Thanks for the help.  Yeah, I'd looked over that file multiple times.  Good suggestion to figure out which condition was failing.  It came through as `storage` being nil. Still trying to determine what could cause that.  It's a run-of-the-mill initializer:

```
ShopifyApp.configure do |config|
  config.application_name = 'Example App'
  config.api_key = ENV['SHOPIFY_API_KEY']
  config.secret = ENV['SHOPIFY_SECRET']
  config.scope = 'read_products'
  config.embedded_app = true
  config.after_authenticate_job = false
  config.session_repository = Shop
end
```

I do not have another `Shop` model, but also a good suggestion.

**Comment by kevinhughes27** [comment]
you could also try an explicit require to load the Shop model and make sure its not nil

**Comment by onedanshow** [comment]
Correction: It's pulling `ShopifyAPI::Shop` over my ActiveRecord `Shop` model.

`ArgumentError: storage must respond to :store - ShopifyAPI::Shop`

I put in an explicit `require_relative '../../app/models/shop'` to `shopify_app.rb` initializer and getting:

`TypeError: superclass mismatch for class Shop`

**Comment by onedanshow** [comment]
**Solution:** I had a `require shopify_api` in old rake task.  Removed that, and the load order is correct now.  Thanks for the hep @kevinhughes27!

**Comment by edavis10** [comment]
Changing `Shop` to `::Shop` in the initializer might also help. That'll reference the top level Shop class and not the one in the ShopifyAPI module.

**Comment by onedanshow** [comment]
@edavis10 Yup, good call. Thanks for the second pair of eyes @edavis10 and @kevinhughes27
