### ISSUE TITLE
Error firing orders/paid webhook with this error <NoMethodError: undefined method `bytesize’ for nil:NilClass>

### ISSUE THREAD

**Issue by FernandoZX** [Shopify/shopify_app#529]
when a execute the orders/paid webhook show this error <NoMethodError: undefined method `bytesize’ for nil:NilClass>

there is the line configured could you give the correct way to be implemented

```{ topic: 'orders/paid', address: "https://#{ENV['HOSTNAME']}/webhooks/orders_paid", format: 'json' },````

thank you give me the correct solution thanks

**Comment by 0ptimusrhyme** [comment]
Can you provide a stack trace so I can see where this is occurring roughly? It looks to me like you're expecting to be a string when it's `nil`, and based on the address you're sharing, maybe `ENV[''HOSTNAME]` isn't resolving to anything?

I'd suggest using byebug, pry, or even puts to debug this a little more.

**Comment by yoonwaiyan** [comment]
Hi there, I'm facing the same problem and I did a little bit of debugging from my end. I'm trying to simulate 'fraud' case where the webhook headers are not provided and this error occurs, this is because `shopify_hmac` does not exist which was being compared in the `secure_compare`:

```ruby
```
