### ISSUE TITLE
Global methods for all controllers

### ISSUE THREAD

**Issue by mmaauu** [Shopify/shopify_app#531]
Hi, this is not a bug, is just a question, I'm trying to add some global methods to the application_controller, and I'm getting _undefined local variable or method `xxxxx' for #<HomeController:0xa0955e8>_, do I have to include anything?

Thanks!

**Comment by kartikluke** [comment]
`ShopifyApp::AuthenticatedController` now inherits from `ActionController::Base` instead of `ApplicationController`. So methods you define in `ApplicationController` won't be available to Home and such.

**Comment by jamiemtdwyer** [comment]
Thanks for clarifying @kartikluke. Closing this as it does not appear to be an issue.

**Comment by kartikluke** [comment]
You're welcome @jamiemtdwyer . @mmaauu for a more elaborate example, you can create a controller concern with the functions you want to add or before_action, etc. and include it into your ApplicationController and mix it into the AuthenticatedController then it should be available throughout.

``` concern.rb
module Base
  extend ActiveSupport::Concern

  included do
    helper_method :current_shop
  end
  
  def current_shop;end
end
```

``` controller.rb
class AuthenticatedController < ShopifyApp::AuthenticatedController
  layout 'embedded_app'
  helper ApplicationHelper # or helper :all
  include Base
end
```

``` app_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include Base
end
```

**Comment by mmaauu** [comment]
Thank you very much @kartikluke !!
