### ISSUE TITLE
Move inline Javascript to js assets

### ISSUE THREAD

**Issue by jamiemtdwyer** [Shopify/shopify_app#539]
Continuation of work started in https://github.com/Shopify/shopify_app/pull/537

Move inline javascript into a .js asset so it plays nicely with CSP for Rails 5.2 support.

https://github.com/Shopify/shopify_app/search?p=1&q=script+type&type=&utf8=%E2%9C%93

**Comment by tanema** [comment]
The only script tags left now are to setup window variables rendered in erb and I think that is fine enough
