### ISSUE TITLE
Documentation not accurate about AuthenticatedController

### ISSUE THREAD

**Issue by nickmealey** [Shopify/shopify_app#541]
Readme currently [says about](https://github.com/Shopify/shopify_app#authenticatedcontroller) the AuthenticatedController that it inherits from `ApplicationController`, when it actually inherits from `ActionController::Base` which was changed in [this commit](https://github.com/Shopify/shopify_app/blob/master/app/controllers/shopify_app/authenticated_controller.rb). What was the reason for this change? Controllers that inherit from `AuthenticatedController` now can't use `ApplicationController methods`

**Comment by kevinhughes27** [comment]
It was done to avoid a situation where a developer or another gem adds methods to application controller which interferes with ShopifyApp. If you need custom behavior then you can still make your own controller from application controller and include the concern.

The readme should be updated.

**Comment by vfonic** [comment]
I fixed this here: https://github.com/Shopify/shopify_app/pull/550

This issue can be closed now.

**Comment by 0ptimusrhyme** [comment]
Thanks!
