### ISSUE TITLE
Oauth error invalid_request: The redirect_uri is missing or not whitelisted

### ISSUE THREAD

**Issue by ignachiou** [Shopify/shopify_app#543]
I'm trying to solve an issue with a private app, but to do that I need to whitelist my local environment to make tests. So I get this error 

"Oauth error invalid_request: The redirect_uri is missing or not whitelisted".

URL:
`https://{shop}.myshopify.com/admin/oauth/authorize?client_id=d0936cc5d317004db934c533e566962a&scope=read_orders,read_customers,read_products,read_fulfillments&redirect_uri=http://192.168.99.100/alegraconnect/redirection-checks.php&state=7`

The documentation says in this url https://www.shopify.com/partners/blog/17056443-how-to-generate-a-shopify-api-token , at the part "before getting staerted" I need to add my local environment to a callback field. I haven't found this at the site.

**Comment by jamiemtdwyer** [comment]
The blog post you've linked is completely unrelated to this repo, which is a scaffolding platform for Ruby on Rails applications.

You'll need to make sure that the value you are passing in for the redirect_uri is whitelisted in your partner dashboard.

If you have additional questions, I encourage you to head to our [developer forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology) for more assistance.

**Comment by flavio-b** [comment]
@ignachiou open the app details on your partner dashboard. Click on the "App info" tab and then enter the url to whitelist on that text area on the right side. 

It might not work if you're using http though. My advice is to install [ngrok](https://ngrok.com/). It generates a random url that links to a port your localhost, with the command `$ ngrok http [PORT NUMBER] `

**Comment by ignachiou** [comment]
@flavio-b the rare thing is that I don't see the field your talking about http://take.ms/idhZ1n, http://take.ms/B24LW,http://take.ms/WKJhz

**Comment by flavio-b** [comment]
The text area I was talking about is in the partner dashboard, when you create an app over there. But I see now yours is a private app. I haven't developed any of those, so not sure how the auth flow works. 

Take a look [here](https://help.shopify.com/api/getting-started/authentication/private-authentication), might have the info you need.
