### ISSUE TITLE
Certain Shopify Webhooks not handled 

### ISSUE THREAD

**Issue by sumith** [Shopify/shopify_app#546]
The Shopify Webhook API lists many webhooks https://help.shopify.com/api/reference/webhook

However, using some of the webhooks like orders_fulfillment/create, fails Webhook registration with  message:
`ShopifyApp::WebhooksManager::CreationFailed: Topic Invalid topic specified. Topics allowed: app/uninstalled, carts/create, carts/update, checkouts/create, checkouts/delete, checkouts/update, collections/create, collections/delete, collections/update, order_transactions/create, orders/cancelled, orders/create, orders/delete, orders/fulfilled, orders/paid, orders/partially_fulfilled, orders/updated, products/create, products/delete, products/update, refunds/create, shop/update`

Will the missing ones be added? Or can we extend or add them?

Thanks

**Comment by jamiemtdwyer** [comment]
There is no such webhook topic. The topic you're looking for is
orders/fulfilled or fulfillment/create.

**Comment by sumith** [comment]
This is from https://help.shopify.com/api/reference/events/webhook

![image](https://user-images.githubusercontent.com/1023760/39853336-592f3c4a-543f-11e8-8bcb-aa7a1357b046.png)

These are not in the list generated by 'ShopifyApp::WebhooksManager' !

**Comment by vfonic** [comment]
@sumith keep in mind that Shopify returns "Topics allowed" based on the auth scope your app has: https://help.shopify.com/api/getting-started/authentication/oauth/scopes

**Comment by sumith** [comment]
@vfonic That was the missing link.  Webhook registration works as expected.  Thanks
