### ISSUE TITLE
OmniAuth::Strategies::OAuth2::CallbackError

### ISSUE THREAD

**Issue by bgmat** [Shopify/shopify_app#547]
invalid_site | OAuth endpoint is not a myshopify site

I get this error when I try to install a fresh app on a development store.

App URL: http://some.ngrok.io/
Whitelisted redirection URL(s): http://localhost:3000/auth/shopify/callback

I get to the store confirmation page, but after I click "Install unlisted app" I get this error.

The app appears in the list of apps installed on the store, but it is not showing the list of products.

The app is new, it has only the default generator executed. No other change.

The URL:
http://localhost:3000/auth/shopify/callback?code=8bf7a9e9c001158d9a8a14d75f0840f1&hmac=3a3a5c55033480555b057dc88b85196b9ca7a91f6bebf96ed7520b0820efffa4&shop=mydemo.myshopify.com&state=b1d9e2fd8159b65ffef4f227d4994bf3741717339bf1dd99&timestamp=1518515465

Rails 5.1.4
Ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]

Error details:
invalid_site | OAuth endpoint is not a myshopify site.
Extracted source (around line #25):
              
23
24    def raise_out!
25      raise(env['omniauth.error'] || OmniAuth::Error.new(env['omniauth.error.type']))
26    end
27
28    def redirect_to_failure

Application Trace | Framework Trace | Full Trace
omniauth (1.8.1) lib/omniauth/failure_endpoint.rb:25:in `raise_out!'
omniauth (1.8.1) lib/omniauth/failure_endpoint.rb:20:in `call'
omniauth (1.8.1) lib/omniauth/failure_endpoint.rb:12:in `call'
omniauth (1.8.1) lib/omniauth/strategy.rb:486:in `fail!'
omniauth-shopify-oauth2 (1.2.1) lib/omniauth/strategies/shopify.rb:110:in `callback_phase'
omniauth (1.8.1) lib/omniauth/strategy.rb:236:in `callback_call'
omniauth (1.8.1) lib/omniauth/strategy.rb:188:in `call!'
omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
omniauth (1.8.1) lib/omniauth/builder.rb:63:in `call'
rack (2.0.4) lib/rack/etag.rb:25:in `call'
rack (2.0.4) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.4) lib/rack/head.rb:12:in `call'
rack (2.0.4) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.4) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.1.4) lib/active_record/migration.rb:556:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.4) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.4) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
web-console (3.5.1) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.5.1) lib/web_console/middleware.rb:28:in `block in call'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `catch'
web-console (3.5.1) lib/web_console/middleware.rb:18:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.4) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.4) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.4) lib/rails/rack/logger.rb:24:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.4) lib/rack/method_override.rb:22:in `call'
rack (2.0.4) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.4) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.4) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.4) lib/rack/sendfile.rb:111:in `call'
railties (5.1.4) lib/rails/engine.rb:522:in `call'
puma (3.11.2) lib/puma/configuration.rb:225:in `call'
puma (3.11.2) lib/puma/server.rb:624:in `handle_request'
puma (3.11.2) lib/puma/server.rb:438:in `process_client'
puma (3.11.2) lib/puma/server.rb:302:in `block in run'
puma (3.11.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
Request
Parameters:

{"code"=>"8bf7a9e9c001158d9a8a14d75f0840f1",
 "hmac"=>"3a3a5c55033480555b057dc88b85196b9ca7a91f6bebf96ed7520b0820efffa4",
 "shop"=>"mydemo.myshopify.com",
 "state"=>"b1d9e2fd8159b65ffef4f227d4994bf3741717339bf1dd99",
 "timestamp"=>"1518515465"}

Toggle session dump
locale: "en"
return_to: "/"
session_id: "511418e39471441d43c21dbbe7a6c348"

Toggle env dump
GATEWAY_INTERFACE: "CGI/1.2"
HTTP_ACCEPT: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"
HTTP_ACCEPT_ENCODING: "gzip, deflate, br"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.9,ro;q=0.8"
HTTP_CACHE_CONTROL: "max-age=0"
HTTP_VERSION: "HTTP/1.1"
ORIGINAL_SCRIPT_NAME: ""
REMOTE_ADDR: "127.0.0.1"
SERVER_NAME: "localhost"
SERVER_PROTOCOL: "HTTP/1.1"

Response
Headers:

None

**Comment by bgmat** [comment]
I deployed the same app on Heroku and changed the URL in the Shopify partners  ... it works
So, what's wrong with my local settings?

**Comment by bgmat** [comment]
Guys, sorry for spamming ... there is no issue
It was in the way I started ngrok ... it was changing my redirect uri to localhost

**Comment by matsuihidetoshi** [comment]
@bgmat Hi, thank you for creating this issue.
I'm building a custom app and I'm facing same problem, using **ngrok**.

You said:
> It was in the way I started ngrok ... it was changing my redirect uri to localhost

and how did you solve this problem?
Is there any way to solve this problem hosting an app locally through ngrok tunnel?

**Comment by bgmat** [comment]
@matsuihidetoshi Hi, sorry for the late reply.
I honestly, do not remember how ... I stopped using ngrok shortly after this. I prefer Pagekite

**Comment by matsuihidetoshi** [comment]
@bgmat Hi!
I tried another way, and it worked well for me.
Thank you very much for answering me!
