### ISSUE TITLE
Issue with `login_url` being redefined

### ISSUE THREAD

**Issue by vfonic** [Shopify/shopify_app#552]
I'm using a rails engine gem that is built on top of `shopify_app`. I've got some custom additional logic that I've put in my gem and I'm directly inheriting, instead of from `ShopifyApp::AuthenticatedController`, from `BulletTrain::AuthenticatedController` (my gem's awesome name), which inherits from `ShopifyApp::AuthenticatedController`.

The issue I'm currently having is because of this line:
```rb
controller :sessions do
  get 'login' => :new, :as => :login
end
```

What happens is that this line causes rails url helper to create a `login_url` method. When called through my gem, it looks like the app overrides `login_url` defined in `shopify_app` gem in [`LoginProtection`](https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/controller_concerns/login_protection.rb#L54)

This causes a bug, where a user, without session (in my app), gets a login screen (due to rails url helper `login_url` returning login url without the shop param, therefore preventing auto-login), instead of being logged in immediately.

Related issue: https://github.com/Shopify/shopify_app/issues/524

A simple solution would be to rename the `login_url` method in `ShopifyApp::LoginProtection` to a non-conflicting name. I don't know how to fix this error otherwise. Any ideas?

Should I create a PR? I suggest `login_url_for_shop` as it creates the url based on the `params[:shop]`.

**Comment by EiNSTeiN-** [comment]
I totally understand that the name clash is unexpected. I believe you should be able to solve this problem without changes to this gem:

Assuming you mount the engine as our generator suggests:
```ruby
mount ShopifyApp::Engine, at: '/'
```
Add a namespace to this line:
```ruby
mount ShopifyApp::Engine, at: '/', as: :shopify_app
```
this should work as well:
```ruby
namespace :shopify_app do
  mount ShopifyApp::Engine, at: '/'
end
```
then you'll be able to avoid the name conflict between LoginProtection's login_url and the route helper:
```ruby
shopify_app_login_url
```

**Comment by vfonic** [comment]
@EiNSTeiN- ah nice! I didn't know that all the routes used internally inside the gem will still work (for example `sessions/new.html.erb` uses `form_for login_path, ...`.
Is this because of `isolate_namespace` or it's just a standard gem behavior?

I guess I could close this issue.

**Comment by EiNSTeiN-** [comment]
In the view context you would only have access to route helpers, so the LoginProtection methods would not be available unless you also add `helper_method :login_url` somewhere in your controller.
As you mentioned using `login_path` instead of `login_url` is a valid alternative. As a third option I believe you could also use the engine proxy provided by rails which should be named `shopify_app_engine` to access the routes: `shopify_app_engine.login_url`.

Glad this is fixed for you 👍
