### ISSUE TITLE
invalid_site encountered with shopify_app/example

### ISSUE THREAD

**Issue by brcampbe** [Shopify/shopify_app#558]
I'm having a problem getting the example under shopify_app to work without encountering an "invalid_site" error in omniauth-shopify-oauth2 (1.2.1) lib/omniauth/strategies/shopify.rb:105. The valid_site? variable is set to false.

**Comment by brcampbe** [comment]
Extracted source (around line #105): 
          super
        else
          fail!(:invalid_site)
        end
      end

**Comment by 0ptimusrhyme** [comment]
As mentioned by Jamie in #561, the example app is dated and shouldn't be expected to run out of the box. I assume this doesn't occur for you when you generate the app yourself following the guide?

**Comment by MisinformedDNA** [comment]
Having an actual example app is much more helpful then a single page guide that goes into no real detail.

**Comment by 0ptimusrhyme** [comment]
@MisinformedDNA Absolutely agree. Editing my comment from _Shouldn't be expected to run out of the box_ to something I actually meant to say :D

**Comment by mahlingam** [comment]
Took a day of my life to finally get to `!!(/\A(https|http)\:\/\/[a-zA-Z0-9][a-zA-Z0-9\-]*\.#{Regexp.quote(options[:myshopify_domain])}[\/]?\z/ =~ options[:client_options][:site])`
which forbids any local development after all. Not mentioned anywhere else afaik, except maybe here: https://github.com/Shopify/omniauth-shopify-oauth2/issues/61

**Comment by tylerball** [comment]
The example app has been fixed up to resolve this problem. Try latest master and feel free to reopen if you have any issues.
