### ISSUE TITLE
App only works on the computer it's installed on..?

### ISSUE THREAD

**Issue by sizzlecentral** [Shopify/shopify_app#559]
My app works fine (oauth and billing api) in development with ngrok, and also fine when deployed to heroku, but only on the computer/browser it is installed on. 

- If I log into my store on another machine and try to access the app I get a 406 error.
- if I install on machine A with Chrome, then try to use the app on machine A with another browser I get an "invalid_site" error.

If anyone has an answer for this I would really appreciate it, hopefully it's an easy fix.

Thanks!

Don

**Comment by sizzlecentral** [comment]
Additionally, it seems to break if installed in more than one store at a time - not good!

ngrok logs show '/auth/shopify/callback' returning '302 Found' if installed in one store, '406 Not Acceptable' if installed in more than one.

**Comment by jamiemtdwyer** [comment]
If you haven't configured redis or SQL storage, by default all tokens are stored in memory. This sounds like it could possibly be a side effect of that.

**Comment by jamiemtdwyer** [comment]
(sorry, tried to blow away your duplicate comment but I think we both did it at the same time)

**Comment by sizzlecentral** [comment]
Thanks for the reply Jamie! I'm not sure what that means, but I will look into it (this is my first app).

**Comment by jamiemtdwyer** [comment]
No worries! This [section of the README](https://github.com/Shopify/shopify_app#shopifyappsessionrepository) should help – if you have any questions, I'd be happy to help clarify.

**Comment by sizzlecentral** [comment]
I see that I have:

-  'config.session_repository = Shop', in shopify_app.rb, and
- 'include ShopifyApp::SessionStorage', in my Shop model (and nothing else)

Is there something else I need to set up here?

**Comment by sizzlecentral** [comment]
This looks to be a bug I introduced when trying to write my recurring_application_charge method. If I take that out, push to heroku, and install in multiple stores it works again.

Thanks for getting me on the right track @jamiemtdwyer!

**Comment by jamiemtdwyer** [comment]
Glad you were able to sort it!
