### ISSUE TITLE
Example app results in infinite loop

### ISSUE THREAD

**Issue by MisinformedDNA** [Shopify/shopify_app#561]
I created a new rails app following the instructions in the README. I have made no code changes.

As best I can tell, this is what's happening:
1. Load app at https://[example].shopify.com
2. App goes through auth process and is brought to the callback URL
1. Callback redirects to home/index
1. App displays contents outside of Shopify
1. Shopify is reloaded in an attempt to embed the app
1. We are brought back to step 2.

I'm looking for the right way to create an app and it is difficult when the examples don't work.

Can you please fix this?

**Comment by PatrickFang** [comment]
what browser were you using?

**Comment by jamiemtdwyer** [comment]
I don't believe the example app is intended to run out of the box, it simply serves as an example of how the generated application is architected.

The controllers in the example app folder were last updated over 2 years ago.

It's fairly simple to follow the documentation to generate a new application and run that instead.

I think the example folder should be nuked or regenerated as part of the deployment / release steps.

**Comment by MisinformedDNA** [comment]
Actually, I determined that it works fine if you disable the embedded app functionality.

**Comment by 0ptimusrhyme** [comment]
For now we can look into modernizing the example app in a PR if anyone can spare the cycles, and I agree it should be regenerated as part of deployment/release. I can look into it next week if nobody has by then.

**Comment by wnm** [comment]
Do you allow third party cookies in your browser? I  have an embedded app, and when I disable third party cookies, it results in a redirect loop.

**Comment by tanema** [comment]
Example app no longer exists so this app is stale.
