### ISSUE TITLE
{{ content_for_header }} doesn't load script tags

### ISSUE THREAD

**Issue by vfonic** [Shopify/shopify_app#562]
> NOTE: This is more of a Shopify issue than ShopifyApp issue, but, I don't know where to post it. Please let me know if there's a channel I could post such issues, as I've got one more issue I'd like to report.

I've received a support question regarding my app from one of the shop owners. It turns out that the app's script tag is not being loaded on the storefront. I checked the list of installed/created script tags through `ShopifyAPI::ScriptTag.all` and I got back the valid script tag that my app added automatically upon app install.
When I view page source of customer's store, I can't see my script being async loaded. In fact, I can't see the Shopify's `asyncLoad` javascript function that's normally used to load all apps' script tags. I opened customers `theme.liquid` file and saw there's `{{ content_for_header }}` properly added right above the `</head>` closing tag. In fact it seems like he's using the default Debut theme.

Here's a working store, loading my script tag:
[https://cart-button-effects.myshopify.com/collections/frontpage/products/14k-wire-bloom-earrings](https://cart-button-effects.myshopify.com/collections/frontpage/products/14k-wire-bloom-earrings) - please view source and search for "asyncLoad" or my script tag directly "https:\/\/d26ft7cbcd9n47.cloudfront.net\/assets\/shopify_store-9750fee08f5f2194e21f913c578cc5f56a3c24636d4dd86d6d1dab740ef96ab4.js?shop=cart-button-effects.myshopify.com"

The customer's shop (that doesn't load scripts) is new and I'm wondering if that could be the issue. Also the store is password protected so you won't get much if I sent you the store link. If you need me for more details, I'm on skype: viktor.fonic

Any suggestions what I might tell the customer?

Thanks!

**Comment by vfonic** [comment]
It got fixed after I installed another app in the client's store.
Script tags from both apps are now being loaded correctly.

**Comment by chinapalace** [comment]
@vfonic I'm running into this same issue. Any idea why that fix worked?
