### ISSUE TITLE
Recurring UsageCharge?

### ISSUE THREAD

**Issue by vfonic** [Shopify/shopify_app#563]
Let's say I have an app with `RecurringApplicationCharge` of $1.99. It allows shop owners to create and place a slideshow on the site.

I'd like to offer the possibility for creating more slideshows and charge $1 for each additional slideshow. I've never used `UsageCharge`, but as far as I understand, `UsageCharge` is a one-off/one-time thing. You create charge when a certain threshold is hit, for example when the 100th order is created or 100th email sent.

I'd like to charge my customers $1 _monthly_ for each new slideshow they create. Is it possible to achieve this "`RecurringUsageCharge`" (1) or should I just offer "threshold-based" plans, that will re-create `RecurringApplicationCharge` (2)?

(2): For example:
* 1 slideshow $1.99
* 5 slideshows $3.99
* 10 slideshows $5.99

**Comment by 0ptimusrhyme** [comment]
This is absolutely possible, but this discussion isn't specific to shopify_app. I'd suggest directing questions like these to the [APIs and SDKs forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology).

To address your question: You can apply usage charges up to the set `capped_amount` on the recurring charge it lives on. You can apply as many as you like up to that threshold. There's no such `RecurringUsageCharge` object you can leverage, so you'll be setting these values programatically on your end based on how many slideshows are created.

I'm going to close this issue but if you feel I've misunderstood you feel free to re-open and let me know why this belongs here.
