### ISSUE TITLE
ShopifyAPI::InventoryLevel

### ISSUE THREAD

**Issue by tomlober** [Shopify/shopify_app#565]
Hello,

Thanks for your work.
I have an undefined method when I call ShopifyAPI::InventoryLevel or InventoryItem.

I want retrieve stock level, in fact in productVariant inventory_quantity is deprecated.

Have you got a solution ?

All the best,

ToM

**Comment by jamiemtdwyer** [comment]
Hey @tomlober,

This issue is unrelated to `shopify_app` – you'll need to bump your `shopify_api` gem to the latest version.

https://github.com/shopify/shopify_api

Cheers,

JD
