### ISSUE TITLE
Local dev and "The redirect_uri is not whitelisted"

### ISSUE THREAD

**Issue by yeoenggu** [Shopify/shopify_app#573]
I have created a new app in a local dev environment, running ngrok and I encounter the familiar error "The redirect_uri is not whitelisted".  The generated url is using localhost.  The old redirect_uri has been taken away with little or no documentation on its replacement.  The only thing mentioned is that it is now automatically generated (which work for heroku deployment but not local dev).  

To fix it:
`Rails.application.config.middleware.use OmniAuth::Builder do
  provider :shopify,
           ShopifyApp.configuration.api_key,
           ShopifyApp.configuration.secret,
           callback_url: "http://12b67495.ngrok.io/auth/shopify/callback",
           scope: ShopifyApp.configuration.scope,

           setup: lambda { |env|
             strategy = env['omniauth.strategy']

             shopify_auth_params = strategy.session['shopify.omniauth_params']&.with_indifferent_access

             shop = if shopify_auth_params.present?
               "https://#{shopify_auth_params[:shop]}"
             else
               ''
             end

             strategy.options[:client_options][:site] = shop
           }
end`

I have to add callback_url.  Could you confirm?  

Documentation needs to improve for local dev.  Common need.  I am willing to chip in.

**Comment by rsfxiii** [comment]
I would like to help with documentation on this. However, I have a question about the localhost setup: **what are your whitelisted URLs within the Shopify Partner's App?**

Just wanted to compare to mine, because I don't have the `callback_url` in my `initializers/omniauth.rb` file, though I've got the following in my whitelisted URLs:

https://[NGROK_URL]**/login**
https://[NGROK_URL]**/auth/shopify/callback**

**Comment by rsfxiii** [comment]
Follow-up: I am also adding my NGROK_URL value through the following process:
1. Add "https://****.ngrok.io" to `development.env` as `NGROK_URL` env variable
2. Using `Dotenv` on `config/environment.rb` to require `NGROK_URL` upon startup
3. Adding `ENV['NGROK_URL']` to `config.hosts` array on `config/environments/development.rb`

**Comment by tanema** [comment]
This error is simply a problem with adding your ngrok URL to the app whitelist configuration in the Partners dashboard. To get past all of this I suggest using the shopify-app-cli and it takes care of that step for you
