### ISSUE TITLE
Shopify Mobile App - HMAC? 

### ISSUE THREAD

**Issue by sheppyh** [Shopify/shopify_app#574]
Hello,

My shopify app works great in browsers, although on new browsers I have to go back to my app login page, enter the shop URL and "reinstall" the app for it to get the sessions and be logged in and working. A minor annoyance.

However with the Shopify Android App it just doesn't load and of course I can't browse to the login page to create a session. 

I can see the shopify mobile app is passing the HMAC to the root page via params. HomeController#index is processed and a redirect to /login with the shop domain parameter takes place. ShopifyApp::Sessions Controller processes the request and we get a completed 200 OK. At this point we have a blank screen in the mobile app. Seems authentication did not complete and redirect back to the home page.

Has anyone got shopfiy_app working with the official shopify mobile app? Is my issue because shopfiy_app doesn't use HMAC and instead uses browser sessions?

Please forgive my ignorance, I've been using Ruby on rails for 1 week! (however have a fully working product bundle and multibuy app working, so seem to have learnt something)

**Comment by nwtn** [comment]
Closing because I believe this should no longer be an issue. We have a number of shopify_app-based apps working as expected in the Shopify mobile app (Android & iOS). Feel free to re-open if this is still a problem.
