### ISSUE TITLE
Token synchronization problem

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#576]
### Scenario

Shopify informs xyz.myshopify.com has API access to scoped resources with token __aabbcc00ff__

App has persisted a record of store install with shopify_domain __xyz.myshopify.com__ but token is different as __ddccff99aa__

### Questions

How can Shopify have a differing token than the one recorded?

If the App receives a different token than the one stored, should it not update the stored token? 

The caused me some grief. I understand that if I changed scopes that change will force the merchant to re-install the app and generate a new token, so I was under the assumption the code handles updating tokens. Seems on re-installs there is a hole in the App code at login time? 

To hard to re-produce example, but I am hoping my written presentation here stimulates some answers to what I faced. I lost some time thinking it was my code when really all along it was just a stale token stored in my DB that through 401 API request errors, hence App kept bouncing to login over and over..

**Comment by EiNSTeiN-** [comment]
The merchant may uninstall the app, and the old token will be destroyed from shopify. Upon reinstall the token would be different, so you would need to keep the new token and throw away the old one.

You can also register for the `app/uninstall` webhook topic (see https://help.shopify.com/api/reference/webhook) to be notified when your app is uninstalled, so you can then proactively destroy the access token for example. However there are scenarios where the webhook delivery may fail, if your app is unavailable for example, so you should still update your access token to whatever shopify gives you.

One caveat, if you request `per-user` permissions ([see `options` parameter in this doc](https://help.shopify.com/api/getting-started/authentication/oauth#step-2-ask-for-permission)) then you will get a different access token for each user, and you would keep this one in the user's `session` object, not in your DB.

**Comment by EiNSTeiN-** [comment]
I'll close this issue since it is unrelated to the gem.

**Comment by resistorsoftware** [comment]
My point was, I am pointing out that the gem currently does not handle this scenario, so it needs some code for token refresh. I do not normally use this gem, in my Apps I handle this scenario, so I was surprised when it popped up. I guess this Issue could serve others.
