### ISSUE TITLE
session[:shopify_user] is nil

### ISSUE THREAD

**Issue by yoonwaiyan** [Shopify/shopify_app#577]
I'm trying to use `session[:shopify_user]` to retrieve current user record, but apparently it's returning nil and I'm guessing that `associated_user` is nil too based on my experience developing another shopify_app. Am I missing out any configuration?

Sample app is provided here: https://github.com/yoonwaiyan/shopify-example. I'm trying to display what's inside `session[:shopify_user]` in the `current_shop` method.

**Comment by EiNSTeiN-** [comment]
Have a look at the configuration options for the shopify omniauth strategy:
https://github.com/Shopify/omniauth-shopify-oauth2/blob/master/lib/omniauth/strategies/shopify.rb#L21-L23
