### ISSUE TITLE
The redirect_uri is not whitelisted while working on dev using ngrok

### ISSUE THREAD

**Issue by tanya-bhargava** [Shopify/shopify_app#581]
Submitting Issues
-----------------

I used this code to setup an Application on my localstore, Everytime I try to install the app it redirects me to error page which says Oauth error invalid_request: The redirect_uri is not whitelisted.
I have checked all my authentication parameters URL, API key,Secret Key

**Comment by EiNSTeiN-** [comment]
closing since this is not an issue with this gem. the application must be configured correctly in the partner's dashboard.

**Comment by benwoodward** [comment]
@tanya-bhargava This can happen if you change the URL of the app (which happens if you change the app name in Heroku). In which case you would need to log into partners.shopify.com and update the app's URL whitelist settings there.
