### ISSUE TITLE
Missing Site URI in Shop Model

### ISSUE THREAD

**Issue by bstarr322** [Shopify/shopify_app#582]
Hi,

I'm calling shopify shop api in Shop model and saving domain into column called as domain on Shop table, but got this error:
```
ArgumentError (Missing site URI):

app/models/shop.rb:14:in `add_domain'

```
```
# shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::SessionStorage
  

  has_many :products, dependent: :destroy
  has_many :script_tags, dependent: :destroy

  after_create :add_domain
  
  private
  def add_domain
  	shop = ShopifyAPI::Shop.current
  	self.domain = shop.domain
  	save!
  end
end
```

Looking forward to your help.

Thank you

**Comment by jamiemtdwyer** [comment]
As the error indicates, the issue is with your `add_domain` hook. It appears to be expecting a fully qualified URI, which `shop.domain` is not.
