### ISSUE TITLE
postMessage issue

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#584]
What are most people doing with this Embedded App pattern when you deal with XHR calls to your App? 

If the current session has expired, that XHR call should fail. At this time, a lack of session means rendering HTML with the Javascript in the iframe supposedly informing the parent shop to re-authenticate. This does not work though, as the original call was an XHR call. 

So what do most people do these days to mitigate that? Same thing happens with expired JWT tokens I suppose.

**Comment by tylerball** [comment]
Hmm this is an interesting use case that I don't think we have an elegant solution for. I suppose if the XHR fails you could just refresh the page and have the page be protected by `AuthenticatedController` which would send them back through authentication and give them a new session, but that isn't very elegant.

**Comment by resistorsoftware** [comment]
There are a couple of super clunky patterns like this that remain. The other is links from the Admin. An App processes the link request (deal with order X, deal with products X,Y,Z) and then the App has nothing to do put stick up a silly page saying "We did it". Forcing the merchant to then stare at a dumb screen and re-click themselves back to the Admin.

An ELEGANT solution would allow the App to process the incoming link, and setup a FLASH message and go right back to where the click originated in the /admin. 

When can Shopify provide that? That would be some nice progress.

**Comment by tylerball** [comment]
This exact use case is one of the reasons why we built [App Extensions](https://help.shopify.com/en/api/embedded-apps/app-extensions), so apps can specify user interactions inside the Admin without that dance. Have a look, and feel free to reopen this if you have more questions.

**Comment by resistorsoftware** [comment]
So you are saying the following is possible.
* Shopify sends a GET to an EASDK App endpoint with an ID
* EASDK App accepts the GET, does whatever it needs to do based on the ID
* Can display a Flash message in the merchant's current /admin/XYZ 

In my mind, once that GET is complete, I return back the /admin using a redirect, but I cannot fill the Flash mechanism of Shopify, so how do I display a message? 

Please do inform me... I am very curious about how your expertise plays out here.

**Comment by resistorsoftware** [comment]
Well, so far, it has been about what? 6 years? Ever since there were Apps anyway... and no one has figured out how to allow Apps to populate the Shopify Admin Flash and land on a /admin page... I was hoping at some point since they went all in on EASDK and now Banana Bridge, there would be a way... still hoping...
