### ISSUE TITLE
uninitialized constant ShopifyApp::Shop  

### ISSUE THREAD

**Issue by alfredopantoja** [Shopify/shopify_app#593]
Rails 5.0.7, shopify_app gem 8.2.6 

This app has existed for about a year and this is the first time I see this issue.  When I try to run the rails server on my local environment: 

    /app/models/shop.rb:2:in `<class:Shop>': uninitialized constant ShopifyApp::Shop (NameError)
	from /Users/alfredo/Genius/Shop_creatify/foldabox/out_of_stock_notifier/app/models/shop.rb:1:in `<top (required)>'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /Users/alfredo/Genius/Shop_creatify/foldabox/out_of_stock_notifier/config/initializers/shopify_session_repository.rb:5:in `block in <top (required)>'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:396:in `instance_exec'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:396:in `block in make_lambda'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:546:in `catch'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:546:in `block in default_terminator'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:170:in `block in halting'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:454:in `block in call'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:454:in `each'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:454:in `call'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:750:in `_run_prepare_callbacks'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:90:in `run_callbacks'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.7/lib/active_support/reloader.rb:87:in `prepare!'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.7/lib/rails/application/finisher.rb:53:in `block in <module:Finisher>'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:30:in `run'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.7/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.7/lib/rails/application.rb:352:in `initialize!'
	from /Users/alfredo/Genius/Shop_creatify/foldabox/out_of_stock_notifier/config/environment.rb:5:in `<top (required)>'
	from /Users/alfredo/Genius/Shop_creatify/foldabox/out_of_stock_notifier/config.ru:3:in `require_relative'
	from /Users/alfredo/Genius/Shop_creatify/foldabox/out_of_stock_notifier/config.ru:3:in `block in <main>'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
	from /Users/alfredo/Genius/Shop_creatify/foldabox/out_of_stock_notifier/config.ru:in `new'
	from /Users/alfredo/Genius/Shop_creatify/foldabox/out_of_stock_notifier/config.ru:in `<main>'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `eval'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/builder.rb:40:in `parse_file'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:219:in `app'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.7/lib/rails/commands/server.rb:84:in `app'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.5/lib/rack/server.rb:354:in `wrapped_app'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.7/lib/rails/commands/server.rb:148:in `log_to_stdout'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.7/lib/rails/commands/server.rb:102:in `start'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.0.7/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/alfredo/Genius/Shop_creatify/foldabox/out_of_stock_notifier/bin/rails:9:in `require'
	from /Users/alfredo/Genius/Shop_creatify/foldabox/out_of_stock_notifier/bin/rails:9:in `<top (required)>'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	from /Users/alfredo/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:70:in `require'
	from /Users/alfredo/Genius/Shop_creatify/foldabox/out_of_stock_notifier/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by vfonic** [comment]
I'm pretty sure this is namespacing issue. Just change this line in `config/initializers/shopify_app.rb`:

```ruby
  config.session_repository = Shop
```

to:

```ruby
  config.session_repository = ::Shop
```

**Comment by alfredopantoja** [comment]
Thanks, Viktor. 

I actually didn't have that line at all in my `config/initializers/shopify_app.rb`

I tried that line in both versions (with and without the namespace), but still no luck.  I'm still getting the same error.  

My `config/initializers/shopify_app.rb` currently looks like this:

    ShopifyApp.configure do |config|
      config.application_name = "App name"
      config.api_key = ENV['shopify_api_key']
      config.secret = ENV['shopify_secret_key']
      config.scope = "read_products, write_products"
      config.embedded_app = true
      config.session_repository = ::Shop
   end

**Comment by vfonic** [comment]
The first line of the error message gives you great insight here:

> `/app/models/shop.rb:2`

Add `::` before Shop there. Or, if it's inside ShopifyApp, remove the module.

**Comment by alfredopantoja** [comment]
This is what my `app/models/shop.rb` file looks like:

    class Shop < ActiveRecord::Base
       include ShopifyApp::Shop
       include ShopifyApp::SessionStorage
     end

Basically it's as was generated by shopify_app.   If I comment out that second line, I'm once again able to start the rails server.   

But isn't that module somehow important? Why would it suddenly break?

**Comment by vfonic** [comment]
That's exactly what version 8 tells you to do: https://github.com/Shopify/shopify_app/blob/master/CHANGELOG.md#800

**Comment by vfonic** [comment]
Basically, you can remove that line of code and everything will work just fine (if you updated everything else for v8 “khm“omniauth.rb“khm“

**Comment by alfredopantoja** [comment]
Awesome.  Yeah, everything seems to be working.  Thanks so much for you help, Viktor!  Should I just close this issue?

**Comment by 0ptimusrhyme** [comment]
Closing
