### ISSUE TITLE
Error : invalid_site

### ISSUE THREAD

**Issue by ankit009** [Shopify/shopify_app#598]
Submitting Issues
<img width="1184" alt="screen shot 2018-06-05 at 12 01 06 pm" src="https://user-images.githubusercontent.com/4904953/40993983-35de51da-68b8-11e8-9d14-92311fb7d227.png">

-----------------

Please open an issue here if you encounter a specific bug with this gem or the generators

General questions about the Shopify API should be posted on the [Shopify forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology).

Authentication Issues
---------------------

A great deal of the issues surrounding this repo are around authenticating (installing) the generated app with Shopify.

If you are experiencing issues with your app authenticating/installing the best way to get help fast is to create a repo with the minimal amount of code to demonstrate the issue and a clearly documented set of steps you took to arrive there. This will help us solve your problem quicker since we won't need to spend any time figuring out how to reproduce the bug. Please also include your operating system and browser.

**Comment by EiNSTeiN-** [comment]
Looks like a configuration issue so I'm going to close this. In the future it would help if you added a proper description of the problem instead of submitting the issue template.
