### ISSUE TITLE
Latest Release is 7.40?

### ISSUE THREAD

**Issue by talecK** [Shopify/shopify_app#602]
Are there any plans to update the latest release or should it still be 7.40?  

We are planning to add support for the inventory API changes in our app and we are going to bump our shopify_api gem up to a more recent version.  Should we do the same for shopify_app or should we stick with 7.40? 

Thanks

**Comment by vfonic** [comment]
`shopify_app` gem is on version 8.2.6. You can see that at the top of the `Readme.md` (the badge icon): https://github.com/Shopify/shopify_app
`shopify_api` gem is on 4.11.0: https://github.com/Shopify/shopify_api

Maybe you read it someplace where it hasn't been updated yet. Anyway, these two versions are officially released.

**Comment by talecK** [comment]
Thanks @vfonic - if you take a look at https://github.com/Shopify/shopify_app/releases 7.4.0 is tagged as the latest release.  I'm guessing they just haven't updated the tag?

**Comment by jamiemtdwyer** [comment]
You can ignore the releases on github. The latest version will always be available from https://rubygems.org/gems/shopify_app.
