### ISSUE TITLE
Embedded app + custom front end.

### ISSUE THREAD

**Issue by jejacks0n** [Shopify/shopify_app#606]
I have a fully functional "embedded app" using this engine, so thanks so much for providing it!

The major question I have here is that I'd like to be able to have an embedded admin application, AND a custom front end where we load in collections, products, and variants without requiring a session. 

I'm using an unlisted partner application (I think this is the correct phrasing) and have provided some custom admin features using polaris and metafields, so my question is more around just loading collections/products/variants without a signed in/authed user. I created a secondary "private app", but they have very different authentication methods, and those clobber each other between requests.

Thanks in advance! I've found using the tooling from shopify to be refreshingly nice.

**Comment by jejacks0n** [comment]
Ok, after a lot of digging.

To give more clarity, I wanted an admin area and not admin area of a site. A custom front end, and some custom admin tools. To accomplish this I want one set of controllers to require authentication, so they inherit from`ShopifyApp::AuthenticatedController` -- these controllers provide the embedded admin interface. I do the standard setup in `config/initializers/shopify_app.rb`, nothing special there. this gets the admin tooling working well.

Now additionally, I want to display the collections/products/variants in my application to people who might not be authenticated in shopify with admin rights to the current shop. To do this, I have a set of controllers that inherit from your standard `ActionController::Base` chain. Inside these controllers I just want to read data.

This -- this was the hard part. I'm going to close the issue, as I've somewhat resolved it, but maybe someone else can shed light on it further and maybe there's a bug around this, or a way I can help document it for others.

Now, to load data without a session, the only way I found to do it was via a private app that generates an api_key and a password, which is a different setup then the api_key and secret that I've used to date in the basic setup. So we create the private app and add those new credentials. The docs for ShopifyAPI clearly state we can set `ShopifyAPI::Base.site`. Awesome, I initially did this in an around_filter in the controller and clear them out after yielding. This mostly seems to work, but I was getting 401s and 403s periodically when I would be doing things in the admin interface and then reviewing them in the front end. This left me feeling really hacky and I wanted to resolve it.

So a deep dive into ActiveResource later, it appears there's a bug somewhere in the way that `ShopifyAPI::Base` and `ActiveResource::Base` handle this with thread variables.

This is what I was seeing with the around filter:

```ruby
def setup_shopify_site
  begin
    creds = Rails.application.credentials.shopify_api
    ShopifyAPI::Base.site = "https://#{creds[:api_key]}:#{creds[:password]}@#{store_name}.myshopify.com/admin"
    yield
  ensure
    ShopifyAPI::Base.clear_session
  end
end
```

Super simple, right? Set it, yield, clear it. Now, this is where the odd behavior comes in.. Next request, `ShopifyAPI::Base.site` is set to what I set it last request, even though I've cleared it. I tried various ways to clear it but it would pollute the next request. No good.

The way I ended up solving this is to clear it ALWAYS in both the admin level controller and the front end controller by creating a before filter.

```ruby
  config = Rails.application.credentials.shopify_api
  ShopifyAPI::Base.clear_session
  ShopifyAPI::Base.site = "https://#{config[:api_key]}:#{config[:password]}@# {store_name}.myshopify.com/admin"
```

**Comment by kevinhughes27** [comment]
You shouldn't need a separate private app to load data for a shop outside of a ShopifyApp::Authenticated controller. After a user has installed the app you have a saved credential that you can use without the session. The webhook process controller already does this. You've actually identified the latter part of the solution correctly only instead of using a separate private app you should load the credential you already have and then create a Shopify API session.

**Comment by jejacks0n** [comment]
Thanks @kevinhughes27 that's useful. I felt a little strange with that because the scopes are setup very differently -- with the partner app having read/write access, and the private app setup to only read. So yeah, that might be something I investigate if I don't want to have to create the private app too.

**Comment by jamiemtdwyer** [comment]
Hey Jeremy,

If you want to continue to maintain separate access scopes, you could use [access token delegation](https://help.shopify.com/api/getting-started/authentication/oauth/delegating-access) to delegate a new token with only _read_ permissions.

> Now additionally, I want to display the collections/products/variants in my application to people who might not be authenticated in shopify with admin rights to the current shop.

I would be careful here though to ensure that the access token is never exposed to the end user. An Admin API access token, even limited to _read_ permissions grants access to a lot of a merchant's information that could be considered sensitive.

**Comment by jejacks0n** [comment]
Oh man, yeah, that's super useful info too. Thanks!

> I would be careful here though to ensure that the access token is never exposed to the end user. An Admin API access token, even limited to read permissions grants access to a lot of a merchant's information that could be considered sensitive.

For sure, I'm taking that into account and consider security to be pretty important generally speaking.
