### ISSUE TITLE
what to do next?

### ISSUE THREAD

**Issue by rammane650** [Shopify/shopify_app#609]
I don't have any issue but I don't know how to move ahead. How to start actual coding. where should I learn developing Apps using shopify API's
![screen1](https://user-images.githubusercontent.com/40760988/42163315-a12e1e80-7e1f-11e8-9d6c-de5219c08085.jpg)

**Comment by 0ptimusrhyme** [comment]
From here you can refer to the documentation to get an idea of what you can do through our APIs through the various endpoints. If you want to learn more about developing web apps there are plenty of tutorials around the internet.

For your reference: this public repository is for the shopify_app gem and subject matter relating to it only. If you're having an issue or have found a bug with the gem itself, feel free to open another issue here in the future.
