### ISSUE TITLE
Implement Recurring Charges

### ISSUE THREAD

**Issue by chrisjmccrum** [Shopify/shopify_app#610]
I apologize if this isn't the right place to ask this but being that skeleton of my app was generated from this gem - I thought I'd start here.  I completed an app using this gem which by the way was VERY helpful and would like to charge for the app. I'm looking for an example on how to integrate the recurring charge logic with the generated code from this project. 

Once the app is installed and shop is authenticated I'd like to make the charge. Is it possible to add this logic into the auth/sessions controller? An example would be helpful being that this is the only thing left holding me up.

Thanks again for any support!

**Comment by 0ptimusrhyme** [comment]
You can add this to the `SessionsController` as one possible approach. You can copy this into your codebase with `rails g shopify_app:controllers`. I personally put my post-install behavior within the `callback` method inside the `if auth_hash` conditional. For example:

```rb
module ShopifyApp
  class SessionsController < ActionController::Base
    # ...
    def callback
      if auth_hash
        # ...
        create_recurring_charge
        # ...
      end
    end
    # ...
  end
end
```

Where `create_recurring_charge` does as it describes with `ShopifyAPI`.
