### ISSUE TITLE
API objects and webhook payloads

### ISSUE THREAD

**Issue by JasonBarnabe** [Shopify/shopify_app#614]
If I do `ShopifyAPI::Shop.current` then I get a `ShopifyAPI::Shop` object with which I can do `o.name`. If I receive a `shop/update` webhook, then with the payload I can do `o[:name]`.

I have a few actions where our app is listening for webhooks but will also send API requests periodically or on demand and I would like them to use the same code when dealing with the response/payload. Right now I'm using code like:

```
    def fetch(object, key)
      if object.is_a?(Hash)
        object.fetch(key.to_s)
      else
        object.try!(key)
      end
    end
```
Is there a better way, e.g. converting a webhook payload into an API object?

**Comment by kevinhughes27** [comment]
All active resource based classes accept a hash to their constructor so you can pass the webhook to the constructor for the object and then use it the same way as if you fetched it.

**Comment by edavis10** [comment]
For example:

```ruby
shopify_order = ShopifyAPI::Order.new(JSON.parse(shopify_order_json)) 
shopify_order.name
```

**Comment by JasonBarnabe** [comment]
Got it. This works:

```ruby
my_shopify_model.with_shopify_session do
  return ShopifyAPI::Shop.new(JSON.parse(shop_update_payload)) 
end
```
