### ISSUE TITLE
Unauthorized Access on embedded app redirect with ShopifyApp.redirect();

### ISSUE THREAD

**Issue by JoshuaSoileau** [Shopify/shopify_app#616]
Hey guys

I have an embedded app, and I'm getting this when I try to redirect using JS client side:
![image](https://user-images.githubusercontent.com/2104388/43682049-17184790-9835-11e8-8741-5c23d467e9e2.png)

I make an AJAX request on link click like this:

**signup.html.erb**
```html
<a id="sign-up-button" class="Polaris-Button" href="/signup/confirmation">Buy Now</a>

<% content_for :javascript do %>
  <script type="text/javascript">
    ShopifyApp.ready(function(){
      ShopifyApp.Bar.initialize();
    });

    $(document).ready(function() {
      $("#sign-up-button").on('click', function(event) {
        event.preventDefault();
        console.log('clicked');

        $.ajax({
          type: 'GET',
          url: $("#sign-up-button").attr("href"),
          success: function(response) {
            console.log('succeeded')

            console.log(response);
            ShopifyApp.redirect(response.confirmation_url);
          },
        });
      });
  </script>
<% end %>
```

The URL set up for the button is set up in routes.rb like this:

**routes.rb**
```ruby
get 'signup/confirmation' => 'billing#do_charge'
```

Which points to my `BillingController::do_charge` method:

**billing_controller.rb**

```ruby
def do_charge
  # activates session
  MyModule.activate(session[:shopify_domain])

  # Do Charge
  # First instantiate a new charge object
  application_charge = ShopifyAPI::ApplicationCharge.new(
    name: "My Charge Name",
    price: MyModule.price,
    return_url: "https:\/\/my-url.herokuapp.com",
    test: true
  )

  # Then save the charge object (this executes the HTTP request necessary to create it)
  if application_charge.save
    if application_charge.status == "pending"

      render :json => application_charge
    else
      flash[:error] = "Uh oh, something went wrong!"
      render :json => { error: "status not pending" }
    end
  else
    flash[:error] = "Uh oh, something went wrong!"
    render :json => { error: "charge couldn't save" }
  end

end
```

Several other issues I found online mentioned the need for the redirect to work in an embedded app, you need to do it client side with JS. I've tried doing the same redirect with `redirect_to application_charge.confirmation_url` as well as `fullpage_redirect_to application_charge.confirmation_url` in my controller (without an AJAX call), but the embedded app doesn't redirect, it just routes to a blank page.

I've also tried this with the JS in place of `ShopifyApp.redirect()`:

```javascript
window.location = response.confirmation_url;
// as well as
window.top.location = response.confirmation_url;
```

Neither of those work either.

What am I getting wrong here?

**Comment by JoshuaSoileau** [comment]
In most of my AJAX attempts (outside of the `ShopifyApp.redirect()`) result in:

```javascript
Refused to display 'THE_URL' in a frame because it set 'X-Frame-Options' to 'deny'.
```

**Comment by JoshuaSoileau** [comment]
I also figured it has something to do with not having my session data in the redirect, so I also made a `form` that included the `csrf_meta_tags` and made the AJAX request on that form - although I probably didn't handle the session keys or whatnot properly in my controller for this approach.

**Comment by nwtn** [comment]
Are you able to change your `X-Frame-Options` heading? E.g., see the [Getting started section](https://help.shopify.com/en/api/embedded-apps/embedded-app-sdk/getting-started#x-frame-options-header) of the EASDK docs.

**Comment by katiedavis** [comment]
I'm going to go ahead and close this as it's stale with no reply
