### ISSUE TITLE
Webhook manager not registering multiple webhooks

### ISSUE THREAD

**Issue by flavio-b** [Shopify/shopify_app#619]
Hello, I noticed that when I added more webhooks to be setup by the webhooks manager, it stopped registering them all. This is the code that's not working:
```
#... other stuff in ShopifyApp.configure
config.webhooks = [
    {topic: 'customers/data_request', address: "https://#{ENV['DOMAIN']}/webhooks/customers_data_request", format: 'json'},
    {topic: 'shop/redact', address: "https://#{ENV['DOMAIN']}/webhooks/shop_redact", format: 'json'},
    {topic: 'customers/redact', address: "https://#{ENV['DOMAIN']}/webhooks/customers_redact", format: 'json'},
    {topic: 'app/uninstalled', address: "https://#{ENV['DOMAIN']}/webhooks/app_uninstalled", format: 'json'}
  ]
```

When I comment out the webhooks, except for the last one (app/uninstalled), it registers normally. Is anyone experiencing this issue? Do you see anything wrong with this code?

**Comment by JasonBarnabe** [comment]
The mandatory webhooks do not need to be configured in your code. You define the URLs to use in your app settings on the partner dashboard on Shopify. See also https://github.com/Shopify/shopify_api/issues/461

**Comment by flavio-b** [comment]
Got it! Thanks for the clarification. So those mandatory webhooks can't be registered via API, only via dashboard then. Maybe that's why they aren't mentioned in the [webhook API docs](url
https://help.shopify.com/en/api/reference/events/webhook)...

**Comment by JasonBarnabe** [comment]
Documentation on them is available at https://help.shopify.com/en/api/guides/gdpr-resources (in case you haven't already found that page)
