### ISSUE TITLE
Redirect issue on some browsers

### ISSUE THREAD

**Issue by CaseJnr** [Shopify/shopify_app#628]
Hi, I am using 8.2.6 of the gem with rails 5.1.6. The admin page of my app can be access from some browsers but others keep returning a "Blocked by extension" error due to being redirect to /login. Here are some logs

Succesful Request:

Started GET "/?hmac=2889e8541d1b9b777c55504286ef8f85248eefdcca69854bf2e1d43af13ff8b3&locale=en&protocol=https%3A%2F%2F&shop=myshop.myshopify.com&timestamp=1536050168" for 108.162.249.225 at 2018-09-04 08:36:10 +0000
Processing by CheckController#index as HTML
Parameters: {"hmac"=>"2889e8541d1b9b777c55504286ef8f85248eefdcca69854bf2e1d43af13ff8b3", "locale"=>"en", "protocol"=>"https://", "shop"=>"myshop.myshopify.com", "timestamp"=>"1536050168"}
[Shop Load (1.8ms)[SELECT  "shops".* FROM "shops" WHERE "shops"."id" = $1 LIMIT $[0m  [["id", 1], ["LIMIT", 1]]
Rendering check/index.html.erb within layouts/embedded_app
Rendered check/index.html.erb within layouts/embedded_app (0.3ms)
Rendered layouts/_flash_messages.html.erb (0.5ms)
Completed 200 OK in 213ms (Views: 3.4ms | ActiveRecord: 25.7ms)
 
Failed Request
 
Started GET "/?hmac=02c0931d0b62a6f20f33487e93f8bccba5791700f524398d90c36d483f674b65&locale=en&protocol=https%3A%2F%2F&shop=myshop.myshopify.com&timestamp=1536050193" for 108.162.250.51 at 2018-09-04 08:36:33 +0000
Processing by CheckController#index as HTML
 Parameters: {"hmac"=>"02c0931d0b62a6f20f33487e93f8bccba5791700f524398d90c36d483f674b65", "locale"=>"en", "protocol"=>"https://", "shop"=>"myshop.myshopify.com", "timestamp"=>"1536050193"}
Redirected to http://mydomain.com/login?shop=myshop.myshopify.com
Completed 302 Found in 1ms (ActiveRecord: 0.0ms)

My admin controller is super simple 

class CheckController < ShopifyApp::AuthenticatedController
  def index
  end
end

Routes are

mount ShopifyApp::Engine, at: '/'
get 'check/index'
root to: 'check#index'

Ive even tried removing the initialiser script from views/layouts/embedded_app.html.erb

**Comment by DavidAPC** [comment]
I figured out what my specific issue was. Basically I hadn't configured Nginx to properly request Https from the Rails server, so there was a mismatch between a http request and the https, causing an InvalidAuthenticityToken.

I've written more details on the problem and how I fixed it in a comment here: https://gist.github.com/abachman/851492

**Comment by nwtn** [comment]
Closing assuming @DavidAPC’s solution is the right one. Feel free to re-open if there are changes needed in the gem.
