### ISSUE TITLE
Oauth error invalid_request: The redirect_uri is not whitelisted

### ISSUE THREAD

**Issue by bryanbeshore** [Shopify/shopify_app#631]
I am building a new application, and in the process I am testing on a development store (just created) and am receiving the error:

Oauth error invalid_request: The redirect_uri is not whitelisted

I am using ngrok; I have whitelisted the URL's both http and https formats.

I followed the issue along on this post with no resolve:
https://github.com/Shopify/shopify_app/issues/486

Could you please help.

**Comment by CaseJnr** [comment]
I'm having the same issue here, try adding 

callback_url: "https://YOUR-URL.COM/auth/shopify/callback",

to config/initializers/omniauth.rb to so it looks something like this

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :shopify,
           ShopifyApp.configuration.api_key,
           ShopifyApp.configuration.secret,
           callback_url: "https://your-url.com/auth/shopify/callback",
           scope: ShopifyApp.configuration.scope,
           setup: lambda { |env|
             strategy = env['omniauth.strategy']

             shopify_auth_params = strategy.session['shopify.omniauth_params']&.with_indifferent_access
             shop = if shopify_auth_params.present?
               "https://#{shopify_auth_params[:shop]}"
             else
               '' 
             end
             strategy.options[:client_options][:site] = shop
           }
end

**Comment by bryanbeshore** [comment]
Yep. Got it to work. 

My issue was that my whitelisted URL was incorrect and I needed to shorten it to what you have: 
callback_url: "https://YOUR-URL.COM/auth/shopify/callback"

**Comment by bryanbeshore** [comment]
Ahh...And thanks for commenting
