### ISSUE TITLE
OAuth Error

### ISSUE THREAD

**Issue by IkumaOka** [Shopify/shopify_app#637]
I want an access token. I installed an application and redirected it to **http: // localhost: 3000 / auth / shopify / callback**, but I got an error. The image below is the content of the error.
<img width="1677" alt="problem" src="https://user-images.githubusercontent.com/37896288/45925225-16753580-bf4c-11e8-94ef-d3cfe5de509b.png">

**Comment by tylerball** [comment]
Hi sorry for the late response. It looks like this might not be the full error, instead of a screenshot could you copy and paste the full text of the error?

**Comment by flavio-b** [comment]
@tylerball , I've been getting this same error sporadically, but I can't find the reason yet. 

It's on the same route `/auth/shopify/callback` I've checked the query params passed in an error request and one in a request that works and they all seem the be passing the same params: `code, hmac, shop, state timestamp`. I can't see the headers nor cookies on the error request though. 

I've attached the error trace. 
[oauth_error_trace.txt](https://github.com/Shopify/shopify_app/files/2669726/oauth_error_trace.txt)

Please advise.

I'm using `Rails 5.0.7.1` with `shopify_app 8.3.2`, `Ruby 2.5.3`
