### ISSUE TITLE
ActionView::Template::Error when calling Product#metafields

### ISSUE THREAD

**Issue by wangthony** [Shopify/shopify_app#639]
1. Set up a new Rails app using the gem and the default AppProxyController.
2. Modified the app_proxy#index action to load a ShopifyAPI::Product into @product instance var.
3. Tried it out and the app proxy was loading in my Shopify store correctly. Yay!
4. Changed the view to this:

```
<code>
    <%= @product.id %>
    <%= @product.metafields.inspect %>
</code>
```

and got this error:

```
ActionView::Template::Error (undefined method `strip' for nil:NilClass):
    1: <code>
    2:   <%= @product.id %>
    3:   <%= @product.metafields.inspect %>
    4: </code>
  
app/views/app_proxy/index.html.erb:3:in `_app_views_app_proxy_index_html_erb___209846640228262040_70328798151860'
```

Am I doing something wrong? Should I not be passing data to the view like this? Or is it a bug?

Thanks!

**Comment by tanema** [comment]
This is an issue in ShopifyAPI and should no longer be an issue
