### ISSUE TITLE
Safari Technology Preview 65 breaks ITP workaround

### ISSUE THREAD

**Issue by smandegar** [Shopify/shopify_app#640]
After playing around with the latest release of Safari Technology Preview, it seems the redirect for cookie access no longer works; The page keeps reloading back to the `enable_cookies` route.

If I'm reading this correct, it seems in Safari Technology Preview 65 they added a test case to prevent what we are trying to do here with the `enable_cookies` route: https://trac.webkit.org/changeset/235569/webkit/trunk/LayoutTests/http/tests/storageAccess/request-and-grant-access-then-navigate-cross-site-should-not-have-access.html

**Comment by seashellski** [comment]
That's not good.

**Comment by ragalie** [comment]
Hi, thanks for the report!

We're aware of the changes coming in Safari 12.1 and are actively working on a solution to them. As you note there have been some changes to how ITP works in STP (including removing cookie partitioning, which our current solution uses), and there's a different path forward we're still implementing.

Based on past release patterns we expect Safari 12.1 to come out next spring, and you can expect us to make an announcement before then.

Thanks again! I'll assign this to our team so we can follow-up when the updates are announced.

**Comment by nwtn** [comment]
safari 12.1 itp solutions are in the gem now
