### ISSUE TITLE
Update README to recommend against linking directly to /login

### ISSUE THREAD

**Issue by smandegar** [Shopify/shopify_app#641]
We've been experiencing a strange issue where sometimes Safari 12 users who install our app for the first time are getting a 404 error from Shopify after clicking on the enable cookies button.

When the user installs, they're directed to our `new` action, but then the `redirect_for_cookie_access?` method kicks them to the enable cookies page before the app authorization screen is presented. The `enable_cookies.html.erb` page then redirects them to `window.shopOrigin + "/admin/apps/" + window.apiKey`, but that route wouldn't exist if the app has never been authorized by the client. 

It seems that the `after_action` in `LoginProtection` that sets in the session the `shopify.cookies_persist` value is happening too late and perhaps it should be a `before_action`. As a workaround we actually changed the `window.location.href` value in `enable_cookies.html.erb` to be `"<%= main_app.new_install_url %>"` which seems to be working fine.

Anyone else experiencing this issue? I can open a PR to change the `after_action` to a `before_action` if anyone else is running into this.

**Comment by EiNSTeiN-** [comment]
Hi @smandegar, I think this is the same issue as described in #640 ?

**Comment by smandegar** [comment]
Not quite. The difference here is the cookie actually does get set, but it appears to happen too late so that enable_cookies redirect results in a 404. If the client were to go through the install flow for the second time, it would work just fine because the `shopify.cookies_persist` would be present in the session.

The other issue describes the Technology Preview release of Safari which doesn't allow for cross-site access to that cookie, so even if the client were to go through the flow again it still wouldn't work with that build of Safari.

**Comment by ragalie** [comment]
Interesting, the merchant should never hit `enable_cookies` on the first install, because the first install happens in the top-level context, so there should always be cookie access.

I don't think the `after_action` is the culprit here, since it executes before the response is sent to the client. And if we were to change it to be a `before_action`, would we incorrectly assume that we always had cookie access, which isn't what we want.

How are you directing the user to the `new` action? The flow implicitly depends on the merchant first hitting a page that's protected by `AuthenticatedController`, which sets the test cookie and then redirects to `new`. If somehow the merchant were to get to the `new` action directly, then they would incorrectly be redirected to `enable_cookies`.

**Comment by smandegar** [comment]
Yeah, I assumed because we are at the top level that we'd have the cookie access already. I haven't been able to consistently reproduce this issue, but a couple customers have raised it to us who were using Safari 12.

The app is being installed from the Shopify app store which hits our root URL. In my routes I have `root to: 'shopify_app/sessions#new'`, so that would be going directly to the `new` action. I didn't know we weren't supposed to be going directly there. I'll adjust my routes file and hopefully that resolves this issue.

**Comment by ragalie** [comment]
That should resolve the issue, let us know if it doesn't.

I'm going to update the README to make this dependency clear and then I'll close this out. Thanks!

**Comment by smandegar** [comment]
Seems to be working, thanks for your help!

**Comment by tanhengyeow** [comment]
Hi @ragalie 

I'm a new contributor for Shopify and would love to work on this issue to get acquainted with the community. Could I be assigned this issue? Thanks :smile:

**Comment by ragalie** [comment]
Hi @tanhengyeow! Thanks for offering, that would be great!

You can read through this issue to get a better sense of the problem, but the gist of it is that it's not recommended to link users directly to the `/login` page.

Instead, app developers should link users to a page protected by [`AuthenticatedController`](https://github.com/Shopify/shopify_app/blob/master/app/controllers/shopify_app/authenticated_controller.rb), and that controller will redirect users to the `/login` page as needed.
