### ISSUE TITLE
Question - is there a NodeJS or PHP equivalent of this example app?

### ISSUE THREAD

**Issue by EugeneLiang** [Shopify/shopify_app#642]
Hi there!
Awesome work! 
May i know if there's a NodeJS or PHP equivalent of this example app?

Cheers!

**Comment by ragalie** [comment]
Hi! I'd recommend you look at a couple things:

1. We have a node sample app, but it uses a deprecated package: https://github.com/Shopify/shopify-node-app
2. We have a replacement for the deprecated package, but you'd need to roll your own app around it (though it's not too difficult to get started using it): https://github.com/Shopify/quilt/tree/master/packages/koa-shopify-auth

Good luck!
