### ISSUE TITLE
OmniAuth::Error invalid_site when trying to run example plugin

### ISSUE THREAD

**Issue by ice-lenor** [Shopify/shopify_app#649]
Hello,
I am trying out the shopify example plugin from the 'example' folder.

I have downloaded the repo from master, made no local changes (*), and I am following all steps from this instruction:
https://github.com/Shopify/shopify_app/tree/master/example

When I start the rails server on `localhost:3000`, and I open this URL with my test shop
`http://localhost:3000/login?shop=smartpuffinstore.myshopify.com`

I see this error page:

![shopify_example_app_error](https://user-images.githubusercontent.com/5493050/47239509-d63b9280-d3e5-11e8-8428-9372136a6ea3.jpg)

![shopify_example_app_error_2](https://user-images.githubusercontent.com/5493050/47240078-81991700-d3e7-11e8-9c3a-47cfeea989bb.jpg)

Expected effect, of course, is this:
> You will be prompted to install the application and will be redirected to the embedded Shopify environment once installed.

I am using Chrome	69.0.3497.100, Windows 8.1, Ruby 2.4.4. Please let me know if I should provide some more data.

I would really appreciate some help!

Thank you in advance.

(*) No local changes except for the `.env` file with my API keys; and also I had to add `gem 'tzinfo-data'` to `example/Gemfile`, which also might be a separate issue.

**Comment by ragalie** [comment]
I suspect the example app is out of date. I'd recommend following the installation instructions here on a new rails app: https://github.com/Shopify/shopify_app#installation

**Comment by overallduka** [comment]
Actually Im seeing this error on safari too, did not knew this until test, i bet few people use safari, because the apps did not work there at all:

https://www.dropbox.com/s/vl2mintjfn6g8jp/Screenshot%202018-11-16%2010.30.10.png?dl=0

Im using this gems:
```
  s.add_dependency "shopify_app", '~> 8.2.6'
  s.add_dependency "omniauth-shopify-oauth2", '~> 1.2.0'
  s.add_dependency "shopify_api", '~> 4.3.5'
  s.add_dependency "omniauth-oauth2", '~> 1.4.0'
  s.add_dependency "omniauth", '~> 1.7.1'
```

Any solution for this?

**Comment by ragalie** [comment]
`>= 8.3.0` includes a variety of fixes for the most recent Safari versions, you might try upgrading and see if that resolves your issue: https://github.com/Shopify/shopify_app/blob/master/CHANGELOG.md#830

**Comment by ice-lenor** [comment]
> I suspect the example app is out of date. I'd recommend following the installation instructions here on a new rails app: https://github.com/Shopify/shopify_app#installation

Thanks for replying!

May I ask if there are plans to fix the example app? So many official shopify tutorials point on this repo for examples, and it would greatly help new developers if they could peek into the example app and see how it should work.
For example, this tutorial page points here:
https://help.shopify.com/en/api/embedded-apps/embedded-app-sdk/examples

**Comment by tanema** [comment]
I am closing this since we no longer support the example app and generating a new app should create a working app
