### ISSUE TITLE
Infinite loop if Chrome blocks third-party cookies

### ISSUE THREAD

**Issue by flavio-b** [Shopify/shopify_app#677]
Hello,

I've observed a couple of issues when trying to authenticate to a shopify_app if Chrome has third-party cookies blocked. It has been a bit more common than I expected.

On 8.3.1, `SessionsController#redirect_for_cookie_access?` never returns false, so the user keeps getting redirect to `/ `-> `/login` -> `/enable_cookies`   infinitely. 

On 8.4.0, upon running `storage_access.js` it throws an error because it can't access `window.sessionStorage`, on line 36.

Steps to recreate: 

1. Visit  chrome://settings/content/cookies  and choose the option to block third-party cookies.
2. Try to open an embedded app running 8.3.1 and 8.4.0

I'm still running 8.3.1 in production because I've also seen some infinite redirections in 8.4.0, though I didn't have a chance to look at the cause yet. 

A possible solution for these issues would be:

1. Add a counter query param to check the number of attempts at setting a cookie.
2. Handle exceptions in the ITP Javascript side. 

I'm not too familiar with the current ITP workaround implementation, so I can't even say if these ideas make much sense. Any input is appreciated.

**Comment by sergey-alekseev** [comment]
I reproduced this problem as well with third-party cookies blocked in Chrome:  
![chrome-third-party-cookies-blocked](https://user-images.githubusercontent.com/2371639/51963610-2ec10800-248a-11e9-90eb-d969505efa63.png)

**Comment by sergey-alekseev** [comment]
Looks like this issue should be prioritized. We did a quick research in our app and here is what we found out.  

We only have logs for a very recent period. According to our tech lead @dhalai 48 users out of ~1500 installs during this period experienced this problem. This means more than 3% of users were affected.  We'll continue our research and reach out to those users. When we have more details we'll share them here.  

cc @nwtn @ragalie who were recently active in the repo

**Comment by markiiikram** [comment]
Hi @flavio-b and @sergey-alekseev, Thanks for bringing this issue to our attention, we are looking into solutions. Can you tell us more about why the cookies are being  blocked in Chrome? Thanks.

**Comment by flavio-b** [comment]
@markiiikram, thanks for looking into it.

In my case, I think it's just something that a few merchants have set on their browser, perhaps to increase privacy, or even unknowingly. Often a merchant's staff will use a shared computer, on which someone changed the cookie settings at some point in time, maybe without knowledge of its purpose. So, it's difficult to track the real reason.

**Comment by sergey-alekseev** [comment]
Hi @markiiikram, thanks for looking into solutions.  

As @flavio-b I'm not sure about people block third-party cookies in Chrome. However this is what I got from a conversation with a user who reported this:  
>Thank you for your help, yes I enabled third party cookies and had it installed without any problems afterwards.  

So looks like people do block third-party cookies for some reason, or at least they are blocked without their involvement.

@dhalai may bring more details this week, probably he'll be communicating with other users who experienced this problem.
