### ISSUE TITLE
couldn't find file 'twitter/bootstrap'

### ISSUE THREAD

**Issue by rngtng** [Shopify/shopify_app#68]
I just got the exception with a fresh, plain rails 4.0.1 app:  
```
couldn't find file 'twitter/bootstrap'
```
After reading this: https://github.com/metaskills/less-rails-bootstrap/issues/93, I added `require 'less-rails-bootstrap'` to `application.rb` and enabled `gem 'therubyracer', platforms: :ruby` for production - tataaa the exception is gone. 

Pls verify and I'll create a PR

**Comment by gmalette** [comment]
Is this still an issue?

**Comment by ckhatton** [comment]
I don't think so... well it definitely won't be any longer, once myself or someone removes the bootstrap :octocat:

**Comment by kevinhughes27** [comment]
latest version doesn't include bootstrap anymore. closing.
