### ISSUE TITLE
Content Security Policy prevents iframe from being rendered

### ISSUE THREAD

**Issue by goalaleo** [Shopify/shopify_app#680]
In the README for starting development [it is suggested](https://github.com/Shopify/shopify_app#becoming-a-shopify-app-developer) to set the Application Callback URL to http://localhost:3000/

However, it seems like this prevents rendering of the app in an iframe after the app has been installed in a store because it violates the Content Security Policy 

<img width="765" alt="screenshot 2019-01-11 12 57 54" src="https://user-images.githubusercontent.com/3275302/51030784-1f455200-15a3-11e9-8aef-6cd4d1ad10ee.png">

Resulting in this being shown
<img width="562" alt="screenshot 2019-01-11 12 58 12" src="https://user-images.githubusercontent.com/3275302/51030793-279d8d00-15a3-11e9-90ef-a052e6c29bd8.png">

It would be great to be able to do development without any proxy to localhost, and I find it a bit misleading that taking the steps in the README doesn't actually allow me to test the app inside the admin (embedded).

This *can* be circumvented by setting the `forceRedirect` to false, although it's not exactly the same.

**Comment by tylerball** [comment]
That CSP is set by Shopify and most likely will not change to allow `http` urls, but you're right about the README being a bit misleading. I'll open a PR to be more explicit about using [tunneling](https://github.com/Shopify/shopify_app#app-tunneling), show and example and maybe move it higher in the document.
