### ISSUE TITLE
Not storing shop in database

### ISSUE THREAD

**Issue by Shine18** [Shopify/shopify_app#682]
Hi, I created a shopify app following all the right steps and generated the controllers and models using the generators. I have mounted the engine at '/shopify'. I am stuck in an infinite loop of login when i try to install it or open the app from store admin. I also tried setting the 'embedded_app' to false. It seems to me the problem is that it's not storing the credentials of shop in the database. I checked the database.

**Comment by jamiemtdwyer** [comment]
Have you followed the instructions here? It doesn't sound like you've updated the omniauth provider.

https://github.com/Shopify/shopify_app#nested-routes

**Comment by Shine18** [comment]
Yes i followed all of the instructions. It seems i was adding the path with the host 'https://xxx.xxx.com/' as callback_path. Thanks for the help.
