### ISSUE TITLE
AfterAuthenticateJob misleading documentation => CAUSED US A LOT OF HEADACHE

### ISSUE THREAD

**Issue by nafaabout** [Shopify/shopify_app#690]
The documentation says: 

> If your app needs to perform specific actions after it is installed ShopifyApp can queue or run a job of your choosing (note that we already provide support for automatically creating Webhooks and Scripttags). To configure the after authenticate job update your initializer as follows:

I used it to send a welcome email to the user after he installs the app about how to better use it. After a couple days we received a flood of complaints, people are receiving too many emails even if **THEY HAVE BEEN USING THE APP FOR MONTHS NOW**. 
The problem was that the documentation was misleading and it turns out that this job is getting run every time a new session is created for the shop, for example when the user closes and reopens his browser.

**I suggest to change it to** 
> If your app needs to perform specific actions after the shop is authenticated successfully (i.e every time a new session is created for the shop), ShopifyApp can queue a job ... bla bla bla.

**And add this to make sure the message is clear**

> If you want to perform that action only once, e.g send a welcome email to the user when he installs the app, you should make sure that this action is idempotent, i.e make sure from your side that this action can only be performed once.

**Comment by gfscott** [comment]
Closing this issue since change was merged in #706
