### ISSUE TITLE
Question: is it possible to access a file in the `/public` folder from the web? 

### ISSUE THREAD

**Issue by Siggs2000** [Shopify/shopify_app#693]
I'm looking to provide access to a javascript file that I've placed inside my app. It needs to be publicly available on the web, unauthenticated, so I've placed it into the `/public` folder of my rails app and then tried to access it via https://my-store-name-here.myshopify.com/apps/my-app-name/file-name.js

I seem to get a 404 though. In fact I get a 404 even if I just go with https://my-store-name-here.myshopify.com/apps/my-app-name

I've seen this done in another shopify app like this: https://my-store-name-here.myshopify.com/apps/pushowl/sdks/service-worker.js?v1.6

Is mine not accessable because my app isn't published in the shopify app directory yet? (even though it's installed on my site) or is there a setting or something that I can change to allow for this behavior? 

Thanks in advance for any clues or assistance! 

UPDATE: 
As soon as I posted this, I noticed that if I add `/admin` to the URL, I can view the file like this:  https://my-store-name-here.myshopify.com/admin/apps/my-app-name/file-name.js but only as an authenticated user from my store and it's embedded into my store (since this is an embedded app) . So it's one step closer but still not quite there...

**Comment by Siggs2000** [comment]
I figured out a way to make this work. If you have the file in the `public` directory of your rails app, you can then use the Shopify "Proxy" feature to serve that file and have it be located as an extension of the store's URL. Like: https://my-store-name.myshopify.com/apps/file-name-here.js

**Comment by ajaysaini99** [comment]
Hi, what did you add in sub-Path and proxy url in "App proxy" region.
I have js file in public folder of shopify react app. I am stuck at what to add in sub-path and proxy url.

**Comment by ifat420** [comment]
Hey @ajaysaini99 . 
Did you find the solution?
