### ISSUE TITLE
Redirect loop when loading apps with an older version of shopify_app gem on iOS

### ISSUE THREAD

**Issue by jgodson** [Shopify/shopify_app#702]
On iOS 12.1.4 I'm having issues with getting into apps that are using older versions of the shopify_app gem. I'm getting a redirect loop and then a message that says `This application can't be loaded with the current version of Safari, try clearing your cookies or trying a different browser`

Version 8.5.1 seems to be working fine (besides another issue detailed [here](https://github.com/Shopify/shopify_app/issues/701)), but this was happening on apps using 8.2.5, 7.2.11 and 7.2.3.

**Comment by ragalie** [comment]
Thanks! This is (unfortunately) the expected behaviour on those prior versions, as Safari 12 introduced breaking changes that we were only able to work around by releasing new versions of the gem.
