### ISSUE TITLE
Enable 3p cookie toast not working in Chrome, Edge

### ISSUE THREAD

**Issue by nwtn** [Shopify/shopify_app#711]
Previously, a flash/toast message appeared if 3rd party cookies were turned off, prompting users to turn them on. The toast used to appear after 3 unsuccessful oauth attempts/redirects. [According to partner reports](https://github.com/Shopify/shopify_app/pull/697#issuecomment-478688187), this toast is no longer appearing in latest Chrome or Edge. I have reproduced in Chrome.

This is controlled by `preauthorized_redirect` in our oauth_controller, and there are no obvious recent changes there that would cause a problem.

**Comment by nwtn** [comment]
I spoke with @jaxee about this and it looks like it was missed when the Apps index page was ported to React.

**Comment by djirdehh** [comment]
The initial front end work for the intended solution has been established, details on approach can be found here: https://github.com/Shopify/web/pull/12576. With the minor changes on the server, and additional 🎩 - this ETA looks to be complete sometime next week.

**Comment by djirdehh** [comment]
The fix needed for this PR has been merged. 🎩 on my production store with third party cookies disabled [see image below].

![image](https://user-images.githubusercontent.com/12476938/56160072-34f85800-5f94-11e9-858f-5a351d8fb4e7.png)

@nwtn - do let me know if you'll be able to verify this; and we can go ahead and close this issue 👍.

**Comment by nwtn** [comment]
@djirdehh confirmed! this is awesome, thank you!
