### ISSUE TITLE
GDPR Mandatory Webhooks

### ISSUE THREAD

**Issue by robbyklein** [Shopify/shopify_app#712]
I'm confused how we're supposed handle these Webhooks. If I add

```
  config.webhooks = [
    {topic: 'shop/redact', address: 'https://example-app.com/webhooks/shop_redact'}
  ]
```

I get

```
ShopifyApp::WebhooksManager::CreationFailed (Topic Invalid topic specified.
```

Then i read [here](https://github.com/Shopify/shopify_app/issues/619) that you don't have to register these webhooks?

How do i handle the delete request? Is it as simple as creating 

```
class ShopRedactJob < ActiveJob::Base
  def perform(shop_domain:, webhook:)
    shop = Shop.find_by(shopify_domain: shop_domain)
    shop.destroy()
  end
end
```

and shopifyapp will verify the request and preform the job?

Thanks!

**Comment by kevinhughes27** [comment]
@robbyklein you've found a bit of a confusing gap between the Shopify docuementation and what this framework can do for you.

The GDPR webhooks are registered in the partner dashboard so you don't need to re-regiester them. If you configure the webhook to send to the `/webhooks/shop_redact' endpoint then the generic webhook handler controller will forward it to thhe job you've written above. Have a look at the Webhook controller to see how it works.

I hope that makes sense.

**Comment by Alex1sz** [comment]
@kevinhughes27 why not fix the documentation which is unclear in this area. Notice how there are many issues relating to the webhooks; probably a good indication that the documentation is poor in this area.

**Comment by benbonnet** [comment]
Does those webhooks works the same as others ? (gem embedded hmac verification, etc...)

**Comment by mysticaltech** [comment]
Exactly, spent a few hours debugging this 😠

**Comment by shan1122** [comment]
Any one who has implemented this share code with me
