### ISSUE TITLE
Update shopify_app gem to use App Bridge actions

### ISSUE THREAD

**Issue by gf3** [Shopify/shopify_app#723]
[Original issue](https://github.com/Shopify/app-bridge/issues/692) by @nwtn:

**Is your feature request related to a problem? Please describe.**
Right now shopify_app is using EASDK methods, and in its OAuth thingy it’s actually directly sending a postMessage

**Describe the solution you'd like**
In general, switching to App Bridge best actions and best practices around those

The OAuth thing is interesting. I think the reason we’re doing a raw postMessage is for perf — having to download the whole client just to dispatch a Redirect is pretty huge overhead, especially on a page we want to immediately get the user away from. I know doing postMessage directly is no bueno, so maybe we need to find a less fragile but still performant way to do this. 

**Describe alternatives you've considered**
Leaving it alone? It still works as is, because the postMessage signature is still valid for legacy bridge, so everything still works.

**Additional context**
I’m trying to write up instructions/docs for creating 1P embedded apps and I’d like to get this resolved within ~1 week to include in this guide.

**Comment by sergey-alekseev** [comment]
From https://help.shopify.com/en/api/embedded-apps/app-bridge/migrating#using-shopify-app-bridge-directly:  
>In the future, most new features will be added to Shopify App Bridge only, and will not be made available to the EASDK.
