### ISSUE TITLE
Using the ShopifyAPI in a controller that inherits AppProxyController

### ISSUE THREAD

**Issue by jimmypoulsen** [Shopify/shopify_app#724]
Hi!

I'm having some trouble using the ShopifyAPI inside a controller that inherits AppProxyController. Basically I have a controller named ApiController that inherits this AppProxyController. When a customer visits the account page I want to check if they have bought a specific product in the past. If they have they will be shown different information than the customers that haven't bought this product.

My ApiController has a method, `index` that renders some liquid in which I'm trying to do this:
`p ShopifyAPI::Customer.find({customer_id})`
When trying to do this an error immediately occurs in the terminal and I can't seem to figure out why:
`NoMethodError (undefined method `construct_api_path' for nil:NilClass):`

This works flawlessly in a controller that inherits AuthenticatedController but as far as I know this controller is only to be inherited in controllers that concerns the admin section and not the storefront. 

**My questions is: is it even possible to do this in a controller that inherits AppProxyController?**

I've managed to do it using only liquid syntax in the view, but I'm not sure that this is the right way to do it.

Thanks in advance.

**Comment by 0ptimusrhyme** [comment]
Hey @jimmypoulsen, that code path seems to be related to `shopify_api`'s code path surrounding API versioning. What versions of `shopify_app` and `shopify_api` are you using?

**Comment by jimmypoulsen** [comment]
Hi @0ptimusrhyme.

Sorry for the late answer. As for my versions they are as follows:
shopify_app: 9.0.1
shopify_api: 7.0.1

Thanks!

**Comment by mikeyhew** [comment]
`AppProxyController` is created by the generator using [this template](https://github.com/Shopify/shopify_app/blob/48faaf9e9455ccf467f153765fef077d5062a6e8/lib/generators/shopify_app/app_proxy_controller/templates/app_proxy_controller.rb), which `include`s the module `ShopifyApp::AppProxyVerification`, defined [here](https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/controller_concerns/app_proxy_verification.rb). All that does is verify that the hmac is valid and render `head :forbidden` if it isn't. It doesn't make any effort to set up an API session for the shop. You'll have to do that manually using the shop's domain in the params. (I can't remember the exact key, but try `params[:shop]`.
