### ISSUE TITLE
Issue Related to API Versioning

### ISSUE THREAD

**Issue by Shine18** [Shopify/shopify_app#725]
I am experiencing this issue on production mode on heroku, 
![image](https://user-images.githubusercontent.com/6214437/56342348-32367680-61d1-11e9-84a0-089652d0008b.png)

Yet it is running good on development mode on local environment. 
I think it is related to the latest api versioning of the shopify.

**Comment by dougmacqueen** [comment]
You need to add this method to your shop model as outlined here: https://github.com/Shopify/shopify_app#session-storage-change

**Comment by Shine18** [comment]
Yes Figured it out that day, Thanks

**Comment by Shine18** [comment]
Also in the latest version of this gem, there is an issue of registering webhooks on install. It is not registering the webhooks when installed in any store. I tried it with different dev stores. I couldn't debug it, so I specified these versions in my gemfile to make my app work. 

gem 'shopify_app', '~>8.4.0'
gem 'shopify_api', '~>5.2.4'
