### ISSUE TITLE
How do I make my paths use the shop URL instead of my app URL for a proxy app?

### ISSUE THREAD

**Issue by skillmatic-co** [Shopify/shopify_app#727]
So when I'm using the app as a proxy, my forms and paths are all returning the app proxy path.

For example, if I created a model called Review, and in a view i have `new_review_path`, it's returning `/app_proxy/review/new`, and this is creating an issue on the actual site side of things. If that link is clicked, it will try to go to `/app_proxy/review/new`, which obviously doesn't exist on the shop. How do I make `new_review_path` go to the correct proxy URL? Such as: `https://[SHOP_URL]/apps/myapp/review/new`?

Is this something I need to set in routes.rb?

**Comment by tanema** [comment]
You need to use the absolute url as you have specified. This is not a support forum this is a bug tracking board, please use the forums for this sort of request in the future.
