### ISSUE TITLE
Is it possible to get the current logged in Customer?

### ISSUE THREAD

**Issue by skillmatic-co** [Shopify/shopify_app#728]
I know how to get the currently logged in User (shop admin user). But is it possible to get the currently logged in customer?

**Comment by jimmypoulsen** [comment]
I'm not quite sure, because this has something to do with the authorization on your shop. I'm checking to see if a customer is logged in, when rendering the liquid:
`%{ if customer }%`

**Comment by nwtn** [comment]
As far as I know, this isn’t possible without rendering some liquid on the storefront, as @jimmypoulsen mentioned. For more help with this, you may want to pose this on our [APIs and SDKs Community forum](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology).
