### ISSUE TITLE
Webhook handler authentication problem

### ISSUE THREAD

**Issue by ggsandro** [Shopify/shopify_app#740]
Hi guys, I'm new to shopify, I have install my app, created a webhook on order creation (it's working) and want to handle this webhook inside of app. I set my webhook url to my-app.heroku.com and have a controller in my app. I'm trying to create a new session with this code

`ShopifyAPI::Session.setup(api_key: ShopifyApp.configuration.api_key, secret: ShopifyApp.configuration.secret)
    session = ShopifyAPI::Session.new(domain: domain, api_version: ShopifyApp.configuration.api_version, token: nil)
    scope = ["read_products"]
    permission_url = session.create_permission_url(scope)
    parameters = { 'client_id' => ShopifyApp.configuration.api_key, 'client_secret' => ShopifyApp.configuration.secret, 'code' => permission_url }
    token = session.request_token(parameters)
    session = ShopifyAPI::Session.new(domain: domain, api_version: ShopifyApp.configuration.api_version, token: token)
    ShopifyAPI::Base.activate_session(session)`

What am I doing wrong? I have no 'code' parameter and that's why got "ShopifyAPI::ValidationException (Invalid Signature: Possible malicious login)". Can someone tell me how can I authenticate?

Thx in advance and sorry if this question was asked, I have not found such thread.

**Comment by gfscott** [comment]
Hi @ggsandro, thanks for getting in touch.

You might have already investigated this, but have you looked at the [**WebhooksManager**](https://github.com/Shopify/shopify_app#webhooksmanager) section of the readme? It automates many common webhook tasks and handles authentication too.

That section of the readme goes over a few things that might address the issue you're having: the `config.webhooks` object, the `WebhookVerification` module, and the command-line `add_webhook` generator.

If none of these tools solve your problem, please let me know!

**Comment by ggsandro** [comment]
Thx a lot @gfscott I have read it again and made a job for handling that. Issue can be closed, that is my code if somebody will experience the same issues

WebhooksController

class WebhooksController < ActionController::Base
  include ShopifyApp::WebhookVerification

  class ShopifyApp::MissingWebhookJobError < StandardError; end

  def receive
    params.try(:permit!)
    job_args = {shop_domain: shop_domain, webhook: webhook_params.to_h}
    webhook_job_klass.perform_later(job_args)
  end

  private

  def webhook_params
    params.except(:controller, :action, :type)
  end

  def webhook_job_klass
    "OrdersCreateJob".safe_constantize or raise ShopifyApp::MissingWebhookJobError
  end

  def webhook_type
    params[:type]
  end
  
end


OrdersCreateJob:


class OrdersCreateJob < ActiveJob::Base
    def perform(shop_domain:, webhook:)
        shop = Shop.find_by(shopify_domain: shop_domain)
        shop.with_shopify_session do
            # something to do
        end
    end
end
