### ISSUE TITLE
:order => "created_at DESC" is not a valid parameter for the Order query

### ISSUE THREAD

**Issue by ckhatton** [Shopify/shopify_app#75]
In: `home_controller.rb` Line: `15`
https://github.com/Shopify/shopify_app/blob/master/lib/generators/shopify_app/templates/app/controllers/home_controller.rb#L15

The `:order => "created_at DESC"` parameter is not valid. In other words, it does not work.

This is because the Shopify API is an ActiveResource, the parameter `order` does not work in the same way that it would with an ActiveRecord model.

`limit` is one of the end points of `Order`, so that parameter works.
http://docs.shopify.com/api/order#index

**Comment by Waynenabors** [comment]
I noticed that ordering still does not work for Draft Orders. Is there a work around besides sorting the array?

`ShopifyAPI::DraftOrder.find(:all, :params => {limit: 5, order: "updated_at DESC"}).map(&:updated_at)`

**Comment by 0ptimusrhyme** [comment]
@Waynenabors Can you create an issue in https://github.com/Shopify/shopify_api if one does not exist already, and you can reliably replicate on a recent release?

This repository is not the place for shopify_api issues.

**Comment by 0ptimusrhyme** [comment]
Thanks for clarifying! Due to the age of the post, would you mind creating a new thread on the APIs and SDKs forum specific to the issue? Post a link here when you have and I'll try to get to it soon unless someone else does.

**Comment by Waynenabors** [comment]
https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/shopify-admin-api-draft-order-order-updated_at-desc-not-ordering-results-552742

**Comment by ckhatton** [comment]
I know you have created the forum post, but commenting on it doesn't seem to want to work for me 😑

---

I know it isn't a fix perse, but have you tried the work around...

`.sort_by(&:created_at) or .sort_by(&:created_at).reverse`

For example:

```
<% @DraftOrders.sort_by(&:created_at).reverse.each do |order| %>
...
<% end %>
```

It could be worth doing that in the meantime while an endpoint is being created.

**Comment by Yu-coding** [comment]
Hi @csaunders 
Can I use like this?
ShopifyAPI::Product.find(:all, :params => {:limit => 5, :order => "order_number DESC"})

**Comment by ckhatton** [comment]
@yu-coder `order_id` maybe, but not `order_number` as that doesn't exist as a parameter.
