### ISSUE TITLE
undefined method `api_version' for #<ShopifyShop:0x00007ff590685348

### ISSUE THREAD

**Issue by iamricks** [Shopify/shopify_app#750]
When i try to update the access token on a ShopifyShop object in my database i get:

`undefined method api_version' for #<ShopifyShop:0x00007ff590685348`

My code is just:

`shop.update_attributes(shopify_token: token) if shop`

In my ShopifyShop model i do include `include ShopifyApp::SessionStorage`

Anyone know why this error keeps being thrown?

**Comment by heldopslippers** [comment]
yes me too.

**Comment by andreas-sotnik-2k19** [comment]
@iamricks  @heldopslippers 

I got similar issue during upgrade to the latest shopify_app gem version.

I regenerated code with `$ rails generate shopify_app:install` and also did these https://github.com/Shopify/shopify_app#upgrading-from-86-to-900 changes and now it's all working for me.

**Comment by nwtn** [comment]
@iamricks @heldopslippers did @andreas-sotnik-2k19’s solution work for you?

**Comment by iamricks** [comment]
@nwtn Just tested it.

After following these instructions:

> Configuration change
> 
> Add an api version configuration in config/initializers/shopify_app.rb Set this to the version you want to run against by default. See Shopify API docs for versions available.
> 
> config.api_version = '2019-04'
> 
> Session storage change
> 
> You will need to add an api_version method to you session storage object. The default implmentation for this is.
> 
> def api_version
>   ShopifyApp.configuration.api_version
> end

My fault for not reading the changelog.

**Comment by seshna** [comment]
@iamricks hey im having the same issue - i cant for the life of me figure out where I'm supposed to put 
`def api_version
ShopifyApp.configuration.api_version
end`

could you help me out?

**Comment by Rasovsky** [comment]
@seshna Have you figured it out? I have the same issue...

**Comment by seshna** [comment]
@Rasovsky my shopify_app and shopiy_api gems both needed to be updated, and with the code i wrote above, it worked.
