### ISSUE TITLE
[PR question] Any reason you're using following pattern with IIFE's in JS files?

### ISSUE THREAD

**Issue by juliantrueflynn** [Shopify/shopify_app#753]
The IIFE's being used are passing the argument `window` but never used in function. If the goal was to bind `window` to the IIFE, this wouldn't be accomplishing it and you would instead need to do something like `(function() { /* code */ }).call(window)`.

This caused some issues for my SPA. Would you be open to me doing a PR to fix this?

[Here's an example](https://gist.github.com/juliantrueflynn/666e4e7b6cb1dfb2068f999e185d36b4) using `storage_access.js` file and what would be changed. (Please note comments I made on lines: 1, 92, 124.)

**Another PR Suggestion**: For my SPA I also had to move all `app/assets/javascripts/shopify_app` files to partial views to avoid Rails asset pipeline. I notice you do this with styles already, is there any reason you don't do it with the scripts? Another benefit to this would be it would work with the gem's generators better for users to overwrite them if needed. I would be willing to do this as PR too.

**Comment by nwtn** [comment]
In general, yes, we are open to PRs! What sort of issues with your SPA did you see?

**Comment by juliantrueflynn** [comment]
If you have 2 different sources of assets (ex. create-react-app and shopify_app) being compiled to `/public` then there's issues with assets being missing. If shopify_app avoided Rails asset pipeline, which I could do as separate PR, this gem could be integrated a lot easier with SPA's.
