### ISSUE TITLE
Rails 6.0.0.rc1 deprecation for initialization autoloading of session_repository

### ISSUE THREAD

**Issue by axlekb** [Shopify/shopify_app#757]
Hi folks,

Running `rails 6.0.0.rc1` and noticed a deprecation with `shopify_app.rb` initializer.

This appears to be the offending line which is created by `rails generate shopify_app:shop_model`
```
  config.session_repository = Shop
```

```
DEPRECATION WARNING: Initialization autoloaded the constant Shop.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload Shop, for example,
the expected changes won't be reflected in that stale Class object.

This autoloaded constant has been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <top (required)> at <...>/config/environment.rb:7)
```

**Comment by nwtn** [comment]
thanks for the heads-up!

**Comment by shawnfrench** [comment]
A workaround for now is to remove code calling `session_repository=` and instead set the session repository storage class directly within a `to_prepare` callback (avoids autoloading the constant, but runs once at application startup and every time the code is reloaded):
```
ShopifyApp.configure do |config|
  ...
end

Rails.application.config.to_prepare do
  ShopifyApp::SessionRepository.storage = ShopifyApp::InMemorySessionStore
end
```

**Comment by axlekb** [comment]
So I can confirm this appears to work when the `Rails.configuration.cache_classes` is `true`.  So it works on my production environment, however I get errors in my test and development environment that don't cache classes.

```
#<ShopifyApp::SessionRepository::ConfigurationError: ShopifySessionRepository.storage is not configured!>
/.../gems/shopify_app-11.4.0/lib/shopify_app/session/session_repository.rb:23:in `storage'
/.../gems/shopify_app-11.4.0/lib/shopify_app/session/session_repository.rb:15:in `retrieve'
/.../gems/shopify_app-11.4.0/lib/shopify_app/controller_concerns/login_protection.rb:31:in `shop_session'
/.../gems/shopify_app-11.4.0/lib/shopify_app/controller_concerns/login_protection.rb:35:in `login_again_if_different_shop'
```

```ruby
# lib/shopify_app/configuration.rb
    def session_repository=(klass)
      if Rails.configuration.cache_classes
        ShopifyApp::SessionRepository.storage = klass
      else
        ActiveSupport::Reloader.to_prepare do
          ShopifyApp::SessionRepository.storage = klass
        end
      end
    end
```

**Comment by shawnfrench** [comment]
After some discussion a better approach is to simply use a string to set `session_repository` instead of a class. So anyone using rails 6 should be able to solve the load warning by changing their initializer to look like:
```
ShopifyApp.configure do |config|
  ...
  config.session_repository = 'ShopifyApp::InMemorySessionStore'
end
```

Closing now that the workaround has been documented, and the fix to the setter and our generators has been merged in https://github.com/Shopify/shopify_app/issues/757. We'll include in the next release asap.
