### ISSUE TITLE
undefined method `construct_api_path' for nil:NilClass

### ISSUE THREAD

**Issue by markdavies** [Shopify/shopify_app#758]
When using version 9+ of this gem, which in turn uses version 7+ of shopify_api, we get this error when trying to make an API call:

NoMethodError: undefined method `construct_api_path' for nil:NilClass

This error occurs in the shopify_api gem, but I believe is because the setting for api_version from the config is not being passed through to shopify_api.

[See here](https://github.com/Shopify/shopify_api/issues/574)

**Comment by LouiseEH** [comment]
@markdavies Was the issue fixed? I am struggling with this in shopify_app 11.0.1 and shopify_api 8.0.0
