### ISSUE TITLE
Unable to retrieve orders through the gem only

### ISSUE THREAD

**Issue by adamhenstock** [Shopify/shopify_app#767]
Hi

I'm unable to retrieve all orders from a customer when in Rails, only a partial result (2 out of 9).  orders_count gives the correct number, but customer.orders does not.  I've added a status: 'any' to the call with no change.  I've tried upgrading to the latest shopify_app gem (8.3.1 to 9.0.4), but this made no change.  This is happening for multiple customers and there is no obvious difference between the orders.
  
```
2.4.1 :012 > shopify_session = ShopifyAPI::Session.new(domain: "customshop.myshopify.com", token: "xxxx", api_version: '2019-04')
 => #<ShopifyAPI::Session:0x005623745341c8 @domain="customshop.myshopify.com", @api_version=2019-04, @token="xxxx", @extra={}>
2.4.1 :013 > ShopifyAPI::Base.activate_session(shopify_session)
 => 2019-04
2.4.1 :014 > shop_customer = ShopifyAPI::Customer.find(123456789)
 => #<ShopifyAPI::Customer:0x005623744c3810 @attributes={"id"=>123456789, "email"=>"customer@customshop.com", "accepts_marketing"=>true, ........ }
2.4.1 :015 > shop_customer.orders.where(status: "any").size
 => 2
2.4.1 :016 > shop_customer.orders_count
 => 9
2.4.1 :017 > ShopifyAPI::Order.find(12345)  # order id one of .orders above
 => #<ShopifyAPI::Order:0x007f59a47dac58 @attributes={"id"=>1025706852446, "email"=>"justine@castawayyarnshop.com", "closed_at"=>nil, "created_at"=>"2019-04-18T11:43:43-07:00", ....... }
2.4.1 :018 > ShopifyAPI::Order.find(54321)  # order id retrieved from the json response below
ActiveResource::ResourceNotFound: Failed.  Response code = 404.  Response message = Not Found.
```

API calls in the browser work (listing all nine orders and returning the order missing above) :
https://customshop.myshopify.com/admin/api/2019-04/customers/123456789/orders.json
https://customshop.myshopify.com/admin/api/2019-04/orders/54321.json  

---

I'm guessing this is not a wider problem, but something specific to my install.  I seem to be authenticated correctly as I can receive some orders, but I've no idea why not the others.  Any assistance in a direction to start looking would be appreciated.

**Comment by kevinhughes27** [comment]
Is it possible you are running into this? https://community.shopify.com/c/API-Announcements/ACTION-REQUIRED-Apps-require-Shopify-approval-to-read-orders/m-p/413004

**Comment by adamhenstock** [comment]
Yeah, that was the cause, thanks for the help!
