### ISSUE TITLE
Would be good to have `MIGRATION_GUIDE.md` or similar

### ISSUE THREAD

**Issue by vfonic** [Shopify/shopify_app#774]
I just saw that v10.0.0 of this gem has been released couple of days ago.

So I went to README.md and [CHANGELOG.md](https://github.com/Shopify/shopify_app/blob/master/CHANGELOG.md) to see what are the breaking changes before upgrading.
From reading both of these files, I have no idea what are the breaking changes.

There's required rails version bump, apart from that, I not sure I'm missing something else or not?

Here's how it looked like for v9 and I was glad to see this and more confident upgrading:
https://github.com/Shopify/shopify_app#upgrading-from-86-to-900

Edit: `shopify_app` v9 also got a clear(er) entry (regarding breaking changes) in CHANGELOG.md: https://github.com/Shopify/shopify_app/blob/master/CHANGELOG.md#900
> Breaking change: Api version support added see migration guide

(migration guide pointing to the above-linked README.md "Upgrading from 8.6 to 9.0.0"

I think a `MIGRATION_GUIDE.md` would be great, or at least an entry in `CHANGELOG.md` which would clearly state what are the breaking changes. So in this version bump it would state something like:

> Apart from minimum required rails version change, there are no other breaking changes.

Thanks!

**Comment by tanema** [comment]
Thank you @vfonic I will be adding to our contribution guidlines that any breaking changes need a note in the changelog on how to migrate, or what to use instead.

**Comment by vfonic** [comment]
Thank you @tanema!

Feel free to close this issue when the contribution guidelines are updated. 👍
