### ISSUE TITLE
session[:shopify_domain] gives me wrong domain

### ISSUE THREAD

**Issue by marko-ivan** [Shopify/shopify_app#778]
I have developed Shopify App using shopify_app gem.
I have installed my app on 2 stores.
For example, 
one store's domain:  **store-test.myshopify.com**
one store's domain:  **store.myshopify.com**

First, I have installed on **store.myshopify.com** and then I have installed on **store-test.myshopify.com**

But when I retrieve the Shopify domain from **session[:shopify_domain]**, I always get **store-test.myshopify.com**

Anyone could help me please?

**Comment by tiffanytse** [comment]
Have you tried uninstalling it from the first domain just to test for now? 

That or which store are you currently logged into?

**Comment by marko-ivan** [comment]
@tiffanytse thanks for your reply. I appreciate it.
As first domain(**store.myshopify.com**) is live store, so I want to fix this without uninstalling on this store.
But it is okay for me to uninstall and install on **store-test.myshopify.com**
I have uninstalled on **store-test.myshopify.com** and checked on **store.myshopify.com** but session[:shopify_domain] gave me **store-test.myshopify.com** again.

**Comment by marko-ivan** [comment]
@tiffanytse sorry, could you please help me to fix? Thank you.

**Comment by marko-ivan** [comment]
I have fixed this issue.

The issue was that **HomeController** is inherited from **ApplicationController**, not 
**ShopifyApp::AuthenticatedController**

Anyway thanks @tiffanytse

**Comment by tiffanytse** [comment]
Was this a mistake in the documentation somewhere or just your app? I just want to know if it's a mistake on our end so I can fix it. :)

Glad you figured it out!

**Comment by marko-ivan** [comment]
@tiffanytse 
The issues were just on my app. Your documentation is great and very helpful.
Thank you.
