### ISSUE TITLE
Safari 12.1 - localization and return_to URL don't work

### ISSUE THREAD

**Issue by rebeccajfriedman** [Shopify/shopify_app#779]
Following the instructions for the latest version of shopify_app (11.0.1), I'm having two issues on Safari 12.1. When the flow to grant storage access starts:
1) The `return_to` value in the session seems to get lost.
2) The `locale` value that gets sent from the original request is lost.

**Comment by mkevinosullivan** [comment]
Confirmed fixed using `shopify_app` gem v12 (was on v11) by Buy Button team
