### ISSUE TITLE
deployed app UI issue

### ISSUE THREAD

**Issue by azzouzze** [Shopify/shopify_app#780]
when trying to log into the app, first screen where you enter your shop url i am getting the following error 

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

url is: 
https://flagback.herokuapp.com/auth/shopify/callback?code=4ab2f202e271f2de138c50744eaf97bd&hmac=b7eb91f8cc74dd2830d9243f18bae58322a467f79ae41e579785687f9eaf7d02&shop=flagback.myshopify.com&state=ccf798e623033ceab95807e87b1015093795a4d08c2e6322&timestamp=1563557681

**Comment by Rasovsky** [comment]
@azzouzze Have you fixed it? I am having the same issue...

**Comment by Rasovsky** [comment]
I fixed this issue now with this https://github.com/Shopify/shopify_app/issues/750#issuecomment-519144205
