### ISSUE TITLE
Rails asset problem with generated app

### ISSUE THREAD

**Issue by peteoleary** [Shopify/shopify_app#784]
I am in the process of upgrading a set of existing app to the latest ShopifyApp and ShopifyAPI gems. I am seeing a problem whenever I try to run the new ShopifyApp in production. I have reproduced this problem by simply generating a new app and running it in production mode on my local machine. Same thing happens running in production at Heroku. If I turn off "embedded app" then request_storage_access is not loaded but that is not an acceptable workaround.

I, [2019-08-19T10:10:55.973412 #63860]  INFO -- : [3d4f3b7b-ebd4-464e-9929-50656450f1a0] Started GET "/assets/shopify_app/request_storage_access-fb446fdeb85f0a8fa5f9f540bb0e6d7c9732014d6e9c2f6f4f7be2ec47c863b4.js" for 127.0.0.1 at 2019-08-19 10:10:55 -0700
F, [2019-08-19T10:10:56.089838 #63860] FATAL -- : [3d4f3b7b-ebd4-464e-9929-50656450f1a0]   
F, [2019-08-19T10:10:56.090112 #63860] FATAL -- : [3d4f3b7b-ebd4-464e-9929-50656450f1a0] ActionController::RoutingError (No route matches [GET] "/assets/shopify_app/request_storage_access-fb446fdeb85f0a8fa5f9f540bb0e6d7c9732014d6e9c2f6f4f7be2ec47c863b4.js"):

**Comment by tanema** [comment]
Hey @peteoleary I am just checking that everything runs fine while in developing? Also when you say in production mode, you mean `RAILS_ENV=production rails s`

**Comment by peteoleary** [comment]
@tanema yes, it seems to work fine when RAILS_ENV=development but fails when RAILS_ENV=production

**Comment by tanema** [comment]
This may be one of two problems. You may need to precompile your assets if you have not already. You also may need to enable the public file server in config/environments/production.rb

**Comment by tanema** [comment]
@peteoleary did you figure this out?

**Comment by AfolabiOlaoluwa** [comment]
I am experiencing the same problem with Rails 6 and Ruby 2.6.3 with Heroku and to make it funny it is during an interview session.

**Comment by AfolabiOlaoluwa** [comment]
@peteoleary did you fix this and how?

**Comment by tanema** [comment]
This should be fixed now, There was an issue that ActionController::Base was referred to at startup before asset host config could be set so the assets would get served from your app instead of where you have setup your CDN. This would break especially if you have configured your production app to not serve static assets.
