### ISSUE TITLE
Bugsnag/API deprication console warnings

### ISSUE THREAD

**Issue by mwalkowiak** [Shopify/shopify_app#785]
Console warnings
-----------------

Once installing new shopify app and landing on the main page chrome console keeps sending these warnings to the console:

```
[bugsnag] notify endpoint is set but sessions endpoint is not. No sessions will be sent.
console.warn @ main-9e8529b5f22e51958bc3d958d2b48e774278c1297f1cbab5f5b6265d4267a7b0.js:1

Deprecated API for given entry type.
vendors~main-58cb8d62dd47ff9d384a0d652dc0208feab6f56960fa4f262609269c35341659.js:1 
```

does anybody have any idea how to fix it? I believe this is related to EASDK

**Comment by tanema** [comment]
Is this a problem with shopify_app? As far as I can tell, bugsnag is not part of this gem. (although there have been fixes in the past for integration)

**Comment by tanema** [comment]
I think you were right, but now easdk has been removed in favour of AppBridge
