### ISSUE TITLE
SessionStorage.with_shopify_session raises UnknownVersion error

### ISSUE THREAD

**Issue by chrismbarnes** [Shopify/shopify_app#787]
This issue seems to stem from `ShopifyAPI::Session.temp` not using the `api_version` that is passed when reverting the session to `original_session`. It ends up using `ShopifyAPI::Base.api_version` which I don't believe is set within ShopifyApp. 

It looks like setting `ShopifyAPI::Base.api_version` has only been a requirement starting with version 7.0.0 of the shopify_api gem.

Not sure if this is something that should be changed in the shopify_api gem, but perhaps we could add this to `ShopifyApp::Configuration`:
```ruby
def api_version=(version)
  @api_version = version
  ShopifyAPI::Base.api_version = version
end
```

Here is the code I referred to from `ShopifyAPI::Session`:

```ruby
def temp(domain:, token:, api_version:, &block)
  session = new(domain: domain, token: token, api_version: api_version)

  with_session(session, &block)
end

def with_session(session, &_block)
  original_session = extract_current_session

  begin
    ShopifyAPI::Base.activate_session(session)
    yield
  ensure
    ShopifyAPI::Base.activate_session(original_session)
  end
end

def extract_current_session
  site = ShopifyAPI::Base.site.to_s
  token = ShopifyAPI::Base.headers['X-Shopify-Access-Token']
  version = ShopifyAPI::Base.api_version
  new(domain: site, token: token, api_version: version)
end
```

**Comment by arialblack14** [comment]
Shopify/shopify_api#614

**Comment by tanema** [comment]
This seems like a ShopifyAPI issue instead and I will see if I can address it over there
