### ISSUE TITLE
WebhooksManager failing to register webhook, returning 404

### ISSUE THREAD

**Issue by alex-espinoza** [Shopify/shopify_app#793]
# Issue

I'm trying to register the `app_subscriptions/update` and `app/uninstalled` webhooks to a shop after authentication. The `ShopifyApp::WebhooksManagerJob` task is enqueued just fine in my message queue, but when my queue attempts to work on it, it fails with this message:

`ERROR: Processor failed: Failed.  Response code = 404.  Response message = Not Found.`

From looking at the stack trace, this error is occurring in the `webhooks_manager.rb` file:

`/Users/alex/.rvm/gems/ruby-2.6.2/gems/shopify_app-11.1.0/lib/shopify_app/managers/webhooks_manager.rb:48:in 'create_webhook'`

It seems that the Shopify API is not recognizing the webhook topic names for whatever reason, here specifically, in the `webhooks_manager.rb` file:

```ruby
    def create_webhook(attributes)
      attributes.reverse_merge!(format: 'json')
      webhook = ShopifyAPI::Webhook.create(attributes)
      raise CreationFailed, webhook.errors.full_messages.to_sentence unless webhook.persisted?
      webhook
    end
```

# Environment

Installed gem versions:
`ruby (2.6.2)`
`rails (6.0.0)`
`shopify_app (11.1.0)`
`shopify_api (8.0.0)`
`shoryuken (5.0.1)`

Using Shoryuken/Amazon SQS as my message processor: https://github.com/phstc/shoryuken

### shopify_app.rb
```ruby
ShopifyApp.configure do |config|
  config.application_name = "Test App"
  config.api_key = ENV['SHOPIFY_API_KEY']
  config.secret = ENV['SHOPIFY_API_SECRET']
  config.old_secret = "<old_secret>"
  config.scope = "read_products, write_products, read_themes, write_themes" # Consult this page for more scope options:
                                 # https://help.shopify.com/en/api/getting-started/authentication/oauth/scopes
  config.embedded_app = true
  config.after_authenticate_job = false
  config.api_version = "2019-10"
  config.session_repository = Shop
  config.webhook_jobs_namespace = "shopify/webhooks"
  config.webhooks_manager_queue_name = "ph_webhooks"

  config.webhooks = [
    {topic: 'app_subscriptions/update', address: "#{ENV['APP_URL']}/webhooks/app_subscriptions_update", format: 'json'},
    {topic: 'app/uninstalled', address: "#{ENV['APP_URL']}/webhooks/app_uninstalled", format: 'json'}
  ]
end
```

### shoryuken.yml
```
verbose: false
concurrency: 4
delay: 30
queues:
  - ph_webhooks
  - ph_app_subscriptions_update
  - ph_app_uninstalled
```

Command to run Shoryuken: `bundle exec shoryuken -R -C config/shoryuken.yml`

All queues set up correctly in Amazon SQS, I can see the `ShopifyApp::WebhooksManagerJob` data stuck in there, as it keeps failing.

This is the `ShopifyApp::WebhooksManagerJob` webhook payload stuck in Shoryuken/SQS:

```javascript
{
   "job_class":"ShopifyApp::WebhooksManagerJob",
   "job_id":"0af251c6-0f20-43d1-81bf-c2c382481149",
   "provider_job_id":null,
   "queue_name":"development_ph_webhooks",
   "priority":null,
   "arguments":[
      {
         "shop_domain":"<snip>.myshopify.com",
         "shop_token":"e421<snip>",
         "webhooks":[
            {
               "topic":"app_subscriptions/update",
               "address":"https://<snip>.ngrok.io/webhooks/app_subscriptions_update",
               "format":"json",
               "_aj_symbol_keys":[
                  "topic",
                  "address",
                  "format"
               ]
            },
            {
               "topic":"app/uninstalled",
               "address":"https://<snip>.ngrok.io/webhooks/app_uninstalled",
               "format":"json",
               "_aj_symbol_keys":[
                  "topic",
                  "address",
                  "format"
               ]
            }
         ],
         "_aj_symbol_keys":[
            "shop_domain",
            "shop_token",
            "webhooks"
         ]
      }
   ],
   "executions":0,
   "exception_executions":{

   },
   "locale":"en",
   "timezone":"UTC",
   "enqueued_at":"2019-09-18T20:55:54Z"
}
```

In the Shopify Partners backend, I have the app settings set up to use the `2019-10` Webhook API version.

# Solution attempts

I've tried changing the topic name in the `shopify_app.rb` file from `app_subscriptions/update` to `app_subscription/update` (non-plural) as I thought there could be a typo in the Shopify API documentation and in the Shopify webhooks update announcement blog post. When I tried with `app_subscription/update` (non-plural), I got an error that said the topic wasn't valid. The error also stated that I could subscribe to the `app_subscriptions/update` and `app/uninstalled` topics with the current app scope.

I've tried changing the `api_version` in both the `shopify_app.rb` file and Shopify Partners app settings backend to both be `2019-07` - still the same issue.

I've also tried without having `config.webhooks_manager_queue_name` set to a custom queue name, so it just works on the `default` queue - still the same issue.

I'm at a loss as to why these webhook topics aren't registering correctly. When I try to check with the `ShopifyAPI::Webhook.all` method (inside the shop's scope) it just returns an empty array. Not subscribed to either webhook topic, but can still access the embedded app pages without an issue.

Any assistance with this would be greatly appreciated. Thank you.

### EDIT:

It turns out that these 404s may be coming from my server, as I am seeing these in my `rails s` output:

`ActionController::RoutingError (No route matches [GET] "/webhooks/app_subscriptions_update"):`
`ActionController::RoutingError (No route matches [GET] "/webhooks/app_uninstalled"):`

But I have my `routes.rb` set up just fine:

```ruby
Rails.application.routes.draw do
  mount ShopifyApp::Engine, at: '/'

  root to: 'home#index'
  get '/activate_recurring_charge', to: 'recurring_charge#index'
end
```

Not sure what may be going on here, shouldn't the webhook URLs be set up automatically? My `ENV['APP_URL']` is outputting the correct ngrok URL I am using.

#### Another edit: 

Not 100% sure if the 404s are from my server, but I'm pretty sure it is coming from the Shopify API.

#### Another edit:

The 404 response is definitely coming from the Shopify API. It seems that the `app_subscriptions/update` webhook can only be subscribed to via a GraphQL mutation. 

https://community.shopify.com/c/Shopify-APIs-SDKs/webhook-for-the-topic-quot-appsubscriptions-update-quot-failing/m-p/564987/highlight/true

Is there any way this can be handled through setting it up in `config.webhooks`? I'm assuming for now this will have to be handled manually via our own app code. Quite annoying that this isn't stated in the Shopify API documentation and that it is only available through GraphQL and not REST.

**Comment by mkevinosullivan** [comment]
Hi Alex,

The [REST supported topics](https://shopify.dev/docs/admin-api/rest/reference/events/webhook?api[version]=2020-01#topic-property-2020-01) and [GraphQL supported topics](https://shopify.dev/docs/admin-api/graphql/reference/object/webhooksubscription/webhooksubscriptiontopic?api[version]=2020-01) are listed on [shopify.dev](https://shopify.dev).

Regarding the `app_subscription/update` topic being supported via REST, it is not currently planned.

As for `shopify_api` supporting webhooks via `graphql`, it is on the roadmap, but the exact timeline is unknown.
