### ISSUE TITLE
Rails 6 generator fix

### ISSUE THREAD

**Issue by ryanckulp** [Shopify/shopify_app#794]
i set up a vanilla Rails 6.0.0 app w/ the generator.

just FYI, had to change this line in `embedded_app.html.erb`:
`<%= javascript_include_tag 'application', "data-turbolinks-track" => true %>`

to this:
`<%= javascript_pack_tag 'application', turbolink_track: true %>`

for it to work. 

(_not to mention also running `bundle exec rails webpacker:install` and other usual Rails 6 stuff, for anyone else who sees this._)

**Comment by petebof** [comment]
The full extend of this problem was reported with a workaround at #786
