### ISSUE TITLE
Add Contributors.MD file

### ISSUE THREAD

**Issue by katiedavis** [Shopify/shopify_app#803]

**Comment by andyw8** [comment]
Hi @katiedavis, I'm reviewing some of the older issues here.

Do you think adding a contributors file adds much over the [contributors page](https://github.com/Shopify/shopify_app/graphs/contributors) already provided by GitHub?

**Comment by katiedavis** [comment]
Hi @andyw8! When we wrote up this issue, we were referring to a guide for the developers who wanted to contribute to the app.

**Comment by tanema** [comment]
I will be adding this soon so that I can add our security policy

**Comment by andyw8** [comment]
Ah, I see. I think that's usually named `CONTRIBUTING`, e.g. https://github.com/rails/rails/blob/master/CONTRIBUTING.md
