### ISSUE TITLE
Webhooks not Processing

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#809]
Rails 6
Ruby 2.6.5
Shopify_App 11.2
Shopify API 8.0.0

Basic Rails App built with the generators. Config specifies a webhook. Webhook gets assigned in Shop. Shopify store generates the webhook. Through forwarding, I can see the POST event hits /webhooks/order_create

Thing is, nothing happens. So the payload is sent via Shopify, and hits my local machine, and the App running on the same PORT does not pickup the route and nothing happens. It is like the App is dead. It works fine itself, puma serves it all up, it installs in Shopify, all the networking is cool. But everything to do with responding to webhooks is dead. 

What should I be looking at here? I have yet to experience this kind of problem with the shiny new Rails 6...

**Comment by resistorsoftware** [comment]
Just a note here to clarify some things... when I login to a shop using the Rails App, with a new session, the Webhooks Manager kicks in, and tries to ensure the needed Webhooks exist. In the logs, I see the following results. The redirect is so wrong! It ensures the oAuth handshake and all that results in the user seeing the App outside Shopify, not embedded in an iframe in the store. What is that? Wrong... not sure why this is happening.

[ActiveJob] Enqueued ShopifyApp::WebhooksManagerJob (Job ID: d1ebcd57-91d8-4393-9adf-50ecfd9b7417) to Sidekiq(default) with arguments: {:shop_domain=>"zlow-braun3430.myshopify.com", :shop_token=>"redacted", :webhooks=>[{:topic=>"orders/create", :format=>"json", :address=>"https://glooble-resistorsoftware.fwd.wf/webhooks/order_create"}]}
09:31:07 worker.1  | 2019-10-30T13:31:07.000Z pid=79430 tid=ow6etfjcu class=ShopifyApp::WebhooksManagerJob jid=38f1738664bb3cf24e09d7a7 INFO: start
09:31:07 rails.1   | Redirected to https://glooble.test/?
09:31:07 rails.1   | Completed 302 Found in 2ms (ActiveRecord: 0.0ms | Allocations: 2699)

**Comment by resistorsoftware** [comment]
Webhooks process perfect in production. So the problem is clearly just Rails 6.0.0 in development. 

Lesson learned. Continue using production to develop working code as the development environment has become unstable.

**Comment by tanema** [comment]
Sorry for clarification, are you still having an issue with the config.hosts? If so, I would love to figure this out to update our readme for when rails 6 is ready. Also I have heard `config.hosts = nil` will disable that functionality if it is in your way.

**Comment by resistorsoftware** [comment]
To clarify, nothing worked! 

setting config.hosts = ["myApp.test"] where myApp.test is my localhost App running at a tunnel, works! You have to do that, and so that part of Rails is great!!

But now how do you get the public URL for webhooks in there? Nothing I tried allows a webhook from the public tunnel to work. I get 403 forbidden with config.hosts set to the (dot)test namae only.

If I set config.hosts to nil, allowing everything through, I get webhooks hitting the App and getting rejected. Adding the public tunnel name through a regex, a string or any other method also fails. 

So I give up on Rails that way. I noted this in am issue with Rails. There are only 2 possibilities left to me. 

1) Rails is borked
2) my ForwardHQ tunnel is somehow borked. 

I am not seeing #2 as the webhook payloads are hitting the localhost. So it is the Rails App dying. And I have zero clue as to why that is. Tried everything..

**Comment by resistorsoftware** [comment]
More clarification. I added debug code into ActionDispatch. It is actually approving the request, and marking it good, and passing it on in the chain. 

So there could be something borked in how the Shopify App is working it's magic right now with respect to webhooks and that part of the engine and routes.

**Comment by tanema** [comment]
Okay I will take a deeper look into webhook acceptance tomorrow to see if I can reproduce this.

**Comment by resistorsoftware** [comment]
I am no Rails Wizard, but now I guess the thing to check is, why when the request is passed on through the Rack Middleware chain, does it get rejected... so that I see the request being authorized like 10 times... before that stops... what is the step passed the Host Authentication is my next target...

**Comment by resistorsoftware** [comment]
I log my Middleware stack on an incoming webhook call. So the Webhook is directed to the public URI and internally, should be processed by the localhost App. The Middleware shows a HTTP 307 but nothing happens in terms of the request actually being dealt with?

MiddleWare: entry Webpacker::DevServerProxy
11:01:54 rails.1   | MiddleWare: entry ActionDispatch::HostAuthorization
11:01:54 rails.1   | origin host: shinesty.test forwarded_host shinesty-resistorsoftware.fwd.wf
11:01:54 rails.1   | Authorized the request!
11:01:54 rails.1   | MiddleWare: entry ActionDispatch::SSL
11:01:54 rails.1   | MiddleWare: ActionDispatch::SSL, returning with status 307
11:01:54 rails.1   | MiddleWare: ActionDispatch::HostAuthorization, returning with status 307
11:01:54 rails.1   | MiddleWare: Webpacker::DevServerProxy, returning with status 307

**Comment by resistorsoftware** [comment]
Ok so I figured it out. When I saw the 307 emerge from the SSL module, it clued me in. Why? A silly config in application.rb to force SSL of course. In production, whatever. In development, that causes issues. So I turned that off, and bingo, 307 got replaced with 204, and the webhook routines kicked in no trouble.
