### ISSUE TITLE
Is it just me or is this App wonky?

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#810]
I use Forward instead of ngrok. So shoot me. It worked. 

I have a localhost URL for my App, setup in the Partner App section. Say http://gooble.test which works. I sign-up to my Shopify store, and Shopify pops up, asking if I want to install the App. I say yes. 

What used to happen, was all the oAuth trickery, and boom, and iframe'd App inside Shopify store. 

Now, I get sad Panda. Url is https://gooble.test?hmac blah blah with the shop name etc.. and no nice iframing. 

What? The App is installed. And when I revisit the Admin, it pops up in the iframe now, but this is a pretty lousy experience... what happened to the nice Shopify App? Is this Rails 6 problems? 

Plus now the deprecation notice in the logs about NOT using Shop in the initializer is annoying, as there is no real suggested fix for that? My logs groweth huge from that alone.
 
Rails 6
Shopify App 11.2
Shopify API 8.0

App from generator.

**Comment by tanema** [comment]
Yes it may be because the gem is not fully rails 6 compatible from generation at the moment. You can see the ongoing work here https://github.com/Shopify/shopify_app/pull/808 I am surprised that you did not get any errors when you generated it? Are you still using sprockets?

**Comment by resistorsoftware** [comment]
I am using Webpack. The App itself works, it is just the onboarding to the iframe that seems all butchered, and as well, I am having troubles with the webhooks. For the webhooks, that could be networking, but again, suspicious how all these problems are Rails 6? Also, I quit using Chrome, and use FF, so the iframe issues could be browser inflicted pain. I won't know till I try other browsers I guess. Sucks because I just wanted to whip up an App, and get it done... not piddle around with tons of borked little things!

**Comment by resistorsoftware** [comment]
One clue that kind of bugs me. In development I set the config.hosts to allow my Proxy URL. So in my case https://gooble.test. I forward that to my localhost host port. So that all works. But the Webhooks are sent to the public URL of my Proxy, and that service, like ngrok, sends forth the data. So that data is hitting my localhost. But I suspect Rails 6 is just rejecting it outright, with not errors. Dead. A manual POST to the webhook endpoint hits localhost, but the message returned is 403 forbidden. So WTF is that? I added the public URL to config.hosts too, and it makes no difference. So I am at a loss as to why development is now so hard... something little has changed.

**Comment by tanema** [comment]
I am really surprised that your app works at all if you generated it with webpack. None of the JS is setup to work in rails6 currently and you should have gotten an error with the `javascript_include_tag` I see you also opened https://github.com/Shopify/shopify_app/issues/809
If your controller is returning 403, that means that the request could not  be validated for some reason while checking the hmac. I will have to dig a bit deeper as to why that would be because the only reason I can think of is that you have an incorrect secret but you are able to install so that should not be an issue.

**Comment by resistorsoftware** [comment]
A simple POST to the Rails App endpoint for webhooks returns a slew of fetch 307 redirects... nothing works... there. 

Not sure why you say webpack does not work. I have a few Apps that work fine recently with webpack, Rails 6, and the such, but none of them used Webhooks. So now that I started a new project with the latest generators, and need webhooks, this is when all the bad happened. Not sure what JS you are referring to as not working?

**Comment by resistorsoftware** [comment]
I have Rails 6 running Polaris and not having problems, but with older Shopify App code. Like around version 8... seems new changes are the problem... perhaps it should be use Rails 6 but downgrade to older Shopify App till that gets updated to work.

**Comment by noctivityinc** [comment]
@resistorsoftware im having similar issues.  Clean install, nothing fancy, and I get a ton of redirects and then this message:

```The application can’t be loaded, check that your browser allows third-party cookies```

Im going to downgrade to Rails 5 and try again.

**Comment by resistorsoftware** [comment]
I saw postMessage could not be delivered because https://shop.myshopify.com is not the same as https://myapp.test

So I just manually redirect into the App, and so now I don't have that problem anymore. So it seems the old technique of using postMessage to jump into the App no longer works, but you can simulate what you need. 

As for webhooks... still puzzled about that one.. why the POST to a valid route is not triggering is the stress point... I see the hit, but the App does nothing with it.

**Comment by tanema** [comment]
@resistorsoftware Are you still using rails 6? Because that is a rails 6 error and has nothing to do with shopify app. To accept any requests with that domain, it will need to be in your config.hosts

**Comment by resistorsoftware** [comment]
I agree it is a Rails 6 error. I added my apps to the config.hosts. I even cleared the entire block of them, allowing everything through, supposedly, and even that does not work. ie)

    Rails.application.configure do
      config.hosts.clear
    end

**Comment by noctivityinc** [comment]
@resistorsoftware this isn't just you.  SOMETHING is going on with one of the packages at Shopify - I think its app-bridge.  I've now tried to get this all working in Rails, Node, Next.js and React and anything that has app-bridge in it results in the same redirect / postMessage / third-party cookie situation.

Im trying Rails 5 now but I truly believe there is some kind of an issue with one of the Shopify packages.

**Comment by noctivityinc** [comment]
@resistorsoftware same thing in Rails 5.  Just keeps redirecting.

**Comment by tanema** [comment]
@noctivityinc We have tens of thousands of apps serving millions of requests using App Bridge, if there was an issue with app bridge we would see so many large indications, even our RPM would tank. I can guarantee you that App Bridge is working. Also to note that the shopify_app is using easdk instead of app bridge so that would not be the case here as well.

**Comment by resistorsoftware** [comment]
I have App Bridge working fine in my Rails 6.0.0 App as a simple thing, updating the App Titlebar. Nothing else, but it worked. So I assume App Bridge to be benign and working. Rails 6.0.0 on the other hand, does not seem to want to work properly due to this middleware of host checking.

**Comment by noctivityinc** [comment]
Thanks @tanema.  Can you tell me the name of one of your apps so I can test it in my browser?  Google and facebooks app was doing the same redirect thing so I’m trying to understand if this is a chrome thing or something wonky with my settings.

**Comment by resistorsoftware** [comment]
too much going on... will reduce clutter
