### ISSUE TITLE
Enable Rubocop

### ISSUE THREAD

**Issue by tanema** [Shopify/shopify_app#813]
I think that since policial was dismantled, we have not enabled linting on this repo for a while. We need to get our code up to appropriate standards.

**Comment by adfaris** [comment]
Hi, my name is A.D. I am looking to start contributing to the Shopify ecosystem. It looks like you have en existing rubocop config:  https://github.com/Shopify/shopify_api/blob/master/.rubocop.yml. I will open a PR with this soon. 

cc @katiedavis

**Comment by katiedavis** [comment]
That's great! Thank you so much :)
