### ISSUE TITLE
Why did you add 'dotenv-rails' gem?

### ISSUE THREAD

**Issue by DemidenkoAndrey** [Shopify/shopify_app#818]
I've noticed that you [added](https://github.com/Shopify/shopify_app/commit/8f834508603725744d94594c565995414131210a#diff-6c17e5d5dd7f3aea2ffa6fb82a5de3a8R17) 'dotenv-rails' gem into 'shopify_app.gemspec' file.
Is there any specific reason for it?

**Comment by tylerball** [comment]
We did this because in most of our apps and in the apps generated by this gem we use environment variables or `.env` files to load secrets.

**Comment by slucaskim** [comment]
This was removed in https://github.com/Shopify/shopify_app/pull/835
