### ISSUE TITLE
App Install Fails to Create Webhook

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#819]
Rails 6.0.0 and an install should be good to go on listenening to fulfillments/create webhooks. Order scope is all that is needed according to docs.  Instead this generated a 401 unauthorized, and a list of allowed topics that does not include fulfillments/create. Why?

    ShopifyApp.configure do |config|
      config.application_name = "busted app install"
      config.api_key = ENV.fetch('SHOPIFY_API_KEY')
      config.secret = ENV.fetch('SHOPIFY_SECRET_KEY')
      config.old_secret = ''
      config.scope = 'read_orders'
      config.embedded_app = true
      config.after_authenticate_job = false
      config.api_version = '2019-10'
      config.session_repository = Shop
      webhooks_hostname = ENV.fetch('WEBHOOKS_HOSTNAME')
      raise 'Missing WEBHOOKS_HOSTNAME' unless webhooks_hostname.present?
      config.webhooks = [
         { topic: 'fulfillments/create', format: 'json', address: "https://#{webhooks_hostname}/webhooks/fulfillment_create" }
       ]
    end

    ShopifyApp::WebhooksManager::CreationFailed: Topic Invalid topic specified. Topics allowed:     app/uninstalled, carts/create, carts/update, checkouts/create, checkouts/delete, checkouts/update, checkouts/paid, collections/create, collections/delete, collections/update, customer_groups/create, customer_groups/delete, customer_groups/update, customers/create, customers/delete, customers/disable, customers/enable, customers/update, order_transactions/create, orders/cancelled, orders/create, orders/delete, orders/edited, orders/fulfilled, orders/paid, orders/partially_fulfilled, orders/updated, products/create, products/delete, products/update, refunds/create, shop/update, locations/create, locations/update, locations/delete, tender_transactions/create, app_purchases_one_time/update, app_subscriptions/update

**Comment by martinbottanek** [comment]
Try adding write_orders scope ... if I am not mistaken fulfillments/create creates a new Fullfilment and thus needs a write permission.

**Comment by tanema** [comment]
You may have already figured this out but you at least need the `read_fulfillments` scope to subscribe to that webhook subscription
