### ISSUE TITLE
Creating records on another table that has one-to-many associations with Shop is not possible. How do I go about it?

### ISSUE THREAD

**Issue by AfolabiOlaoluwa** [Shopify/shopify_app#825]
Submitting Issues
-----------------

After installing the app in a Rails 6 app, the shop got authenticated and shop created on ShopTable, so I added `has_many :values` and on ValueTable I added `belongs_to :shop` :

**Shop.rb**
```
class Shop < ActiveRecord::Base
  include ShopifyApp::SessionStorage

  has_many :customer_details
  has_many :values

  def api_version
    ShopifyApp.configuration.api_version
  end
end
```

**Value.rb**
```
class Value < ApplicationRecord
  belongs_to :shop

  validates :name, presence: true
  validates :point, presence: true
end
```

So when I create Value attributes, shop_id column on the doesn't get created. Is there a way I could have current_shop recorded on the associated table? `shop_domain` etc are not available globally in rails app except from the webhook job.

**Comment by dan-gamble** [comment]
Are you saying the `shop_id` column doesn't get generated in the schema or that the value is empty?

If you want to fill the value by default you could do `shop.values.create!` so it will get filled for you automatically?

**Comment by AfolabiOlaoluwa** [comment]
I think the problem being that the current shop domain is not accessible anywhere in the code. I asked the full question [here](https://stackoverflow.com/questions/58950589/rails-one-to-many-assocaition-not-saving-record-on-db/58950774#58950774) and I see that is where the problem is really.

**Comment by tanema** [comment]
current_shopify_domain as available on any controller that you have ShopifyApp::LoginProtection on. It does not have any context outside of a controller either because outside of the request lifecycle, there is no concept of a current shop. 

Since this is a rails issue and not a shopify_app issue I am going to close this
