### ISSUE TITLE
Why do I keep getting this page immediately I install my app with a store? 

### ISSUE THREAD

**Issue by AfolabiOlaoluwa** [Shopify/shopify_app#826]
Why do I keep getting this page immediately I install my app with a store? 

<img width="1677" alt="Screenshot 2019-11-21 at 14 06 39" src="https://user-images.githubusercontent.com/15254043/69340869-b6ba0d80-0c68-11ea-80d5-6484898c2259.png">

**My HomePage Controller**
```
class EarningRulesController < ApplicationController
  include ShopifyApp::Authenticated
end
```

**My Model**
```
# frozen_string_literal: true

class EarningRule < ApplicationRecord
  def set_shop
    self.shop = current_shop
  end

  private

  # I added  `include ShopifyApp::Authenticated` to the controller so that I can have access to shop/current_shop querying.
  def current_shop
    shop ||= ShopifyAPI::Shop.current.domain

    Shop.find_by(shopify_domain: shop)
  end
end
```

Could this problem be because of `include ShopifyApp::Authenticated`

**Comment by tanema** [comment]
Hey @AfolabiOlaoluwa this looks like an issue with your shopify store and not your app.
