### ISSUE TITLE
Is the bootstrap responsive import still necessary?

### ISSUE THREAD

**Issue by ckhatton** [Shopify/shopify_app#83]
Is this file required anymore?
https://github.com/Shopify/shopify_app/blob/master/lib/generators/shopify_app/templates/app/assets/stylesheets/imports.css.less

The file relates to this issue...
https://github.com/metaskills/less-rails-bootstrap/issues/26

I assume this issue is no longer apparent as the newest bootstrap includes responsive anyway.

The line even comes up in my IDE with an error, as file missing.

**Comment by kevinhughes27** [comment]
latest version doesn't include bootstrap anymore. closing.
