### ISSUE TITLE
External JS script

### ISSUE THREAD

**Issue by janklimo** [Shopify/shopify_app#832]
The generator adds the following script to the layout file:

```html
<script src="https://cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>
```

A few questions about this way of including it:
1. What does it do? Definitely worth documenting.
1. Can it be included with the gem so it can be bundled with JS pack, thus removing a network call?

**Comment by tanema** [comment]
This is no longer part of the app, but there is a link to AppBridge. That is available for usage with webpacker ect
