### ISSUE TITLE
Oauth error invalid_request: Could not find Shopify API application with api_key

### ISSUE THREAD

**Issue by mrbme** [Shopify/shopify_app#833]
Here's my gem file.

The app is not grabbing my API key when redirecting when in production in Heroku,

```
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.5'

gem 'rails', '~> 6.0.1'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 4.1'
gem 'sass-rails', '>= 6'
gem 'webpacker', '~> 4.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'
gem 'bootsnap', '>= 1.4.2', require: false
#########################
gem 'sprockets', '~> 3.0'
gem 'simple_form'
gem 'pg_search'
gem 'httparty'
gem 'will_paginate'
gem 'figaro'
gem 'shopify_app', '~> 11.3', '>= 11.3.2'
gem 'faraday'


group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'pry-rails'
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test do
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  gem 'webdrivers'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'dotenv-rails', group: [:test, :development]
```

**Comment by tylerball** [comment]
@mrbme if you have the [heroku CLI](https://devcenter.heroku.com/articles/heroku-cli) installed you can run `heroku config` to verify that you have the right credentials on your app and that they match what's in the Shopify Partners Dashboard. My hunch is they may not be set correctly.

**Comment by svaustin66** [comment]
I'm having the same issue - https://gyazo.com/21c0caedbbc440295274b2370e9ed9fe

This is a totally new install of a dev environment, so the latest versions of apps.  I was getting another error and read that the fix was to use an older version of sprockets so I made this change to Gemfile -> gem 'sprockets', '~> 3.0'.

To register the Shopify API key and secret, I used 'rails generate shopify_app --api_key 218dadfd4a343ad5893ef20bf0d17d18 --secret XXXXXXXXXXXXXXXXXXXXXXXX' at the command line.  But still getting this error.  

I can't find a file in my app where this information is/should stored to verify the entries.  So a pointer there would be great.  

Running heroku config gives me this - https://gyazo.com/58de13443e901965edea9a97e8fde68e - which I'm not sure what it is telling me.

So any suggestions appreciated.

**Comment by svaustin66** [comment]
A little more information.  Something about my setup is not adding the API Key to the URL.  When trying to install the app, I'm getting sent to https://product-configurator-metafields.myshopify.com/admin/oauth/authorize?client_id&redirect_uri=https%3A%2F%2Fconfigurator-metafields.herokuapp.com%2Fauth%2Fshopify%2Fcallback&response_type=code&scope=read_products&state=5a8e81d0b3ccc9a57c74ca39309b44dc9af0e317b36db902 - which has no value for client_id.

For now, I just added the api-key as the client id in the URL and that got me to the next step.

**Comment by mrbme** [comment]
Hey @svaustin66 is this working for you locally? If you're pushing this to production on Heroku, you'll need to add the api secret and public api to the heroku config vars and that might fix the problem.

**Comment by svaustin66** [comment]
@mrbme  

I'm not working locally just through Heroku.  I'm using these instructions - https://github.com/Shopify/shopify_app/blob/master/docs/Quickstart.md (as I'm new to all of this).  I thought this step
`$ rails generate shopify_app --api_key <shopify_api_key> --secret <shopify_api_secret> `
would insert the api keys in heroku.

**Comment by mrbme** [comment]
Well in `config/initializers/shopify.rb` you'll see something like
```
 config.api_key = ENV['SHOPIFY_API_KEY']
  config.secret = ENV['SHOPIFY_API_SECRET']
```

You'll need to get the gem `figaro` and run the exec to create an `application.yml` file in your config folder, from there you'll write something like 
```
SHOPIFY_API_KEY: 123456789
SHOPIFY_API_SECRET: 123456789
 ```

**Comment by svaustin66** [comment]
Makes sense!  I'm going to try that out.

**Comment by svaustin66** [comment]
Hmm.  Did the figaro gem (pretty easy).  And still getting the same error. 

When I go to the app - https://configurator-metafields.herokuapp.com/login - and enter a .myshopify store domain.

It redirects to the .myshopify store with this URL - https://product-configurator-metafields-2.myshopify.com/admin/oauth/authorize?client_id&redirect_uri=https%3A%2F%2Fconfigurator-metafields.herokuapp.com%2Fauth%2Fshopify%2Fcallback&response_type=code&scope=read_products&state=ae8e972500bc6cac4a27ae96eeb37537e46bbfaec9062c79 

This URL still does not have a value for 'client_id'.  Is one required?  How do I add that in the app code?

**Comment by mrbme** [comment]
In heroku, got to settings > reveal config vars.

There, you should see something like this:

![image](https://user-images.githubusercontent.com/10884625/70811676-b30f3780-1d8b-11ea-9371-9b942c6dba6a.png)
If you dont, then you'll need to add your API keys.

**Comment by svaustin66** [comment]
Thanks!  That worked.  I went into Heroku settings and manually added API Key and Secret.  Not sure why it wasn't added by the other steps.  But its working!

**Comment by sammitrovic** [comment]
Thanks @mrbme. This worked for me too!

**Comment by tanema** [comment]
This seems resolved so I am going to close it
