### ISSUE TITLE
Safari 13.0.4 + shopify_app + Devise: devise authentication lost in shopify_app controllers

### ISSUE THREAD

**Issue by lastobelus** [Shopify/shopify_app#836]
I maintain an app used privately by a shopify plus customer. Since we have a lot of staff, and some parts of the app are accessed in a non-embedded context, and not all users of the app have shopify accounts, and `shopify_app` is not set up to do _user_ authentication, we use Devise authentication in addition to shopify authentication, and link our devise users to corresponding shopify users when they exist.

After installing this week's Safari upgrade (=> 13.0.4), devise login no longer works in an embedded context (seems the CSRF token is getting reset) AND after logging in in a non-embeddded context, the devise authentication is not working in subsequent embedded pages.

The session is not discarded altogether -- if I go back to a non-embedded page I'm still logged in.

Everything still works correctly in Chrome.

Rails 5.2.4
shopify_app 11.4.0

**Comment by lastobelus** [comment]
Note: we are not using omniauth with Devise, just username/password login.

**Comment by tanema** [comment]
Hi @lastobelus, sorry about the inconvenience but I am not sure there is much we can do about this issue. However we are working on adding [per-user authentication](https://github.com/Shopify/shopify_app/pull/760) and hopefully this will allow you to be able to migrate your app to that method of authentication soon.

**Comment by tanema** [comment]
@lastobelus I think this may be the same issue as https://github.com/Shopify/shopify_app/issues/845 since there is more discussion there so I think I will close this in favour of that issue.
