### ISSUE TITLE
Reauthenticate required for each new session?

### ISSUE THREAD

**Issue by axlekb** [Shopify/shopify_app#839]
Hi folks,

There are a number of apps that appear to not require re-authentication for a shop that has _already_ authenticated _but_ is trying to access the app on a new session (for example, after installing on Machine A, clicking into the app from the App List on Machine B).  I'd like to emulate this behavior.

However, it appears that `ShopifyApp::Authentication` uses `around_action :shopify_session` which will redirect to the `login_path` unless `session[:shopify]` is present.  However it also appears the only way `session[:shopify]` is set is through authentication.  

Am I missing something?  Is there any way to easily get that behavior using this ShopifyApp gem? 

Thank you!

**Comment by tanema** [comment]
Session is coming from authentication yes but it depends how you persist your session. If you are using a cookie store, then the session will persist for a while and you will not need to reauthenticate everytime

**Comment by axlekb** [comment]
Figured it out.  My problem was due to a redirected route not passing along the necessary params. 

Thanks for your help!
