### ISSUE TITLE
ActiveRecord required?

### ISSUE THREAD

**Issue by netwire88** [Shopify/shopify_app#840]
Is `ActiveRecord` required as part of this Gem? I'm using Mongoid but wasn't sure if it plays nice with ActiveRecord.

I see that `class Shop < ActiveRecord::Base` uses ActiveRecord but is the class required?
Also, what goes into the `database.yml` if I don't use postgres or sqlite for anything?

**Comment by tanema** [comment]
ActiveRecord is strongly advised for use, however I am sure you could alter the generated code to make it work for yourself. This would be unsupported and I can't really help you with how to do that but I am sure it is possible.

**Comment by marschattha** [comment]
Resolved?
I have set it up with Mongoid in one of my apps, so it is possible.
I remember making some changes to default configuration to make it work but I have forgotten how.

**Comment by tanema** [comment]
Yeah I think this should be closed as this is not an issue with the library
