### ISSUE TITLE
Rails 6 blocks App Proxy requests

### ISSUE THREAD

**Issue by wnm** [Shopify/shopify_app#846]
With Rails 6, and using App Proxies, I get the following error:

> Blocked host: new-development-store.myshopify.com
> 
> To allow requests to new-development-store.myshopify.com, add the following to your environment configuration:
> 
> config.hosts << "new-development-store.myshopify.com"
> 

[Its a new feauture in Rails: ](https://www.fngtps.com/2019/rails6-blocked-host/)

> Host Authorization, new middleware included in Rails to prevent against DNS rebinding attacks

We can disable the feature with
```
Rails.application.configure do
  config.hosts.clear
end
```
but then the new security feauture is lost?

Is there a way to allow all request from Shopify? Are requests made from myshopify.com-domains (e.g. nike.myshopify.com), or from individual domains (e.g. nike.com)?

**Comment by talecK** [comment]
I believe you should be getting requests from *.myshopify.com rather than *.com in this case (but you would have to confirm this for your own situation).

You could set config.hosts = ".myshopify.com" to allow requests from *.myshopify.com.  You can also give config.hosts a regex or even a Proc {} if you want to get really fancy and only whitelist a list of Shop's from your database.

I'm pretty sure this value is blank in production on rails 6 by default so you might only need to set it in development.rb but I haven't confirmed this myself so double check.

**Comment by resistorsoftware** [comment]
If you are developing an App with Rails 6, you will wanting to do two things. 

1. Setup a tunnel using forwardHQ or ngrok so you can test App Proxy and Webhooks etc.
2. In config developement.rb set your host as per your tunnel. 

     config.hosts = ['fizzbuzz-marblehead.test']

That works. 100%. Tried, tested, and put that through the ringer. Did have trouble with error messages from webpack server but those issues never affected development. 

And in production, none of this matters.

**Comment by tanema** [comment]
Just to reiterate what @talecK has said you can add the following to your config to allow all myshopify domains

```
config.hosts << /\h+.myshopify.com/
```

But also as he said this is only a worry in development.

**Comment by isaacbowen** [comment]
I belieeeeve that allowing myshopify.com subdomains literally only covers myshopify.com subdomains. In my tests, the x-forwarded-host header from Shopify's proxy always reflects whatever host is responding to the original request, whether that's a myshopify.com subdomain or another storefront domain.

Unless I've missed something, this means that there isn't a straightforward way to use Rails host authorization with app proxies (unless literally all of your merchants are still using their myshopify.com subdomains as their primary domain).

**Comment by isaacbowen** [comment]
For posterity, am currently solving this like so:

```rb
# in config/application.rb or therabouts
config.host_authorization = {

  # if it came via the shopify app proxy, it's fine
  exclude: -> (request) {
    # we only care about things that arrive via the app proxy, so bail
    # early unless that's what clearly we're looking at
    unless request.path.starts_with?('/the_local_route_prefix_our_app_looks_for/')
      next false
    end

    query_hash = Rack::Utils.parse_query(request.env['QUERY_STRING'])
    signature = query_hash.delete('signature')

    # unsigned requests don't count; bail early if we're missing a signature
    unless signature
      next false
    end

    sorted_params = query_hash.collect { |k, v| "#{k}=#{Array(v).join(',')}" }.sort.join

    calculated_signature = OpenSSL::HMAC.hexdigest(
      OpenSSL::Digest.new('sha256'),
      ShopifyApp.configuration.secret,
      sorted_params
    )

    ActiveSupport::SecurityUtils.secure_compare(
      calculated_signature,
      signature
    )
  },

  # this is our 403 response, when host verification fails. we do this to standardize the
  # response, which has the side-effect of making this much nicer for dev and test environments :)
  response_app: -> (env) {
    request = ActionDispatch::Request.new(env)

    body = '403 Forbidden'

    [403, {
      "Content-Type" => "text/plain; charset=#{ActionDispatch::Response.default_charset}",
      "Content-Length" => body.bytesize.to_s,
    }, [body]]
  }

}
```
