### ISSUE TITLE
Investigate / update install instructions to include adding app from partner dashboard.

### ISSUE THREAD

**Issue by tiffanytse** [Shopify/shopify_app#850]
Instructions for adding the app to the store from the partners dashboard, install link doesn't work if this is not done first.

cc: @ShayneP @stevehaase

**Comment by stevehaase** [comment]
When following the tutorial, the final step is to open the URL and enter the myshopify domain to add the app. That process results in a 400 - Oauth error invalid_request page with the message 

> Oauth error invalid_request: Could not find Shopify API application with api_key

This happens whether installing the app via an install link created in the partner dash, or through the login screen from the app's UI.

**Comment by Jipsica** [comment]
@stevehaase A few questions about the app and how you installed it:

> enter the myshopify domain to add the app. 

Was this a custom app, or public app? In either case, did you try to install on your dev shop using the UI or with a url pasted into the browser?

If you tried to paste the url into your browser in either case, you'll see `Oauth error invalid_link: This app can't be installed using this link. Contact the app developer for more information.`

Also, we're not quite sure how you saw the error: `Oauth error invalid_request: Could not find Shopify API application with api_key`. Can you tell us the steps you took to get this error?

**Comment by oehlschl** [comment]
Sorry if this is unrelated, but this issue is the one place I've ever seen the error message we just received, which was the `Oauth error invalid_link` error while working with a partner to install our custom app.

> Was this a custom app, or public app.... If you tried to paste the url into your browser in either case, you'll see Oauth error invalid_link....

Does this mean that custom apps can no longer be installed with OAuth links as described here? https://help.shopify.com/en/api/getting-started/authentication/custom-authentication#create-a-custom-app-and-generate-an-installation-link

Again, sorry if this is unrelated; just trying to get more information on the error we're experiencing.

**Comment by jessipa** [comment]
@oehlschl The help guide you linked is the most up to date way on how custom apps can be installed on stores. 

Note that you must use the link provided when you hit `Generate link`. If you try to install using a link constructed following Step 2 [here](https://help.shopify.com/en/api/getting-started/authentication/oauth#step-2-ask-for-permission), installation will not work.

**Comment by oehlschl** [comment]
Thanks for the prompt response @jessipa! I'll double check our installation steps now.

**Comment by oehlschl** [comment]
Just for completeness, I did confirm that we went through the prescribed "Generate Link" flow but still received the invalid_link error above.

I understand that at some point we'll just need to reach out to Shopify support.

Anyway, thanks again for your answer!

**Comment by MicrexIT** [comment]
Hello everybody,

I am not a Shopify expert but I am also unable to test my public app on any testing store.
I just cannot find any working solution online. I literally followed step by step the official tutorial... what am I supposed to do?

**Comment by andresespinosapc** [comment]
I'm also having this issue, but only with some stores. Did you solve it @oehlschl ? Or how can I contact Shopify support for developers?

**Comment by meandillar** [comment]
@gamahugh @krisgholson I've had the same problem a couple of times and I narrowed it down to the fact that Shopify occasionally generates malformed redirect parameter in their installation urls, therefore i think it generates an incorrect access_change_uuid param and produces the error.

In my case here was the solution - I'm part of a Shopify Plus organisation so I can install custom apps on multiple stores within the Plus organisation. When I paste the install link into the browser I'm prompted to select the store I want to install the app on. At this point I copy the `redirect` param from the current url (the text after `redirect=`) and run it through a url decoder. The outcome should be a relative url starting with `/oauth/install_custom_app`. I then go to the store that I want to install the app on and paste that relative url after `https://your-store-name.myshopify.com/admin` (replacing your-store-name with your actual store) and it works.

This is definitely a bug.

Hope it helps. Good luck!

**Comment by molotow11** [comment]
> @gamahugh @krisgholson I've had the same problem a couple of times and I narrowed it down to the fact that Shopify occasionally generates malformed redirect parameter in their installation urls, therefore i think it generates an incorrect access_change_uuid param and produces the error.
> 
> In my case here was the solution - I'm part of a Shopify Plus organisation so I can install custom apps on multiple stores within the Plus organisation. When I paste the install link into the browser I'm prompted to select the store I want to install the app on. At this point I copy the `redirect` param from the current url (the text after `redirect=`) and run it through a url decoder. The outcome should be a relative url starting with `/oauth/install_custom_app`. I then go to the store that I want to install the app on and paste that relative url after `https://your-store-name.myshopify.com/admin` (replacing your-store-name with your actual store) and it works.
> 
> This is definitely a bug.
> 
> Hope it helps. Good luck!

Worked for me
