### ISSUE TITLE
HMAC Oauth error during callback

### ISSUE THREAD

**Issue by mwalkowiak** [Shopify/shopify_app#852]
Shopify app version: `8.4.0`
Rails `4.2`

![image](https://user-images.githubusercontent.com/2458327/72214558-37a7bf80-34ca-11ea-8407-7d72ddeb5a92.png)

**Comment by tanema** [comment]
Hey @mwalkowiak This means your secret_key_base is not set in your application so.

**Comment by mwalkowiak** [comment]
@tanema you're golden 🏅

**Comment by tanema** [comment]
@mwalkowiak You are up and running again then?

**Comment by mwalkowiak** [comment]
> @mwalkowiak You are up and running again then?

Yes, I am :)
