### ISSUE TITLE
Issue when installing applications - GET [SITE].myshopify.com/admin/oauth/grant

### ISSUE THREAD

**Issue by flavio-b** [Shopify/shopify_app#864]
I have a couple of apps running `Rails 5.2.4.1`. Today I updated both from `shopify_app 11.4.0` to `11.7.0`. 
Testing, I started noticing an issue when installing these apps. Steps to reproduce:

1) Clear browser cache.
2) Login into Shopify admin, proceed to AppStore, click to install the app.
3) In the screen where you confirm the app's permission, after you click the button to authorize, Shopify redirects to GET [SITE].myshopify.com/admin/oauth/grant, which is Not Found.

I've recorded the network calls for this sequence of events. It looks like the issue is an incorrect response from Shopify's servers from the first POST, but it seems like a coincidence since I installed 11.7.0, so wanted to check here.

This issue is quite difficult to reproduce. I've had 8 successful attempts (steps 1 -3), followed by 1 where the error occurs.

<img width="1123" alt="Screen Shot 2020-01-19 at 8 12 45 PM" src="https://user-images.githubusercontent.com/25246024/72699140-1bc0a100-3afc-11ea-81cd-21b6301b9b68.png">

**Edit: Just tested with the old version, `11.3.4`, and noticed the error again, so I think it's just a glitch on Shopify. It took about 10 tries (install/uninstall) to get the error.**

**Comment by flavio-b** [comment]
These are the "correct" event after a user clicks to accept the app's permission:

<img width="1127" alt="Screen Shot 2020-01-19 at 8 45 02 PM" src="https://user-images.githubusercontent.com/25246024/72699374-eb2d3700-3afc-11ea-981c-5f81df56bd83.png">

**Comment by tanema** [comment]
`/admin/oauth/authorize` is our oauth endpoint initialization. If it did not work, none of our apps would work. Are you sure you are using the correct domain? Is this a custom app or a public app? 

Since this seems like an issue with installing through the app store I suggest you reach out to support

**Comment by flavio-b** [comment]
@tanema, thanks for the quick reply! Both of the apps that I've tested are public and have been published for about 2 years. I've made no changes to domains or the auth flow. Just updated to `v.11.7.0` (now noticed it also occurs on my pre-update `v11.3.4`).

Like I mentioned, the error is quite difficult to reproduce (most of the time everything works), but I ran into it by chance 3 times. Then it took about 10 tries of clearing out sessions -> Install fresh -> Uninstall to make it show up again. So it could be a fluke or a bug.

I've logged all headers on the the requests when the issue occurred. I'm sending it to Shopify Support to look into.

**Comment by tanema** [comment]
I suggest that you reach out to support then. You are right, this sounds like a glitch of communication between app store and shopify admin

**Comment by airhorns** [comment]
FWIW I got this error once as well but also struggled to reproduce it. Definitely something amiss.

**Comment by flavio-b** [comment]
@airhorns, thanks for adding this. I've raised the issue with Shopify Support last week, and a person in the technical team is already investigating. I don't have an ETA, but will post the findings here before closing the issue.

**Comment by flavio-b** [comment]
Update: Shopify Technical Merchant Support could not find anything wrong on their end with regards to these requests. 

They've advised to post on the [API forum](https://community.shopify.com/c/Shopify-APIs-SDKs/bd-p/shopify-apis-and-technology), with more details and request Id, if we run into the issue again.

**Comment by jonathanrhodes** [comment]
FWIW, we hit this once as well. I didn't clear the browser cache, just uninstalled the app on one of our development shops and tried re-installing it. After the "authorize" screen (I think), I hit this:

<img width="1680" alt="Screen_Shot_2020-03-09_at_5_50_48_PM" src="https://user-images.githubusercontent.com/23245153/76271089-940e2d80-6234-11ea-98e5-de50411b0b45.png">

Unfortunately, I was not recording our network events at the time, and haven't been able to reproduce it since, though I've tried about a dozen times.

**Comment by flavio-b** [comment]
Yeah, it's seem like an intermittent issue. Looking your address bar, I think it's the same sequence of events, that lead to a GET to .../grant.

**Comment by jonathanrhodes** [comment]
Yeah, strange, I don't know where the GET to .../grant came from. All of my subsequent tests only ever saw POST to .../grant (with a 302 response). Weird.
