### ISSUE TITLE
Just another borked install. 

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#865]
shopify app: 11.5
shopify_api: 8.1
rails 6.0.2

Completely messed up. Went for an install and got this crap:

None of the “sha256” hashes in the integrity attribute match the content of the subresource. login

​This gem is quickly sinking into unusable.

It does work with LOCALHOST fine. OK. It is a Custom App. I used the generated install link to get to this dismal dark place with a cloud based version of the App.

**Comment by tanema** [comment]
> None of the “sha256” hashes in the integrity attribute match the content of the subresource. login

Can you please include the steps that you took to get you to this error, or even where this error is coming from. Any more information would help greatly.

> ​This gem is quickly sinking into unusable.

Please refrain from posting these sorts of opinions on this repo, it creates a hostile work environment leaving my coworkers burnt out. If you cannot refrain from these sort of postings, your contribution to this community can be limited.

**Comment by tanema** [comment]
> It does work with LOCALHOST fine. OK. It is a Custom App. I used the generated install link to get to this dismal dark place with a cloud-based version of the App.

So Is this error coming from installation? Are you receiving errors because of our new public/custom app features?

**Comment by resistorsoftware** [comment]
It is coming from FF latest. I am using the latest gem now. 11.7. I generate an install link, and click that link. The error is coming from the console. So the login page in the App renders, but everything comes to a screeching halt in the browser with a blank screen, and this SHA problem. Nothing else to go on.

**Comment by resistorsoftware** [comment]
> > None of the “sha256” hashes in the integrity attribute match the content of the subresource. login
> 
> Can you please include the steps that you took to get you to this error, or even where this error is coming from. Any more information would help greatly.
> 
> > ​This gem is quickly sinking into unusable.
> 
> Please refrain from posting these sorts of opinions on this repo, it creates a hostile work environment leaving my coworkers burnt out. If you cannot refrain from these sort of postings, your contribution to this community can be limited.

Thanks for the hot tip. This is not directed at any individual, but the corporation known as Shopify, the multi-billion dollar babe of the universe. She is nothing but legal papers filed somewhere. As for the people that work there, they are great. 

One has to understand that there are expectations we suffer from, that stem from dependence on this relationship working. A little give and take. Sorry for the tough love. Sometimes the timing is most awkward, as we have clients ticked off at us, and we have mortgages to pay with their happiness, and if they are not happy, due to this gem, well, that is the cause of it... mostly.

**Comment by resistorsoftware** [comment]
Here is the log of what happens server-side. Wish it was more informative.

    method=GET path="/login?shop=cholula.myshopify.com" host=cholula.herokuapp.com     request_id=d1a195c2-2bd1-4441-bb81-9c4b89081abe fwd="67.70.27.178" dyno=web.1 connect=1ms service=8ms status=304 bytes=1483 protocol=https
    Started GET "/login?shop=cholula.myshopify.com" for 67.70.27.178 at 2020-01-20 16:39:02 +0000
    Processing by ShopifyApp::SessionsController#new as HTML
      Parameters: {"shop"=>"cholula.myshopify.com"}
      Rendering vendor/bundle/ruby/2.6.0/gems/shopify_app-11.7.0/app/views/shopify_app/sessions/request_storage_access.html.erb
      Rendered vendor/bundle/ruby/2.6.0/gems/shopify_app-11.7.0/app/views/shopify_app/partials/_layout_styles.html.erb (Duration: 0.1ms | Allocations: 6)
      Rendered vendor/bundle/ruby/2.6.0/gems/shopify_app-11.7.0/app/views/shopify_app/partials/_typography_styles.html.erb (Duration: 0.0ms | Allocations: 5)
      Rendered vendor/bundle/ruby/2.6.0/gems/shopify_app-11.7.0/app/views/shopify_app/partials/_card_styles.html.erb (Duration: 0.0ms | Allocations: 5)
      Rendered vendor/bundle/ruby/2.6.0/gems/shopify_app-11.7.0/app/views/shopify_app/partials/_button_styles.html.erb (Duration: 0.0ms | Allocations: 5)
      Rendered vendor/bundle/ruby/2.6.0/gems/shopify_app-11.7.0/app/views/shopify_app/sessions/request_storage_access.html.erb (Duration: 1.5ms | Allocations: 548)
Completed 200 OK in 3ms (Views: 2.0ms | Allocations: 1408)

**Comment by resistorsoftware** [comment]
As a note Safari 13.0.4 shows this as the source of frustration:

Cannot load script https://bella-grace.herokuapp.com/assets/shopify_app/request_storage_access-5a556c57b51c57f00d9d6a2ba007f3172739bab34cc2f647a93e792348e8798d.js. 

Failed integrity metadata check.

**Comment by resistorsoftware** [comment]
Thanks for the hot tip. Got me to the next level of "issues". I appreciate the pointer here!
