### ISSUE TITLE
Error: CSRF detected

### ISSUE THREAD

**Issue by Shine18** [Shopify/shopify_app#870]
I am redirecting the user to install the app directly if they have removed the app from store and accessing any page directly 
with this code

[http://prntscr.com/qqxqs7](http://prntscr.com/qqxqs7)

but omniauth throws error about csrf vulnerability. 
[http://prntscr.com/qqxrcy](http://prntscr.com/qqxrcy)

Any help/hint would be appreciated.

**Comment by BoomDig** [comment]
We, too, started to see the same error in our logs when we upgraded our Rails 5 app from shopify_app 11.3.2 to 11.7.0 (in a test environment with a private app) and installed the app in a shop. A relevant snippet from our logs:

INFO -- omniauth: (shopify) Setup endpoint detected, running now.
INFO -- omniauth: (shopify) Callback phase initiated.
ERROR -- omniauth: (shopify) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected

And like some others reported recently when upgrading to version 11.6 or 11.7 of this gem, the error you get when installing an app comes and goes and is not repeatable. Hoping Shopify can investigate this and offer a solution before Feb 4!

**Comment by Shine18** [comment]
Yes, the issue is critical. I'm developing a client's app, and timeline is delayed because of the issue.

**Comment by tanema** [comment]
I will try to look at this today.

**Comment by tanema** [comment]
Can you please give me steps to reproduce? Is it the same issue as https://github.com/Shopify/shopify_app/issues/861 ?

**Comment by BoomDig** [comment]
Our app (created initially with the shopify_app generator) is on Rails 5.2 using Ruby 2.6.5. When we put the app on a test server and add it as a private app to a test shop we get the csrf_detected error after seeing Shopify's permission screen and clicking on the button to allow installation. The app does get installed, though, despite the error. We've applied the work-around described in the discussion to issue 589: https://github.com/Shopify/shopify_app/issues/589 (see vfonic's "acceptable solution"), which appears to be working. But we didn't run into this issue before upgrading from shopify_app 11.3.2 to 11.7.0.

**Comment by tanema** [comment]
Thanks for pointing me to the issue, that really helps with historic issues. I will see what I can do.

**Comment by overallduka** [comment]
@Shine18 Maybe the error is related to existent cookies, because I had had the same, but it goes away when I clear my cookie, maybe you should try.

The bad news is that when this error go away I continue with the same error I reported here: https://github.com/Shopify/shopify_app/issues/860

**Comment by tanema** [comment]
The issue seems to only happen when the user is already logged in, which is why it would work again once the cookies are removed. It seems like it is also a fluke where sometimes there are multiple redirects and in one of the redirects the `state` param is removed. This seems present in other apps for facebook and google. I am trying to find out if anyone has any non-hack mitigations

**Comment by sshaw** [comment]
What happens when you remove the `SameSiteCookieMiddleware`?

**Comment by tanema** [comment]
We are starting to figure out some of the rough edges of the middleware. https://github.com/Shopify/shopify_app/pull/898 I also discovered that I would get csrf errors when not running a tunnel. I would sometimes just start the app without a tunnel to just quickly debug something but it seems like we need the tunnel for the whole process

**Comment by asecondwill** [comment]
Is there any update on this? I'm getting this error trying to update the scopes.  

```
def check_permissions
    unless ShopifyAPI::AccessScope.all.map(&:handle) == ShopifyApp.configuration.scope
      url = "https://#{@shop.shopify_domain}/admin/oauth/authorize"
      request_params = []
      request_params << "client_id=#{ENV.fetch('SHOPIFY_API_KEY')}"
      request_params << "scope=#{ShopifyApp.configuration.scope}"
      request_params << "redirect_uri=https://#{host}/shopify/auth/shopify/callback"
      # request_params << "state=#{@shop.scope_nonce}"
      fullpage_redirect_to "#{url}?#{request_params.join('&')}"
    end
end
```

**Comment by asecondwill** [comment]
And now I'm getting it just trying to install an app to a development store.

**Comment by asecondwill** [comment]
any update on this?
