### ISSUE TITLE
ActionController::RoutingError (No route matches [GET] "/javascripts/shopify_app/request_storage_access.js")

### ISSUE THREAD

**Issue by pmokariya** [Shopify/shopify_app#878]
I am using Shopify_app gem with application. I have updated my **shopify_app gem version 8.2.0 to 11.7.1**

After doing gem updates I started getting the following error for the `request_storage_access` file in production

```
rails s -e production

ActionController::RoutingError (No route matches [GET] "/javascripts/shopify_app/request_storage_access.js"):
```
I run command for ` rake assets:precomplie` but still facing the same error after run this command too.

Environment info:

Browser: Chrome Version 78.0.3904.108 (Official Build) (64-bit)
Ruby: 2.5.7
Rails: '~> 5.2.0'
Shopify App: 11.7.1

**Comment by tanema** [comment]
Are you getting this in development or production?  
If it is development
- you should not have to precompile. 
- are you using sprockets or webpack
if it is production
- are you serving static assets
- have you set your assets host

**Comment by acoustic86** [comment]
Same error here. Only in production. Sprockets 3.7.2.
