### ISSUE TITLE
RSpec controller tests fail with v11 of the shopify app

### ISSUE THREAD

**Issue by Jay-Plumb** [Shopify/shopify_app#879]
Hey team,

Until v10 of the shopify app, it was possible to stub out the sessions controller within our RSpec tests such as:

```ruby
# spec/support/controller_session.rb

module ControllerSession
  def shopify_controller_session(shop)
    @request.session[:shopify] = shop.id
    @request.session[:shopify_domain] = shop.shopify_domain
  end
end
```

From there, we could define a before action within our controller tests which would prevent our test from redirecting due to not having an activated session:

```ruby
 # within any controller_spec.rb file
  before do
    @shop = create(:installed_shop)
    shopify_controller_session(@shop)
  end
```

However, since v11 of the shopify app gem, I found the above no longer worked and after looking at how `/lib/shopify_app/controller_concerns/login_protection.rb` operated, I fixed the test suite by doing the following:

```ruby
# spec/support/controller_session.rb

module ControllerSession
  def shopify_controller_session(shop)
    stubbed_session = ShopifyAPI::Session.new(domain: shop.shopify_domain, token: shop.shopify_token, api_version: shop.api_version)
    allow(ShopifyApp::SessionRepository).to receive(:retrieve).and_return(stubbed_session)
    @request.session[:shopify] = shop.id
    @request.session[:shopify_domain] = shop.shopify_domain
  end
end
```

All I am doing is stubbing out the retrieve call to ShopifyApp::SessionRepository and returning a stubbed version and allows the session to be activated.

Now, the reason why I wanted to open an issue is to help share my solution with others. I have had comments in the past with how to still test controllers when inheriting from `ShopifyApp::AuthenticatedController`. I think it could be really useful to have the above added to the README.md to help others that use RSpec for their testsuite. I am more than happy to make the change but I will wait for feedback from the team first. Equally, if anyone has a better solution to the above then do share and we can take it from there!

**Comment by tiffanytse** [comment]
Thanks @Jay-Plumb this is a duplicate; please follow along here: https://github.com/Shopify/shopify_app/issues/874

**Comment by tanema** [comment]
@Jay-Plumb Thank you for sharing your workaround. It does seem like this is not a duplicate (As I told tiffany it might be, it was my fault she closed it! Sorry) I just want to clarify. Your tests stubbing changed to add versioning? Is that what change? Or do you know exactly why you need to change it this way?

I think I will reopen this because it would be a good idea to add test helpers for this gem to make it easier for people to test their code. This way these sort of issues need to be opened

**Comment by Jay-Plumb** [comment]
Hey @tanema, I attempted the solution within [#874](https://github.com/Shopify/shopify_app/issues/874) but I can confirm that the approach did not work for me. I believe the reason for the change was in relation to switching from:

```ruby
# config/initializers/shopify_app.rb
ShopifyApp.configure do |config|
  ...
  config.session_repository = Shop
end
```

to: 

```ruby
# config/initializers/shopify_app.rb
ShopifyApp.configure do |config|
  ...
  config.session_repository = 'ShopifyApp::InMemorySessionStore'
end
```
but I am not 100% sure if that is the cause. However, I can definitely confirm that on v10 the old approach worked but I hit into issues from `v11.4.0` onwards.

**Comment by mattkc7** [comment]
I'm stuck on this, however the proposed workaround isn't working for me :(

**Comment by ristooi** [comment]
I also encountered this issue with `shopify_app 14.0.0`, proposed solution did not work for me.
This worked:

```ruby
def login_shop(shop)
    stubbed_session = ShopifyAPI::Session.new(domain: shop.shopify_domain, token: shop.shopify_token, api_version: shop.api_version)
    expect(ShopifyApp::SessionRepository).to receive(:retrieve_shop_session).and_return(stubbed_session)
    @request.session[:shop_id] = shop.id
end
```
