### ISSUE TITLE
Chrome SameSite warning on shopify.granted_storage_access cookie

### ISSUE THREAD

**Issue by flavio-b** [Shopify/shopify_app#881]
Hello,

I've upgraded some apps to` v11.7.0`, which adds the SameSite=none attribute to cookies, but just noticed that the same does not apply to the `shopify.granted_storage_access` cookie that is set in the client by storage_access.js. It's showing a warning in the console.

<img width="657" alt="Screen Shot 2020-02-03 at 1 54 25 PM" src="https://user-images.githubusercontent.com/25246024/73694737-8db4f080-468d-11ea-90ce-9c65a7f2ba9d.png">

Will this lead to an issue when authenticating? I'm particularly looking at this line in `sessions_controller.rb`

```
def request_storage_access?
      return false unless ShopifyApp.configuration.embedded_app?
      return false if params[:top_level]
      return false if user_agent_is_mobile
      return false if user_agent_is_pos

      # **** If cookie will not be sent to the server, this will always return true, right?
      !session['shopify.granted_storage_access']
end
```

Just wanted to double check if this was left on purpose. Thanks!

**Comment by tanema** [comment]
The SameSite middleware applies the security policy to all cookies set by the the app. You can see here https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/middleware/same_site_cookie_middleware.rb#L12 that we check for the Set-Cookie header and apply the `SameSite=None`. So how did you notice that it does not apply to `granted_storage_access`. This may just be a bug

**Comment by flavio-b** [comment]
This cookie is set on the client in `storage_acess.js`

```
StorageAccessHelper.prototype.grantedStorageAccess = function() {
    try {
      sessionStorage.setItem('shopify.granted_storage_access', true);
      document.cookie = 'shopify.granted_storage_access=true'; //   **** HERE
      if (!document.cookie) {
        throw 'Cannot set third-party cookie.'
      }
      this.redirectToAppHome();
    } catch (error) {
      console.warn('Third party cookies may be blocked.', error);
      this.redirectToAppTLD(ACCESS_DENIED_STATUS);
    }
  }
```

**Comment by tanema** [comment]
Okay I put up this PR here but I still am getting warnings on a fresh app install so I think there might be something else I need to fix

**Comment by flavio-b** [comment]
Ok, I just checked your PR #882 . 

I think the warning you're seeing is it's missing the **Secure** flag. Adding it seems to make the warning go away, on my end at least.

Also, it looks like you've left a call to `alert()`.

Sorry, I'm learning as I read about this stuff, but it [It looks like](https://www.chromium.org/updates/same-site/incompatible-clients) macOS Mojave, and browsers in iOS 12 interpret SameSite=None as SameSite=Strict. This may cause issues on these systems preventing the apps from opening.

For now, I would suggest to do a conditional check for Chrome's latest versions, and set SameSite and Secure only in those cases, while settings the same way for everything else. That is until we figure out something better. 

I don't know a good way to get the user agent, aside from browser_sniffer, in the client. Perhaps you have something that you use at Shopify on the client side?

**Comment by tanema** [comment]
😓 Yeah sorry, that PR should have been marked as draft. I wanted something up to show you I was working on it. You are right about how SameSite is interpreted, and I will have to figure out a browser sniffer options 👍

**Comment by tanema** [comment]
Okay I have updated the PR with better handling and tests however I cannot get those code paths to execute. A lot of that code was to handle ITP cookie partitioning in safari and that cookie should only be set by the enable_cookies page which should really only ever appear on safari with ITP. However even when testing with safari I could not trigger the page. Also that line that you pointed out in the sessions controller I dont belive has much to do with the cookie. This is because in the granted_storage_access, the session variable is set and that is what is being checked in the line that you highlighted. If we were checking the cookie value, that would not come from `session` but `cookies`. I think all of this ITP code need to be re-addressed. I have no problem merging my change but I dont think it will make much of a change.

**Comment by flavio-b** [comment]
Thanks for looking into it, and for working on the PR.

Yes, I see now that in `sessions_controller.rb`, it is reading from `sessions`, not `cookies`. And the `shopify.granted_storage_access `is set on the server. Thanks for pointing that out. I think this part won't be a problem.

I do manage to get that cookie to be set on the client in `storage_acess.js`, using Chrome. So Chrome is still writing something that won't be readable on the server. I think your PR addresses this issue by making a wrapper method for setting cookies properly regardless.

However, I could not find a place in shopify_app's controller where it's reading from `cookies`. So maybe `grantedStorageAccess` is just setting that to see if the browser can accept third-party cookies at all?

FYI, I tested with Chrome Beta v.80 today and my updated apps are working fine on it. It only warns that the cookie has been blocked.

<img width="566" alt="Screen Shot 2020-02-04 at 12 25 55 PM" src="https://user-images.githubusercontent.com/25246024/73791311-edc39980-4756-11ea-87e5-a7f399cda076.png">
