### ISSUE TITLE
Per User tokens being used for Webhooks Callback Controller

### ISSUE THREAD

**Issue by tanema** [Shopify/shopify_app#883]
Currently, after the release of the per_user_authentication, there is an issue with callbacks/webhooks where the user token is currently used. This will work for a time but the user tokens have a short expiry.

To fix this we need to 
- Modify our installation process to get both tokens
- Store both shop and user tokens
- Look up shop token in callbacks controller using shop domain
- [Maybe] Add an `app/uninstall` webhook required so that we can track shop session to require re-auth
- [Maybe] Add a way to check if shop token is still valid so that we can skip shop auth, so that shop auth is not repeated every time the app is used

@slucaskim

**Comment by slucaskim** [comment]
For knowing if user token or shop token came back from the omniauth callback, we can check for presence of [`associated_user`](https://github.com/Shopify/shopify_app/blob/master/app/controllers/shopify_app/callback_controller.rb#L37) because that would only be present in case of user token strategy
