### ISSUE TITLE
SameSite Cookie Not Set on Ruby < 2.4

### ISSUE THREAD

**Issue by sshaw** [Shopify/shopify_app#888]
I was wondering why `SameSite` wasn't being added to my cookies and it turns out that [you're rescuing `NoMethodError` and returning `true`](https://github.com/Shopify/shopify_app/commit/c57ef409384140e269241854735a337b96ee7d8d#diff-89520877523f34645e272383ae801163R27-R28) which means the browser is "incompatible". No `SameSite` 😱 

With the addition of the SameSite cooke middleware [2.3.X](https://github.com/Shopify/shopify_app/blob/3d30a5dd86fe47a110400cb34929f8fb384fd371/shopify_app.gemspec#L11) no longer works because [the middleware uses `String#match?` in various locations](https://github.com/Shopify/shopify_app/commit/c57ef409384140e269241854735a337b96ee7d8d#diff-89520877523f34645e272383ae801163R32) which was first (?) made available in 2.4.

**Comment by sshaw** [comment]
Also no need to interpolate cookie [in the first `gsub` argument](https://github.com/Shopify/shopify_app/commit/c57ef409384140e269241854735a337b96ee7d8d#diff-89520877523f34645e272383ae801163R18). And any reason not to `gsub!` to save allocating new String? Maybe no difference 🤷‍♂️

**Comment by tanema** [comment]
Thanks for pointing this out. I will see what I can do to fix this, however, I recommend that you upgrade your ruby version as 2.3 support has ended. This is why we do not test on those versions

**Comment by sshaw** [comment]
> I recommend that you upgrade your ruby version as 2.3 support has ended

Yes, I'm aware. Unfortunately this is not how software works in the wild. 

Independent of compatibility issues why not extract this middleware into its own gem?

**Comment by tanema** [comment]
I have a PR up to fix this. This is not in a gem because the rails team is working on mitigating this within the rails stack and adding handling for this so our middleware should be temporary.
