### ISSUE TITLE
Script_tags

### ISSUE THREAD

**Issue by almeidaz** [Shopify/shopify_app#889]
I have configured some script_tags in my shopify.rb and added write script_tags in scope.

config.scripttags = [
{event:'onload', src: 'https://my-domain/main.js'},
]

all works fine. Script is loaded. But when i request script_tags in POSTMAN with :

GET https://my-domain.com/admin/api/2020-01/script_tags.json

the response is empty

{
    "script_tags": []
}

I don't understand how Shopify_app manage script_tags. How can i retrieve script_tags installed with shopify_app ?

**Comment by tanema** [comment]
Hey! Thanks for opening the issue. Do you have your background job queue running? When the shop is installed, it checks if you have script tags and if you do, then it queues a job to install them.

Also once you have all of that running you will need to make sure that you are requesting the `write_script_tags` scope as well on install otherwise the job will throw a forbidden access error

**Comment by almeidaz** [comment]
Hello,
i need to modify scripttags when user change option in the app.
then i do this in my setups_controller.rb

```
class SetupsController < ShopifyApp::AuthenticatedController
def index
....

def update
if mesparams[:player_version] == 'V1'
      puts "cV1"
      ShopifyApp.configure do |config|
        config.scripttags = [
          {event:'onload', src: 'http://apps/myNewScript.js'},

        ]
      end
    else
      puts 'nothing'

    end
```

its seems to not working. What's the best way to update scripttags when user select a particular option in the app.

Thanks.

**Comment by prativapokhrel** [comment]
> I have configured some script_tags in my shopify.rb and added write script_tags in scope.
> 
> config.scripttags = [
> {event:'onload', src: 'https://my-domain/main.js'},
> ]
> 
> all works fine. Script is loaded. But when i request script_tags in POSTMAN with :
> 
> GET https://my-domain.com/admin/api/2020-01/script_tags.json
> 
> the response is empty
> 
> {
> "script_tags": []
> }
> 
> I don't understand how Shopify_app manage script_tags. How can i retrieve script_tags installed with shopify_app ?

Hey, where have you placed main.js?
