### ISSUE TITLE
ActionDispatch::Cookies::CookieOverflow in Rails SPA with Shopify Polaris

### ISSUE THREAD

**Issue by eebasadre20** [Shopify/shopify_app#894]
Hi here,

Currently developing a new app using Shopify Polaris ( Rails SPA ).
Along the way, I encountered this issue

<img width="1020" alt="Screen Shot 2020-02-08 at 11 20 23 AM" src="https://user-images.githubusercontent.com/5001556/74079022-78184000-4a6c-11ea-918f-65befaa24ca3.png">

<img width="594" alt="Screen Shot 2020-02-08 at 11 20 48 AM" src="https://user-images.githubusercontent.com/5001556/74079028-8cf4d380-4a6c-11ea-929a-4b22f2da82d6.png">

Here's my Shopify config

```
ShopifyApp.configure do |config|
  config.application_name = "My App"
  config.api_key = ENV['SHOPIFY_API_KEY']
  config.secret = ENV['SHOPIFY_API_SECRET']
  config.old_secret = ""
  config.scope = "read_products" # Consult this page for more scope options:
                                 # https://help.shopify.com/en/api/getting-started/authentication/oauth/scopes
  config.embedded_app = true
  config.after_authenticate_job = false
  config.api_version = "2020-01"
  config.session_repository = Shop
end

```
I'm not sure what causes this issue. I've researched regarding the issue and it suggested to use  **_gem 'activerecord-session_store'_**. I haven't tried this and hesitant to use it as I prefer to not use another gem.

Is this the only solution? and may I know what's the cause of this?

**Comment by eebasadre20** [comment]
I'll close this issue as I already figured out how to solve it.

**Comment by JuanseGimenez** [comment]
> [@JuanseGimenez](https://github.com/JuanseGimenez) [@eebasadre20](https://github.com/eebasadre20) , How to fix this error ?

I think using `activerecord-session_store` gem and replacing the session_store `Rails.application.config.session_store ` from `cookie_store` to `active_record_store`
