### ISSUE TITLE
Error to use webhook with springBoot

### ISSUE THREAD

**Issue by LuisLopez15** [Shopify/shopify_app#899]
I am trying of get the webhook event in my application with springBoot, but to send test notifications, in the app' logs I have the error 
`SecurityContextHolderAwareRequestWrapper[ FirewalledRequest[ Request(POST //fa583e96.ngrok.io/shopify/webhook/customer/create)@46beb0ea]]`
I am using ngrok for test in my localhost

**Comment by tanema** [comment]
I am sorry but this is outside the scope of our support. This seems like you are not using rails and this error looks Java-based. I can't help with this.
