### ISSUE TITLE
Safari users losing return to address after clicking to allow cookies

### ISSUE THREAD

**Issue by hurracrane** [Shopify/shopify_app#901]
Safari users losing return address after clicking to allow cookies.

An initial attempt to fix was done in https://github.com/Shopify/shopify_app/pull/873 and part of the 12.0.1 release. However, this introduced issues with the login flow that resulted in an infinite loop of requests. The fix was then reverted.

Another attempt to fix is being done in https://github.com/Shopify/shopify_app/pull/900.

**Comment by mkevinosullivan** [comment]
Confirmed with Patrick (hurracrane) that #900 fixed this issue.
