### ISSUE TITLE
Cookie set without SameSite attribute 13.0.0

### ISSUE THREAD

**Issue by derekmorash** [Shopify/shopify_app#930]
We're still seeing this in chrome even though we've been keeping up to date with gem versions.

![Screenshot of Cookie was set without the `SameSite` attribute.](https://user-images.githubusercontent.com/9979079/77209674-9a769200-6add-11ea-83ae-343703a3deab.png)

But viewing the cookies in the application tab it's telling us that it is set as SameSite=none like it should be.
![Screenshot of Chrome application tab.](https://user-images.githubusercontent.com/9979079/77209677-9b0f2880-6add-11ea-82ca-5896af3f8d96.png)

Am I missing something here? The app still seems to be working fine in chrome 80, although just today we had a merchant tell us that we need to update to use the SameSite attribute in order for them to use our app. I'm not sure how they're seeing that it isn't set unless they're looking in the console.

Rails 6.0.2.1, shopify_app 13.0.0

**Comment by resistorsoftware** [comment]
A lot of clients have Chrome really polluted with old code in their cache. You could always try that, telling them to clear cache... and see how that goes. Kinda a whiffle at this point, but it is all there is. I have yet to have one respond that they did, and that that did not work...

**Comment by tanema** [comment]
I would tend to agree, If all of the attributes are set correctly but chrome is raising an issue, it might more likely be a chrome issue. Clearing cache, might help this
