### ISSUE TITLE
Using Shopify GraphQL in Rails App and rake tasks

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#932]
shopify_api (9.0.2)
     shopify_app (13.0.0)

I coded up a bunch of GraphQL and decided to try out the Shopify built-in GraphQL. To my surprise, in a simple rake task, it bombs out as follows:

rails aborted!
ShopifyAPI::ApiVersion::ApiVersionNotSetError: You must set ShopifyAPI::Base.api_version before making a request.

I read the docs and the code, and it explains how it is all self-initialized and should just work. My experience has been somewhat different from that. I would love to run rake tasks that query the shop with the Shopify GraphQL. Any hot tips on how I might get that going without too much trouble?

**Comment by resistorsoftware** [comment]
I guess I need to be a little more clear. Imagine you write a new rake task. It will fire up some object with the capabilities of changing a store, using GraphQL. Nothing scary there. For me, the challenge was to isolate the GraphQL queries into their own little module. So I created a module with them, and that was the source of the problem. A query invokes the client method in the definition and hence when I require them in my rake tasks, before any session and no API version, yes of course they fail. 

So the simplest thing would be to ensure no GraphQL code is accessed until a valid session / API version exists. Not sure about the most elegant way to go about that, but I am sure it will occur to me at some point. How do you write a little library of queries without them bombing this way?

**Comment by tanema** [comment]
This seems like more of an issue to be opened on `shopify_api` because you could also take example from the shopify_api rake task as well https://github.com/Shopify/shopify_api/blob/master/lib/shopify_api/graphql/task.rake#L67-L81

**Comment by resistorsoftware** [comment]
True, it involves the API, but at the abstract higher level, I am trying to deliver App services using Rake tasks, so I feel the App is a good place to anchor the discussion. And the rake task in the API is of no real use here since it simply opens a session to do its thing, which does not help here with the organization of GraphQL tasks. I know it is as simple as ensuring that these rake tasks self-inform of the API version the App has, I am just searching for an elegant way to provide that without going too far. For now, I just inlined all my calls to where they are used and it all works, but it makes maintenance moving forward a little busier.
