### ISSUE TITLE
Removing scripttags when user select a option

### ISSUE THREAD

**Issue by almeidaz** [Shopify/shopify_app#935]
i'm trying to remove scripttags when user select an option in the app

i'm able to delete scripttags by id like this
ShopifyAPI::ScriptTag.delete(19874654987)

but i'm looking to remove all scriptags created from the apps in one time like this
 ShopifyAPI::ScriptTag.delete(:all)

but it's not working. There is a way to remove all scripttags from the app in one time?
Thanks in advance.

**Comment by resistorsoftware** [comment]
Why can you not just use a simple loop? 

`ShopifyAPI::ScriptTag.all.each { |tag| ShopifyAPI::ScriptTag.delete(tag.id) }`

**Comment by almeidaz** [comment]
Thanks for that ! Working good.

**Comment by almeidaz** [comment]
There is a way to delete scripttags by source name like this?  

ShopifyAPI::ScriptTag.delete("https://www.mywebsite.com/myscript.js")

**Comment by resistorsoftware** [comment]
Why not.. did you try the basic approach?

    ShopifyAPI::ScriptTag.all.each { |tag| ShopifyAPI::ScriptTag.delete(tag.id) if tag.src == 'https://www.mywebsite.com/myscript.js' }

**Comment by almeidaz** [comment]
Thanks a lot resistorsoftware
