### ISSUE TITLE
Is whitelisted redirection URL must be https?

### ISSUE THREAD

**Issue by codemicky** [Shopify/shopify_app#940]
Is whitelisted redirection URL must be `https`?

My App is running on AWS EC2 Instance and the domain is `http://myip.com/app`
So my whitelisted redirection URL is `http://myip.com/app/auth/shopify/callback`

When installing the App on the store, I am getting the following error.
`Oauth error invalid_request: The redirect_uri is not whitelisted`

**Comment by tanema** [comment]
No it is not required. (Although you will have cookie issues if you do not) However, the URL comparison is very strict so if you whitelisted `http://myip.com/app/auth/shopify/callback` but it actually redirects to `http://myip.com/app/auth/shopify/callback/` (with the extra slash) then it will not be valid
