### ISSUE TITLE
granted_storage_access bug in version 13.0.1

### ISSUE THREAD

**Issue by uurcank** [Shopify/shopify_app#944]
It seems like version 13 does not work when you set a nested URL in shopify_app.rb 

**For example:**

`  config.root_url = '/shopifyapp'`

If your config.login_url  endpoint is different, granted_storage_access method takes you back to the root_url, which skips the callback_controller, hence user does not login to the app. No session is generated.

**It works when you change line 48 in sessions controller: I did this**
 
```
   def granted_storage_access
      return unless validate_shop_presence
      session['shopify.granted_storage_access'] = true

      copy_return_to_param_to_session

      redirect_to login_url_with_optional_shop
    end
```
 
 
 By the way config.login_url is confusing. I thought this was the same as "/login" but it looks like this is the omniauth endpoint where the login form posts to. It should be called something different, perhaps "config.oauth_url" 

it also looks like 13.0.1 was never released but it was added to the changelog here: https://github.com/Shopify/shopify_app/blob/master/CHANGELOG.md  I am testing the master.

**Comment by uurcankaya** [comment]
@tanema  By the way, the above issue was happening in Chrome. When I change line 48, it started to work on Chrome.

For Safari I am not sure what the solution would be. After the above change, it still raises CSRF error in Safari from time to time. 

Perhaps we can try to run callback_controller multiple times. Even after enable_cookie and top_level_auth methods. Safari clears all cookies by the time session_controller redirects user to the root_url.

**Comment by awd** [comment]
I am seeing the same issue on Safari 13.1 OSX, within the Shopify iOS app, and Chrome 80.0.3987.163 (Official Build) (64-bit) OSX.

All browsers can accept cookies.

Shopify app: 13.0.0
Rails: 6.0.2

**Comment by uurcankaya** [comment]
any update on this?
