### ISSUE TITLE
Shopify domain

### ISSUE THREAD

**Issue by almeidaz** [Shopify/shopify_app#945]
When users install app we add his shopify domain name in database. ex : myshop.myshopify.com

This shopify domain will not be modified overtime even if the user change is domain name right?

Cause sometimes shops remove the myshopify.com to be : (ex: myshop.cl)

actually  i'm able to find it with : ShopifyAPI::Shop.current.myshopify_domain even if they remove the myshopify.com

instead of : ShopifyAPI::Shop.current.domain

i don't really know rules about domain name changing on shopify. i'm just wondering if the :
ShopifyAPI::Shop.current.myshopify_domain will not be change overtime by users.

Thanks

**Comment by marschattha** [comment]
Yes it is static and unique to store.

**Comment by tanema** [comment]
As @marschattha said, it does not change. Merchants can provide a custom domain for their store however that does not change the `myshopify_domain`.
