### ISSUE TITLE
Misleading error banner when third-party cookies are blocked

### ISSUE THREAD

**Issue by flavio-b** [Shopify/shopify_app#946]
Hello there,

Not long ago, if a user had third-party cookies blocked, opening an app would redirect back to Shopify Admin with a red flash saying something like "Third-party cookies may be blocked".

Now, it shows this banner (attached). A few merchants reached out to us and we've been trying to figure out if the issue was with our code (`rails 5.2.4.2, shopify_app 13.0.0`), but turns out it was just that old issue.

<img width="981" alt="Screen Shot 2020-04-06 at 12 55 00 PM" src="https://user-images.githubusercontent.com/25246024/78602616-98b20b80-780b-11ea-9f9c-ca0767b7e6cf.png">

Would you be able to escalate with the Shopify Admin team, to update the message, perhaps to point to a tutorial on unblocking third-party cookies? I think the current message is misleading as there's nothing we can do to workaround this, at least not for now. Thanks!

Edit: tested with `Chrome Beta v81.0.4044.92` and `Chrome 81.0.4044.92`

**Comment by resistorsoftware** [comment]
So you're ruling out the **samesite none** cookie issue with Chrome? You don't specify which browser you use when this happens. Just curious.

**Comment by flavio-b** [comment]
@resistorsoftware Thanks! I forgot to mention the browser. They are the latest I can get for Chrome and Chrome Beta: `81.0.4044.92`

 The Beta is already blocking cross-site cookies without `samesite=none`, but the app has been updated to `shopify_app 13.0.0` which handles this, and everything works. Before that, we had been running v11.6.0 since end of January, which also handled these cookies.

Are you able to reproduce the message on your end?

**Comment by ragalie** [comment]
Hi @flavio-b, thanks for the heads-up, we're looking into it!

**Comment by khoimm92** [comment]
After a long time struggling this issue, I had run this command to override Shop Model
`rails generate shopify_app:shop_model`
It's all about Shop session issue

**Comment by flavio-b** [comment]
It looks like the message has been changed to something specific about cookies, so I'm closing the issue. Thanks! 

<img width="958" alt="Screen Shot 2020-05-04 at 9 54 41 AM" src="https://user-images.githubusercontent.com/25246024/80991797-6fc26d80-8ded-11ea-9622-b2dbb04304f8.png">
