### ISSUE TITLE
Webhooks are not registered on Heroku

### ISSUE THREAD

**Issue by jigarkakadiya** [Shopify/shopify_app#956]
I fired the following command for generating a webhook for local development.

rails g shopify_app:add_webhook -t carts/update -a https://example.com/webhooks/carts_update

I am working on rails 5.

In local the webhooks are working fine. I am able to see logs in sidekiq as well.

So, I proceed to deploy code on Heroku. At that time the webhooks are not being generated. Even I installed the app multiple times. But still, I am not able to generate a webhook for Heroku. 

Even I am confirming with ShopifyAPI::Webhook.find(:all)

In local webhooks are showing but for Heroku ShopifyAPI::Webhook.find(:all) returns This app has not created any webhooks for this Shop

So, Please guide me to resolve this issue.

**Comment by tanema** [comment]
Can you please share your webhook config from your raise initializers here?

**Comment by resistorsoftware** [comment]
You probably forgot to fire up a worker at heroku, so you have nothing running your jobs. Ensure from your Procfile that you took care of this.

heroku ps

Should see a worker. If not, fire one up. And then your jobs and webhooks will all work fine.

**Comment by nelsonwittwer** [comment]
Closing as it appears the suggestion solved the issue
