### ISSUE TITLE
Missing Route on OmniAuth Auth Failure 

### ISSUE THREAD

**Issue by sshaw** [Shopify/shopify_app#960]
Yay, authentication issues (sorta) 🎉 

Users seem to love to fiddle around with their browsers back and forward buttons after logging in via an embedded app (though I don't think I've _ever_ seen this is non-embed apps; certainly it's possible). This results in an authentication failure due to CSRF detected etc...

When OmniAuth OAuth2 detects something fishy [it redirects one to `/auth/failure`](https://github.com/omniauth/omniauth/wiki#getting-started). Unfortunately this results in a `ActionController::RoutingError`.

I checked the latest version of this and `rake routes` indicates that this path is still not handled. 

Seems to makes sense for it to be defined by this engine. No?

**Comment by uurcankaya** [comment]
@sshaw  failure should be detected by omniauth gem, not shopify_app gem. So you need to add a view for that route or rescue failures.

**Comment by sshaw** [comment]
Yes, failure is detected by the OmniAuth gem but in most apps it's brought in by _this gem_ and no one will ever know that they'll need to add this route. 

So you should either **1**) handle it as part of the engine maybe via an opt-on or **2**) mention it in the docs

**Comment by uurcankaya** [comment]
omniauth is pretty common so they may have assumed rails developers know it. You can submit a PR for the docs though
