### ISSUE TITLE
Default shop session strategy is now ShopifyApp::InMemoryShopSessionStore

### ISSUE THREAD

**Issue by jamiemtdwyer** [Shopify/shopify_app#971]
As of 13.0.0, the default shop session strategy is now ShopifyApp::InMemoryShopSessionStore rather than "Shop".

https://github.com/Shopify/shopify_app/blob/master/lib/generators/shopify_app/install/templates/shopify_app.rb.tt#L11

This is a somewhat confusing (and undocumented) change. Should the default shop session strategy be changed back to the `Shop` model?

**Comment by tanema** [comment]
Hey Jamie! You may be right, a shop model is more straightforward. I will try to do this soon.
