### ISSUE TITLE
non proxy server - shopify_app/request_storage_access.js not present in assets projects server

### ISSUE THREAD

**Issue by yudechen0820** [Shopify/shopify_app#979]
I have deployed the `Shopify App` on `AWS EC2` with the `non-proxy `server for example
`http://myserver.com`

But I am getting this error:
```
[2020-04-28T18:13:38.525402 #78789] FATAL -- : [e8a86169-d3cb-45af-8484-e41c2498b5f2]   
[e8a86169-d3cb-45af-8484-e41c2498b5f2] ActionView::Template::Error (The asset "shopify_app/request_storage_access.js" is not present in the asset pipeline.):
[e8a86169-d3cb-45af-8484-e41c2498b5f2]     63:     </div>
[e8a86169-d3cb-45af-8484-e41c2498b5f2]     64:   </div>
[e8a86169-d3cb-45af-8484-e41c2498b5f2]     65: </main>
[e8a86169-d3cb-45af-8484-e41c2498b5f2]     66: <%= javascript_include_tag('shopify_app/request_storage_access', crossorigin: 'anonymous', integrity: true) %>
[e8a86169-d3cb-45af-8484-e41c2498b5f2]     67: </body>
[e8a86169-d3cb-45af-8484-e41c2498b5f2]     68: </html>
[e8a86169-d3cb-45af-8484-e41c2498b5f2] 
```

I have tried to enable the assets server but it didn't work.
`  config.action_controller.asset_host = "http://myserver.com"`

Any one can help me?

**Comment by johnsampson** [comment]
Per this [Shopify Community post](https://community.shopify.com/c/Shopify-APIs-SDKs/The-asset-quot-shopify-app-request-storage-access-js-quot-is-not/td-p/691648), does precompiling the assets resolve your issue @codemicky ?

> RAILS_ENV=production bundle exec rails assets:precompile

**Comment by nikolacojcic99** [comment]
Hi @johnsampson, thanks for your reply.
Sorry, it didn't help me.

**Comment by tanema** [comment]
Closing because this seems stale and with a possible solution

**Comment by csautot** [comment]
Hi @tanema - I ran "RAILS_ENV=production bundle exec rails assets:precompile" via CLI, but I am still getting the error above when I try to have users auth my Shopify app with their store.

I am using shopify_app Gem version 14.2

**Comment by markdavies** [comment]
@tanema - I'm still seeing this too, I think this issue should be re-opened?

**Comment by skillmatic-co** [comment]
I'm also having this issue, despite running `RAILS_ENV=production bundle exec rails assets:precompile`
