### ISSUE TITLE
How to integration test the redirects to permission_url?

### ISSUE THREAD

**Issue by volkanunsal** [Shopify/shopify_app#98]
I have this embedded app that requires the user to modify the product, and I'm trying to write a test for that flow, but the problem is that it needs to redirect me to

     https://my-pretty-shop.myshopify.com/admin/oauth/authorize

 With the authentication flow, this was easy: OmniAuth's test mode simply moves me forward to the callback step, but I'm not sure with this one. I have no control over the redirection. I need some advice please.

**Comment by kevinhughes27** [comment]
I am going to close as this sounds like a question more suited to the Shopify API forums (https://ecommerce.shopify.com/c/shopify-apis-and-technology) and isn't really an issue with the code included in this gem
