### ISSUE TITLE
When is ScriptTagManager added to the background jobs queue?

### ISSUE THREAD

**Issue by netwire88** [Shopify/shopify_app#983]
Hi, 
When does shopify_app add ScriptTagManager to the queue? When I make changes to the shopify_app config file, the changes aren't added to background job queues and aren't pushed to Shopify. How often does the ScriptTagManager run? How can I trigger it manually?

**Comment by dan-gamble** [comment]
From my understanding, the ScriptTagManager gets run on server boot. So if you make changes you'll want to restart your server so it can send out the requests to register any additions you've made.

**Comment by netwire88** [comment]
Ever since I upgraded to v13.1, it doesn't seem to load. I checked my Sidekiq admin and don't see the job. I also tried adding `config.webhooks_manager_queue_name = 'default' ` to the `shopify_app.rb` file. This was working in v12.

**Comment by tanema** [comment]
Both webhooks and scripttag jobs get queued on app installation. You can also change the scripttags queue with `config.scripttags_manager_queue_name`. If you want to re-enqueue them you can do so manually in your application code or re-install your app on your test shop
