### ISSUE TITLE
Uninstall and installing again is not working - Persistent cookies (reopen)

### ISSUE THREAD

**Issue by netwire88** [Shopify/shopify_app#988]
Hi,
Is it possible to reopen #456 as it's not resolved? I tried v13.2 and it's still not working. After uninstall, if I tried to go back to the app, I get this error

```
The page you’re looking for couldn’t be found
Check the web address and try again, or try navigating to the page from Shopify Home.
```
However, I do the same in an incognito browser. It works. I think it has something to do with the cookies.

**Comment by flavio-b** [comment]
In your root route, try adding an API call, for example `ShopifyAPI::Shop.current`
This will trigger a redirect to login.
I think the original issue is difficult to resolve for good.
