### ISSUE TITLE
Running locally the index page redirects to https://{shopname}.myshopify.com/admin/apps/{id}/

### ISSUE THREAD

**Issue by PhilipAnd** [Shopify/shopify_app#990]
I am playing around the app and are having some issues with running it locally, and I hope someone can point me in the right direction.

The application is set up and I have authenticated it, but as soon as I see the frontpage (Index.html.erb page with the products), it will after 3-4 seconds redirect to: https://{my shope name}.myshopify.com/admin/apps/{id}/. I want to be able to run it locally so I can test as I play around with the code.

In the Shopify dashboard I have set the App URL to http://localhost:3000/ and redirect URL to: http://localhost:3000/auth/shopify/callback

I get the following JavaScript error: `Content Security Policy: The page’s settings blocked the loading of a resource at http://localhost:3000/?hmac=12390396be…85b8ab13617&shop={my shop}.myshopify.com&timestamp=1589828169 (“frame-src”).`

Does anyone have some directions on how to actually run the app locally towards a real store to test it out?

**Comment by tanema** [comment]
To stop the redirect you need to pass in `forceRedirect: false` to the `createApp` call from app bridge in your JS.

The CSP errors are because you are trying to use an app in the embedded context however you are not using a https tunnel to do so. It is impossible to make an app in the admin without using https because fo cookie restrictions.

**Comment by vfonic** [comment]
Hey @tanema!

I just came here to report similar issue and search brought me here.

I've added both `forceRedirect: true` and `force_redirect: true` here:

https://github.com/Shopify/shopify_app/blob/master/lib/generators/shopify_app/install/templates/embedded_app.html.erb#L32

But it still redirects.

Commenting out that whole content_tag makes the page not redirect.

PS This used to work fine with EASDK.

Thanks!

**Comment by ragalie** [comment]
I believe you need forceRedirect: **false**. As in, **don't** force a redirect to the myshopify.com URL.

**Comment by vfonic** [comment]
Ah, nevermind the example. I fixed it now. In the app it was `false`.

**Comment by andyw8** [comment]
Closing since this has been solved.
