### ISSUE TITLE
CookieOverflow errors on auth/shopify route 

### ISSUE THREAD

**Issue by flavio-b** [Shopify/shopify_app#991]
Sorry to bother again!

Since updating our app to `shopify_app@13.1.1` , we've started to see some sporadic `ActionDispatch::Cookies::CookieOverflow` errors on the `GET /auth/shopify` route.  

This issue is difficult to track as it shows up randomly, about 2-3 times a week, so I haven't been able to reproduce it yet. I thought it was because User was added to the session, but we haven't turned that on. Has anyone seen this error pop up once in a while with v.13 and newer?
🍪🍪🍪

**Comment by tanema** [comment]
Which version were you on before 13.1.1?

**Comment by flavio-b** [comment]
Before, it was `v11.6.0 ` We updated about a month ago, and soon after started seeing these erros pop up in our logs. I had not seen those before, so thought it was related to the gem. We also didn't add anything to cookies/session nor altered the auth flow in any way.

**Comment by tanema** [comment]
Okay I will have a look around. We have changed a lot to do with the session handling but I don't think any of it added anything to the cookie, only to the session store which is normally implemented in the database.

**Comment by flavio-b** [comment]
@tanema, I think I've found the problem, by logging the cookie size and doing more tests here.

When a merchant clicks an app Admin Link, after selecting multiple products, for example, it generates a long URL containing the ID's. This URL gets saved in the `session`, under the `return_to` key.

Finally, when the cookie is encrypted and signed by Rails, I think this can lead to sizes above 4096 bytes.

This is difficult to replicate. When I do this for 50 products, it clocks around 4036 bytes. I'm guessing that, for some situations, the encryption and signing algorithm inflates the size a bit more than for others. Probably has something to do with the ID's in the URL, but I'm not sure.

**Comment by tanema** [comment]
OHHHH! That might be from the return_to value we store to redirect users back after login. Does this happen around authentication or at any time?

**Comment by flavio-b** [comment]
I think this happens anytime, but where we are seeing the issue is after the `SessionsController`  `new` action redirects to `/auth/shopify`. That's when it raises the error.

The issue is raised in action_pack -> lib -> action_dispatch -> middleware -> cookie.rb. `EncryptedKeyRotatingCookieJar#commit`

**Comment by flavio-b** [comment]
I've found a way to get this error consistently, in Safari 13+

1. Make sure you don't have an active app session. 
2. Open the Products page in the Shopify Admin, check 50 items and click an Admin link that opens your app.
3.  It will open the app and request access for cookies. It then redirects to the top level. When you click to proceed, the `CookieOverflow` occurs. It's on the `/auth/shopify `route. 

I've been trying with no success to go around this problem. Do you know what part of `shopify_app `I could modify to avoid this problem? I can't seem to be able to overwrite the handler for that route.

**Comment by tanema** [comment]
The best solution to this would be to stop using cookie store for sessions I think. You could use an active record store if you dont want to introduce another technology or you could introduce something like memcache or redis for storing your sessions.

**Comment by flavio-b** [comment]
Ok, thank you, I'll look into these alternatives.
