### ISSUE TITLE
Rspec Testing Controllers that inherit from ShopifyAPI::AuthenticatedController

### ISSUE THREAD

**Issue by mattkc7** [Shopify/shopify_app#993]
I was following the solution over in https://github.com/Shopify/shopify_app/issues/731, but i'm still stuck at the 302...

My shopify gem version is 13.0.1

I've also posted my write-up here (re-produced below) https://stackoverflow.com/questions/61947801/rspec-for-shopify-controllers-stuck-on-a-302-for-authentication

Any pointers?

---------

```
require 'rails_helper'

describe OnboardingController, type: :controller do

  before do
    shop = FactoryBot.create(:shop)

    request.env['rack.url_scheme'] = 'https'
    @request.session[:shopify] = shop.id
    @request.session[:shopify_domain] = shop.shopify_domain
  end

   it 'onboards correctly', :focus do
    get :onboard_completed
    expect(response).to have_http_status(:success)
   end

end
```

**Comment by mattkc7** [comment]
just tried https://github.com/Shopify/shopify_app/issues/879, no luck either

**Comment by andyw8** [comment]
Hi @mattkc7,

One thing to note is `session[:shopify]` is no longer used: https://github.com/Shopify/shopify_app#changes-to-rails-session

So instead we can say:
```ruby
@request.session[:shop_id] = shop.id
```
or simply
```ruby
session[:shop_id] = shop.id
```

After that change, you'll probably see a `ActiveResource::UnauthorizedAccess` failure.

We can bypass that stubbing out `current_shop`:

```ruby
allow(Shop).to receive(:current_shop).and_return(shop)
```

Does this solve your problem?

**Comment by mattkc7** [comment]
Hi @andyw8 ! Thanks for the input! I just tried out those changes, but still got a 302 :(

I've shared my repo with you for closer look if that can shed any light?

**Comment by andyw8** [comment]
Hi @mattkc7, I verified it against the repo you shared, and test was passing – I've sent you an invite to my version so that you can see the exact change.

**Comment by mattkc7** [comment]
Hey @andyw8 

I saw your commit, and it cleared things up! I made a mistake and had `session[:shopify_id] = shop.id`, when it should have been `session[:shop_id] = shop.id` ... major 🤦 

🙏 thank you again!

**Comment by mattkc7** [comment]
To the future Shopify developer, here was my final code to get things working:

`require 'rails_helper'

describe WizardController, type: :controller do

  before do
    shop = FactoryBot.create(:shop)

    request.env['rack.url_scheme'] = 'https'
    allow(shop).to receive(:wizard_completed?).and_return(false)
    allow(Shop).to receive(:current_shop).and_return(shop)
    session[:shop_id] = shop.id
    session[:shopify_domain] = shop.shopify_domain
  end

  it 'enter test here', :focus do
    get :wizard
    expect(response).to have_http_status(:success)
  end

end
`

**Comment by andyw8** [comment]
👍 Good to hear it's now working for you.
